package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Actualprice generated by hbm2java
 */
@Entity
@Table(name = "ACTUALPRICE", schema = "PCRM")
public class Actualprice implements java.io.Serializable {

	private String id;
	private Date crd;
	private Date crt;
	private String cru;
	private Date modd;
	private Date modt;
	private String modu;
	private Date deld;
	private Date delt;
	private String delu;
	private Date impd;
	private Date impt;
	private String impu;
	private Date expd;
	private Date expt;
	private String expu;
	private BigDecimal abnLxbenummer;
	private BigDecimal bpLxbenummer;
	private Date bpSidstrettet;
	private String bpProdukt;
	private String bpAnlxg;
	private String bpAbonnr;
	private BigDecimal bpFejlkode;
	private Date bpBeregnet;
	private Date bpPrdato;
	private BigDecimal bpPakkepris;
	private BigDecimal bpRabat;
	private BigDecimal bpKoda;
	private BigDecimal bpRadiokoda;
	private BigDecimal bpCopydan;
	private BigDecimal bpMoms;
	private BigDecimal bpPrisIalt;
	private Set<Product> products = new HashSet<Product>(0);

	public Actualprice() {
	}

	public Actualprice(String id, BigDecimal abnLxbenummer,
			BigDecimal bpLxbenummer, Date bpSidstrettet, String bpProdukt,
			String bpAnlxg, String bpAbonnr, BigDecimal bpFejlkode,
			Date bpBeregnet, Date bpPrdato, BigDecimal bpPakkepris,
			BigDecimal bpRabat, BigDecimal bpKoda, BigDecimal bpRadiokoda,
			BigDecimal bpCopydan, BigDecimal bpMoms, BigDecimal bpPrisIalt) {
		this.id = id;
		this.abnLxbenummer = abnLxbenummer;
		this.bpLxbenummer = bpLxbenummer;
		this.bpSidstrettet = bpSidstrettet;
		this.bpProdukt = bpProdukt;
		this.bpAnlxg = bpAnlxg;
		this.bpAbonnr = bpAbonnr;
		this.bpFejlkode = bpFejlkode;
		this.bpBeregnet = bpBeregnet;
		this.bpPrdato = bpPrdato;
		this.bpPakkepris = bpPakkepris;
		this.bpRabat = bpRabat;
		this.bpKoda = bpKoda;
		this.bpRadiokoda = bpRadiokoda;
		this.bpCopydan = bpCopydan;
		this.bpMoms = bpMoms;
		this.bpPrisIalt = bpPrisIalt;
	}

	public Actualprice(String id, Date crd, Date crt, String cru, Date modd,
			Date modt, String modu, Date deld, Date delt, String delu,
			Date impd, Date impt, String impu, Date expd, Date expt,
			String expu, BigDecimal abnLxbenummer, BigDecimal bpLxbenummer,
			Date bpSidstrettet, String bpProdukt, String bpAnlxg,
			String bpAbonnr, BigDecimal bpFejlkode, Date bpBeregnet,
			Date bpPrdato, BigDecimal bpPakkepris, BigDecimal bpRabat,
			BigDecimal bpKoda, BigDecimal bpRadiokoda, BigDecimal bpCopydan,
			BigDecimal bpMoms, BigDecimal bpPrisIalt, Set<Product> products) {
		this.id = id;
		this.crd = crd;
		this.crt = crt;
		this.cru = cru;
		this.modd = modd;
		this.modt = modt;
		this.modu = modu;
		this.deld = deld;
		this.delt = delt;
		this.delu = delu;
		this.impd = impd;
		this.impt = impt;
		this.impu = impu;
		this.expd = expd;
		this.expt = expt;
		this.expu = expu;
		this.abnLxbenummer = abnLxbenummer;
		this.bpLxbenummer = bpLxbenummer;
		this.bpSidstrettet = bpSidstrettet;
		this.bpProdukt = bpProdukt;
		this.bpAnlxg = bpAnlxg;
		this.bpAbonnr = bpAbonnr;
		this.bpFejlkode = bpFejlkode;
		this.bpBeregnet = bpBeregnet;
		this.bpPrdato = bpPrdato;
		this.bpPakkepris = bpPakkepris;
		this.bpRabat = bpRabat;
		this.bpKoda = bpKoda;
		this.bpRadiokoda = bpRadiokoda;
		this.bpCopydan = bpCopydan;
		this.bpMoms = bpMoms;
		this.bpPrisIalt = bpPrisIalt;
		this.products = products;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "ABN_LXBENUMMER", nullable = false, precision = 22, scale = 0)
	public BigDecimal getAbnLxbenummer() {
		return this.abnLxbenummer;
	}

	public void setAbnLxbenummer(BigDecimal abnLxbenummer) {
		this.abnLxbenummer = abnLxbenummer;
	}

	@Column(name = "BP_LXBENUMMER", nullable = false, precision = 22, scale = 0)
	public BigDecimal getBpLxbenummer() {
		return this.bpLxbenummer;
	}

	public void setBpLxbenummer(BigDecimal bpLxbenummer) {
		this.bpLxbenummer = bpLxbenummer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BP_SIDSTRETTET", nullable = false, length = 7)
	public Date getBpSidstrettet() {
		return this.bpSidstrettet;
	}

	public void setBpSidstrettet(Date bpSidstrettet) {
		this.bpSidstrettet = bpSidstrettet;
	}

	@Column(name = "BP_PRODUKT", nullable = false, length = 20)
	public String getBpProdukt() {
		return this.bpProdukt;
	}

	public void setBpProdukt(String bpProdukt) {
		this.bpProdukt = bpProdukt;
	}

	@Column(name = "BP_ANLXG", nullable = false, length = 10)
	public String getBpAnlxg() {
		return this.bpAnlxg;
	}

	public void setBpAnlxg(String bpAnlxg) {
		this.bpAnlxg = bpAnlxg;
	}

	@Column(name = "BP_ABONNR", nullable = false, length = 12)
	public String getBpAbonnr() {
		return this.bpAbonnr;
	}

	public void setBpAbonnr(String bpAbonnr) {
		this.bpAbonnr = bpAbonnr;
	}

	@Column(name = "BP_FEJLKODE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getBpFejlkode() {
		return this.bpFejlkode;
	}

	public void setBpFejlkode(BigDecimal bpFejlkode) {
		this.bpFejlkode = bpFejlkode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BP_BEREGNET", nullable = false, length = 7)
	public Date getBpBeregnet() {
		return this.bpBeregnet;
	}

	public void setBpBeregnet(Date bpBeregnet) {
		this.bpBeregnet = bpBeregnet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BP_PRDATO", nullable = false, length = 7)
	public Date getBpPrdato() {
		return this.bpPrdato;
	}

	public void setBpPrdato(Date bpPrdato) {
		this.bpPrdato = bpPrdato;
	}

	@Column(name = "BP_PAKKEPRIS", nullable = false, precision = 32, scale = 16)
	public BigDecimal getBpPakkepris() {
		return this.bpPakkepris;
	}

	public void setBpPakkepris(BigDecimal bpPakkepris) {
		this.bpPakkepris = bpPakkepris;
	}

	@Column(name = "BP_RABAT", nullable = false, precision = 32, scale = 16)
	public BigDecimal getBpRabat() {
		return this.bpRabat;
	}

	public void setBpRabat(BigDecimal bpRabat) {
		this.bpRabat = bpRabat;
	}

	@Column(name = "BP_KODA", nullable = false, precision = 32, scale = 16)
	public BigDecimal getBpKoda() {
		return this.bpKoda;
	}

	public void setBpKoda(BigDecimal bpKoda) {
		this.bpKoda = bpKoda;
	}

	@Column(name = "BP_RADIOKODA", nullable = false, precision = 32, scale = 16)
	public BigDecimal getBpRadiokoda() {
		return this.bpRadiokoda;
	}

	public void setBpRadiokoda(BigDecimal bpRadiokoda) {
		this.bpRadiokoda = bpRadiokoda;
	}

	@Column(name = "BP_COPYDAN", nullable = false, precision = 32, scale = 16)
	public BigDecimal getBpCopydan() {
		return this.bpCopydan;
	}

	public void setBpCopydan(BigDecimal bpCopydan) {
		this.bpCopydan = bpCopydan;
	}

	@Column(name = "BP_MOMS", nullable = false, precision = 32, scale = 16)
	public BigDecimal getBpMoms() {
		return this.bpMoms;
	}

	public void setBpMoms(BigDecimal bpMoms) {
		this.bpMoms = bpMoms;
	}

	@Column(name = "BP_PRIS_IALT", nullable = false, precision = 32, scale = 16)
	public BigDecimal getBpPrisIalt() {
		return this.bpPrisIalt;
	}

	public void setBpPrisIalt(BigDecimal bpPrisIalt) {
		this.bpPrisIalt = bpPrisIalt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actualprice")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
