package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Addressitem generated by hbm2java
 */
@Entity
@Table(name = "ADDRESSITEM", schema = "PCRM")
public class Addressitem implements java.io.Serializable {

	private String id;
	private Offer offer;
	private Modemaccesspoint modemaccesspoint;
	private Date crd;
	private Date impt;
	private Date expt;
	private Date impd;
	private Date expd;
	private Date modt;
	private String cru;
	private Date delt;
	private Date modd;
	private String impu;
	private String expu;
	private Date deld;
	private String modu;
	private String delu;
	private Date crt;
	private String primdwa;
	private String primarysag;
	private String primaddrint;
	private Long inststatus;
	private String varenr;
	private String progpakke;
	private String inststattext;
	private Character inkluditilbud;
	private Character adddelete;
	private Character existing;
	private Character removed;
	private Character added;
	private Character inststatusaendret;
	private Character showincontract;
	private Long tekniskstatus;
	private Date restjobdone;
	private Character packageselection;
	private Long addressid;
	private String location;
	private BigDecimal installationseq;
	private Set<Addressitemvaluelink> addressitemvaluelinks = new HashSet<Addressitemvaluelink>(
			0);

	public Addressitem() {
	}

	public Addressitem(String id) {
		this.id = id;
	}

	public Addressitem(String id, Offer offer,
			Modemaccesspoint modemaccesspoint, Date crd, Date impt, Date expt,
			Date impd, Date expd, Date modt, String cru, Date delt, Date modd,
			String impu, String expu, Date deld, String modu, String delu,
			Date crt, String primdwa, String primarysag, String primaddrint,
			Long inststatus, String varenr, String progpakke,
			String inststattext, Character inkluditilbud, Character adddelete,
			Character existing, Character removed, Character added,
			Character inststatusaendret, Character showincontract,
			Long tekniskstatus, Date restjobdone, Character packageselection,
			Long addressid, String location, BigDecimal installationseq,
			Set<Addressitemvaluelink> addressitemvaluelinks) {
		this.id = id;
		this.offer = offer;
		this.modemaccesspoint = modemaccesspoint;
		this.crd = crd;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.cru = cru;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.modu = modu;
		this.delu = delu;
		this.crt = crt;
		this.primdwa = primdwa;
		this.primarysag = primarysag;
		this.primaddrint = primaddrint;
		this.inststatus = inststatus;
		this.varenr = varenr;
		this.progpakke = progpakke;
		this.inststattext = inststattext;
		this.inkluditilbud = inkluditilbud;
		this.adddelete = adddelete;
		this.existing = existing;
		this.removed = removed;
		this.added = added;
		this.inststatusaendret = inststatusaendret;
		this.showincontract = showincontract;
		this.tekniskstatus = tekniskstatus;
		this.restjobdone = restjobdone;
		this.packageselection = packageselection;
		this.addressid = addressid;
		this.location = location;
		this.installationseq = installationseq;
		this.addressitemvaluelinks = addressitemvaluelinks;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMTILBKONTR")
	public Offer getOffer() {
		return this.offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMFAP")
	public Modemaccesspoint getModemaccesspoint() {
		return this.modemaccesspoint;
	}

	public void setModemaccesspoint(Modemaccesspoint modemaccesspoint) {
		this.modemaccesspoint = modemaccesspoint;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "PRIMDWA", length = 22)
	public String getPrimdwa() {
		return this.primdwa;
	}

	public void setPrimdwa(String primdwa) {
		this.primdwa = primdwa;
	}

	@Column(name = "PRIMARYSAG", length = 19)
	public String getPrimarysag() {
		return this.primarysag;
	}

	public void setPrimarysag(String primarysag) {
		this.primarysag = primarysag;
	}

	@Column(name = "PRIMADDRINT", length = 19)
	public String getPrimaddrint() {
		return this.primaddrint;
	}

	public void setPrimaddrint(String primaddrint) {
		this.primaddrint = primaddrint;
	}

	@Column(name = "INSTSTATUS", precision = 10, scale = 0)
	public Long getInststatus() {
		return this.inststatus;
	}

	public void setInststatus(Long inststatus) {
		this.inststatus = inststatus;
	}

	@Column(name = "VARENR", length = 15)
	public String getVarenr() {
		return this.varenr;
	}

	public void setVarenr(String varenr) {
		this.varenr = varenr;
	}

	@Column(name = "PROGPAKKE")
	public String getProgpakke() {
		return this.progpakke;
	}

	public void setProgpakke(String progpakke) {
		this.progpakke = progpakke;
	}

	@Column(name = "INSTSTATTEXT")
	public String getInststattext() {
		return this.inststattext;
	}

	public void setInststattext(String inststattext) {
		this.inststattext = inststattext;
	}

	@Column(name = "INKLUDITILBUD", length = 1)
	public Character getInkluditilbud() {
		return this.inkluditilbud;
	}

	public void setInkluditilbud(Character inkluditilbud) {
		this.inkluditilbud = inkluditilbud;
	}

	@Column(name = "ADDDELETE", length = 1)
	public Character getAdddelete() {
		return this.adddelete;
	}

	public void setAdddelete(Character adddelete) {
		this.adddelete = adddelete;
	}

	@Column(name = "EXISTING", length = 1)
	public Character getExisting() {
		return this.existing;
	}

	public void setExisting(Character existing) {
		this.existing = existing;
	}

	@Column(name = "REMOVED", length = 1)
	public Character getRemoved() {
		return this.removed;
	}

	public void setRemoved(Character removed) {
		this.removed = removed;
	}

	@Column(name = "ADDED", length = 1)
	public Character getAdded() {
		return this.added;
	}

	public void setAdded(Character added) {
		this.added = added;
	}

	@Column(name = "INSTSTATUSAENDRET", length = 1)
	public Character getInststatusaendret() {
		return this.inststatusaendret;
	}

	public void setInststatusaendret(Character inststatusaendret) {
		this.inststatusaendret = inststatusaendret;
	}

	@Column(name = "SHOWINCONTRACT", length = 1)
	public Character getShowincontract() {
		return this.showincontract;
	}

	public void setShowincontract(Character showincontract) {
		this.showincontract = showincontract;
	}

	@Column(name = "TEKNISKSTATUS", precision = 10, scale = 0)
	public Long getTekniskstatus() {
		return this.tekniskstatus;
	}

	public void setTekniskstatus(Long tekniskstatus) {
		this.tekniskstatus = tekniskstatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "RESTJOBDONE", length = 7)
	public Date getRestjobdone() {
		return this.restjobdone;
	}

	public void setRestjobdone(Date restjobdone) {
		this.restjobdone = restjobdone;
	}

	@Column(name = "PACKAGESELECTION", length = 1)
	public Character getPackageselection() {
		return this.packageselection;
	}

	public void setPackageselection(Character packageselection) {
		this.packageselection = packageselection;
	}

	@Column(name = "ADDRESSID", precision = 10, scale = 0)
	public Long getAddressid() {
		return this.addressid;
	}

	public void setAddressid(Long addressid) {
		this.addressid = addressid;
	}

	@Column(name = "LOCATION", length = 30)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "INSTALLATIONSEQ", precision = 22, scale = 0)
	public BigDecimal getInstallationseq() {
		return this.installationseq;
	}

	public void setInstallationseq(BigDecimal installationseq) {
		this.installationseq = installationseq;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "addressitem")
	public Set<Addressitemvaluelink> getAddressitemvaluelinks() {
		return this.addressitemvaluelinks;
	}

	public void setAddressitemvaluelinks(
			Set<Addressitemvaluelink> addressitemvaluelinks) {
		this.addressitemvaluelinks = addressitemvaluelinks;
	}

}
