package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BusinesssphereChghist generated by hbm2java
 */
@Entity
@Table(name = "BUSINESSSPHERE_CHGHIST", schema = "PCRM")
public class BusinesssphereChghist implements java.io.Serializable {

	private String audId;
	private String audAction;
	private Serializable audTimestamp;
	private String audOsuser;
	private String audDbuser;
	private String audUserterminal;
	private String id;
	private Date crd;
	private String cru;
	private Date modd;
	private String modu;
	private String code;
	private String head;
	private Date startDate;
	private Date endDate;
	private String logtrace;
	private Short placementX;
	private Short placementY;
	private Byte width;
	private Integer orderNumber;
	private String assetReference;
	private String urlReference;
	private Character portalActive;
	private String tooltip;
	private Character sgportal;

	public BusinesssphereChghist() {
	}

	public BusinesssphereChghist(String audId, String id) {
		this.audId = audId;
		this.id = id;
	}

	public BusinesssphereChghist(String audId, String audAction,
			Serializable audTimestamp, String audOsuser, String audDbuser,
			String audUserterminal, String id, Date crd, String cru, Date modd,
			String modu, String code, String head, Date startDate,
			Date endDate, String logtrace, Short placementX, Short placementY,
			Byte width, Integer orderNumber, String assetReference,
			String urlReference, Character portalActive, String tooltip,
			Character sgportal) {
		this.audId = audId;
		this.audAction = audAction;
		this.audTimestamp = audTimestamp;
		this.audOsuser = audOsuser;
		this.audDbuser = audDbuser;
		this.audUserterminal = audUserterminal;
		this.id = id;
		this.crd = crd;
		this.cru = cru;
		this.modd = modd;
		this.modu = modu;
		this.code = code;
		this.head = head;
		this.startDate = startDate;
		this.endDate = endDate;
		this.logtrace = logtrace;
		this.placementX = placementX;
		this.placementY = placementY;
		this.width = width;
		this.orderNumber = orderNumber;
		this.assetReference = assetReference;
		this.urlReference = urlReference;
		this.portalActive = portalActive;
		this.tooltip = tooltip;
		this.sgportal = sgportal;
	}

	@Id
	@Column(name = "AUD_ID", unique = true, nullable = false, length = 19)
	public String getAudId() {
		return this.audId;
	}

	public void setAudId(String audId) {
		this.audId = audId;
	}

	@Column(name = "AUD_ACTION", length = 50)
	public String getAudAction() {
		return this.audAction;
	}

	public void setAudAction(String audAction) {
		this.audAction = audAction;
	}

	@Column(name = "AUD_TIMESTAMP")
	public Serializable getAudTimestamp() {
		return this.audTimestamp;
	}

	public void setAudTimestamp(Serializable audTimestamp) {
		this.audTimestamp = audTimestamp;
	}

	@Column(name = "AUD_OSUSER", length = 50)
	public String getAudOsuser() {
		return this.audOsuser;
	}

	public void setAudOsuser(String audOsuser) {
		this.audOsuser = audOsuser;
	}

	@Column(name = "AUD_DBUSER", length = 50)
	public String getAudDbuser() {
		return this.audDbuser;
	}

	public void setAudDbuser(String audDbuser) {
		this.audDbuser = audDbuser;
	}

	@Column(name = "AUD_USERTERMINAL", length = 50)
	public String getAudUserterminal() {
		return this.audUserterminal;
	}

	public void setAudUserterminal(String audUserterminal) {
		this.audUserterminal = audUserterminal;
	}

	@Column(name = "ID", nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "CODE", length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "HEAD")
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "LOGTRACE", length = 19)
	public String getLogtrace() {
		return this.logtrace;
	}

	public void setLogtrace(String logtrace) {
		this.logtrace = logtrace;
	}

	@Column(name = "PLACEMENT_X", precision = 3, scale = 0)
	public Short getPlacementX() {
		return this.placementX;
	}

	public void setPlacementX(Short placementX) {
		this.placementX = placementX;
	}

	@Column(name = "PLACEMENT_Y", precision = 3, scale = 0)
	public Short getPlacementY() {
		return this.placementY;
	}

	public void setPlacementY(Short placementY) {
		this.placementY = placementY;
	}

	@Column(name = "WIDTH", precision = 2, scale = 0)
	public Byte getWidth() {
		return this.width;
	}

	public void setWidth(Byte width) {
		this.width = width;
	}

	@Column(name = "ORDER_NUMBER", precision = 5, scale = 0)
	public Integer getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(Integer orderNumber) {
		this.orderNumber = orderNumber;
	}

	@Column(name = "ASSET_REFERENCE")
	public String getAssetReference() {
		return this.assetReference;
	}

	public void setAssetReference(String assetReference) {
		this.assetReference = assetReference;
	}

	@Column(name = "URL_REFERENCE")
	public String getUrlReference() {
		return this.urlReference;
	}

	public void setUrlReference(String urlReference) {
		this.urlReference = urlReference;
	}

	@Column(name = "PORTAL_ACTIVE", length = 1)
	public Character getPortalActive() {
		return this.portalActive;
	}

	public void setPortalActive(Character portalActive) {
		this.portalActive = portalActive;
	}

	@Column(name = "TOOLTIP", length = 4000)
	public String getTooltip() {
		return this.tooltip;
	}

	public void setTooltip(String tooltip) {
		this.tooltip = tooltip;
	}

	@Column(name = "SGPORTAL", length = 1)
	public Character getSgportal() {
		return this.sgportal;
	}

	public void setSgportal(Character sgportal) {
		this.sgportal = sgportal;
	}

}
