package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CableunitChghistFdbId generated by hbm2java
 */
@Embeddable
public class CableunitChghistFdbId implements java.io.Serializable {

	private String audId;
	private String audAction;
	private Serializable audTimestamp;
	private String audOsuser;
	private String audDbuser;
	private String audUserterminal;
	private String id;
	private Date crd;
	private Date crt;
	private String cru;
	private Date modd;
	private Date modt;
	private String modu;
	private Date deld;
	private Date delt;
	private String delu;
	private Date impd;
	private Date impt;
	private String impu;
	private Date expd;
	private Date expt;
	private String expu;
	private String anlAnlaegsnr;
	private String anlAnlaegsnavn;
	private Short anlKommunenr;
	private Boolean anlEjerkode;
	private Boolean anlAdmKode;
	private Boolean anlAnlaegsform;
	private String anlHovedanlaegsnr;
	private String anlAfleveringspunkt;
	private String anlNoegleboks;
	private Date anlIdriftDato;
	private Date anlForvIdriftDato;
	private Byte anlAnlaegsStatus;
	private String anlSalgskoncept;
	private BigDecimal RRating;
	private Date RRatingDate;
	private BigDecimal RNextRating;
	private Date RNextRatingDate;
	private Date sourceChgDate;
	private String sourceChgCode;
	private BigDecimal noInst;
	private BigDecimal noDumInst;
	private BigDecimal noAllInst;
	private Character reforhandlFlag;
	private Date reforhandlDate;
	private Date anlGenberegnetdato;
	private Date anlForhandlingsdato;
	private String primhfinfo;
	private String primanltype;
	private String primarykontrakt;
	private String aflpunkt;
	private String nglboxopsat;
	private String paralleldatanet;
	private String coaxloesning;
	private String fwaloesning;
	private Character retvejsduelfn3;
	private String primservlev;
	private String primarytidllev;
	private String priminternetlev;
	private String primarytelefonilev;
	private String primarydigstblev;
	private String primaryfrekvens;
	private String primkommune;
	private String primanlstatus;
	private Date expdate;
	private String signalforskilde;
	private BigDecimal noInstAbnm;
	private Long pottilsl;
	private Long akttilsl;
	private String mainZip;
	private Character sloejfe;
	private Character stik;
	private Character nyoprettet;
	private Character quickpot;
	private String primsf;
	private String returfrekvens;
	private String amheadend;
	private String prevAnlaegsnr;
	private String primsegmgroup;
	private String primpostcode;
	private String primcurrlev;
	private Date REtabldate;
	private Character aktivSag;
	private String calcKommune;
	private Character returvejokfn2;
	private Character returvejokfn3;
	private Character returvejok;
	private BigDecimal anlIHusleje;
	private String primaryklumaxhast;
	private String primaryklulntype;
	private String primaryklulnejer;
	private String primarykluintype;
	private String primarykluaftkap;
	private String primproj;
	private String primfap;
	private String decAslKapacitet;
	private Character voip;
	private BigDecimal udtagetvoip;
	private Long annr;
	private String primdekoder;
	private String primcompany;
	private Character sourceChgBool;
	private Long leasaar;
	private String refdebnr;
	private String refanlnr;
	private Date anlDatoinaktiv;
	private String primmunicipality;
	private Character allowPresale;
	private String logtrace;
	private Character dktv;

	public CableunitChghistFdbId() {
	}

	public CableunitChghistFdbId(String audId, String audAction,
			Serializable audTimestamp, String audOsuser, String audDbuser,
			String audUserterminal, String id, Date crd, Date crt, String cru,
			Date modd, Date modt, String modu, Date deld, Date delt,
			String delu, Date impd, Date impt, String impu, Date expd,
			Date expt, String expu, String anlAnlaegsnr, String anlAnlaegsnavn,
			Short anlKommunenr, Boolean anlEjerkode, Boolean anlAdmKode,
			Boolean anlAnlaegsform, String anlHovedanlaegsnr,
			String anlAfleveringspunkt, String anlNoegleboks,
			Date anlIdriftDato, Date anlForvIdriftDato, Byte anlAnlaegsStatus,
			String anlSalgskoncept, BigDecimal RRating, Date RRatingDate,
			BigDecimal RNextRating, Date RNextRatingDate, Date sourceChgDate,
			String sourceChgCode, BigDecimal noInst, BigDecimal noDumInst,
			BigDecimal noAllInst, Character reforhandlFlag,
			Date reforhandlDate, Date anlGenberegnetdato,
			Date anlForhandlingsdato, String primhfinfo, String primanltype,
			String primarykontrakt, String aflpunkt, String nglboxopsat,
			String paralleldatanet, String coaxloesning, String fwaloesning,
			Character retvejsduelfn3, String primservlev,
			String primarytidllev, String priminternetlev,
			String primarytelefonilev, String primarydigstblev,
			String primaryfrekvens, String primkommune, String primanlstatus,
			Date expdate, String signalforskilde, BigDecimal noInstAbnm,
			Long pottilsl, Long akttilsl, String mainZip, Character sloejfe,
			Character stik, Character nyoprettet, Character quickpot,
			String primsf, String returfrekvens, String amheadend,
			String prevAnlaegsnr, String primsegmgroup, String primpostcode,
			String primcurrlev, Date REtabldate, Character aktivSag,
			String calcKommune, Character returvejokfn2,
			Character returvejokfn3, Character returvejok,
			BigDecimal anlIHusleje, String primaryklumaxhast,
			String primaryklulntype, String primaryklulnejer,
			String primarykluintype, String primarykluaftkap, String primproj,
			String primfap, String decAslKapacitet, Character voip,
			BigDecimal udtagetvoip, Long annr, String primdekoder,
			String primcompany, Character sourceChgBool, Long leasaar,
			String refdebnr, String refanlnr, Date anlDatoinaktiv,
			String primmunicipality, Character allowPresale, String logtrace,
			Character dktv) {
		this.audId = audId;
		this.audAction = audAction;
		this.audTimestamp = audTimestamp;
		this.audOsuser = audOsuser;
		this.audDbuser = audDbuser;
		this.audUserterminal = audUserterminal;
		this.id = id;
		this.crd = crd;
		this.crt = crt;
		this.cru = cru;
		this.modd = modd;
		this.modt = modt;
		this.modu = modu;
		this.deld = deld;
		this.delt = delt;
		this.delu = delu;
		this.impd = impd;
		this.impt = impt;
		this.impu = impu;
		this.expd = expd;
		this.expt = expt;
		this.expu = expu;
		this.anlAnlaegsnr = anlAnlaegsnr;
		this.anlAnlaegsnavn = anlAnlaegsnavn;
		this.anlKommunenr = anlKommunenr;
		this.anlEjerkode = anlEjerkode;
		this.anlAdmKode = anlAdmKode;
		this.anlAnlaegsform = anlAnlaegsform;
		this.anlHovedanlaegsnr = anlHovedanlaegsnr;
		this.anlAfleveringspunkt = anlAfleveringspunkt;
		this.anlNoegleboks = anlNoegleboks;
		this.anlIdriftDato = anlIdriftDato;
		this.anlForvIdriftDato = anlForvIdriftDato;
		this.anlAnlaegsStatus = anlAnlaegsStatus;
		this.anlSalgskoncept = anlSalgskoncept;
		this.RRating = RRating;
		this.RRatingDate = RRatingDate;
		this.RNextRating = RNextRating;
		this.RNextRatingDate = RNextRatingDate;
		this.sourceChgDate = sourceChgDate;
		this.sourceChgCode = sourceChgCode;
		this.noInst = noInst;
		this.noDumInst = noDumInst;
		this.noAllInst = noAllInst;
		this.reforhandlFlag = reforhandlFlag;
		this.reforhandlDate = reforhandlDate;
		this.anlGenberegnetdato = anlGenberegnetdato;
		this.anlForhandlingsdato = anlForhandlingsdato;
		this.primhfinfo = primhfinfo;
		this.primanltype = primanltype;
		this.primarykontrakt = primarykontrakt;
		this.aflpunkt = aflpunkt;
		this.nglboxopsat = nglboxopsat;
		this.paralleldatanet = paralleldatanet;
		this.coaxloesning = coaxloesning;
		this.fwaloesning = fwaloesning;
		this.retvejsduelfn3 = retvejsduelfn3;
		this.primservlev = primservlev;
		this.primarytidllev = primarytidllev;
		this.priminternetlev = priminternetlev;
		this.primarytelefonilev = primarytelefonilev;
		this.primarydigstblev = primarydigstblev;
		this.primaryfrekvens = primaryfrekvens;
		this.primkommune = primkommune;
		this.primanlstatus = primanlstatus;
		this.expdate = expdate;
		this.signalforskilde = signalforskilde;
		this.noInstAbnm = noInstAbnm;
		this.pottilsl = pottilsl;
		this.akttilsl = akttilsl;
		this.mainZip = mainZip;
		this.sloejfe = sloejfe;
		this.stik = stik;
		this.nyoprettet = nyoprettet;
		this.quickpot = quickpot;
		this.primsf = primsf;
		this.returfrekvens = returfrekvens;
		this.amheadend = amheadend;
		this.prevAnlaegsnr = prevAnlaegsnr;
		this.primsegmgroup = primsegmgroup;
		this.primpostcode = primpostcode;
		this.primcurrlev = primcurrlev;
		this.REtabldate = REtabldate;
		this.aktivSag = aktivSag;
		this.calcKommune = calcKommune;
		this.returvejokfn2 = returvejokfn2;
		this.returvejokfn3 = returvejokfn3;
		this.returvejok = returvejok;
		this.anlIHusleje = anlIHusleje;
		this.primaryklumaxhast = primaryklumaxhast;
		this.primaryklulntype = primaryklulntype;
		this.primaryklulnejer = primaryklulnejer;
		this.primarykluintype = primarykluintype;
		this.primarykluaftkap = primarykluaftkap;
		this.primproj = primproj;
		this.primfap = primfap;
		this.decAslKapacitet = decAslKapacitet;
		this.voip = voip;
		this.udtagetvoip = udtagetvoip;
		this.annr = annr;
		this.primdekoder = primdekoder;
		this.primcompany = primcompany;
		this.sourceChgBool = sourceChgBool;
		this.leasaar = leasaar;
		this.refdebnr = refdebnr;
		this.refanlnr = refanlnr;
		this.anlDatoinaktiv = anlDatoinaktiv;
		this.primmunicipality = primmunicipality;
		this.allowPresale = allowPresale;
		this.logtrace = logtrace;
		this.dktv = dktv;
	}

	@Column(name = "AUD_ID", unique = true, length = 19)
	public String getAudId() {
		return this.audId;
	}

	public void setAudId(String audId) {
		this.audId = audId;
	}

	@Column(name = "AUD_ACTION", length = 50)
	public String getAudAction() {
		return this.audAction;
	}

	public void setAudAction(String audAction) {
		this.audAction = audAction;
	}

	@Column(name = "AUD_TIMESTAMP")
	public Serializable getAudTimestamp() {
		return this.audTimestamp;
	}

	public void setAudTimestamp(Serializable audTimestamp) {
		this.audTimestamp = audTimestamp;
	}

	@Column(name = "AUD_OSUSER", length = 50)
	public String getAudOsuser() {
		return this.audOsuser;
	}

	public void setAudOsuser(String audOsuser) {
		this.audOsuser = audOsuser;
	}

	@Column(name = "AUD_DBUSER", length = 50)
	public String getAudDbuser() {
		return this.audDbuser;
	}

	public void setAudDbuser(String audDbuser) {
		this.audDbuser = audDbuser;
	}

	@Column(name = "AUD_USERTERMINAL", length = 50)
	public String getAudUserterminal() {
		return this.audUserterminal;
	}

	public void setAudUserterminal(String audUserterminal) {
		this.audUserterminal = audUserterminal;
	}

	@Column(name = "ID", length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "ANL_ANLAEGSNR", length = 10)
	public String getAnlAnlaegsnr() {
		return this.anlAnlaegsnr;
	}

	public void setAnlAnlaegsnr(String anlAnlaegsnr) {
		this.anlAnlaegsnr = anlAnlaegsnr;
	}

	@Column(name = "ANL_ANLAEGSNAVN", length = 40)
	public String getAnlAnlaegsnavn() {
		return this.anlAnlaegsnavn;
	}

	public void setAnlAnlaegsnavn(String anlAnlaegsnavn) {
		this.anlAnlaegsnavn = anlAnlaegsnavn;
	}

	@Column(name = "ANL_KOMMUNENR", precision = 3, scale = 0)
	public Short getAnlKommunenr() {
		return this.anlKommunenr;
	}

	public void setAnlKommunenr(Short anlKommunenr) {
		this.anlKommunenr = anlKommunenr;
	}

	@Column(name = "ANL_EJERKODE", precision = 1, scale = 0)
	public Boolean getAnlEjerkode() {
		return this.anlEjerkode;
	}

	public void setAnlEjerkode(Boolean anlEjerkode) {
		this.anlEjerkode = anlEjerkode;
	}

	@Column(name = "ANL_ADM_KODE", precision = 1, scale = 0)
	public Boolean getAnlAdmKode() {
		return this.anlAdmKode;
	}

	public void setAnlAdmKode(Boolean anlAdmKode) {
		this.anlAdmKode = anlAdmKode;
	}

	@Column(name = "ANL_ANLAEGSFORM", precision = 1, scale = 0)
	public Boolean getAnlAnlaegsform() {
		return this.anlAnlaegsform;
	}

	public void setAnlAnlaegsform(Boolean anlAnlaegsform) {
		this.anlAnlaegsform = anlAnlaegsform;
	}

	@Column(name = "ANL_HOVEDANLAEGSNR", length = 11)
	public String getAnlHovedanlaegsnr() {
		return this.anlHovedanlaegsnr;
	}

	public void setAnlHovedanlaegsnr(String anlHovedanlaegsnr) {
		this.anlHovedanlaegsnr = anlHovedanlaegsnr;
	}

	@Column(name = "ANL_AFLEVERINGSPUNKT", length = 60)
	public String getAnlAfleveringspunkt() {
		return this.anlAfleveringspunkt;
	}

	public void setAnlAfleveringspunkt(String anlAfleveringspunkt) {
		this.anlAfleveringspunkt = anlAfleveringspunkt;
	}

	@Column(name = "ANL_NOEGLEBOKS", length = 60)
	public String getAnlNoegleboks() {
		return this.anlNoegleboks;
	}

	public void setAnlNoegleboks(String anlNoegleboks) {
		this.anlNoegleboks = anlNoegleboks;
	}

	@Column(name = "ANL_IDRIFT_DATO", length = 7)
	public Date getAnlIdriftDato() {
		return this.anlIdriftDato;
	}

	public void setAnlIdriftDato(Date anlIdriftDato) {
		this.anlIdriftDato = anlIdriftDato;
	}

	@Column(name = "ANL_FORV_IDRIFT_DATO", length = 7)
	public Date getAnlForvIdriftDato() {
		return this.anlForvIdriftDato;
	}

	public void setAnlForvIdriftDato(Date anlForvIdriftDato) {
		this.anlForvIdriftDato = anlForvIdriftDato;
	}

	@Column(name = "ANL_ANLAEGS_STATUS", precision = 2, scale = 0)
	public Byte getAnlAnlaegsStatus() {
		return this.anlAnlaegsStatus;
	}

	public void setAnlAnlaegsStatus(Byte anlAnlaegsStatus) {
		this.anlAnlaegsStatus = anlAnlaegsStatus;
	}

	@Column(name = "ANL_SALGSKONCEPT", length = 20)
	public String getAnlSalgskoncept() {
		return this.anlSalgskoncept;
	}

	public void setAnlSalgskoncept(String anlSalgskoncept) {
		this.anlSalgskoncept = anlSalgskoncept;
	}

	@Column(name = "R_RATING", precision = 22, scale = 0)
	public BigDecimal getRRating() {
		return this.RRating;
	}

	public void setRRating(BigDecimal RRating) {
		this.RRating = RRating;
	}

	@Column(name = "R_RATING_DATE", length = 7)
	public Date getRRatingDate() {
		return this.RRatingDate;
	}

	public void setRRatingDate(Date RRatingDate) {
		this.RRatingDate = RRatingDate;
	}

	@Column(name = "R_NEXT_RATING", precision = 22, scale = 0)
	public BigDecimal getRNextRating() {
		return this.RNextRating;
	}

	public void setRNextRating(BigDecimal RNextRating) {
		this.RNextRating = RNextRating;
	}

	@Column(name = "R_NEXT_RATING_DATE", length = 7)
	public Date getRNextRatingDate() {
		return this.RNextRatingDate;
	}

	public void setRNextRatingDate(Date RNextRatingDate) {
		this.RNextRatingDate = RNextRatingDate;
	}

	@Column(name = "SOURCE_CHG_DATE", length = 7)
	public Date getSourceChgDate() {
		return this.sourceChgDate;
	}

	public void setSourceChgDate(Date sourceChgDate) {
		this.sourceChgDate = sourceChgDate;
	}

	@Column(name = "SOURCE_CHG_CODE", length = 50)
	public String getSourceChgCode() {
		return this.sourceChgCode;
	}

	public void setSourceChgCode(String sourceChgCode) {
		this.sourceChgCode = sourceChgCode;
	}

	@Column(name = "NO_INST", precision = 22, scale = 0)
	public BigDecimal getNoInst() {
		return this.noInst;
	}

	public void setNoInst(BigDecimal noInst) {
		this.noInst = noInst;
	}

	@Column(name = "NO_DUM_INST", precision = 22, scale = 0)
	public BigDecimal getNoDumInst() {
		return this.noDumInst;
	}

	public void setNoDumInst(BigDecimal noDumInst) {
		this.noDumInst = noDumInst;
	}

	@Column(name = "NO_ALL_INST", precision = 22, scale = 0)
	public BigDecimal getNoAllInst() {
		return this.noAllInst;
	}

	public void setNoAllInst(BigDecimal noAllInst) {
		this.noAllInst = noAllInst;
	}

	@Column(name = "REFORHANDL_FLAG", length = 1)
	public Character getReforhandlFlag() {
		return this.reforhandlFlag;
	}

	public void setReforhandlFlag(Character reforhandlFlag) {
		this.reforhandlFlag = reforhandlFlag;
	}

	@Column(name = "REFORHANDL_DATE", length = 7)
	public Date getReforhandlDate() {
		return this.reforhandlDate;
	}

	public void setReforhandlDate(Date reforhandlDate) {
		this.reforhandlDate = reforhandlDate;
	}

	@Column(name = "ANL_GENBEREGNETDATO", length = 7)
	public Date getAnlGenberegnetdato() {
		return this.anlGenberegnetdato;
	}

	public void setAnlGenberegnetdato(Date anlGenberegnetdato) {
		this.anlGenberegnetdato = anlGenberegnetdato;
	}

	@Column(name = "ANL_FORHANDLINGSDATO", length = 7)
	public Date getAnlForhandlingsdato() {
		return this.anlForhandlingsdato;
	}

	public void setAnlForhandlingsdato(Date anlForhandlingsdato) {
		this.anlForhandlingsdato = anlForhandlingsdato;
	}

	@Column(name = "PRIMHFINFO", length = 19)
	public String getPrimhfinfo() {
		return this.primhfinfo;
	}

	public void setPrimhfinfo(String primhfinfo) {
		this.primhfinfo = primhfinfo;
	}

	@Column(name = "PRIMANLTYPE", length = 19)
	public String getPrimanltype() {
		return this.primanltype;
	}

	public void setPrimanltype(String primanltype) {
		this.primanltype = primanltype;
	}

	@Column(name = "PRIMARYKONTRAKT", length = 19)
	public String getPrimarykontrakt() {
		return this.primarykontrakt;
	}

	public void setPrimarykontrakt(String primarykontrakt) {
		this.primarykontrakt = primarykontrakt;
	}

	@Column(name = "AFLPUNKT")
	public String getAflpunkt() {
		return this.aflpunkt;
	}

	public void setAflpunkt(String aflpunkt) {
		this.aflpunkt = aflpunkt;
	}

	@Column(name = "NGLBOXOPSAT")
	public String getNglboxopsat() {
		return this.nglboxopsat;
	}

	public void setNglboxopsat(String nglboxopsat) {
		this.nglboxopsat = nglboxopsat;
	}

	@Column(name = "PARALLELDATANET")
	public String getParalleldatanet() {
		return this.paralleldatanet;
	}

	public void setParalleldatanet(String paralleldatanet) {
		this.paralleldatanet = paralleldatanet;
	}

	@Column(name = "COAXLOESNING")
	public String getCoaxloesning() {
		return this.coaxloesning;
	}

	public void setCoaxloesning(String coaxloesning) {
		this.coaxloesning = coaxloesning;
	}

	@Column(name = "FWALOESNING")
	public String getFwaloesning() {
		return this.fwaloesning;
	}

	public void setFwaloesning(String fwaloesning) {
		this.fwaloesning = fwaloesning;
	}

	@Column(name = "RETVEJSDUELFN3", length = 1)
	public Character getRetvejsduelfn3() {
		return this.retvejsduelfn3;
	}

	public void setRetvejsduelfn3(Character retvejsduelfn3) {
		this.retvejsduelfn3 = retvejsduelfn3;
	}

	@Column(name = "PRIMSERVLEV", length = 19)
	public String getPrimservlev() {
		return this.primservlev;
	}

	public void setPrimservlev(String primservlev) {
		this.primservlev = primservlev;
	}

	@Column(name = "PRIMARYTIDLLEV", length = 19)
	public String getPrimarytidllev() {
		return this.primarytidllev;
	}

	public void setPrimarytidllev(String primarytidllev) {
		this.primarytidllev = primarytidllev;
	}

	@Column(name = "PRIMINTERNETLEV", length = 19)
	public String getPriminternetlev() {
		return this.priminternetlev;
	}

	public void setPriminternetlev(String priminternetlev) {
		this.priminternetlev = priminternetlev;
	}

	@Column(name = "PRIMARYTELEFONILEV", length = 19)
	public String getPrimarytelefonilev() {
		return this.primarytelefonilev;
	}

	public void setPrimarytelefonilev(String primarytelefonilev) {
		this.primarytelefonilev = primarytelefonilev;
	}

	@Column(name = "PRIMARYDIGSTBLEV", length = 19)
	public String getPrimarydigstblev() {
		return this.primarydigstblev;
	}

	public void setPrimarydigstblev(String primarydigstblev) {
		this.primarydigstblev = primarydigstblev;
	}

	@Column(name = "PRIMARYFREKVENS", length = 19)
	public String getPrimaryfrekvens() {
		return this.primaryfrekvens;
	}

	public void setPrimaryfrekvens(String primaryfrekvens) {
		this.primaryfrekvens = primaryfrekvens;
	}

	@Column(name = "PRIMKOMMUNE", length = 19)
	public String getPrimkommune() {
		return this.primkommune;
	}

	public void setPrimkommune(String primkommune) {
		this.primkommune = primkommune;
	}

	@Column(name = "PRIMANLSTATUS", length = 19)
	public String getPrimanlstatus() {
		return this.primanlstatus;
	}

	public void setPrimanlstatus(String primanlstatus) {
		this.primanlstatus = primanlstatus;
	}

	@Column(name = "EXPDATE", length = 7)
	public Date getExpdate() {
		return this.expdate;
	}

	public void setExpdate(Date expdate) {
		this.expdate = expdate;
	}

	@Column(name = "SIGNALFORSKILDE")
	public String getSignalforskilde() {
		return this.signalforskilde;
	}

	public void setSignalforskilde(String signalforskilde) {
		this.signalforskilde = signalforskilde;
	}

	@Column(name = "NO_INST_ABNM", precision = 22, scale = 0)
	public BigDecimal getNoInstAbnm() {
		return this.noInstAbnm;
	}

	public void setNoInstAbnm(BigDecimal noInstAbnm) {
		this.noInstAbnm = noInstAbnm;
	}

	@Column(name = "POTTILSL", precision = 10, scale = 0)
	public Long getPottilsl() {
		return this.pottilsl;
	}

	public void setPottilsl(Long pottilsl) {
		this.pottilsl = pottilsl;
	}

	@Column(name = "AKTTILSL", precision = 10, scale = 0)
	public Long getAkttilsl() {
		return this.akttilsl;
	}

	public void setAkttilsl(Long akttilsl) {
		this.akttilsl = akttilsl;
	}

	@Column(name = "MAIN_ZIP", length = 4)
	public String getMainZip() {
		return this.mainZip;
	}

	public void setMainZip(String mainZip) {
		this.mainZip = mainZip;
	}

	@Column(name = "SLOEJFE", length = 1)
	public Character getSloejfe() {
		return this.sloejfe;
	}

	public void setSloejfe(Character sloejfe) {
		this.sloejfe = sloejfe;
	}

	@Column(name = "STIK", length = 1)
	public Character getStik() {
		return this.stik;
	}

	public void setStik(Character stik) {
		this.stik = stik;
	}

	@Column(name = "NYOPRETTET", length = 1)
	public Character getNyoprettet() {
		return this.nyoprettet;
	}

	public void setNyoprettet(Character nyoprettet) {
		this.nyoprettet = nyoprettet;
	}

	@Column(name = "QUICKPOT", length = 1)
	public Character getQuickpot() {
		return this.quickpot;
	}

	public void setQuickpot(Character quickpot) {
		this.quickpot = quickpot;
	}

	@Column(name = "PRIMSF", length = 19)
	public String getPrimsf() {
		return this.primsf;
	}

	public void setPrimsf(String primsf) {
		this.primsf = primsf;
	}

	@Column(name = "RETURFREKVENS", length = 20)
	public String getReturfrekvens() {
		return this.returfrekvens;
	}

	public void setReturfrekvens(String returfrekvens) {
		this.returfrekvens = returfrekvens;
	}

	@Column(name = "AMHEADEND", length = 5)
	public String getAmheadend() {
		return this.amheadend;
	}

	public void setAmheadend(String amheadend) {
		this.amheadend = amheadend;
	}

	@Column(name = "PREV_ANLAEGSNR", length = 20)
	public String getPrevAnlaegsnr() {
		return this.prevAnlaegsnr;
	}

	public void setPrevAnlaegsnr(String prevAnlaegsnr) {
		this.prevAnlaegsnr = prevAnlaegsnr;
	}

	@Column(name = "PRIMSEGMGROUP", length = 19)
	public String getPrimsegmgroup() {
		return this.primsegmgroup;
	}

	public void setPrimsegmgroup(String primsegmgroup) {
		this.primsegmgroup = primsegmgroup;
	}

	@Column(name = "PRIMPOSTCODE", length = 19)
	public String getPrimpostcode() {
		return this.primpostcode;
	}

	public void setPrimpostcode(String primpostcode) {
		this.primpostcode = primpostcode;
	}

	@Column(name = "PRIMCURRLEV", length = 19)
	public String getPrimcurrlev() {
		return this.primcurrlev;
	}

	public void setPrimcurrlev(String primcurrlev) {
		this.primcurrlev = primcurrlev;
	}

	@Column(name = "R_ETABLDATE", length = 7)
	public Date getREtabldate() {
		return this.REtabldate;
	}

	public void setREtabldate(Date REtabldate) {
		this.REtabldate = REtabldate;
	}

	@Column(name = "AKTIV_SAG", length = 1)
	public Character getAktivSag() {
		return this.aktivSag;
	}

	public void setAktivSag(Character aktivSag) {
		this.aktivSag = aktivSag;
	}

	@Column(name = "CALC_KOMMUNE", length = 19)
	public String getCalcKommune() {
		return this.calcKommune;
	}

	public void setCalcKommune(String calcKommune) {
		this.calcKommune = calcKommune;
	}

	@Column(name = "RETURVEJOKFN2", length = 1)
	public Character getReturvejokfn2() {
		return this.returvejokfn2;
	}

	public void setReturvejokfn2(Character returvejokfn2) {
		this.returvejokfn2 = returvejokfn2;
	}

	@Column(name = "RETURVEJOKFN3", length = 1)
	public Character getReturvejokfn3() {
		return this.returvejokfn3;
	}

	public void setReturvejokfn3(Character returvejokfn3) {
		this.returvejokfn3 = returvejokfn3;
	}

	@Column(name = "RETURVEJOK", length = 1)
	public Character getReturvejok() {
		return this.returvejok;
	}

	public void setReturvejok(Character returvejok) {
		this.returvejok = returvejok;
	}

	@Column(name = "ANL_I_HUSLEJE", precision = 22, scale = 0)
	public BigDecimal getAnlIHusleje() {
		return this.anlIHusleje;
	}

	public void setAnlIHusleje(BigDecimal anlIHusleje) {
		this.anlIHusleje = anlIHusleje;
	}

	@Column(name = "PRIMARYKLUMAXHAST", length = 19)
	public String getPrimaryklumaxhast() {
		return this.primaryklumaxhast;
	}

	public void setPrimaryklumaxhast(String primaryklumaxhast) {
		this.primaryklumaxhast = primaryklumaxhast;
	}

	@Column(name = "PRIMARYKLULNTYPE", length = 19)
	public String getPrimaryklulntype() {
		return this.primaryklulntype;
	}

	public void setPrimaryklulntype(String primaryklulntype) {
		this.primaryklulntype = primaryklulntype;
	}

	@Column(name = "PRIMARYKLULNEJER", length = 19)
	public String getPrimaryklulnejer() {
		return this.primaryklulnejer;
	}

	public void setPrimaryklulnejer(String primaryklulnejer) {
		this.primaryklulnejer = primaryklulnejer;
	}

	@Column(name = "PRIMARYKLUINTYPE", length = 19)
	public String getPrimarykluintype() {
		return this.primarykluintype;
	}

	public void setPrimarykluintype(String primarykluintype) {
		this.primarykluintype = primarykluintype;
	}

	@Column(name = "PRIMARYKLUAFTKAP", length = 19)
	public String getPrimarykluaftkap() {
		return this.primarykluaftkap;
	}

	public void setPrimarykluaftkap(String primarykluaftkap) {
		this.primarykluaftkap = primarykluaftkap;
	}

	@Column(name = "PRIMPROJ", length = 19)
	public String getPrimproj() {
		return this.primproj;
	}

	public void setPrimproj(String primproj) {
		this.primproj = primproj;
	}

	@Column(name = "PRIMFAP", length = 19)
	public String getPrimfap() {
		return this.primfap;
	}

	public void setPrimfap(String primfap) {
		this.primfap = primfap;
	}

	@Column(name = "DEC_ASL_KAPACITET")
	public String getDecAslKapacitet() {
		return this.decAslKapacitet;
	}

	public void setDecAslKapacitet(String decAslKapacitet) {
		this.decAslKapacitet = decAslKapacitet;
	}

	@Column(name = "VOIP", length = 1)
	public Character getVoip() {
		return this.voip;
	}

	public void setVoip(Character voip) {
		this.voip = voip;
	}

	@Column(name = "UDTAGETVOIP", precision = 22, scale = 0)
	public BigDecimal getUdtagetvoip() {
		return this.udtagetvoip;
	}

	public void setUdtagetvoip(BigDecimal udtagetvoip) {
		this.udtagetvoip = udtagetvoip;
	}

	@Column(name = "ANNR", precision = 10, scale = 0)
	public Long getAnnr() {
		return this.annr;
	}

	public void setAnnr(Long annr) {
		this.annr = annr;
	}

	@Column(name = "PRIMDEKODER", length = 19)
	public String getPrimdekoder() {
		return this.primdekoder;
	}

	public void setPrimdekoder(String primdekoder) {
		this.primdekoder = primdekoder;
	}

	@Column(name = "PRIMCOMPANY", length = 19)
	public String getPrimcompany() {
		return this.primcompany;
	}

	public void setPrimcompany(String primcompany) {
		this.primcompany = primcompany;
	}

	@Column(name = "SOURCE_CHG_BOOL", length = 1)
	public Character getSourceChgBool() {
		return this.sourceChgBool;
	}

	public void setSourceChgBool(Character sourceChgBool) {
		this.sourceChgBool = sourceChgBool;
	}

	@Column(name = "LEASAAR", precision = 10, scale = 0)
	public Long getLeasaar() {
		return this.leasaar;
	}

	public void setLeasaar(Long leasaar) {
		this.leasaar = leasaar;
	}

	@Column(name = "REFDEBNR", length = 10)
	public String getRefdebnr() {
		return this.refdebnr;
	}

	public void setRefdebnr(String refdebnr) {
		this.refdebnr = refdebnr;
	}

	@Column(name = "REFANLNR", length = 10)
	public String getRefanlnr() {
		return this.refanlnr;
	}

	public void setRefanlnr(String refanlnr) {
		this.refanlnr = refanlnr;
	}

	@Column(name = "ANL_DATOINAKTIV", length = 7)
	public Date getAnlDatoinaktiv() {
		return this.anlDatoinaktiv;
	}

	public void setAnlDatoinaktiv(Date anlDatoinaktiv) {
		this.anlDatoinaktiv = anlDatoinaktiv;
	}

	@Column(name = "PRIMMUNICIPALITY", length = 19)
	public String getPrimmunicipality() {
		return this.primmunicipality;
	}

	public void setPrimmunicipality(String primmunicipality) {
		this.primmunicipality = primmunicipality;
	}

	@Column(name = "ALLOW_PRESALE", length = 1)
	public Character getAllowPresale() {
		return this.allowPresale;
	}

	public void setAllowPresale(Character allowPresale) {
		this.allowPresale = allowPresale;
	}

	@Column(name = "LOGTRACE", length = 19)
	public String getLogtrace() {
		return this.logtrace;
	}

	public void setLogtrace(String logtrace) {
		this.logtrace = logtrace;
	}

	@Column(name = "DKTV", length = 1)
	public Character getDktv() {
		return this.dktv;
	}

	public void setDktv(Character dktv) {
		this.dktv = dktv;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CableunitChghistFdbId))
			return false;
		CableunitChghistFdbId castOther = (CableunitChghistFdbId) other;

		return ((this.getAudId() == castOther.getAudId()) || (this.getAudId() != null
				&& castOther.getAudId() != null && this.getAudId().equals(
				castOther.getAudId())))
				&& ((this.getAudAction() == castOther.getAudAction()) || (this
						.getAudAction() != null
						&& castOther.getAudAction() != null && this
						.getAudAction().equals(castOther.getAudAction())))
				&& ((this.getAudTimestamp() == castOther.getAudTimestamp()) || (this
						.getAudTimestamp() != null
						&& castOther.getAudTimestamp() != null && this
						.getAudTimestamp().equals(castOther.getAudTimestamp())))
				&& ((this.getAudOsuser() == castOther.getAudOsuser()) || (this
						.getAudOsuser() != null
						&& castOther.getAudOsuser() != null && this
						.getAudOsuser().equals(castOther.getAudOsuser())))
				&& ((this.getAudDbuser() == castOther.getAudDbuser()) || (this
						.getAudDbuser() != null
						&& castOther.getAudDbuser() != null && this
						.getAudDbuser().equals(castOther.getAudDbuser())))
				&& ((this.getAudUserterminal() == castOther
						.getAudUserterminal()) || (this.getAudUserterminal() != null
						&& castOther.getAudUserterminal() != null && this
						.getAudUserterminal().equals(
								castOther.getAudUserterminal())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null
						&& castOther.getId() != null && this.getId().equals(
						castOther.getId())))
				&& ((this.getCrd() == castOther.getCrd()) || (this.getCrd() != null
						&& castOther.getCrd() != null && this.getCrd().equals(
						castOther.getCrd())))
				&& ((this.getCrt() == castOther.getCrt()) || (this.getCrt() != null
						&& castOther.getCrt() != null && this.getCrt().equals(
						castOther.getCrt())))
				&& ((this.getCru() == castOther.getCru()) || (this.getCru() != null
						&& castOther.getCru() != null && this.getCru().equals(
						castOther.getCru())))
				&& ((this.getModd() == castOther.getModd()) || (this.getModd() != null
						&& castOther.getModd() != null && this.getModd()
						.equals(castOther.getModd())))
				&& ((this.getModt() == castOther.getModt()) || (this.getModt() != null
						&& castOther.getModt() != null && this.getModt()
						.equals(castOther.getModt())))
				&& ((this.getModu() == castOther.getModu()) || (this.getModu() != null
						&& castOther.getModu() != null && this.getModu()
						.equals(castOther.getModu())))
				&& ((this.getDeld() == castOther.getDeld()) || (this.getDeld() != null
						&& castOther.getDeld() != null && this.getDeld()
						.equals(castOther.getDeld())))
				&& ((this.getDelt() == castOther.getDelt()) || (this.getDelt() != null
						&& castOther.getDelt() != null && this.getDelt()
						.equals(castOther.getDelt())))
				&& ((this.getDelu() == castOther.getDelu()) || (this.getDelu() != null
						&& castOther.getDelu() != null && this.getDelu()
						.equals(castOther.getDelu())))
				&& ((this.getImpd() == castOther.getImpd()) || (this.getImpd() != null
						&& castOther.getImpd() != null && this.getImpd()
						.equals(castOther.getImpd())))
				&& ((this.getImpt() == castOther.getImpt()) || (this.getImpt() != null
						&& castOther.getImpt() != null && this.getImpt()
						.equals(castOther.getImpt())))
				&& ((this.getImpu() == castOther.getImpu()) || (this.getImpu() != null
						&& castOther.getImpu() != null && this.getImpu()
						.equals(castOther.getImpu())))
				&& ((this.getExpd() == castOther.getExpd()) || (this.getExpd() != null
						&& castOther.getExpd() != null && this.getExpd()
						.equals(castOther.getExpd())))
				&& ((this.getExpt() == castOther.getExpt()) || (this.getExpt() != null
						&& castOther.getExpt() != null && this.getExpt()
						.equals(castOther.getExpt())))
				&& ((this.getExpu() == castOther.getExpu()) || (this.getExpu() != null
						&& castOther.getExpu() != null && this.getExpu()
						.equals(castOther.getExpu())))
				&& ((this.getAnlAnlaegsnr() == castOther.getAnlAnlaegsnr()) || (this
						.getAnlAnlaegsnr() != null
						&& castOther.getAnlAnlaegsnr() != null && this
						.getAnlAnlaegsnr().equals(castOther.getAnlAnlaegsnr())))
				&& ((this.getAnlAnlaegsnavn() == castOther.getAnlAnlaegsnavn()) || (this
						.getAnlAnlaegsnavn() != null
						&& castOther.getAnlAnlaegsnavn() != null && this
						.getAnlAnlaegsnavn().equals(
								castOther.getAnlAnlaegsnavn())))
				&& ((this.getAnlKommunenr() == castOther.getAnlKommunenr()) || (this
						.getAnlKommunenr() != null
						&& castOther.getAnlKommunenr() != null && this
						.getAnlKommunenr().equals(castOther.getAnlKommunenr())))
				&& ((this.getAnlEjerkode() == castOther.getAnlEjerkode()) || (this
						.getAnlEjerkode() != null
						&& castOther.getAnlEjerkode() != null && this
						.getAnlEjerkode().equals(castOther.getAnlEjerkode())))
				&& ((this.getAnlAdmKode() == castOther.getAnlAdmKode()) || (this
						.getAnlAdmKode() != null
						&& castOther.getAnlAdmKode() != null && this
						.getAnlAdmKode().equals(castOther.getAnlAdmKode())))
				&& ((this.getAnlAnlaegsform() == castOther.getAnlAnlaegsform()) || (this
						.getAnlAnlaegsform() != null
						&& castOther.getAnlAnlaegsform() != null && this
						.getAnlAnlaegsform().equals(
								castOther.getAnlAnlaegsform())))
				&& ((this.getAnlHovedanlaegsnr() == castOther
						.getAnlHovedanlaegsnr()) || (this
						.getAnlHovedanlaegsnr() != null
						&& castOther.getAnlHovedanlaegsnr() != null && this
						.getAnlHovedanlaegsnr().equals(
								castOther.getAnlHovedanlaegsnr())))
				&& ((this.getAnlAfleveringspunkt() == castOther
						.getAnlAfleveringspunkt()) || (this
						.getAnlAfleveringspunkt() != null
						&& castOther.getAnlAfleveringspunkt() != null && this
						.getAnlAfleveringspunkt().equals(
								castOther.getAnlAfleveringspunkt())))
				&& ((this.getAnlNoegleboks() == castOther.getAnlNoegleboks()) || (this
						.getAnlNoegleboks() != null
						&& castOther.getAnlNoegleboks() != null && this
						.getAnlNoegleboks()
						.equals(castOther.getAnlNoegleboks())))
				&& ((this.getAnlIdriftDato() == castOther.getAnlIdriftDato()) || (this
						.getAnlIdriftDato() != null
						&& castOther.getAnlIdriftDato() != null && this
						.getAnlIdriftDato()
						.equals(castOther.getAnlIdriftDato())))
				&& ((this.getAnlForvIdriftDato() == castOther
						.getAnlForvIdriftDato()) || (this
						.getAnlForvIdriftDato() != null
						&& castOther.getAnlForvIdriftDato() != null && this
						.getAnlForvIdriftDato().equals(
								castOther.getAnlForvIdriftDato())))
				&& ((this.getAnlAnlaegsStatus() == castOther
						.getAnlAnlaegsStatus()) || (this.getAnlAnlaegsStatus() != null
						&& castOther.getAnlAnlaegsStatus() != null && this
						.getAnlAnlaegsStatus().equals(
								castOther.getAnlAnlaegsStatus())))
				&& ((this.getAnlSalgskoncept() == castOther
						.getAnlSalgskoncept()) || (this.getAnlSalgskoncept() != null
						&& castOther.getAnlSalgskoncept() != null && this
						.getAnlSalgskoncept().equals(
								castOther.getAnlSalgskoncept())))
				&& ((this.getRRating() == castOther.getRRating()) || (this
						.getRRating() != null && castOther.getRRating() != null && this
						.getRRating().equals(castOther.getRRating())))
				&& ((this.getRRatingDate() == castOther.getRRatingDate()) || (this
						.getRRatingDate() != null
						&& castOther.getRRatingDate() != null && this
						.getRRatingDate().equals(castOther.getRRatingDate())))
				&& ((this.getRNextRating() == castOther.getRNextRating()) || (this
						.getRNextRating() != null
						&& castOther.getRNextRating() != null && this
						.getRNextRating().equals(castOther.getRNextRating())))
				&& ((this.getRNextRatingDate() == castOther
						.getRNextRatingDate()) || (this.getRNextRatingDate() != null
						&& castOther.getRNextRatingDate() != null && this
						.getRNextRatingDate().equals(
								castOther.getRNextRatingDate())))
				&& ((this.getSourceChgDate() == castOther.getSourceChgDate()) || (this
						.getSourceChgDate() != null
						&& castOther.getSourceChgDate() != null && this
						.getSourceChgDate()
						.equals(castOther.getSourceChgDate())))
				&& ((this.getSourceChgCode() == castOther.getSourceChgCode()) || (this
						.getSourceChgCode() != null
						&& castOther.getSourceChgCode() != null && this
						.getSourceChgCode()
						.equals(castOther.getSourceChgCode())))
				&& ((this.getNoInst() == castOther.getNoInst()) || (this
						.getNoInst() != null && castOther.getNoInst() != null && this
						.getNoInst().equals(castOther.getNoInst())))
				&& ((this.getNoDumInst() == castOther.getNoDumInst()) || (this
						.getNoDumInst() != null
						&& castOther.getNoDumInst() != null && this
						.getNoDumInst().equals(castOther.getNoDumInst())))
				&& ((this.getNoAllInst() == castOther.getNoAllInst()) || (this
						.getNoAllInst() != null
						&& castOther.getNoAllInst() != null && this
						.getNoAllInst().equals(castOther.getNoAllInst())))
				&& ((this.getReforhandlFlag() == castOther.getReforhandlFlag()) || (this
						.getReforhandlFlag() != null
						&& castOther.getReforhandlFlag() != null && this
						.getReforhandlFlag().equals(
								castOther.getReforhandlFlag())))
				&& ((this.getReforhandlDate() == castOther.getReforhandlDate()) || (this
						.getReforhandlDate() != null
						&& castOther.getReforhandlDate() != null && this
						.getReforhandlDate().equals(
								castOther.getReforhandlDate())))
				&& ((this.getAnlGenberegnetdato() == castOther
						.getAnlGenberegnetdato()) || (this
						.getAnlGenberegnetdato() != null
						&& castOther.getAnlGenberegnetdato() != null && this
						.getAnlGenberegnetdato().equals(
								castOther.getAnlGenberegnetdato())))
				&& ((this.getAnlForhandlingsdato() == castOther
						.getAnlForhandlingsdato()) || (this
						.getAnlForhandlingsdato() != null
						&& castOther.getAnlForhandlingsdato() != null && this
						.getAnlForhandlingsdato().equals(
								castOther.getAnlForhandlingsdato())))
				&& ((this.getPrimhfinfo() == castOther.getPrimhfinfo()) || (this
						.getPrimhfinfo() != null
						&& castOther.getPrimhfinfo() != null && this
						.getPrimhfinfo().equals(castOther.getPrimhfinfo())))
				&& ((this.getPrimanltype() == castOther.getPrimanltype()) || (this
						.getPrimanltype() != null
						&& castOther.getPrimanltype() != null && this
						.getPrimanltype().equals(castOther.getPrimanltype())))
				&& ((this.getPrimarykontrakt() == castOther
						.getPrimarykontrakt()) || (this.getPrimarykontrakt() != null
						&& castOther.getPrimarykontrakt() != null && this
						.getPrimarykontrakt().equals(
								castOther.getPrimarykontrakt())))
				&& ((this.getAflpunkt() == castOther.getAflpunkt()) || (this
						.getAflpunkt() != null
						&& castOther.getAflpunkt() != null && this
						.getAflpunkt().equals(castOther.getAflpunkt())))
				&& ((this.getNglboxopsat() == castOther.getNglboxopsat()) || (this
						.getNglboxopsat() != null
						&& castOther.getNglboxopsat() != null && this
						.getNglboxopsat().equals(castOther.getNglboxopsat())))
				&& ((this.getParalleldatanet() == castOther
						.getParalleldatanet()) || (this.getParalleldatanet() != null
						&& castOther.getParalleldatanet() != null && this
						.getParalleldatanet().equals(
								castOther.getParalleldatanet())))
				&& ((this.getCoaxloesning() == castOther.getCoaxloesning()) || (this
						.getCoaxloesning() != null
						&& castOther.getCoaxloesning() != null && this
						.getCoaxloesning().equals(castOther.getCoaxloesning())))
				&& ((this.getFwaloesning() == castOther.getFwaloesning()) || (this
						.getFwaloesning() != null
						&& castOther.getFwaloesning() != null && this
						.getFwaloesning().equals(castOther.getFwaloesning())))
				&& ((this.getRetvejsduelfn3() == castOther.getRetvejsduelfn3()) || (this
						.getRetvejsduelfn3() != null
						&& castOther.getRetvejsduelfn3() != null && this
						.getRetvejsduelfn3().equals(
								castOther.getRetvejsduelfn3())))
				&& ((this.getPrimservlev() == castOther.getPrimservlev()) || (this
						.getPrimservlev() != null
						&& castOther.getPrimservlev() != null && this
						.getPrimservlev().equals(castOther.getPrimservlev())))
				&& ((this.getPrimarytidllev() == castOther.getPrimarytidllev()) || (this
						.getPrimarytidllev() != null
						&& castOther.getPrimarytidllev() != null && this
						.getPrimarytidllev().equals(
								castOther.getPrimarytidllev())))
				&& ((this.getPriminternetlev() == castOther
						.getPriminternetlev()) || (this.getPriminternetlev() != null
						&& castOther.getPriminternetlev() != null && this
						.getPriminternetlev().equals(
								castOther.getPriminternetlev())))
				&& ((this.getPrimarytelefonilev() == castOther
						.getPrimarytelefonilev()) || (this
						.getPrimarytelefonilev() != null
						&& castOther.getPrimarytelefonilev() != null && this
						.getPrimarytelefonilev().equals(
								castOther.getPrimarytelefonilev())))
				&& ((this.getPrimarydigstblev() == castOther
						.getPrimarydigstblev()) || (this.getPrimarydigstblev() != null
						&& castOther.getPrimarydigstblev() != null && this
						.getPrimarydigstblev().equals(
								castOther.getPrimarydigstblev())))
				&& ((this.getPrimaryfrekvens() == castOther
						.getPrimaryfrekvens()) || (this.getPrimaryfrekvens() != null
						&& castOther.getPrimaryfrekvens() != null && this
						.getPrimaryfrekvens().equals(
								castOther.getPrimaryfrekvens())))
				&& ((this.getPrimkommune() == castOther.getPrimkommune()) || (this
						.getPrimkommune() != null
						&& castOther.getPrimkommune() != null && this
						.getPrimkommune().equals(castOther.getPrimkommune())))
				&& ((this.getPrimanlstatus() == castOther.getPrimanlstatus()) || (this
						.getPrimanlstatus() != null
						&& castOther.getPrimanlstatus() != null && this
						.getPrimanlstatus()
						.equals(castOther.getPrimanlstatus())))
				&& ((this.getExpdate() == castOther.getExpdate()) || (this
						.getExpdate() != null && castOther.getExpdate() != null && this
						.getExpdate().equals(castOther.getExpdate())))
				&& ((this.getSignalforskilde() == castOther
						.getSignalforskilde()) || (this.getSignalforskilde() != null
						&& castOther.getSignalforskilde() != null && this
						.getSignalforskilde().equals(
								castOther.getSignalforskilde())))
				&& ((this.getNoInstAbnm() == castOther.getNoInstAbnm()) || (this
						.getNoInstAbnm() != null
						&& castOther.getNoInstAbnm() != null && this
						.getNoInstAbnm().equals(castOther.getNoInstAbnm())))
				&& ((this.getPottilsl() == castOther.getPottilsl()) || (this
						.getPottilsl() != null
						&& castOther.getPottilsl() != null && this
						.getPottilsl().equals(castOther.getPottilsl())))
				&& ((this.getAkttilsl() == castOther.getAkttilsl()) || (this
						.getAkttilsl() != null
						&& castOther.getAkttilsl() != null && this
						.getAkttilsl().equals(castOther.getAkttilsl())))
				&& ((this.getMainZip() == castOther.getMainZip()) || (this
						.getMainZip() != null && castOther.getMainZip() != null && this
						.getMainZip().equals(castOther.getMainZip())))
				&& ((this.getSloejfe() == castOther.getSloejfe()) || (this
						.getSloejfe() != null && castOther.getSloejfe() != null && this
						.getSloejfe().equals(castOther.getSloejfe())))
				&& ((this.getStik() == castOther.getStik()) || (this.getStik() != null
						&& castOther.getStik() != null && this.getStik()
						.equals(castOther.getStik())))
				&& ((this.getNyoprettet() == castOther.getNyoprettet()) || (this
						.getNyoprettet() != null
						&& castOther.getNyoprettet() != null && this
						.getNyoprettet().equals(castOther.getNyoprettet())))
				&& ((this.getQuickpot() == castOther.getQuickpot()) || (this
						.getQuickpot() != null
						&& castOther.getQuickpot() != null && this
						.getQuickpot().equals(castOther.getQuickpot())))
				&& ((this.getPrimsf() == castOther.getPrimsf()) || (this
						.getPrimsf() != null && castOther.getPrimsf() != null && this
						.getPrimsf().equals(castOther.getPrimsf())))
				&& ((this.getReturfrekvens() == castOther.getReturfrekvens()) || (this
						.getReturfrekvens() != null
						&& castOther.getReturfrekvens() != null && this
						.getReturfrekvens()
						.equals(castOther.getReturfrekvens())))
				&& ((this.getAmheadend() == castOther.getAmheadend()) || (this
						.getAmheadend() != null
						&& castOther.getAmheadend() != null && this
						.getAmheadend().equals(castOther.getAmheadend())))
				&& ((this.getPrevAnlaegsnr() == castOther.getPrevAnlaegsnr()) || (this
						.getPrevAnlaegsnr() != null
						&& castOther.getPrevAnlaegsnr() != null && this
						.getPrevAnlaegsnr()
						.equals(castOther.getPrevAnlaegsnr())))
				&& ((this.getPrimsegmgroup() == castOther.getPrimsegmgroup()) || (this
						.getPrimsegmgroup() != null
						&& castOther.getPrimsegmgroup() != null && this
						.getPrimsegmgroup()
						.equals(castOther.getPrimsegmgroup())))
				&& ((this.getPrimpostcode() == castOther.getPrimpostcode()) || (this
						.getPrimpostcode() != null
						&& castOther.getPrimpostcode() != null && this
						.getPrimpostcode().equals(castOther.getPrimpostcode())))
				&& ((this.getPrimcurrlev() == castOther.getPrimcurrlev()) || (this
						.getPrimcurrlev() != null
						&& castOther.getPrimcurrlev() != null && this
						.getPrimcurrlev().equals(castOther.getPrimcurrlev())))
				&& ((this.getREtabldate() == castOther.getREtabldate()) || (this
						.getREtabldate() != null
						&& castOther.getREtabldate() != null && this
						.getREtabldate().equals(castOther.getREtabldate())))
				&& ((this.getAktivSag() == castOther.getAktivSag()) || (this
						.getAktivSag() != null
						&& castOther.getAktivSag() != null && this
						.getAktivSag().equals(castOther.getAktivSag())))
				&& ((this.getCalcKommune() == castOther.getCalcKommune()) || (this
						.getCalcKommune() != null
						&& castOther.getCalcKommune() != null && this
						.getCalcKommune().equals(castOther.getCalcKommune())))
				&& ((this.getReturvejokfn2() == castOther.getReturvejokfn2()) || (this
						.getReturvejokfn2() != null
						&& castOther.getReturvejokfn2() != null && this
						.getReturvejokfn2()
						.equals(castOther.getReturvejokfn2())))
				&& ((this.getReturvejokfn3() == castOther.getReturvejokfn3()) || (this
						.getReturvejokfn3() != null
						&& castOther.getReturvejokfn3() != null && this
						.getReturvejokfn3()
						.equals(castOther.getReturvejokfn3())))
				&& ((this.getReturvejok() == castOther.getReturvejok()) || (this
						.getReturvejok() != null
						&& castOther.getReturvejok() != null && this
						.getReturvejok().equals(castOther.getReturvejok())))
				&& ((this.getAnlIHusleje() == castOther.getAnlIHusleje()) || (this
						.getAnlIHusleje() != null
						&& castOther.getAnlIHusleje() != null && this
						.getAnlIHusleje().equals(castOther.getAnlIHusleje())))
				&& ((this.getPrimaryklumaxhast() == castOther
						.getPrimaryklumaxhast()) || (this
						.getPrimaryklumaxhast() != null
						&& castOther.getPrimaryklumaxhast() != null && this
						.getPrimaryklumaxhast().equals(
								castOther.getPrimaryklumaxhast())))
				&& ((this.getPrimaryklulntype() == castOther
						.getPrimaryklulntype()) || (this.getPrimaryklulntype() != null
						&& castOther.getPrimaryklulntype() != null && this
						.getPrimaryklulntype().equals(
								castOther.getPrimaryklulntype())))
				&& ((this.getPrimaryklulnejer() == castOther
						.getPrimaryklulnejer()) || (this.getPrimaryklulnejer() != null
						&& castOther.getPrimaryklulnejer() != null && this
						.getPrimaryklulnejer().equals(
								castOther.getPrimaryklulnejer())))
				&& ((this.getPrimarykluintype() == castOther
						.getPrimarykluintype()) || (this.getPrimarykluintype() != null
						&& castOther.getPrimarykluintype() != null && this
						.getPrimarykluintype().equals(
								castOther.getPrimarykluintype())))
				&& ((this.getPrimarykluaftkap() == castOther
						.getPrimarykluaftkap()) || (this.getPrimarykluaftkap() != null
						&& castOther.getPrimarykluaftkap() != null && this
						.getPrimarykluaftkap().equals(
								castOther.getPrimarykluaftkap())))
				&& ((this.getPrimproj() == castOther.getPrimproj()) || (this
						.getPrimproj() != null
						&& castOther.getPrimproj() != null && this
						.getPrimproj().equals(castOther.getPrimproj())))
				&& ((this.getPrimfap() == castOther.getPrimfap()) || (this
						.getPrimfap() != null && castOther.getPrimfap() != null && this
						.getPrimfap().equals(castOther.getPrimfap())))
				&& ((this.getDecAslKapacitet() == castOther
						.getDecAslKapacitet()) || (this.getDecAslKapacitet() != null
						&& castOther.getDecAslKapacitet() != null && this
						.getDecAslKapacitet().equals(
								castOther.getDecAslKapacitet())))
				&& ((this.getVoip() == castOther.getVoip()) || (this.getVoip() != null
						&& castOther.getVoip() != null && this.getVoip()
						.equals(castOther.getVoip())))
				&& ((this.getUdtagetvoip() == castOther.getUdtagetvoip()) || (this
						.getUdtagetvoip() != null
						&& castOther.getUdtagetvoip() != null && this
						.getUdtagetvoip().equals(castOther.getUdtagetvoip())))
				&& ((this.getAnnr() == castOther.getAnnr()) || (this.getAnnr() != null
						&& castOther.getAnnr() != null && this.getAnnr()
						.equals(castOther.getAnnr())))
				&& ((this.getPrimdekoder() == castOther.getPrimdekoder()) || (this
						.getPrimdekoder() != null
						&& castOther.getPrimdekoder() != null && this
						.getPrimdekoder().equals(castOther.getPrimdekoder())))
				&& ((this.getPrimcompany() == castOther.getPrimcompany()) || (this
						.getPrimcompany() != null
						&& castOther.getPrimcompany() != null && this
						.getPrimcompany().equals(castOther.getPrimcompany())))
				&& ((this.getSourceChgBool() == castOther.getSourceChgBool()) || (this
						.getSourceChgBool() != null
						&& castOther.getSourceChgBool() != null && this
						.getSourceChgBool()
						.equals(castOther.getSourceChgBool())))
				&& ((this.getLeasaar() == castOther.getLeasaar()) || (this
						.getLeasaar() != null && castOther.getLeasaar() != null && this
						.getLeasaar().equals(castOther.getLeasaar())))
				&& ((this.getRefdebnr() == castOther.getRefdebnr()) || (this
						.getRefdebnr() != null
						&& castOther.getRefdebnr() != null && this
						.getRefdebnr().equals(castOther.getRefdebnr())))
				&& ((this.getRefanlnr() == castOther.getRefanlnr()) || (this
						.getRefanlnr() != null
						&& castOther.getRefanlnr() != null && this
						.getRefanlnr().equals(castOther.getRefanlnr())))
				&& ((this.getAnlDatoinaktiv() == castOther.getAnlDatoinaktiv()) || (this
						.getAnlDatoinaktiv() != null
						&& castOther.getAnlDatoinaktiv() != null && this
						.getAnlDatoinaktiv().equals(
								castOther.getAnlDatoinaktiv())))
				&& ((this.getPrimmunicipality() == castOther
						.getPrimmunicipality()) || (this.getPrimmunicipality() != null
						&& castOther.getPrimmunicipality() != null && this
						.getPrimmunicipality().equals(
								castOther.getPrimmunicipality())))
				&& ((this.getAllowPresale() == castOther.getAllowPresale()) || (this
						.getAllowPresale() != null
						&& castOther.getAllowPresale() != null && this
						.getAllowPresale().equals(castOther.getAllowPresale())))
				&& ((this.getLogtrace() == castOther.getLogtrace()) || (this
						.getLogtrace() != null
						&& castOther.getLogtrace() != null && this
						.getLogtrace().equals(castOther.getLogtrace())))
				&& ((this.getDktv() == castOther.getDktv()) || (this.getDktv() != null
						&& castOther.getDktv() != null && this.getDktv()
						.equals(castOther.getDktv())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getAudId() == null ? 0 : this.getAudId().hashCode());
		result = 37 * result
				+ (getAudAction() == null ? 0 : this.getAudAction().hashCode());
		result = 37
				* result
				+ (getAudTimestamp() == null ? 0 : this.getAudTimestamp()
						.hashCode());
		result = 37 * result
				+ (getAudOsuser() == null ? 0 : this.getAudOsuser().hashCode());
		result = 37 * result
				+ (getAudDbuser() == null ? 0 : this.getAudDbuser().hashCode());
		result = 37
				* result
				+ (getAudUserterminal() == null ? 0 : this.getAudUserterminal()
						.hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getCrd() == null ? 0 : this.getCrd().hashCode());
		result = 37 * result
				+ (getCrt() == null ? 0 : this.getCrt().hashCode());
		result = 37 * result
				+ (getCru() == null ? 0 : this.getCru().hashCode());
		result = 37 * result
				+ (getModd() == null ? 0 : this.getModd().hashCode());
		result = 37 * result
				+ (getModt() == null ? 0 : this.getModt().hashCode());
		result = 37 * result
				+ (getModu() == null ? 0 : this.getModu().hashCode());
		result = 37 * result
				+ (getDeld() == null ? 0 : this.getDeld().hashCode());
		result = 37 * result
				+ (getDelt() == null ? 0 : this.getDelt().hashCode());
		result = 37 * result
				+ (getDelu() == null ? 0 : this.getDelu().hashCode());
		result = 37 * result
				+ (getImpd() == null ? 0 : this.getImpd().hashCode());
		result = 37 * result
				+ (getImpt() == null ? 0 : this.getImpt().hashCode());
		result = 37 * result
				+ (getImpu() == null ? 0 : this.getImpu().hashCode());
		result = 37 * result
				+ (getExpd() == null ? 0 : this.getExpd().hashCode());
		result = 37 * result
				+ (getExpt() == null ? 0 : this.getExpt().hashCode());
		result = 37 * result
				+ (getExpu() == null ? 0 : this.getExpu().hashCode());
		result = 37
				* result
				+ (getAnlAnlaegsnr() == null ? 0 : this.getAnlAnlaegsnr()
						.hashCode());
		result = 37
				* result
				+ (getAnlAnlaegsnavn() == null ? 0 : this.getAnlAnlaegsnavn()
						.hashCode());
		result = 37
				* result
				+ (getAnlKommunenr() == null ? 0 : this.getAnlKommunenr()
						.hashCode());
		result = 37
				* result
				+ (getAnlEjerkode() == null ? 0 : this.getAnlEjerkode()
						.hashCode());
		result = 37
				* result
				+ (getAnlAdmKode() == null ? 0 : this.getAnlAdmKode()
						.hashCode());
		result = 37
				* result
				+ (getAnlAnlaegsform() == null ? 0 : this.getAnlAnlaegsform()
						.hashCode());
		result = 37
				* result
				+ (getAnlHovedanlaegsnr() == null ? 0 : this
						.getAnlHovedanlaegsnr().hashCode());
		result = 37
				* result
				+ (getAnlAfleveringspunkt() == null ? 0 : this
						.getAnlAfleveringspunkt().hashCode());
		result = 37
				* result
				+ (getAnlNoegleboks() == null ? 0 : this.getAnlNoegleboks()
						.hashCode());
		result = 37
				* result
				+ (getAnlIdriftDato() == null ? 0 : this.getAnlIdriftDato()
						.hashCode());
		result = 37
				* result
				+ (getAnlForvIdriftDato() == null ? 0 : this
						.getAnlForvIdriftDato().hashCode());
		result = 37
				* result
				+ (getAnlAnlaegsStatus() == null ? 0 : this
						.getAnlAnlaegsStatus().hashCode());
		result = 37
				* result
				+ (getAnlSalgskoncept() == null ? 0 : this.getAnlSalgskoncept()
						.hashCode());
		result = 37 * result
				+ (getRRating() == null ? 0 : this.getRRating().hashCode());
		result = 37
				* result
				+ (getRRatingDate() == null ? 0 : this.getRRatingDate()
						.hashCode());
		result = 37
				* result
				+ (getRNextRating() == null ? 0 : this.getRNextRating()
						.hashCode());
		result = 37
				* result
				+ (getRNextRatingDate() == null ? 0 : this.getRNextRatingDate()
						.hashCode());
		result = 37
				* result
				+ (getSourceChgDate() == null ? 0 : this.getSourceChgDate()
						.hashCode());
		result = 37
				* result
				+ (getSourceChgCode() == null ? 0 : this.getSourceChgCode()
						.hashCode());
		result = 37 * result
				+ (getNoInst() == null ? 0 : this.getNoInst().hashCode());
		result = 37 * result
				+ (getNoDumInst() == null ? 0 : this.getNoDumInst().hashCode());
		result = 37 * result
				+ (getNoAllInst() == null ? 0 : this.getNoAllInst().hashCode());
		result = 37
				* result
				+ (getReforhandlFlag() == null ? 0 : this.getReforhandlFlag()
						.hashCode());
		result = 37
				* result
				+ (getReforhandlDate() == null ? 0 : this.getReforhandlDate()
						.hashCode());
		result = 37
				* result
				+ (getAnlGenberegnetdato() == null ? 0 : this
						.getAnlGenberegnetdato().hashCode());
		result = 37
				* result
				+ (getAnlForhandlingsdato() == null ? 0 : this
						.getAnlForhandlingsdato().hashCode());
		result = 37
				* result
				+ (getPrimhfinfo() == null ? 0 : this.getPrimhfinfo()
						.hashCode());
		result = 37
				* result
				+ (getPrimanltype() == null ? 0 : this.getPrimanltype()
						.hashCode());
		result = 37
				* result
				+ (getPrimarykontrakt() == null ? 0 : this.getPrimarykontrakt()
						.hashCode());
		result = 37 * result
				+ (getAflpunkt() == null ? 0 : this.getAflpunkt().hashCode());
		result = 37
				* result
				+ (getNglboxopsat() == null ? 0 : this.getNglboxopsat()
						.hashCode());
		result = 37
				* result
				+ (getParalleldatanet() == null ? 0 : this.getParalleldatanet()
						.hashCode());
		result = 37
				* result
				+ (getCoaxloesning() == null ? 0 : this.getCoaxloesning()
						.hashCode());
		result = 37
				* result
				+ (getFwaloesning() == null ? 0 : this.getFwaloesning()
						.hashCode());
		result = 37
				* result
				+ (getRetvejsduelfn3() == null ? 0 : this.getRetvejsduelfn3()
						.hashCode());
		result = 37
				* result
				+ (getPrimservlev() == null ? 0 : this.getPrimservlev()
						.hashCode());
		result = 37
				* result
				+ (getPrimarytidllev() == null ? 0 : this.getPrimarytidllev()
						.hashCode());
		result = 37
				* result
				+ (getPriminternetlev() == null ? 0 : this.getPriminternetlev()
						.hashCode());
		result = 37
				* result
				+ (getPrimarytelefonilev() == null ? 0 : this
						.getPrimarytelefonilev().hashCode());
		result = 37
				* result
				+ (getPrimarydigstblev() == null ? 0 : this
						.getPrimarydigstblev().hashCode());
		result = 37
				* result
				+ (getPrimaryfrekvens() == null ? 0 : this.getPrimaryfrekvens()
						.hashCode());
		result = 37
				* result
				+ (getPrimkommune() == null ? 0 : this.getPrimkommune()
						.hashCode());
		result = 37
				* result
				+ (getPrimanlstatus() == null ? 0 : this.getPrimanlstatus()
						.hashCode());
		result = 37 * result
				+ (getExpdate() == null ? 0 : this.getExpdate().hashCode());
		result = 37
				* result
				+ (getSignalforskilde() == null ? 0 : this.getSignalforskilde()
						.hashCode());
		result = 37
				* result
				+ (getNoInstAbnm() == null ? 0 : this.getNoInstAbnm()
						.hashCode());
		result = 37 * result
				+ (getPottilsl() == null ? 0 : this.getPottilsl().hashCode());
		result = 37 * result
				+ (getAkttilsl() == null ? 0 : this.getAkttilsl().hashCode());
		result = 37 * result
				+ (getMainZip() == null ? 0 : this.getMainZip().hashCode());
		result = 37 * result
				+ (getSloejfe() == null ? 0 : this.getSloejfe().hashCode());
		result = 37 * result
				+ (getStik() == null ? 0 : this.getStik().hashCode());
		result = 37
				* result
				+ (getNyoprettet() == null ? 0 : this.getNyoprettet()
						.hashCode());
		result = 37 * result
				+ (getQuickpot() == null ? 0 : this.getQuickpot().hashCode());
		result = 37 * result
				+ (getPrimsf() == null ? 0 : this.getPrimsf().hashCode());
		result = 37
				* result
				+ (getReturfrekvens() == null ? 0 : this.getReturfrekvens()
						.hashCode());
		result = 37 * result
				+ (getAmheadend() == null ? 0 : this.getAmheadend().hashCode());
		result = 37
				* result
				+ (getPrevAnlaegsnr() == null ? 0 : this.getPrevAnlaegsnr()
						.hashCode());
		result = 37
				* result
				+ (getPrimsegmgroup() == null ? 0 : this.getPrimsegmgroup()
						.hashCode());
		result = 37
				* result
				+ (getPrimpostcode() == null ? 0 : this.getPrimpostcode()
						.hashCode());
		result = 37
				* result
				+ (getPrimcurrlev() == null ? 0 : this.getPrimcurrlev()
						.hashCode());
		result = 37
				* result
				+ (getREtabldate() == null ? 0 : this.getREtabldate()
						.hashCode());
		result = 37 * result
				+ (getAktivSag() == null ? 0 : this.getAktivSag().hashCode());
		result = 37
				* result
				+ (getCalcKommune() == null ? 0 : this.getCalcKommune()
						.hashCode());
		result = 37
				* result
				+ (getReturvejokfn2() == null ? 0 : this.getReturvejokfn2()
						.hashCode());
		result = 37
				* result
				+ (getReturvejokfn3() == null ? 0 : this.getReturvejokfn3()
						.hashCode());
		result = 37
				* result
				+ (getReturvejok() == null ? 0 : this.getReturvejok()
						.hashCode());
		result = 37
				* result
				+ (getAnlIHusleje() == null ? 0 : this.getAnlIHusleje()
						.hashCode());
		result = 37
				* result
				+ (getPrimaryklumaxhast() == null ? 0 : this
						.getPrimaryklumaxhast().hashCode());
		result = 37
				* result
				+ (getPrimaryklulntype() == null ? 0 : this
						.getPrimaryklulntype().hashCode());
		result = 37
				* result
				+ (getPrimaryklulnejer() == null ? 0 : this
						.getPrimaryklulnejer().hashCode());
		result = 37
				* result
				+ (getPrimarykluintype() == null ? 0 : this
						.getPrimarykluintype().hashCode());
		result = 37
				* result
				+ (getPrimarykluaftkap() == null ? 0 : this
						.getPrimarykluaftkap().hashCode());
		result = 37 * result
				+ (getPrimproj() == null ? 0 : this.getPrimproj().hashCode());
		result = 37 * result
				+ (getPrimfap() == null ? 0 : this.getPrimfap().hashCode());
		result = 37
				* result
				+ (getDecAslKapacitet() == null ? 0 : this.getDecAslKapacitet()
						.hashCode());
		result = 37 * result
				+ (getVoip() == null ? 0 : this.getVoip().hashCode());
		result = 37
				* result
				+ (getUdtagetvoip() == null ? 0 : this.getUdtagetvoip()
						.hashCode());
		result = 37 * result
				+ (getAnnr() == null ? 0 : this.getAnnr().hashCode());
		result = 37
				* result
				+ (getPrimdekoder() == null ? 0 : this.getPrimdekoder()
						.hashCode());
		result = 37
				* result
				+ (getPrimcompany() == null ? 0 : this.getPrimcompany()
						.hashCode());
		result = 37
				* result
				+ (getSourceChgBool() == null ? 0 : this.getSourceChgBool()
						.hashCode());
		result = 37 * result
				+ (getLeasaar() == null ? 0 : this.getLeasaar().hashCode());
		result = 37 * result
				+ (getRefdebnr() == null ? 0 : this.getRefdebnr().hashCode());
		result = 37 * result
				+ (getRefanlnr() == null ? 0 : this.getRefanlnr().hashCode());
		result = 37
				* result
				+ (getAnlDatoinaktiv() == null ? 0 : this.getAnlDatoinaktiv()
						.hashCode());
		result = 37
				* result
				+ (getPrimmunicipality() == null ? 0 : this
						.getPrimmunicipality().hashCode());
		result = 37
				* result
				+ (getAllowPresale() == null ? 0 : this.getAllowPresale()
						.hashCode());
		result = 37 * result
				+ (getLogtrace() == null ? 0 : this.getLogtrace().hashCode());
		result = 37 * result
				+ (getDktv() == null ? 0 : this.getDktv().hashCode());
		return result;
	}

}
