package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cardorder generated by hbm2java
 */
@Entity
@Table(name = "CARDORDER", schema = "PCRM")
public class Cardorder implements java.io.Serializable {

	private String id;
	private Offer offer;
	private Date crd;
	private Date crt;
	private String cru;
	private Date modd;
	private Date modt;
	private String modu;
	private Date deld;
	private Date delt;
	private String delu;
	private Date impd;
	private Date impt;
	private String impu;
	private Date expd;
	private Date expt;
	private String expu;
	private String code;
	private String head;
	private Character serviceaftale;
	private Date provedato;
	private String installator;
	private String kundenribs;
	private String bokslabel;
	private Character hardigit;
	private Date fradato;
	private Character harselect;
	private Character ikkedigit;
	private Character ikkekort;
	private Character lonebox;
	private String selectorlabel;
	private Character skaldigit;
	private Character skalselect;
	private Date tildato;
	private Set<Offer> offers = new HashSet<Offer>(0);

	public Cardorder() {
	}

	public Cardorder(String id) {
		this.id = id;
	}

	public Cardorder(String id, Offer offer, Date crd, Date crt, String cru,
			Date modd, Date modt, String modu, Date deld, Date delt,
			String delu, Date impd, Date impt, String impu, Date expd,
			Date expt, String expu, String code, String head,
			Character serviceaftale, Date provedato, String installator,
			String kundenribs, String bokslabel, Character hardigit,
			Date fradato, Character harselect, Character ikkedigit,
			Character ikkekort, Character lonebox, String selectorlabel,
			Character skaldigit, Character skalselect, Date tildato,
			Set<Offer> offers) {
		this.id = id;
		this.offer = offer;
		this.crd = crd;
		this.crt = crt;
		this.cru = cru;
		this.modd = modd;
		this.modt = modt;
		this.modu = modu;
		this.deld = deld;
		this.delt = delt;
		this.delu = delu;
		this.impd = impd;
		this.impt = impt;
		this.impu = impu;
		this.expd = expd;
		this.expt = expt;
		this.expu = expu;
		this.code = code;
		this.head = head;
		this.serviceaftale = serviceaftale;
		this.provedato = provedato;
		this.installator = installator;
		this.kundenribs = kundenribs;
		this.bokslabel = bokslabel;
		this.hardigit = hardigit;
		this.fradato = fradato;
		this.harselect = harselect;
		this.ikkedigit = ikkedigit;
		this.ikkekort = ikkekort;
		this.lonebox = lonebox;
		this.selectorlabel = selectorlabel;
		this.skaldigit = skaldigit;
		this.skalselect = skalselect;
		this.tildato = tildato;
		this.offers = offers;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMOFFER")
	public Offer getOffer() {
		return this.offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "CODE", length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "HEAD")
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "SERVICEAFTALE", length = 1)
	public Character getServiceaftale() {
		return this.serviceaftale;
	}

	public void setServiceaftale(Character serviceaftale) {
		this.serviceaftale = serviceaftale;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PROVEDATO", length = 7)
	public Date getProvedato() {
		return this.provedato;
	}

	public void setProvedato(Date provedato) {
		this.provedato = provedato;
	}

	@Column(name = "INSTALLATOR")
	public String getInstallator() {
		return this.installator;
	}

	public void setInstallator(String installator) {
		this.installator = installator;
	}

	@Column(name = "KUNDENRIBS", length = 20)
	public String getKundenribs() {
		return this.kundenribs;
	}

	public void setKundenribs(String kundenribs) {
		this.kundenribs = kundenribs;
	}

	@Column(name = "BOKSLABEL")
	public String getBokslabel() {
		return this.bokslabel;
	}

	public void setBokslabel(String bokslabel) {
		this.bokslabel = bokslabel;
	}

	@Column(name = "HARDIGIT", length = 1)
	public Character getHardigit() {
		return this.hardigit;
	}

	public void setHardigit(Character hardigit) {
		this.hardigit = hardigit;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FRADATO", length = 7)
	public Date getFradato() {
		return this.fradato;
	}

	public void setFradato(Date fradato) {
		this.fradato = fradato;
	}

	@Column(name = "HARSELECT", length = 1)
	public Character getHarselect() {
		return this.harselect;
	}

	public void setHarselect(Character harselect) {
		this.harselect = harselect;
	}

	@Column(name = "IKKEDIGIT", length = 1)
	public Character getIkkedigit() {
		return this.ikkedigit;
	}

	public void setIkkedigit(Character ikkedigit) {
		this.ikkedigit = ikkedigit;
	}

	@Column(name = "IKKEKORT", length = 1)
	public Character getIkkekort() {
		return this.ikkekort;
	}

	public void setIkkekort(Character ikkekort) {
		this.ikkekort = ikkekort;
	}

	@Column(name = "LONEBOX", length = 1)
	public Character getLonebox() {
		return this.lonebox;
	}

	public void setLonebox(Character lonebox) {
		this.lonebox = lonebox;
	}

	@Column(name = "SELECTORLABEL")
	public String getSelectorlabel() {
		return this.selectorlabel;
	}

	public void setSelectorlabel(String selectorlabel) {
		this.selectorlabel = selectorlabel;
	}

	@Column(name = "SKALDIGIT", length = 1)
	public Character getSkaldigit() {
		return this.skaldigit;
	}

	public void setSkaldigit(Character skaldigit) {
		this.skaldigit = skaldigit;
	}

	@Column(name = "SKALSELECT", length = 1)
	public Character getSkalselect() {
		return this.skalselect;
	}

	public void setSkalselect(Character skalselect) {
		this.skalselect = skalselect;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TILDATO", length = 7)
	public Date getTildato() {
		return this.tildato;
	}

	public void setTildato(Date tildato) {
		this.tildato = tildato;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cardorder")
	public Set<Offer> getOffers() {
		return this.offers;
	}

	public void setOffers(Set<Offer> offers) {
		this.offers = offers;
	}

}
