package com.tdc.persistence.dao.entity;
// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Casetype generated by hbm2java
 */
@Entity
@Table(name="CASETYPE"
    ,schema="PCRM"
)
public class Casetype  implements java.io.Serializable {


     private String id;
     private Salestype salestype;
     private Date crd;
     private String code;
     private Date impt;
     private Date expt;
     private Date impd;
     private Date expd;
     private Date modt;
     private String cru;
     private Date delt;
     private Date modd;
     private String impu;
     private String expu;
     private Date deld;
     private String modu;
     private String head;
     private String delu;
     private Date crt;
     private String primsagsstatus;
     private String primanlstatus;
     private Character anleg;
     private Character anlaeg;
     private String dddetail;
     private Character allonge;
     private String cdmtableclass;
     private String key2rule;
     private String cmtranslation;
     private String oldcode;
     private Set<CrTemplateCasetype> crTemplateCasetypes = new HashSet<CrTemplateCasetype>(0);
     private Set<Casefolder> casefolders = new HashSet<Casefolder>(0);

    public Casetype() {
    }

	
    public Casetype(String id) {
        this.id = id;
    }
    public Casetype(String id, Salestype salestype, Date crd, String code, Date impt, Date expt, Date impd, Date expd, Date modt, String cru, Date delt, Date modd, String impu, String expu, Date deld, String modu, String head, String delu, Date crt, String primsagsstatus, String primanlstatus, Character anleg, Character anlaeg, String dddetail, Character allonge, String cdmtableclass, String key2rule, String cmtranslation, String oldcode, Set<CrTemplateCasetype> crTemplateCasetypes, Set<Casefolder> casefolders) {
       this.id = id;
       this.salestype = salestype;
       this.crd = crd;
       this.code = code;
       this.impt = impt;
       this.expt = expt;
       this.impd = impd;
       this.expd = expd;
       this.modt = modt;
       this.cru = cru;
       this.delt = delt;
       this.modd = modd;
       this.impu = impu;
       this.expu = expu;
       this.deld = deld;
       this.modu = modu;
       this.head = head;
       this.delu = delu;
       this.crt = crt;
       this.primsagsstatus = primsagsstatus;
       this.primanlstatus = primanlstatus;
       this.anleg = anleg;
       this.anlaeg = anlaeg;
       this.dddetail = dddetail;
       this.allonge = allonge;
       this.cdmtableclass = cdmtableclass;
       this.key2rule = key2rule;
       this.cmtranslation = cmtranslation;
       this.oldcode = oldcode;
       this.crTemplateCasetypes = crTemplateCasetypes;
       this.casefolders = casefolders;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, length=19)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PRIMSALGSTYPE")
    public Salestype getSalestype() {
        return this.salestype;
    }
    
    public void setSalestype(Salestype salestype) {
        this.salestype = salestype;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CRD", length=7)
    public Date getCrd() {
        return this.crd;
    }
    
    public void setCrd(Date crd) {
        this.crd = crd;
    }

    
    @Column(name="CODE", length=15)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="IMPT", length=7)
    public Date getImpt() {
        return this.impt;
    }
    
    public void setImpt(Date impt) {
        this.impt = impt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXPT", length=7)
    public Date getExpt() {
        return this.expt;
    }
    
    public void setExpt(Date expt) {
        this.expt = expt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="IMPD", length=7)
    public Date getImpd() {
        return this.impd;
    }
    
    public void setImpd(Date impd) {
        this.impd = impd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="EXPD", length=7)
    public Date getExpd() {
        return this.expd;
    }
    
    public void setExpd(Date expd) {
        this.expd = expd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MODT", length=7)
    public Date getModt() {
        return this.modt;
    }
    
    public void setModt(Date modt) {
        this.modt = modt;
    }

    
    @Column(name="CRU", length=19)
    public String getCru() {
        return this.cru;
    }
    
    public void setCru(String cru) {
        this.cru = cru;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DELT", length=7)
    public Date getDelt() {
        return this.delt;
    }
    
    public void setDelt(Date delt) {
        this.delt = delt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="MODD", length=7)
    public Date getModd() {
        return this.modd;
    }
    
    public void setModd(Date modd) {
        this.modd = modd;
    }

    
    @Column(name="IMPU", length=19)
    public String getImpu() {
        return this.impu;
    }
    
    public void setImpu(String impu) {
        this.impu = impu;
    }

    
    @Column(name="EXPU", length=19)
    public String getExpu() {
        return this.expu;
    }
    
    public void setExpu(String expu) {
        this.expu = expu;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DELD", length=7)
    public Date getDeld() {
        return this.deld;
    }
    
    public void setDeld(Date deld) {
        this.deld = deld;
    }

    
    @Column(name="MODU", length=19)
    public String getModu() {
        return this.modu;
    }
    
    public void setModu(String modu) {
        this.modu = modu;
    }

    
    @Column(name="HEAD", length=50)
    public String getHead() {
        return this.head;
    }
    
    public void setHead(String head) {
        this.head = head;
    }

    
    @Column(name="DELU", length=19)
    public String getDelu() {
        return this.delu;
    }
    
    public void setDelu(String delu) {
        this.delu = delu;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="CRT", length=7)
    public Date getCrt() {
        return this.crt;
    }
    
    public void setCrt(Date crt) {
        this.crt = crt;
    }

    
    @Column(name="PRIMSAGSSTATUS", length=19)
    public String getPrimsagsstatus() {
        return this.primsagsstatus;
    }
    
    public void setPrimsagsstatus(String primsagsstatus) {
        this.primsagsstatus = primsagsstatus;
    }

    
    @Column(name="PRIMANLSTATUS", length=19)
    public String getPrimanlstatus() {
        return this.primanlstatus;
    }
    
    public void setPrimanlstatus(String primanlstatus) {
        this.primanlstatus = primanlstatus;
    }

    
    @Column(name="ANL�G", length=1)
    public Character getAnleg() {
        return this.anleg;
    }
    
    public void setAnleg(Character anleg) {
        this.anleg = anleg;
    }

    
    @Column(name="ANLAEG", length=1)
    public Character getAnlaeg() {
        return this.anlaeg;
    }
    
    public void setAnlaeg(Character anlaeg) {
        this.anlaeg = anlaeg;
    }

    
    @Column(name="DDDETAIL", length=80)
    public String getDddetail() {
        return this.dddetail;
    }
    
    public void setDddetail(String dddetail) {
        this.dddetail = dddetail;
    }

    
    @Column(name="ALLONGE", length=1)
    public Character getAllonge() {
        return this.allonge;
    }
    
    public void setAllonge(Character allonge) {
        this.allonge = allonge;
    }

    
    @Column(name="CDMTABLECLASS", length=80)
    public String getCdmtableclass() {
        return this.cdmtableclass;
    }
    
    public void setCdmtableclass(String cdmtableclass) {
        this.cdmtableclass = cdmtableclass;
    }

    
    @Column(name="KEY2RULE")
    public String getKey2rule() {
        return this.key2rule;
    }
    
    public void setKey2rule(String key2rule) {
        this.key2rule = key2rule;
    }

    
    @Column(name="CMTRANSLATION", length=50)
    public String getCmtranslation() {
        return this.cmtranslation;
    }
    
    public void setCmtranslation(String cmtranslation) {
        this.cmtranslation = cmtranslation;
    }

    
    @Column(name="OLDCODE", length=15)
    public String getOldcode() {
        return this.oldcode;
    }
    
    public void setOldcode(String oldcode) {
        this.oldcode = oldcode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="casetype")
    public Set<CrTemplateCasetype> getCrTemplateCasetypes() {
        return this.crTemplateCasetypes;
    }
    
    public void setCrTemplateCasetypes(Set<CrTemplateCasetype> crTemplateCasetypes) {
        this.crTemplateCasetypes = crTemplateCasetypes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="casetype")
    public Set<Casefolder> getCasefolders() {
        return this.casefolders;
    }
    
    public void setCasefolders(Set<Casefolder> casefolders) {
        this.casefolders = casefolders;
    }




}


