package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CatransCableunit generated by hbm2java
 */
@Entity
@Table(name = "CATRANS_CABLEUNIT", schema = "PCRM")
public class CatransCableunit implements java.io.Serializable {

	private CatransCableunitId id;

	public CatransCableunit() {
	}

	public CatransCableunit(CatransCableunitId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", length = 19)),
			@AttributeOverride(name = "crd", column = @Column(name = "CRD", length = 7)),
			@AttributeOverride(name = "impt", column = @Column(name = "IMPT", length = 7)),
			@AttributeOverride(name = "expt", column = @Column(name = "EXPT", length = 7)),
			@AttributeOverride(name = "impd", column = @Column(name = "IMPD", length = 7)),
			@AttributeOverride(name = "expd", column = @Column(name = "EXPD", length = 7)),
			@AttributeOverride(name = "modt", column = @Column(name = "MODT", length = 7)),
			@AttributeOverride(name = "cru", column = @Column(name = "CRU", length = 19)),
			@AttributeOverride(name = "delt", column = @Column(name = "DELT", length = 7)),
			@AttributeOverride(name = "modd", column = @Column(name = "MODD", length = 7)),
			@AttributeOverride(name = "impu", column = @Column(name = "IMPU", length = 19)),
			@AttributeOverride(name = "expu", column = @Column(name = "EXPU", length = 19)),
			@AttributeOverride(name = "deld", column = @Column(name = "DELD", length = 7)),
			@AttributeOverride(name = "modu", column = @Column(name = "MODU", length = 19)),
			@AttributeOverride(name = "delu", column = @Column(name = "DELU", length = 19)),
			@AttributeOverride(name = "crt", column = @Column(name = "CRT", length = 7)),
			@AttributeOverride(name = "primtranssag", column = @Column(name = "PRIMTRANSSAG", length = 19)),
			@AttributeOverride(name = "cdmNoegle", column = @Column(name = "CDM_NOEGLE", length = 19)),
			@AttributeOverride(name = "administrationskode", column = @Column(name = "ADMINISTRATIONSKODE", precision = 10, scale = 0)),
			@AttributeOverride(name = "aendringForetaget", column = @Column(name = "AENDRING_FORETAGET", length = 1)),
			@AttributeOverride(name = "anlaegsStatus", column = @Column(name = "ANLAEGS_STATUS", length = 15)),
			@AttributeOverride(name = "anlaegsform", column = @Column(name = "ANLAEGSFORM", precision = 10, scale = 0)),
			@AttributeOverride(name = "anlaegsnavn", column = @Column(name = "ANLAEGSNAVN", length = 40)),
			@AttributeOverride(name = "anlaegsnr", column = @Column(name = "ANLAEGSNR", length = 10)),
			@AttributeOverride(name = "antalPotentielleTilsl", column = @Column(name = "ANTAL_POTENTIELLE_TILSL", precision = 10, scale = 0)),
			@AttributeOverride(name = "antalTilslutninger", column = @Column(name = "ANTAL_TILSLUTNINGER", precision = 10, scale = 0)),
			@AttributeOverride(name = "ejerkode", column = @Column(name = "EJERKODE", precision = 10, scale = 0)),
			@AttributeOverride(name = "forvIdriftdato", column = @Column(name = "FORV_IDRIFTDATO", length = 7)),
			@AttributeOverride(name = "hfnr", column = @Column(name = "HFNR", length = 11)),
			@AttributeOverride(name = "kommunenr", column = @Column(name = "KOMMUNENR", length = 4)),
			@AttributeOverride(name = "transferStatus", column = @Column(name = "TRANSFER_STATUS", precision = 10, scale = 0)),
			@AttributeOverride(name = "hovedstrOpgr", column = @Column(name = "HOVEDSTR_OPGR", length = 1)),
			@AttributeOverride(name = "transferHist", column = @Column(name = "TRANSFER_HIST")),
			@AttributeOverride(name = "hasDummyAdr", column = @Column(name = "HAS_DUMMY_ADR", length = 1)),
			@AttributeOverride(name = "anlIHusleje", column = @Column(name = "ANL_I_HUSLEJE", precision = 22, scale = 0)),
			@AttributeOverride(name = "anlaegOpgr", column = @Column(name = "ANLAEG_OPGR", length = 1)),
			@AttributeOverride(name = "idriftdato", column = @Column(name = "IDRIFTDATO", length = 7)),
			@AttributeOverride(name = "anlAfleveringspunkt", column = @Column(name = "ANL_AFLEVERINGSPUNKT", length = 60)),
			@AttributeOverride(name = "anlNoegleboks", column = @Column(name = "ANL_NOEGLEBOKS", length = 60)) })
	public CatransCableunitId getId() {
		return this.id;
	}

	public void setId(CatransCableunitId id) {
		this.id = id;
	}

}
