package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CatransAddressitemId generated by hbm2java
 */
@Embeddable
public class CatransAddressitemId implements java.io.Serializable {

	private String id;
	private Date crd;
	private Date impt;
	private Date expt;
	private Date impd;
	private Date expd;
	private Date modt;
	private String cru;
	private Date delt;
	private Date modd;
	private String impu;
	private String expu;
	private Date deld;
	private String modu;
	private String delu;
	private Date crt;
	private String primtranssag;
	private String primdwa;
	private String cdmNoegle;
	private Character aendringForetaget;
	private String boligtype;
	private String caInstId;
	private String caInstLbnr;
	private String cdmAdrId;
	private String kommunenr;
	private String vejkode;
	private String internVejkode;
	private String gadenavn;
	private String husnr;
	private String opgang;
	private String etage;
	private String side;
	private String doer;
	private String postnr;
	private String stednavn;
	private String instStatus;
	private String individPkValg;
	private Long transferStatus;
	private String oprAnlNr;
	private String transferHist;
	private String dwSidedoer;

	public CatransAddressitemId() {
	}

	public CatransAddressitemId(String id, Date crd, Date impt, Date expt,
			Date impd, Date expd, Date modt, String cru, Date delt, Date modd,
			String impu, String expu, Date deld, String modu, String delu,
			Date crt, String primtranssag, String primdwa, String cdmNoegle,
			Character aendringForetaget, String boligtype, String caInstId,
			String caInstLbnr, String cdmAdrId, String kommunenr,
			String vejkode, String internVejkode, String gadenavn,
			String husnr, String opgang, String etage, String side,
			String doer, String postnr, String stednavn, String instStatus,
			String individPkValg, Long transferStatus, String oprAnlNr,
			String transferHist, String dwSidedoer) {
		this.id = id;
		this.crd = crd;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.cru = cru;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.modu = modu;
		this.delu = delu;
		this.crt = crt;
		this.primtranssag = primtranssag;
		this.primdwa = primdwa;
		this.cdmNoegle = cdmNoegle;
		this.aendringForetaget = aendringForetaget;
		this.boligtype = boligtype;
		this.caInstId = caInstId;
		this.caInstLbnr = caInstLbnr;
		this.cdmAdrId = cdmAdrId;
		this.kommunenr = kommunenr;
		this.vejkode = vejkode;
		this.internVejkode = internVejkode;
		this.gadenavn = gadenavn;
		this.husnr = husnr;
		this.opgang = opgang;
		this.etage = etage;
		this.side = side;
		this.doer = doer;
		this.postnr = postnr;
		this.stednavn = stednavn;
		this.instStatus = instStatus;
		this.individPkValg = individPkValg;
		this.transferStatus = transferStatus;
		this.oprAnlNr = oprAnlNr;
		this.transferHist = transferHist;
		this.dwSidedoer = dwSidedoer;
	}

	@Column(name = "ID", length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "PRIMTRANSSAG", length = 19)
	public String getPrimtranssag() {
		return this.primtranssag;
	}

	public void setPrimtranssag(String primtranssag) {
		this.primtranssag = primtranssag;
	}

	@Column(name = "PRIMDWA", length = 22)
	public String getPrimdwa() {
		return this.primdwa;
	}

	public void setPrimdwa(String primdwa) {
		this.primdwa = primdwa;
	}

	@Column(name = "CDM_NOEGLE", length = 19)
	public String getCdmNoegle() {
		return this.cdmNoegle;
	}

	public void setCdmNoegle(String cdmNoegle) {
		this.cdmNoegle = cdmNoegle;
	}

	@Column(name = "AENDRING_FORETAGET", length = 1)
	public Character getAendringForetaget() {
		return this.aendringForetaget;
	}

	public void setAendringForetaget(Character aendringForetaget) {
		this.aendringForetaget = aendringForetaget;
	}

	@Column(name = "BOLIGTYPE", length = 15)
	public String getBoligtype() {
		return this.boligtype;
	}

	public void setBoligtype(String boligtype) {
		this.boligtype = boligtype;
	}

	@Column(name = "CA_INST_ID", length = 19)
	public String getCaInstId() {
		return this.caInstId;
	}

	public void setCaInstId(String caInstId) {
		this.caInstId = caInstId;
	}

	@Column(name = "CA_INST_LBNR", length = 19)
	public String getCaInstLbnr() {
		return this.caInstLbnr;
	}

	public void setCaInstLbnr(String caInstLbnr) {
		this.caInstLbnr = caInstLbnr;
	}

	@Column(name = "CDM_ADR_ID", length = 5)
	public String getCdmAdrId() {
		return this.cdmAdrId;
	}

	public void setCdmAdrId(String cdmAdrId) {
		this.cdmAdrId = cdmAdrId;
	}

	@Column(name = "KOMMUNENR", length = 4)
	public String getKommunenr() {
		return this.kommunenr;
	}

	public void setKommunenr(String kommunenr) {
		this.kommunenr = kommunenr;
	}

	@Column(name = "VEJKODE", length = 4)
	public String getVejkode() {
		return this.vejkode;
	}

	public void setVejkode(String vejkode) {
		this.vejkode = vejkode;
	}

	@Column(name = "INTERN_VEJKODE", length = 1)
	public String getInternVejkode() {
		return this.internVejkode;
	}

	public void setInternVejkode(String internVejkode) {
		this.internVejkode = internVejkode;
	}

	@Column(name = "GADENAVN", length = 40)
	public String getGadenavn() {
		return this.gadenavn;
	}

	public void setGadenavn(String gadenavn) {
		this.gadenavn = gadenavn;
	}

	@Column(name = "HUSNR", length = 3)
	public String getHusnr() {
		return this.husnr;
	}

	public void setHusnr(String husnr) {
		this.husnr = husnr;
	}

	@Column(name = "OPGANG", length = 1)
	public String getOpgang() {
		return this.opgang;
	}

	public void setOpgang(String opgang) {
		this.opgang = opgang;
	}

	@Column(name = "ETAGE", length = 2)
	public String getEtage() {
		return this.etage;
	}

	public void setEtage(String etage) {
		this.etage = etage;
	}

	@Column(name = "SIDE", length = 4)
	public String getSide() {
		return this.side;
	}

	public void setSide(String side) {
		this.side = side;
	}

	@Column(name = "DOER", length = 4)
	public String getDoer() {
		return this.doer;
	}

	public void setDoer(String doer) {
		this.doer = doer;
	}

	@Column(name = "POSTNR", length = 4)
	public String getPostnr() {
		return this.postnr;
	}

	public void setPostnr(String postnr) {
		this.postnr = postnr;
	}

	@Column(name = "STEDNAVN", length = 40)
	public String getStednavn() {
		return this.stednavn;
	}

	public void setStednavn(String stednavn) {
		this.stednavn = stednavn;
	}

	@Column(name = "INST_STATUS", length = 40)
	public String getInstStatus() {
		return this.instStatus;
	}

	public void setInstStatus(String instStatus) {
		this.instStatus = instStatus;
	}

	@Column(name = "INDIVID_PK_VALG", length = 15)
	public String getIndividPkValg() {
		return this.individPkValg;
	}

	public void setIndividPkValg(String individPkValg) {
		this.individPkValg = individPkValg;
	}

	@Column(name = "TRANSFER_STATUS", precision = 10, scale = 0)
	public Long getTransferStatus() {
		return this.transferStatus;
	}

	public void setTransferStatus(Long transferStatus) {
		this.transferStatus = transferStatus;
	}

	@Column(name = "OPR_ANL_NR", length = 50)
	public String getOprAnlNr() {
		return this.oprAnlNr;
	}

	public void setOprAnlNr(String oprAnlNr) {
		this.oprAnlNr = oprAnlNr;
	}

	@Column(name = "TRANSFER_HIST")
	public String getTransferHist() {
		return this.transferHist;
	}

	public void setTransferHist(String transferHist) {
		this.transferHist = transferHist;
	}

	@Column(name = "DW_SIDEDOER", length = 4)
	public String getDwSidedoer() {
		return this.dwSidedoer;
	}

	public void setDwSidedoer(String dwSidedoer) {
		this.dwSidedoer = dwSidedoer;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CatransAddressitemId))
			return false;
		CatransAddressitemId castOther = (CatransAddressitemId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getCrd() == castOther.getCrd()) || (this.getCrd() != null
						&& castOther.getCrd() != null && this.getCrd().equals(
						castOther.getCrd())))
				&& ((this.getImpt() == castOther.getImpt()) || (this.getImpt() != null
						&& castOther.getImpt() != null && this.getImpt()
						.equals(castOther.getImpt())))
				&& ((this.getExpt() == castOther.getExpt()) || (this.getExpt() != null
						&& castOther.getExpt() != null && this.getExpt()
						.equals(castOther.getExpt())))
				&& ((this.getImpd() == castOther.getImpd()) || (this.getImpd() != null
						&& castOther.getImpd() != null && this.getImpd()
						.equals(castOther.getImpd())))
				&& ((this.getExpd() == castOther.getExpd()) || (this.getExpd() != null
						&& castOther.getExpd() != null && this.getExpd()
						.equals(castOther.getExpd())))
				&& ((this.getModt() == castOther.getModt()) || (this.getModt() != null
						&& castOther.getModt() != null && this.getModt()
						.equals(castOther.getModt())))
				&& ((this.getCru() == castOther.getCru()) || (this.getCru() != null
						&& castOther.getCru() != null && this.getCru().equals(
						castOther.getCru())))
				&& ((this.getDelt() == castOther.getDelt()) || (this.getDelt() != null
						&& castOther.getDelt() != null && this.getDelt()
						.equals(castOther.getDelt())))
				&& ((this.getModd() == castOther.getModd()) || (this.getModd() != null
						&& castOther.getModd() != null && this.getModd()
						.equals(castOther.getModd())))
				&& ((this.getImpu() == castOther.getImpu()) || (this.getImpu() != null
						&& castOther.getImpu() != null && this.getImpu()
						.equals(castOther.getImpu())))
				&& ((this.getExpu() == castOther.getExpu()) || (this.getExpu() != null
						&& castOther.getExpu() != null && this.getExpu()
						.equals(castOther.getExpu())))
				&& ((this.getDeld() == castOther.getDeld()) || (this.getDeld() != null
						&& castOther.getDeld() != null && this.getDeld()
						.equals(castOther.getDeld())))
				&& ((this.getModu() == castOther.getModu()) || (this.getModu() != null
						&& castOther.getModu() != null && this.getModu()
						.equals(castOther.getModu())))
				&& ((this.getDelu() == castOther.getDelu()) || (this.getDelu() != null
						&& castOther.getDelu() != null && this.getDelu()
						.equals(castOther.getDelu())))
				&& ((this.getCrt() == castOther.getCrt()) || (this.getCrt() != null
						&& castOther.getCrt() != null && this.getCrt().equals(
						castOther.getCrt())))
				&& ((this.getPrimtranssag() == castOther.getPrimtranssag()) || (this
						.getPrimtranssag() != null
						&& castOther.getPrimtranssag() != null && this
						.getPrimtranssag().equals(castOther.getPrimtranssag())))
				&& ((this.getPrimdwa() == castOther.getPrimdwa()) || (this
						.getPrimdwa() != null && castOther.getPrimdwa() != null && this
						.getPrimdwa().equals(castOther.getPrimdwa())))
				&& ((this.getCdmNoegle() == castOther.getCdmNoegle()) || (this
						.getCdmNoegle() != null
						&& castOther.getCdmNoegle() != null && this
						.getCdmNoegle().equals(castOther.getCdmNoegle())))
				&& ((this.getAendringForetaget() == castOther
						.getAendringForetaget()) || (this
						.getAendringForetaget() != null
						&& castOther.getAendringForetaget() != null && this
						.getAendringForetaget().equals(
								castOther.getAendringForetaget())))
				&& ((this.getBoligtype() == castOther.getBoligtype()) || (this
						.getBoligtype() != null
						&& castOther.getBoligtype() != null && this
						.getBoligtype().equals(castOther.getBoligtype())))
				&& ((this.getCaInstId() == castOther.getCaInstId()) || (this
						.getCaInstId() != null
						&& castOther.getCaInstId() != null && this
						.getCaInstId().equals(castOther.getCaInstId())))
				&& ((this.getCaInstLbnr() == castOther.getCaInstLbnr()) || (this
						.getCaInstLbnr() != null
						&& castOther.getCaInstLbnr() != null && this
						.getCaInstLbnr().equals(castOther.getCaInstLbnr())))
				&& ((this.getCdmAdrId() == castOther.getCdmAdrId()) || (this
						.getCdmAdrId() != null
						&& castOther.getCdmAdrId() != null && this
						.getCdmAdrId().equals(castOther.getCdmAdrId())))
				&& ((this.getKommunenr() == castOther.getKommunenr()) || (this
						.getKommunenr() != null
						&& castOther.getKommunenr() != null && this
						.getKommunenr().equals(castOther.getKommunenr())))
				&& ((this.getVejkode() == castOther.getVejkode()) || (this
						.getVejkode() != null && castOther.getVejkode() != null && this
						.getVejkode().equals(castOther.getVejkode())))
				&& ((this.getInternVejkode() == castOther.getInternVejkode()) || (this
						.getInternVejkode() != null
						&& castOther.getInternVejkode() != null && this
						.getInternVejkode()
						.equals(castOther.getInternVejkode())))
				&& ((this.getGadenavn() == castOther.getGadenavn()) || (this
						.getGadenavn() != null
						&& castOther.getGadenavn() != null && this
						.getGadenavn().equals(castOther.getGadenavn())))
				&& ((this.getHusnr() == castOther.getHusnr()) || (this
						.getHusnr() != null && castOther.getHusnr() != null && this
						.getHusnr().equals(castOther.getHusnr())))
				&& ((this.getOpgang() == castOther.getOpgang()) || (this
						.getOpgang() != null && castOther.getOpgang() != null && this
						.getOpgang().equals(castOther.getOpgang())))
				&& ((this.getEtage() == castOther.getEtage()) || (this
						.getEtage() != null && castOther.getEtage() != null && this
						.getEtage().equals(castOther.getEtage())))
				&& ((this.getSide() == castOther.getSide()) || (this.getSide() != null
						&& castOther.getSide() != null && this.getSide()
						.equals(castOther.getSide())))
				&& ((this.getDoer() == castOther.getDoer()) || (this.getDoer() != null
						&& castOther.getDoer() != null && this.getDoer()
						.equals(castOther.getDoer())))
				&& ((this.getPostnr() == castOther.getPostnr()) || (this
						.getPostnr() != null && castOther.getPostnr() != null && this
						.getPostnr().equals(castOther.getPostnr())))
				&& ((this.getStednavn() == castOther.getStednavn()) || (this
						.getStednavn() != null
						&& castOther.getStednavn() != null && this
						.getStednavn().equals(castOther.getStednavn())))
				&& ((this.getInstStatus() == castOther.getInstStatus()) || (this
						.getInstStatus() != null
						&& castOther.getInstStatus() != null && this
						.getInstStatus().equals(castOther.getInstStatus())))
				&& ((this.getIndividPkValg() == castOther.getIndividPkValg()) || (this
						.getIndividPkValg() != null
						&& castOther.getIndividPkValg() != null && this
						.getIndividPkValg()
						.equals(castOther.getIndividPkValg())))
				&& ((this.getTransferStatus() == castOther.getTransferStatus()) || (this
						.getTransferStatus() != null
						&& castOther.getTransferStatus() != null && this
						.getTransferStatus().equals(
								castOther.getTransferStatus())))
				&& ((this.getOprAnlNr() == castOther.getOprAnlNr()) || (this
						.getOprAnlNr() != null
						&& castOther.getOprAnlNr() != null && this
						.getOprAnlNr().equals(castOther.getOprAnlNr())))
				&& ((this.getTransferHist() == castOther.getTransferHist()) || (this
						.getTransferHist() != null
						&& castOther.getTransferHist() != null && this
						.getTransferHist().equals(castOther.getTransferHist())))
				&& ((this.getDwSidedoer() == castOther.getDwSidedoer()) || (this
						.getDwSidedoer() != null
						&& castOther.getDwSidedoer() != null && this
						.getDwSidedoer().equals(castOther.getDwSidedoer())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getCrd() == null ? 0 : this.getCrd().hashCode());
		result = 37 * result
				+ (getImpt() == null ? 0 : this.getImpt().hashCode());
		result = 37 * result
				+ (getExpt() == null ? 0 : this.getExpt().hashCode());
		result = 37 * result
				+ (getImpd() == null ? 0 : this.getImpd().hashCode());
		result = 37 * result
				+ (getExpd() == null ? 0 : this.getExpd().hashCode());
		result = 37 * result
				+ (getModt() == null ? 0 : this.getModt().hashCode());
		result = 37 * result
				+ (getCru() == null ? 0 : this.getCru().hashCode());
		result = 37 * result
				+ (getDelt() == null ? 0 : this.getDelt().hashCode());
		result = 37 * result
				+ (getModd() == null ? 0 : this.getModd().hashCode());
		result = 37 * result
				+ (getImpu() == null ? 0 : this.getImpu().hashCode());
		result = 37 * result
				+ (getExpu() == null ? 0 : this.getExpu().hashCode());
		result = 37 * result
				+ (getDeld() == null ? 0 : this.getDeld().hashCode());
		result = 37 * result
				+ (getModu() == null ? 0 : this.getModu().hashCode());
		result = 37 * result
				+ (getDelu() == null ? 0 : this.getDelu().hashCode());
		result = 37 * result
				+ (getCrt() == null ? 0 : this.getCrt().hashCode());
		result = 37
				* result
				+ (getPrimtranssag() == null ? 0 : this.getPrimtranssag()
						.hashCode());
		result = 37 * result
				+ (getPrimdwa() == null ? 0 : this.getPrimdwa().hashCode());
		result = 37 * result
				+ (getCdmNoegle() == null ? 0 : this.getCdmNoegle().hashCode());
		result = 37
				* result
				+ (getAendringForetaget() == null ? 0 : this
						.getAendringForetaget().hashCode());
		result = 37 * result
				+ (getBoligtype() == null ? 0 : this.getBoligtype().hashCode());
		result = 37 * result
				+ (getCaInstId() == null ? 0 : this.getCaInstId().hashCode());
		result = 37
				* result
				+ (getCaInstLbnr() == null ? 0 : this.getCaInstLbnr()
						.hashCode());
		result = 37 * result
				+ (getCdmAdrId() == null ? 0 : this.getCdmAdrId().hashCode());
		result = 37 * result
				+ (getKommunenr() == null ? 0 : this.getKommunenr().hashCode());
		result = 37 * result
				+ (getVejkode() == null ? 0 : this.getVejkode().hashCode());
		result = 37
				* result
				+ (getInternVejkode() == null ? 0 : this.getInternVejkode()
						.hashCode());
		result = 37 * result
				+ (getGadenavn() == null ? 0 : this.getGadenavn().hashCode());
		result = 37 * result
				+ (getHusnr() == null ? 0 : this.getHusnr().hashCode());
		result = 37 * result
				+ (getOpgang() == null ? 0 : this.getOpgang().hashCode());
		result = 37 * result
				+ (getEtage() == null ? 0 : this.getEtage().hashCode());
		result = 37 * result
				+ (getSide() == null ? 0 : this.getSide().hashCode());
		result = 37 * result
				+ (getDoer() == null ? 0 : this.getDoer().hashCode());
		result = 37 * result
				+ (getPostnr() == null ? 0 : this.getPostnr().hashCode());
		result = 37 * result
				+ (getStednavn() == null ? 0 : this.getStednavn().hashCode());
		result = 37
				* result
				+ (getInstStatus() == null ? 0 : this.getInstStatus()
						.hashCode());
		result = 37
				* result
				+ (getIndividPkValg() == null ? 0 : this.getIndividPkValg()
						.hashCode());
		result = 37
				* result
				+ (getTransferStatus() == null ? 0 : this.getTransferStatus()
						.hashCode());
		result = 37 * result
				+ (getOprAnlNr() == null ? 0 : this.getOprAnlNr().hashCode());
		result = 37
				* result
				+ (getTransferHist() == null ? 0 : this.getTransferHist()
						.hashCode());
		result = 37
				* result
				+ (getDwSidedoer() == null ? 0 : this.getDwSidedoer()
						.hashCode());
		return result;
	}

}
