package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CatransAddressitem generated by hbm2java
 */
@Entity
@Table(name = "CATRANS_ADDRESSITEM", schema = "PCRM")
public class CatransAddressitem implements java.io.Serializable {

	private CatransAddressitemId id;

	public CatransAddressitem() {
	}

	public CatransAddressitem(CatransAddressitemId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", length = 19)),
			@AttributeOverride(name = "crd", column = @Column(name = "CRD", length = 7)),
			@AttributeOverride(name = "impt", column = @Column(name = "IMPT", length = 7)),
			@AttributeOverride(name = "expt", column = @Column(name = "EXPT", length = 7)),
			@AttributeOverride(name = "impd", column = @Column(name = "IMPD", length = 7)),
			@AttributeOverride(name = "expd", column = @Column(name = "EXPD", length = 7)),
			@AttributeOverride(name = "modt", column = @Column(name = "MODT", length = 7)),
			@AttributeOverride(name = "cru", column = @Column(name = "CRU", length = 19)),
			@AttributeOverride(name = "delt", column = @Column(name = "DELT", length = 7)),
			@AttributeOverride(name = "modd", column = @Column(name = "MODD", length = 7)),
			@AttributeOverride(name = "impu", column = @Column(name = "IMPU", length = 19)),
			@AttributeOverride(name = "expu", column = @Column(name = "EXPU", length = 19)),
			@AttributeOverride(name = "deld", column = @Column(name = "DELD", length = 7)),
			@AttributeOverride(name = "modu", column = @Column(name = "MODU", length = 19)),
			@AttributeOverride(name = "delu", column = @Column(name = "DELU", length = 19)),
			@AttributeOverride(name = "crt", column = @Column(name = "CRT", length = 7)),
			@AttributeOverride(name = "primtranssag", column = @Column(name = "PRIMTRANSSAG", length = 19)),
			@AttributeOverride(name = "primdwa", column = @Column(name = "PRIMDWA", length = 22)),
			@AttributeOverride(name = "cdmNoegle", column = @Column(name = "CDM_NOEGLE", length = 19)),
			@AttributeOverride(name = "aendringForetaget", column = @Column(name = "AENDRING_FORETAGET", length = 1)),
			@AttributeOverride(name = "boligtype", column = @Column(name = "BOLIGTYPE", length = 15)),
			@AttributeOverride(name = "caInstId", column = @Column(name = "CA_INST_ID", length = 19)),
			@AttributeOverride(name = "caInstLbnr", column = @Column(name = "CA_INST_LBNR", length = 19)),
			@AttributeOverride(name = "cdmAdrId", column = @Column(name = "CDM_ADR_ID", length = 5)),
			@AttributeOverride(name = "kommunenr", column = @Column(name = "KOMMUNENR", length = 4)),
			@AttributeOverride(name = "vejkode", column = @Column(name = "VEJKODE", length = 4)),
			@AttributeOverride(name = "internVejkode", column = @Column(name = "INTERN_VEJKODE", length = 1)),
			@AttributeOverride(name = "gadenavn", column = @Column(name = "GADENAVN", length = 40)),
			@AttributeOverride(name = "husnr", column = @Column(name = "HUSNR", length = 3)),
			@AttributeOverride(name = "opgang", column = @Column(name = "OPGANG", length = 1)),
			@AttributeOverride(name = "etage", column = @Column(name = "ETAGE", length = 2)),
			@AttributeOverride(name = "side", column = @Column(name = "SIDE", length = 4)),
			@AttributeOverride(name = "doer", column = @Column(name = "DOER", length = 4)),
			@AttributeOverride(name = "postnr", column = @Column(name = "POSTNR", length = 4)),
			@AttributeOverride(name = "stednavn", column = @Column(name = "STEDNAVN", length = 40)),
			@AttributeOverride(name = "instStatus", column = @Column(name = "INST_STATUS", length = 40)),
			@AttributeOverride(name = "individPkValg", column = @Column(name = "INDIVID_PK_VALG", length = 15)),
			@AttributeOverride(name = "transferStatus", column = @Column(name = "TRANSFER_STATUS", precision = 10, scale = 0)),
			@AttributeOverride(name = "oprAnlNr", column = @Column(name = "OPR_ANL_NR", length = 50)),
			@AttributeOverride(name = "transferHist", column = @Column(name = "TRANSFER_HIST")),
			@AttributeOverride(name = "dwSidedoer", column = @Column(name = "DW_SIDEDOER", length = 4)) })
	public CatransAddressitemId getId() {
		return this.id;
	}

	public void setId(CatransAddressitemId id) {
		this.id = id;
	}

}
