package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cdmcustproject generated by hbm2java
 */
@Entity
@Table(name = "CDMCUSTPROJECT", schema = "PCRM")
public class Cdmcustproject implements java.io.Serializable {

	private CdmcustprojectId id;

	public Cdmcustproject() {
	}

	public Cdmcustproject(CdmcustprojectId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", length = 19)),
			@AttributeOverride(name = "crd", column = @Column(name = "CRD", length = 7)),
			@AttributeOverride(name = "crt", column = @Column(name = "CRT", length = 7)),
			@AttributeOverride(name = "cru", column = @Column(name = "CRU", length = 19)),
			@AttributeOverride(name = "modd", column = @Column(name = "MODD", length = 7)),
			@AttributeOverride(name = "modt", column = @Column(name = "MODT", length = 7)),
			@AttributeOverride(name = "modu", column = @Column(name = "MODU", length = 19)),
			@AttributeOverride(name = "deld", column = @Column(name = "DELD", length = 7)),
			@AttributeOverride(name = "delt", column = @Column(name = "DELT", length = 7)),
			@AttributeOverride(name = "delu", column = @Column(name = "DELU", length = 19)),
			@AttributeOverride(name = "impd", column = @Column(name = "IMPD", length = 7)),
			@AttributeOverride(name = "impt", column = @Column(name = "IMPT", length = 7)),
			@AttributeOverride(name = "impu", column = @Column(name = "IMPU", length = 19)),
			@AttributeOverride(name = "expd", column = @Column(name = "EXPD", length = 7)),
			@AttributeOverride(name = "expt", column = @Column(name = "EXPT", length = 7)),
			@AttributeOverride(name = "expu", column = @Column(name = "EXPU", length = 19)),
			@AttributeOverride(name = "primportaluser", column = @Column(name = "PRIMPORTALUSER", length = 50)),
			@AttributeOverride(name = "primcuprowner", column = @Column(name = "PRIMCUPROWNER", length = 19)),
			@AttributeOverride(name = "primbasissegmbuildingtype", column = @Column(name = "PRIMBASISSEGMBUILDINGTYPE", length = 19)),
			@AttributeOverride(name = "primbasissegmbuildinguse", column = @Column(name = "PRIMBASISSEGMBUILDINGUSE", length = 19)),
			@AttributeOverride(name = "primbasissegmbuildingowner", column = @Column(name = "PRIMBASISSEGMBUILDINGOWNER", length = 19)),
			@AttributeOverride(name = "sourceSystem", column = @Column(name = "SOURCE_SYSTEM", length = 5)),
			@AttributeOverride(name = "projdebkontonr", column = @Column(name = "PROJDEBKONTONR", length = 10)),
			@AttributeOverride(name = "projanlaegsnr", column = @Column(name = "PROJANLAEGSNR", length = 10)),
			@AttributeOverride(name = "projnavn", column = @Column(name = "PROJNAVN", length = 40)),
			@AttributeOverride(name = "projpostnr", column = @Column(name = "PROJPOSTNR", length = 4)),
			@AttributeOverride(name = "tilslpotentiale", column = @Column(name = "TILSLPOTENTIALE", precision = 22, scale = 0)),
			@AttributeOverride(name = "tilslaktuel", column = @Column(name = "TILSLAKTUEL", precision = 22, scale = 0)),
			@AttributeOverride(name = "projaddress", column = @Column(name = "PROJADDRESS", length = 127)),
			@AttributeOverride(name = "anlaegstype", column = @Column(name = "ANLAEGSTYPE", length = 19)),
			@AttributeOverride(name = "accountmgrId", column = @Column(name = "ACCOUNTMGR_ID", length = 19)),
			@AttributeOverride(name = "checkedby", column = @Column(name = "CHECKEDBY", length = 19)),
			@AttributeOverride(name = "primanlaeg", column = @Column(name = "PRIMANLAEG", length = 10)) })
	public CdmcustprojectId getId() {
		return this.id;
	}

	public void setId(CdmcustprojectId id) {
		this.id = id;
	}

}
