package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CdmContactivity generated by hbm2java
 */
@Entity
@Table(name = "CDM_CONTACTIVITY", schema = "PCRM", uniqueConstraints = @UniqueConstraint(columnNames = "ID"))
public class CdmContactivity implements java.io.Serializable {

	private CdmContactivityId id;

	public CdmContactivity() {
	}

	public CdmContactivity(CdmContactivityId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", unique = true, length = 19)),
			@AttributeOverride(name = "crd", column = @Column(name = "CRD", length = 7)),
			@AttributeOverride(name = "crt", column = @Column(name = "CRT", length = 7)),
			@AttributeOverride(name = "cru", column = @Column(name = "CRU", length = 19)),
			@AttributeOverride(name = "modd", column = @Column(name = "MODD", length = 7)),
			@AttributeOverride(name = "modt", column = @Column(name = "MODT", length = 7)),
			@AttributeOverride(name = "modu", column = @Column(name = "MODU", length = 19)),
			@AttributeOverride(name = "deld", column = @Column(name = "DELD", length = 7)),
			@AttributeOverride(name = "delt", column = @Column(name = "DELT", length = 7)),
			@AttributeOverride(name = "delu", column = @Column(name = "DELU", length = 19)),
			@AttributeOverride(name = "impd", column = @Column(name = "IMPD", length = 7)),
			@AttributeOverride(name = "impt", column = @Column(name = "IMPT", length = 7)),
			@AttributeOverride(name = "impu", column = @Column(name = "IMPU", length = 19)),
			@AttributeOverride(name = "expd", column = @Column(name = "EXPD", length = 7)),
			@AttributeOverride(name = "expt", column = @Column(name = "EXPT", length = 7)),
			@AttributeOverride(name = "expu", column = @Column(name = "EXPU", length = 19)),
			@AttributeOverride(name = "primcont2comp", column = @Column(name = "PRIMCONT2COMP", length = 19)),
			@AttributeOverride(name = "primcontactivity", column = @Column(name = "PRIMCONTACTIVITY", length = 19)),
			@AttributeOverride(name = "activitytype", column = @Column(name = "ACTIVITYTYPE", length = 50)),
			@AttributeOverride(name = "prcstatus", column = @Column(name = "PRCSTATUS", length = 50)),
			@AttributeOverride(name = "prcstatusTs", column = @Column(name = "PRCSTATUS_TS", length = 7)) })
	public CdmContactivityId getId() {
		return this.id;
	}

	public void setId(CdmContactivityId id) {
		this.id = id;
	}

}
