package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cdmtypelookup generated by hbm2java
 */
@Entity
@Table(name = "CDMTYPELOOKUP", schema = "PCRM")
public class Cdmtypelookup implements java.io.Serializable {

	private CdmtypelookupId id;

	public Cdmtypelookup() {
	}

	public Cdmtypelookup(CdmtypelookupId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", length = 19)),
			@AttributeOverride(name = "heading", column = @Column(name = "HEADING")),
			@AttributeOverride(name = "crd", column = @Column(name = "CRD", length = 7)),
			@AttributeOverride(name = "code", column = @Column(name = "CODE", length = 20)),
			@AttributeOverride(name = "impt", column = @Column(name = "IMPT", length = 7)),
			@AttributeOverride(name = "expt", column = @Column(name = "EXPT", length = 7)),
			@AttributeOverride(name = "impd", column = @Column(name = "IMPD", length = 7)),
			@AttributeOverride(name = "expd", column = @Column(name = "EXPD", length = 7)),
			@AttributeOverride(name = "modt", column = @Column(name = "MODT", length = 7)),
			@AttributeOverride(name = "cru", column = @Column(name = "CRU", length = 19)),
			@AttributeOverride(name = "delt", column = @Column(name = "DELT", length = 7)),
			@AttributeOverride(name = "modd", column = @Column(name = "MODD", length = 7)),
			@AttributeOverride(name = "impu", column = @Column(name = "IMPU", length = 19)),
			@AttributeOverride(name = "expu", column = @Column(name = "EXPU", length = 19)),
			@AttributeOverride(name = "deld", column = @Column(name = "DELD", length = 7)),
			@AttributeOverride(name = "modu", column = @Column(name = "MODU", length = 19)),
			@AttributeOverride(name = "delu", column = @Column(name = "DELU", length = 19)),
			@AttributeOverride(name = "cdmtableclass", column = @Column(name = "CDMTABLECLASS", length = 80)),
			@AttributeOverride(name = "crt", column = @Column(name = "CRT", length = 7)),
			@AttributeOverride(name = "opslag", column = @Column(name = "OPSLAG", length = 200)),
			@AttributeOverride(name = "primaryowner", column = @Column(name = "PRIMARYOWNER", length = 19)),
			@AttributeOverride(name = "primaryopslag", column = @Column(name = "PRIMARYOPSLAG", length = 19)),
			@AttributeOverride(name = "rebmun", column = @Column(name = "REBMUN", precision = 10, scale = 0)),
			@AttributeOverride(name = "numvari", column = @Column(name = "NUMVARI", precision = 12)),
			@AttributeOverride(name = "charvari", column = @Column(name = "CHARVARI")),
			@AttributeOverride(name = "tsvari", column = @Column(name = "TSVARI", length = 7)),
			@AttributeOverride(name = "primaryopslagstype", column = @Column(name = "PRIMARYOPSLAGSTYPE", length = 19)),
			@AttributeOverride(name = "linkedattribute", column = @Column(name = "LINKEDATTRIBUTE")),
			@AttributeOverride(name = "endid", column = @Column(name = "ENDID", length = 19)),
			@AttributeOverride(name = "sourcesetting", column = @Column(name = "SOURCESETTING")),
			@AttributeOverride(name = "needscomments", column = @Column(name = "NEEDSCOMMENTS", length = 1)) })
	public CdmtypelookupId getId() {
		return this.id;
	}

	public void setId(CdmtypelookupId id) {
		this.id = id;
	}

}
