package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConstructionprojectChghist generated by hbm2java
 */
@Entity
@Table(name = "CONSTRUCTIONPROJECT_CHGHIST", schema = "PCRM")
public class ConstructionprojectChghist implements java.io.Serializable {

	private String audId;
	private String audAction;
	private Serializable audTimestamp;
	private String audOsuser;
	private String audDbuser;
	private String audUserterminal;
	private String id;
	private Date crd;
	private Date impt;
	private Date expt;
	private Date impd;
	private Date expd;
	private Date modt;
	private String cru;
	private Date delt;
	private Date modd;
	private String impu;
	private String expu;
	private Date deld;
	private String modu;
	private String delu;
	private Date crt;
	private String code;
	private String head;
	private BigDecimal belexmoms;
	private Character locked;
	private Character manual;
	private Character autom;
	private String primaryuser;
	private String projectno;
	private Date aflevfor;
	private Date stoejmaal;
	private Date stoejmaalgodk;
	private Date afsluttet;
	private Date opdat;
	private Date dokmodt;
	private Date prisoplyst;
	private Date godkendt;
	private Date ordre;
	private Date idrift;
	private Date annul;
	private String anlprojstatus;
	private Date lovetdato;
	private String primaryprojekttype;
	private String pstyrAnlaegsnr;
	private Date startdate;
	private Date stdlevdate;
	private Date faktidriftdate;
	private Date prisreturdate;
	private Date prisretur;
	private Date prisgyldig;
	private String primpssupplm;
	private String primsalgansv;
	private String primleverand;
	private String projektlobenr;
	private Character afsluttetbool;
	private Date afvist;
	private Date lovetidriftdato;
	private Date nylovetidriftdato;
	private Date ktaacceptdato;
	private Date godkordremodt;
	private Date godkforespmodt;
	private Character afhaengig;
	private BigDecimal timeLeft;
	private Character gravning;
	private String primgeneraltypevalue;
	private Date calcstdlevdate;
	private Date calcprisretur;
	private String logtrace;
	private BigDecimal costtotal;

	public ConstructionprojectChghist() {
	}

	public ConstructionprojectChghist(String audId) {
		this.audId = audId;
	}

	public ConstructionprojectChghist(String audId, String audAction,
			Serializable audTimestamp, String audOsuser, String audDbuser,
			String audUserterminal, String id, Date crd, Date impt, Date expt,
			Date impd, Date expd, Date modt, String cru, Date delt, Date modd,
			String impu, String expu, Date deld, String modu, String delu,
			Date crt, String code, String head, BigDecimal belexmoms,
			Character locked, Character manual, Character autom,
			String primaryuser, String projectno, Date aflevfor,
			Date stoejmaal, Date stoejmaalgodk, Date afsluttet, Date opdat,
			Date dokmodt, Date prisoplyst, Date godkendt, Date ordre,
			Date idrift, Date annul, String anlprojstatus, Date lovetdato,
			String primaryprojekttype, String pstyrAnlaegsnr, Date startdate,
			Date stdlevdate, Date faktidriftdate, Date prisreturdate,
			Date prisretur, Date prisgyldig, String primpssupplm,
			String primsalgansv, String primleverand, String projektlobenr,
			Character afsluttetbool, Date afvist, Date lovetidriftdato,
			Date nylovetidriftdato, Date ktaacceptdato, Date godkordremodt,
			Date godkforespmodt, Character afhaengig, BigDecimal timeLeft,
			Character gravning, String primgeneraltypevalue,
			Date calcstdlevdate, Date calcprisretur, String logtrace,
			BigDecimal costtotal) {
		this.audId = audId;
		this.audAction = audAction;
		this.audTimestamp = audTimestamp;
		this.audOsuser = audOsuser;
		this.audDbuser = audDbuser;
		this.audUserterminal = audUserterminal;
		this.id = id;
		this.crd = crd;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.cru = cru;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.modu = modu;
		this.delu = delu;
		this.crt = crt;
		this.code = code;
		this.head = head;
		this.belexmoms = belexmoms;
		this.locked = locked;
		this.manual = manual;
		this.autom = autom;
		this.primaryuser = primaryuser;
		this.projectno = projectno;
		this.aflevfor = aflevfor;
		this.stoejmaal = stoejmaal;
		this.stoejmaalgodk = stoejmaalgodk;
		this.afsluttet = afsluttet;
		this.opdat = opdat;
		this.dokmodt = dokmodt;
		this.prisoplyst = prisoplyst;
		this.godkendt = godkendt;
		this.ordre = ordre;
		this.idrift = idrift;
		this.annul = annul;
		this.anlprojstatus = anlprojstatus;
		this.lovetdato = lovetdato;
		this.primaryprojekttype = primaryprojekttype;
		this.pstyrAnlaegsnr = pstyrAnlaegsnr;
		this.startdate = startdate;
		this.stdlevdate = stdlevdate;
		this.faktidriftdate = faktidriftdate;
		this.prisreturdate = prisreturdate;
		this.prisretur = prisretur;
		this.prisgyldig = prisgyldig;
		this.primpssupplm = primpssupplm;
		this.primsalgansv = primsalgansv;
		this.primleverand = primleverand;
		this.projektlobenr = projektlobenr;
		this.afsluttetbool = afsluttetbool;
		this.afvist = afvist;
		this.lovetidriftdato = lovetidriftdato;
		this.nylovetidriftdato = nylovetidriftdato;
		this.ktaacceptdato = ktaacceptdato;
		this.godkordremodt = godkordremodt;
		this.godkforespmodt = godkforespmodt;
		this.afhaengig = afhaengig;
		this.timeLeft = timeLeft;
		this.gravning = gravning;
		this.primgeneraltypevalue = primgeneraltypevalue;
		this.calcstdlevdate = calcstdlevdate;
		this.calcprisretur = calcprisretur;
		this.logtrace = logtrace;
		this.costtotal = costtotal;
	}

	@Id
	@Column(name = "AUD_ID", unique = true, nullable = false, length = 19)
	public String getAudId() {
		return this.audId;
	}

	public void setAudId(String audId) {
		this.audId = audId;
	}

	@Column(name = "AUD_ACTION", length = 50)
	public String getAudAction() {
		return this.audAction;
	}

	public void setAudAction(String audAction) {
		this.audAction = audAction;
	}

	@Column(name = "AUD_TIMESTAMP")
	public Serializable getAudTimestamp() {
		return this.audTimestamp;
	}

	public void setAudTimestamp(Serializable audTimestamp) {
		this.audTimestamp = audTimestamp;
	}

	@Column(name = "AUD_OSUSER", length = 50)
	public String getAudOsuser() {
		return this.audOsuser;
	}

	public void setAudOsuser(String audOsuser) {
		this.audOsuser = audOsuser;
	}

	@Column(name = "AUD_DBUSER", length = 50)
	public String getAudDbuser() {
		return this.audDbuser;
	}

	public void setAudDbuser(String audDbuser) {
		this.audDbuser = audDbuser;
	}

	@Column(name = "AUD_USERTERMINAL", length = 50)
	public String getAudUserterminal() {
		return this.audUserterminal;
	}

	public void setAudUserterminal(String audUserterminal) {
		this.audUserterminal = audUserterminal;
	}

	@Column(name = "ID", length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "CODE", length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "HEAD")
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "BELEXMOMS", precision = 12)
	public BigDecimal getBelexmoms() {
		return this.belexmoms;
	}

	public void setBelexmoms(BigDecimal belexmoms) {
		this.belexmoms = belexmoms;
	}

	@Column(name = "LOCKED", length = 1)
	public Character getLocked() {
		return this.locked;
	}

	public void setLocked(Character locked) {
		this.locked = locked;
	}

	@Column(name = "MANUAL", length = 1)
	public Character getManual() {
		return this.manual;
	}

	public void setManual(Character manual) {
		this.manual = manual;
	}

	@Column(name = "AUTOM", length = 1)
	public Character getAutom() {
		return this.autom;
	}

	public void setAutom(Character autom) {
		this.autom = autom;
	}

	@Column(name = "PRIMARYUSER", length = 19)
	public String getPrimaryuser() {
		return this.primaryuser;
	}

	public void setPrimaryuser(String primaryuser) {
		this.primaryuser = primaryuser;
	}

	@Column(name = "PROJECTNO", length = 20)
	public String getProjectno() {
		return this.projectno;
	}

	public void setProjectno(String projectno) {
		this.projectno = projectno;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "AFLEVFOR", length = 7)
	public Date getAflevfor() {
		return this.aflevfor;
	}

	public void setAflevfor(Date aflevfor) {
		this.aflevfor = aflevfor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STOEJMAAL", length = 7)
	public Date getStoejmaal() {
		return this.stoejmaal;
	}

	public void setStoejmaal(Date stoejmaal) {
		this.stoejmaal = stoejmaal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STOEJMAALGODK", length = 7)
	public Date getStoejmaalgodk() {
		return this.stoejmaalgodk;
	}

	public void setStoejmaalgodk(Date stoejmaalgodk) {
		this.stoejmaalgodk = stoejmaalgodk;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "AFSLUTTET", length = 7)
	public Date getAfsluttet() {
		return this.afsluttet;
	}

	public void setAfsluttet(Date afsluttet) {
		this.afsluttet = afsluttet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OPDAT", length = 7)
	public Date getOpdat() {
		return this.opdat;
	}

	public void setOpdat(Date opdat) {
		this.opdat = opdat;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DOKMODT", length = 7)
	public Date getDokmodt() {
		return this.dokmodt;
	}

	public void setDokmodt(Date dokmodt) {
		this.dokmodt = dokmodt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PRISOPLYST", length = 7)
	public Date getPrisoplyst() {
		return this.prisoplyst;
	}

	public void setPrisoplyst(Date prisoplyst) {
		this.prisoplyst = prisoplyst;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GODKENDT", length = 7)
	public Date getGodkendt() {
		return this.godkendt;
	}

	public void setGodkendt(Date godkendt) {
		this.godkendt = godkendt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ORDRE", length = 7)
	public Date getOrdre() {
		return this.ordre;
	}

	public void setOrdre(Date ordre) {
		this.ordre = ordre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IDRIFT", length = 7)
	public Date getIdrift() {
		return this.idrift;
	}

	public void setIdrift(Date idrift) {
		this.idrift = idrift;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ANNUL", length = 7)
	public Date getAnnul() {
		return this.annul;
	}

	public void setAnnul(Date annul) {
		this.annul = annul;
	}

	@Column(name = "ANLPROJSTATUS", length = 50)
	public String getAnlprojstatus() {
		return this.anlprojstatus;
	}

	public void setAnlprojstatus(String anlprojstatus) {
		this.anlprojstatus = anlprojstatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LOVETDATO", length = 7)
	public Date getLovetdato() {
		return this.lovetdato;
	}

	public void setLovetdato(Date lovetdato) {
		this.lovetdato = lovetdato;
	}

	@Column(name = "PRIMARYPROJEKTTYPE", length = 19)
	public String getPrimaryprojekttype() {
		return this.primaryprojekttype;
	}

	public void setPrimaryprojekttype(String primaryprojekttype) {
		this.primaryprojekttype = primaryprojekttype;
	}

	@Column(name = "PSTYR_ANLAEGSNR", length = 10)
	public String getPstyrAnlaegsnr() {
		return this.pstyrAnlaegsnr;
	}

	public void setPstyrAnlaegsnr(String pstyrAnlaegsnr) {
		this.pstyrAnlaegsnr = pstyrAnlaegsnr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STARTDATE", length = 7)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STDLEVDATE", length = 7)
	public Date getStdlevdate() {
		return this.stdlevdate;
	}

	public void setStdlevdate(Date stdlevdate) {
		this.stdlevdate = stdlevdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FAKTIDRIFTDATE", length = 7)
	public Date getFaktidriftdate() {
		return this.faktidriftdate;
	}

	public void setFaktidriftdate(Date faktidriftdate) {
		this.faktidriftdate = faktidriftdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PRISRETURDATE", length = 7)
	public Date getPrisreturdate() {
		return this.prisreturdate;
	}

	public void setPrisreturdate(Date prisreturdate) {
		this.prisreturdate = prisreturdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PRISRETUR", length = 7)
	public Date getPrisretur() {
		return this.prisretur;
	}

	public void setPrisretur(Date prisretur) {
		this.prisretur = prisretur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PRISGYLDIG", length = 7)
	public Date getPrisgyldig() {
		return this.prisgyldig;
	}

	public void setPrisgyldig(Date prisgyldig) {
		this.prisgyldig = prisgyldig;
	}

	@Column(name = "PRIMPSSUPPLM", length = 19)
	public String getPrimpssupplm() {
		return this.primpssupplm;
	}

	public void setPrimpssupplm(String primpssupplm) {
		this.primpssupplm = primpssupplm;
	}

	@Column(name = "PRIMSALGANSV", length = 19)
	public String getPrimsalgansv() {
		return this.primsalgansv;
	}

	public void setPrimsalgansv(String primsalgansv) {
		this.primsalgansv = primsalgansv;
	}

	@Column(name = "PRIMLEVERAND", length = 19)
	public String getPrimleverand() {
		return this.primleverand;
	}

	public void setPrimleverand(String primleverand) {
		this.primleverand = primleverand;
	}

	@Column(name = "PROJEKTLOBENR", length = 20)
	public String getProjektlobenr() {
		return this.projektlobenr;
	}

	public void setProjektlobenr(String projektlobenr) {
		this.projektlobenr = projektlobenr;
	}

	@Column(name = "AFSLUTTETBOOL", length = 1)
	public Character getAfsluttetbool() {
		return this.afsluttetbool;
	}

	public void setAfsluttetbool(Character afsluttetbool) {
		this.afsluttetbool = afsluttetbool;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "AFVIST", length = 7)
	public Date getAfvist() {
		return this.afvist;
	}

	public void setAfvist(Date afvist) {
		this.afvist = afvist;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LOVETIDRIFTDATO", length = 7)
	public Date getLovetidriftdato() {
		return this.lovetidriftdato;
	}

	public void setLovetidriftdato(Date lovetidriftdato) {
		this.lovetidriftdato = lovetidriftdato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NYLOVETIDRIFTDATO", length = 7)
	public Date getNylovetidriftdato() {
		return this.nylovetidriftdato;
	}

	public void setNylovetidriftdato(Date nylovetidriftdato) {
		this.nylovetidriftdato = nylovetidriftdato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "KTAACCEPTDATO", length = 7)
	public Date getKtaacceptdato() {
		return this.ktaacceptdato;
	}

	public void setKtaacceptdato(Date ktaacceptdato) {
		this.ktaacceptdato = ktaacceptdato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GODKORDREMODT", length = 7)
	public Date getGodkordremodt() {
		return this.godkordremodt;
	}

	public void setGodkordremodt(Date godkordremodt) {
		this.godkordremodt = godkordremodt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "GODKFORESPMODT", length = 7)
	public Date getGodkforespmodt() {
		return this.godkforespmodt;
	}

	public void setGodkforespmodt(Date godkforespmodt) {
		this.godkforespmodt = godkforespmodt;
	}

	@Column(name = "AFHAENGIG", length = 1)
	public Character getAfhaengig() {
		return this.afhaengig;
	}

	public void setAfhaengig(Character afhaengig) {
		this.afhaengig = afhaengig;
	}

	@Column(name = "TIME_LEFT", precision = 22, scale = 0)
	public BigDecimal getTimeLeft() {
		return this.timeLeft;
	}

	public void setTimeLeft(BigDecimal timeLeft) {
		this.timeLeft = timeLeft;
	}

	@Column(name = "GRAVNING", length = 1)
	public Character getGravning() {
		return this.gravning;
	}

	public void setGravning(Character gravning) {
		this.gravning = gravning;
	}

	@Column(name = "PRIMGENERALTYPEVALUE", length = 19)
	public String getPrimgeneraltypevalue() {
		return this.primgeneraltypevalue;
	}

	public void setPrimgeneraltypevalue(String primgeneraltypevalue) {
		this.primgeneraltypevalue = primgeneraltypevalue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CALCSTDLEVDATE", length = 7)
	public Date getCalcstdlevdate() {
		return this.calcstdlevdate;
	}

	public void setCalcstdlevdate(Date calcstdlevdate) {
		this.calcstdlevdate = calcstdlevdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CALCPRISRETUR", length = 7)
	public Date getCalcprisretur() {
		return this.calcprisretur;
	}

	public void setCalcprisretur(Date calcprisretur) {
		this.calcprisretur = calcprisretur;
	}

	@Column(name = "LOGTRACE", length = 19)
	public String getLogtrace() {
		return this.logtrace;
	}

	public void setLogtrace(String logtrace) {
		this.logtrace = logtrace;
	}

	@Column(name = "COSTTOTAL", precision = 12)
	public BigDecimal getCosttotal() {
		return this.costtotal;
	}

	public void setCosttotal(BigDecimal costtotal) {
		this.costtotal = costtotal;
	}

}
