package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConstructionrequestChghist generated by hbm2java
 */
@Entity
@Table(name = "CONSTRUCTIONREQUEST_CHGHIST", schema = "PCRM")
public class ConstructionrequestChghist implements java.io.Serializable {

	private String audId;
	private String audAction;
	private Serializable audTimestamp;
	private String audOsuser;
	private String audDbuser;
	private String audUserterminal;
	private String id;
	private Date crd;
	private Date impt;
	private Date expt;
	private Date impd;
	private Date expd;
	private Date modt;
	private String cru;
	private Date delt;
	private Date modd;
	private String impu;
	private String expu;
	private Date deld;
	private String modu;
	private String delu;
	private Date crt;
	private String code;
	private String head;
	private Character estimeret;
	private String prodstyrno;
	private BigDecimal prisoverslag;
	private Character tilbudunderlev;
	private String primtilbkontr;
	private String primanlproj;
	private String primprojtype;
	private BigDecimal fn1;
	private BigDecimal fn2;
	private BigDecimal fn3;
	private BigDecimal opex;
	private String primaarsag;
	private Character active;
	private String primstatus2tbo;
	private String primactivity;
	private BigDecimal serviceaftale;
	private Date idrift;
	private Date tilbudgyldigt;
	private Date invalidated;
	private Date newdelidateconreq;
	private Date expectedproductionstart;
	private Date firstpossibledelivery;
	private BigDecimal costtotal;

	public ConstructionrequestChghist() {
	}

	public ConstructionrequestChghist(String audId) {
		this.audId = audId;
	}

	public ConstructionrequestChghist(String audId, String audAction,
			Serializable audTimestamp, String audOsuser, String audDbuser,
			String audUserterminal, String id, Date crd, Date impt, Date expt,
			Date impd, Date expd, Date modt, String cru, Date delt, Date modd,
			String impu, String expu, Date deld, String modu, String delu,
			Date crt, String code, String head, Character estimeret,
			String prodstyrno, BigDecimal prisoverslag,
			Character tilbudunderlev, String primtilbkontr, String primanlproj,
			String primprojtype, BigDecimal fn1, BigDecimal fn2,
			BigDecimal fn3, BigDecimal opex, String primaarsag,
			Character active, String primstatus2tbo, String primactivity,
			BigDecimal serviceaftale, Date idrift, Date tilbudgyldigt,
			Date invalidated, Date newdelidateconreq,
			Date expectedproductionstart, Date firstpossibledelivery,
			BigDecimal costtotal) {
		this.audId = audId;
		this.audAction = audAction;
		this.audTimestamp = audTimestamp;
		this.audOsuser = audOsuser;
		this.audDbuser = audDbuser;
		this.audUserterminal = audUserterminal;
		this.id = id;
		this.crd = crd;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.cru = cru;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.modu = modu;
		this.delu = delu;
		this.crt = crt;
		this.code = code;
		this.head = head;
		this.estimeret = estimeret;
		this.prodstyrno = prodstyrno;
		this.prisoverslag = prisoverslag;
		this.tilbudunderlev = tilbudunderlev;
		this.primtilbkontr = primtilbkontr;
		this.primanlproj = primanlproj;
		this.primprojtype = primprojtype;
		this.fn1 = fn1;
		this.fn2 = fn2;
		this.fn3 = fn3;
		this.opex = opex;
		this.primaarsag = primaarsag;
		this.active = active;
		this.primstatus2tbo = primstatus2tbo;
		this.primactivity = primactivity;
		this.serviceaftale = serviceaftale;
		this.idrift = idrift;
		this.tilbudgyldigt = tilbudgyldigt;
		this.invalidated = invalidated;
		this.newdelidateconreq = newdelidateconreq;
		this.expectedproductionstart = expectedproductionstart;
		this.firstpossibledelivery = firstpossibledelivery;
		this.costtotal = costtotal;
	}

	@Id
	@Column(name = "AUD_ID", unique = true, nullable = false, length = 19)
	public String getAudId() {
		return this.audId;
	}

	public void setAudId(String audId) {
		this.audId = audId;
	}

	@Column(name = "AUD_ACTION", length = 50)
	public String getAudAction() {
		return this.audAction;
	}

	public void setAudAction(String audAction) {
		this.audAction = audAction;
	}

	@Column(name = "AUD_TIMESTAMP")
	public Serializable getAudTimestamp() {
		return this.audTimestamp;
	}

	public void setAudTimestamp(Serializable audTimestamp) {
		this.audTimestamp = audTimestamp;
	}

	@Column(name = "AUD_OSUSER", length = 50)
	public String getAudOsuser() {
		return this.audOsuser;
	}

	public void setAudOsuser(String audOsuser) {
		this.audOsuser = audOsuser;
	}

	@Column(name = "AUD_DBUSER", length = 50)
	public String getAudDbuser() {
		return this.audDbuser;
	}

	public void setAudDbuser(String audDbuser) {
		this.audDbuser = audDbuser;
	}

	@Column(name = "AUD_USERTERMINAL", length = 50)
	public String getAudUserterminal() {
		return this.audUserterminal;
	}

	public void setAudUserterminal(String audUserterminal) {
		this.audUserterminal = audUserterminal;
	}

	@Column(name = "ID", length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "CODE", length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "HEAD")
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "ESTIMERET", length = 1)
	public Character getEstimeret() {
		return this.estimeret;
	}

	public void setEstimeret(Character estimeret) {
		this.estimeret = estimeret;
	}

	@Column(name = "PRODSTYRNO", length = 30)
	public String getProdstyrno() {
		return this.prodstyrno;
	}

	public void setProdstyrno(String prodstyrno) {
		this.prodstyrno = prodstyrno;
	}

	@Column(name = "PRISOVERSLAG", precision = 12)
	public BigDecimal getPrisoverslag() {
		return this.prisoverslag;
	}

	public void setPrisoverslag(BigDecimal prisoverslag) {
		this.prisoverslag = prisoverslag;
	}

	@Column(name = "TILBUDUNDERLEV", length = 1)
	public Character getTilbudunderlev() {
		return this.tilbudunderlev;
	}

	public void setTilbudunderlev(Character tilbudunderlev) {
		this.tilbudunderlev = tilbudunderlev;
	}

	@Column(name = "PRIMTILBKONTR", length = 19)
	public String getPrimtilbkontr() {
		return this.primtilbkontr;
	}

	public void setPrimtilbkontr(String primtilbkontr) {
		this.primtilbkontr = primtilbkontr;
	}

	@Column(name = "PRIMANLPROJ", length = 19)
	public String getPrimanlproj() {
		return this.primanlproj;
	}

	public void setPrimanlproj(String primanlproj) {
		this.primanlproj = primanlproj;
	}

	@Column(name = "PRIMPROJTYPE", length = 19)
	public String getPrimprojtype() {
		return this.primprojtype;
	}

	public void setPrimprojtype(String primprojtype) {
		this.primprojtype = primprojtype;
	}

	@Column(name = "FN1", precision = 12)
	public BigDecimal getFn1() {
		return this.fn1;
	}

	public void setFn1(BigDecimal fn1) {
		this.fn1 = fn1;
	}

	@Column(name = "FN2", precision = 12)
	public BigDecimal getFn2() {
		return this.fn2;
	}

	public void setFn2(BigDecimal fn2) {
		this.fn2 = fn2;
	}

	@Column(name = "FN3", precision = 12)
	public BigDecimal getFn3() {
		return this.fn3;
	}

	public void setFn3(BigDecimal fn3) {
		this.fn3 = fn3;
	}

	@Column(name = "OPEX", precision = 12)
	public BigDecimal getOpex() {
		return this.opex;
	}

	public void setOpex(BigDecimal opex) {
		this.opex = opex;
	}

	@Column(name = "PRIMAARSAG", length = 19)
	public String getPrimaarsag() {
		return this.primaarsag;
	}

	public void setPrimaarsag(String primaarsag) {
		this.primaarsag = primaarsag;
	}

	@Column(name = "ACTIVE", length = 1)
	public Character getActive() {
		return this.active;
	}

	public void setActive(Character active) {
		this.active = active;
	}

	@Column(name = "PRIMSTATUS2TBO", length = 19)
	public String getPrimstatus2tbo() {
		return this.primstatus2tbo;
	}

	public void setPrimstatus2tbo(String primstatus2tbo) {
		this.primstatus2tbo = primstatus2tbo;
	}

	@Column(name = "PRIMACTIVITY", length = 19)
	public String getPrimactivity() {
		return this.primactivity;
	}

	public void setPrimactivity(String primactivity) {
		this.primactivity = primactivity;
	}

	@Column(name = "SERVICEAFTALE", precision = 12)
	public BigDecimal getServiceaftale() {
		return this.serviceaftale;
	}

	public void setServiceaftale(BigDecimal serviceaftale) {
		this.serviceaftale = serviceaftale;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IDRIFT", length = 7)
	public Date getIdrift() {
		return this.idrift;
	}

	public void setIdrift(Date idrift) {
		this.idrift = idrift;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TILBUDGYLDIGT", length = 7)
	public Date getTilbudgyldigt() {
		return this.tilbudgyldigt;
	}

	public void setTilbudgyldigt(Date tilbudgyldigt) {
		this.tilbudgyldigt = tilbudgyldigt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INVALIDATED", length = 7)
	public Date getInvalidated() {
		return this.invalidated;
	}

	public void setInvalidated(Date invalidated) {
		this.invalidated = invalidated;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "NEWDELIDATECONREQ", length = 7)
	public Date getNewdelidateconreq() {
		return this.newdelidateconreq;
	}

	public void setNewdelidateconreq(Date newdelidateconreq) {
		this.newdelidateconreq = newdelidateconreq;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPECTEDPRODUCTIONSTART", length = 7)
	public Date getExpectedproductionstart() {
		return this.expectedproductionstart;
	}

	public void setExpectedproductionstart(Date expectedproductionstart) {
		this.expectedproductionstart = expectedproductionstart;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FIRSTPOSSIBLEDELIVERY", length = 7)
	public Date getFirstpossibledelivery() {
		return this.firstpossibledelivery;
	}

	public void setFirstpossibledelivery(Date firstpossibledelivery) {
		this.firstpossibledelivery = firstpossibledelivery;
	}

	@Column(name = "COSTTOTAL", precision = 12)
	public BigDecimal getCosttotal() {
		return this.costtotal;
	}

	public void setCosttotal(BigDecimal costtotal) {
		this.costtotal = costtotal;
	}

}
