package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContractversionOld generated by hbm2java
 */
@Entity
@Table(name = "CONTRACTVERSION_OLD", schema = "PCRM")
public class ContractversionOld implements java.io.Serializable {

	private ContractversionOldId id;
	private Docorigin docorigin;
	private Salesconcept salesconcept;

	public ContractversionOld() {
	}

	public ContractversionOld(ContractversionOldId id) {
		this.id = id;
	}

	public ContractversionOld(ContractversionOldId id, Docorigin docorigin,
			Salesconcept salesconcept) {
		this.id = id;
		this.docorigin = docorigin;
		this.salesconcept = salesconcept;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", length = 19)),
			@AttributeOverride(name = "crd", column = @Column(name = "CRD", length = 7)),
			@AttributeOverride(name = "code", column = @Column(name = "CODE", length = 15)),
			@AttributeOverride(name = "impt", column = @Column(name = "IMPT", length = 7)),
			@AttributeOverride(name = "expt", column = @Column(name = "EXPT", length = 7)),
			@AttributeOverride(name = "impd", column = @Column(name = "IMPD", length = 7)),
			@AttributeOverride(name = "expd", column = @Column(name = "EXPD", length = 7)),
			@AttributeOverride(name = "modt", column = @Column(name = "MODT", length = 7)),
			@AttributeOverride(name = "cru", column = @Column(name = "CRU", length = 19)),
			@AttributeOverride(name = "delt", column = @Column(name = "DELT", length = 7)),
			@AttributeOverride(name = "modd", column = @Column(name = "MODD", length = 7)),
			@AttributeOverride(name = "impu", column = @Column(name = "IMPU", length = 19)),
			@AttributeOverride(name = "expu", column = @Column(name = "EXPU", length = 19)),
			@AttributeOverride(name = "deld", column = @Column(name = "DELD", length = 7)),
			@AttributeOverride(name = "modu", column = @Column(name = "MODU", length = 19)),
			@AttributeOverride(name = "head", column = @Column(name = "HEAD")),
			@AttributeOverride(name = "delu", column = @Column(name = "DELU", length = 19)),
			@AttributeOverride(name = "crt", column = @Column(name = "CRT", length = 7)),
			@AttributeOverride(name = "primsalgskonc", column = @Column(name = "PRIMSALGSKONC", length = 19)),
			@AttributeOverride(name = "active", column = @Column(name = "ACTIVE", length = 1)),
			@AttributeOverride(name = "versionno", column = @Column(name = "VERSIONNO", precision = 10, scale = 0)),
			@AttributeOverride(name = "kontraktoverskrift", column = @Column(name = "KONTRAKTOVERSKRIFT", length = 2000)),
			@AttributeOverride(name = "aftaleomfatter", column = @Column(name = "AFTALEOMFATTER", length = 2000)),
			@AttributeOverride(name = "primcontrdoc", column = @Column(name = "PRIMCONTRDOC", length = 19)),
			@AttributeOverride(name = "primoriginal", column = @Column(name = "PRIMORIGINAL", length = 19)),
			@AttributeOverride(name = "primsuccessor", column = @Column(name = "PRIMSUCCESSOR", length = 19)),
			@AttributeOverride(name = "verdate", column = @Column(name = "VERDATE", length = 7)),
			@AttributeOverride(name = "nearlyactive", column = @Column(name = "NEARLYACTIVE", length = 1)),
			@AttributeOverride(name = "primdocorigin", column = @Column(name = "PRIMDOCORIGIN", length = 19)) })
	public ContractversionOldId getId() {
		return this.id;
	}

	public void setId(ContractversionOldId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMDOCORIGIN", insertable = false, updatable = false)
	public Docorigin getDocorigin() {
		return this.docorigin;
	}

	public void setDocorigin(Docorigin docorigin) {
		this.docorigin = docorigin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMSALGSKONC", insertable = false, updatable = false)
	public Salesconcept getSalesconcept() {
		return this.salesconcept;
	}

	public void setSalesconcept(Salesconcept salesconcept) {
		this.salesconcept = salesconcept;
	}

}
