package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrConceptproductspec generated by hbm2java
 */
@Entity
@Table(name = "CR_CONCEPTPRODUCTSPEC", schema = "PCRM")
public class CrConceptproductspec implements java.io.Serializable {

	private CrConceptproductspecId id;
	private Salesconcept salesconcept;

	public CrConceptproductspec() {
	}

	public CrConceptproductspec(CrConceptproductspecId id,
			Salesconcept salesconcept) {
		this.id = id;
		this.salesconcept = salesconcept;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "primsalesconcept", column = @Column(name = "PRIMSALESCONCEPT", nullable = false, length = 19)),
			@AttributeOverride(name = "primproductspec", column = @Column(name = "PRIMPRODUCTSPEC", nullable = false, length = 50)) })
	public CrConceptproductspecId getId() {
		return this.id;
	}

	public void setId(CrConceptproductspecId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMSALESCONCEPT", nullable = false, insertable = false, updatable = false)
	public Salesconcept getSalesconcept() {
		return this.salesconcept;
	}

	public void setSalesconcept(Salesconcept salesconcept) {
		this.salesconcept = salesconcept;
	}

}
