package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CrDocsectionhead2originId generated by hbm2java
 */
@Embeddable
public class CrDocsectionhead2originId implements java.io.Serializable {

	private String primdocsectionhead;
	private String primdocorigin;
	private String logtrace;

	public CrDocsectionhead2originId() {
	}

	public CrDocsectionhead2originId(String primdocsectionhead,
			String primdocorigin) {
		this.primdocsectionhead = primdocsectionhead;
		this.primdocorigin = primdocorigin;
	}

	public CrDocsectionhead2originId(String primdocsectionhead,
			String primdocorigin, String logtrace) {
		this.primdocsectionhead = primdocsectionhead;
		this.primdocorigin = primdocorigin;
		this.logtrace = logtrace;
	}

	@Column(name = "PRIMDOCSECTIONHEAD", nullable = false, length = 19)
	public String getPrimdocsectionhead() {
		return this.primdocsectionhead;
	}

	public void setPrimdocsectionhead(String primdocsectionhead) {
		this.primdocsectionhead = primdocsectionhead;
	}

	@Column(name = "PRIMDOCORIGIN", nullable = false, length = 19)
	public String getPrimdocorigin() {
		return this.primdocorigin;
	}

	public void setPrimdocorigin(String primdocorigin) {
		this.primdocorigin = primdocorigin;
	}

	@Column(name = "LOGTRACE", length = 19)
	public String getLogtrace() {
		return this.logtrace;
	}

	public void setLogtrace(String logtrace) {
		this.logtrace = logtrace;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CrDocsectionhead2originId))
			return false;
		CrDocsectionhead2originId castOther = (CrDocsectionhead2originId) other;

		return ((this.getPrimdocsectionhead() == castOther
				.getPrimdocsectionhead()) || (this.getPrimdocsectionhead() != null
				&& castOther.getPrimdocsectionhead() != null && this
				.getPrimdocsectionhead().equals(
						castOther.getPrimdocsectionhead())))
				&& ((this.getPrimdocorigin() == castOther.getPrimdocorigin()) || (this
						.getPrimdocorigin() != null
						&& castOther.getPrimdocorigin() != null && this
						.getPrimdocorigin()
						.equals(castOther.getPrimdocorigin())))
				&& ((this.getLogtrace() == castOther.getLogtrace()) || (this
						.getLogtrace() != null
						&& castOther.getLogtrace() != null && this
						.getLogtrace().equals(castOther.getLogtrace())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPrimdocsectionhead() == null ? 0 : this
						.getPrimdocsectionhead().hashCode());
		result = 37
				* result
				+ (getPrimdocorigin() == null ? 0 : this.getPrimdocorigin()
						.hashCode());
		result = 37 * result
				+ (getLogtrace() == null ? 0 : this.getLogtrace().hashCode());
		return result;
	}

}
