package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrDocorigin2concept generated by hbm2java
 */
@Entity
@Table(name = "CR_DOCORIGIN2CONCEPT", schema = "PCRM")
public class CrDocorigin2concept implements java.io.Serializable {

	private CrDocorigin2conceptId id;
	private Docorigin docorigin;
	private Salesconcept salesconcept;

	public CrDocorigin2concept() {
	}

	public CrDocorigin2concept(CrDocorigin2conceptId id) {
		this.id = id;
	}

	public CrDocorigin2concept(CrDocorigin2conceptId id, Docorigin docorigin,
			Salesconcept salesconcept) {
		this.id = id;
		this.docorigin = docorigin;
		this.salesconcept = salesconcept;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "primsalesconcept", column = @Column(name = "PRIMSALESCONCEPT", length = 19)),
			@AttributeOverride(name = "primdocorigin", column = @Column(name = "PRIMDOCORIGIN", length = 19)) })
	public CrDocorigin2conceptId getId() {
		return this.id;
	}

	public void setId(CrDocorigin2conceptId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMDOCORIGIN", insertable = false, updatable = false)
	public Docorigin getDocorigin() {
		return this.docorigin;
	}

	public void setDocorigin(Docorigin docorigin) {
		this.docorigin = docorigin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMSALESCONCEPT", insertable = false, updatable = false)
	public Salesconcept getSalesconcept() {
		return this.salesconcept;
	}

	public void setSalesconcept(Salesconcept salesconcept) {
		this.salesconcept = salesconcept;
	}

}
