package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrTemplateCasetype generated by hbm2java
 */
@Entity
@Table(name = "CR_TEMPLATE_CASETYPE", schema = "PCRM")
public class CrTemplateCasetype implements java.io.Serializable {

	private CrTemplateCasetypeId id;
	private Casetype casetype;
	private TemplateStore templateStore;

	public CrTemplateCasetype() {
	}

	public CrTemplateCasetype(CrTemplateCasetypeId id) {
		this.id = id;
	}

	public CrTemplateCasetype(CrTemplateCasetypeId id, Casetype casetype,
			TemplateStore templateStore) {
		this.id = id;
		this.casetype = casetype;
		this.templateStore = templateStore;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "primtemplateid", column = @Column(name = "PRIMTEMPLATEID", length = 19)),
			@AttributeOverride(name = "primcaseid", column = @Column(name = "PRIMCASEID", length = 19)) })
	public CrTemplateCasetypeId getId() {
		return this.id;
	}

	public void setId(CrTemplateCasetypeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMCASEID", insertable = false, updatable = false)
	public Casetype getCasetype() {
		return this.casetype;
	}

	public void setCasetype(Casetype casetype) {
		this.casetype = casetype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMTEMPLATEID", insertable = false, updatable = false)
	public TemplateStore getTemplateStore() {
		return this.templateStore;
	}

	public void setTemplateStore(TemplateStore templateStore) {
		this.templateStore = templateStore;
	}

}
