package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Doccomment generated by hbm2java
 */
@Entity
@Table(name = "DOCCOMMENT", schema = "PCRM")
public class Doccomment implements java.io.Serializable {

	private String id;
	private Docorigin docorigin;
	private Date crd;
	private String code;
	private Date impt;
	private Date expt;
	private Date impd;
	private Date expd;
	private Date modt;
	private String cru;
	private Date delt;
	private Date modd;
	private String impu;
	private String expu;
	private Date deld;
	private String modu;
	private String delu;
	private Date crt;
	private String primcontrdoc;
	private Clob heading;
	private String heading2;
	private BigDecimal commentnr;
	private Date validfrom;
	private Date validto;
	private Set<CrDoccomment2origin> crDoccomment2origins = new HashSet<CrDoccomment2origin>(
			0);
	private Set<Commentcollection> commentcollections = new HashSet<Commentcollection>(
			0);

	public Doccomment() {
	}

	public Doccomment(String id) {
		this.id = id;
	}

	public Doccomment(String id, Docorigin docorigin, Date crd, String code,
			Date impt, Date expt, Date impd, Date expd, Date modt, String cru,
			Date delt, Date modd, String impu, String expu, Date deld,
			String modu, String delu, Date crt, String primcontrdoc,
			Clob heading, String heading2, BigDecimal commentnr,
			Date validfrom, Date validto,
			Set<CrDoccomment2origin> crDoccomment2origins,
			Set<Commentcollection> commentcollections) {
		this.id = id;
		this.docorigin = docorigin;
		this.crd = crd;
		this.code = code;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.cru = cru;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.modu = modu;
		this.delu = delu;
		this.crt = crt;
		this.primcontrdoc = primcontrdoc;
		this.heading = heading;
		this.heading2 = heading2;
		this.commentnr = commentnr;
		this.validfrom = validfrom;
		this.validto = validto;
		this.crDoccomment2origins = crDoccomment2origins;
		this.commentcollections = commentcollections;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMDOCORIGIN")
	public Docorigin getDocorigin() {
		return this.docorigin;
	}

	public void setDocorigin(Docorigin docorigin) {
		this.docorigin = docorigin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CODE", length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "PRIMCONTRDOC", length = 19)
	public String getPrimcontrdoc() {
		return this.primcontrdoc;
	}

	public void setPrimcontrdoc(String primcontrdoc) {
		this.primcontrdoc = primcontrdoc;
	}

	@Column(name = "HEADING")
	public Clob getHeading() {
		return this.heading;
	}

	public void setHeading(Clob heading) {
		this.heading = heading;
	}

	@Column(name = "HEADING2", length = 4000)
	public String getHeading2() {
		return this.heading2;
	}

	public void setHeading2(String heading2) {
		this.heading2 = heading2;
	}

	@Column(name = "COMMENTNR", precision = 22, scale = 0)
	public BigDecimal getCommentnr() {
		return this.commentnr;
	}

	public void setCommentnr(BigDecimal commentnr) {
		this.commentnr = commentnr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VALIDFROM", length = 7)
	public Date getValidfrom() {
		return this.validfrom;
	}

	public void setValidfrom(Date validfrom) {
		this.validfrom = validfrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VALIDTO", length = 7)
	public Date getValidto() {
		return this.validto;
	}

	public void setValidto(Date validto) {
		this.validto = validto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "doccomment")
	public Set<CrDoccomment2origin> getCrDoccomment2origins() {
		return this.crDoccomment2origins;
	}

	public void setCrDoccomment2origins(
			Set<CrDoccomment2origin> crDoccomment2origins) {
		this.crDoccomment2origins = crDoccomment2origins;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "CR_COMMCOLL", schema = "PCRM", joinColumns = { @JoinColumn(name = "PRIMDOCCOMMENT", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "PRIMCOMMENTCOLLECTION", nullable = false, updatable = false) })
	public Set<Commentcollection> getCommentcollections() {
		return this.commentcollections;
	}

	public void setCommentcollections(Set<Commentcollection> commentcollections) {
		this.commentcollections = commentcollections;
	}

}
