package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Docorigin generated by hbm2java
 */
@Entity
@Table(name = "DOCORIGIN", schema = "PCRM", uniqueConstraints = @UniqueConstraint(columnNames = "SAVEFILENAME"))
public class Docorigin implements java.io.Serializable {

	private String id;
	private Doctopic doctopic;
	private Docoriginfolder docoriginfolder;
	private Date crd;
	private String primaryuser;
	private Date impt;
	private Date expt;
	private Date impd;
	private Date expd;
	private Date modt;
	private String cru;
	private Date delt;
	private Date modd;
	private String impu;
	private String expu;
	private Date deld;
	private String modu;
	private String fname;
	private String head;
	private String delu;
	private Character merge;
	private Date crt;
	private String primaryuserdepartment;
	private String class_;
	private String primarykludoktype;
	private Long mergedefinition;
	private String code;
	private String savefilename;
	private Character fritekst;
	private String docext;
	private String webservice;
	private Character includesprograms;
	private Character iscontract;
	private Character withts;
	private Date startDate;
	private Date endDate;
	private String logtrace;
	private Character isnumerationon;
	private Date versiondate;
	private String contracttitle;
	private Set<CrDocorigin2concept> crDocorigin2concepts = new HashSet<CrDocorigin2concept>(
			0);
	private Set<Docfieldproperty> docfieldproperties = new HashSet<Docfieldproperty>(
			0);
	private Set<Doccomment> doccomments = new HashSet<Doccomment>(0);
	private Set<Docdeptaccess> docdeptaccesses = new HashSet<Docdeptaccess>(0);
	private Set<ContractversionOld> contractversionOlds = new HashSet<ContractversionOld>(
			0);
	private Set<Salesconceptdoc> salesconceptdocs = new HashSet<Salesconceptdoc>(
			0);
	private Set<CrDocsection2origin> crDocsection2origins = new HashSet<CrDocsection2origin>(
			0);
	private Set<CrDocorigin2measurepoint> crDocorigin2measurepoints = new HashSet<CrDocorigin2measurepoint>(
			0);
	private Set<CrDocorigin2generaltypevalue> crDocorigin2generaltypevalues = new HashSet<CrDocorigin2generaltypevalue>(
			0);
	private Set<CrDocsectionhead2origin> crDocsectionhead2origins = new HashSet<CrDocsectionhead2origin>(
			0);
	private Set<CrDoccomment2origin> crDoccomment2origins = new HashSet<CrDoccomment2origin>(
			0);
	private Set<Document> documents = new HashSet<Document>(0);

	public Docorigin() {
	}

	public Docorigin(String id, Doctopic doctopic,
			Docoriginfolder docoriginfolder, String code, String savefilename) {
		this.id = id;
		this.doctopic = doctopic;
		this.docoriginfolder = docoriginfolder;
		this.code = code;
		this.savefilename = savefilename;
	}

	public Docorigin(String id, Doctopic doctopic,
			Docoriginfolder docoriginfolder, Date crd, String primaryuser,
			Date impt, Date expt, Date impd, Date expd, Date modt, String cru,
			Date delt, Date modd, String impu, String expu, Date deld,
			String modu, String fname, String head, String delu,
			Character merge, Date crt, String primaryuserdepartment,
			String class_, String primarykludoktype, Long mergedefinition,
			String code, String savefilename, Character fritekst,
			String docext, String webservice, Character includesprograms,
			Character iscontract, Character withts, Date startDate,
			Date endDate, String logtrace, Character isnumerationon,
			Date versiondate, String contracttitle,
			Set<CrDocorigin2concept> crDocorigin2concepts,
			Set<Docfieldproperty> docfieldproperties,
			Set<Doccomment> doccomments, Set<Docdeptaccess> docdeptaccesses,
			Set<ContractversionOld> contractversionOlds,
			Set<Salesconceptdoc> salesconceptdocs,
			Set<CrDocsection2origin> crDocsection2origins,
			Set<CrDocorigin2measurepoint> crDocorigin2measurepoints,
			Set<CrDocorigin2generaltypevalue> crDocorigin2generaltypevalues,
			Set<CrDocsectionhead2origin> crDocsectionhead2origins,
			Set<CrDoccomment2origin> crDoccomment2origins,
			Set<Document> documents) {
		this.id = id;
		this.doctopic = doctopic;
		this.docoriginfolder = docoriginfolder;
		this.crd = crd;
		this.primaryuser = primaryuser;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.cru = cru;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.modu = modu;
		this.fname = fname;
		this.head = head;
		this.delu = delu;
		this.merge = merge;
		this.crt = crt;
		this.primaryuserdepartment = primaryuserdepartment;
		this.class_ = class_;
		this.primarykludoktype = primarykludoktype;
		this.mergedefinition = mergedefinition;
		this.code = code;
		this.savefilename = savefilename;
		this.fritekst = fritekst;
		this.docext = docext;
		this.webservice = webservice;
		this.includesprograms = includesprograms;
		this.iscontract = iscontract;
		this.withts = withts;
		this.startDate = startDate;
		this.endDate = endDate;
		this.logtrace = logtrace;
		this.isnumerationon = isnumerationon;
		this.versiondate = versiondate;
		this.contracttitle = contracttitle;
		this.crDocorigin2concepts = crDocorigin2concepts;
		this.docfieldproperties = docfieldproperties;
		this.doccomments = doccomments;
		this.docdeptaccesses = docdeptaccesses;
		this.contractversionOlds = contractversionOlds;
		this.salesconceptdocs = salesconceptdocs;
		this.crDocsection2origins = crDocsection2origins;
		this.crDocorigin2measurepoints = crDocorigin2measurepoints;
		this.crDocorigin2generaltypevalues = crDocorigin2generaltypevalues;
		this.crDocsectionhead2origins = crDocsectionhead2origins;
		this.crDoccomment2origins = crDoccomment2origins;
		this.documents = documents;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMDOCTOPIC", nullable = false)
	public Doctopic getDoctopic() {
		return this.doctopic;
	}

	public void setDoctopic(Doctopic doctopic) {
		this.doctopic = doctopic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMDOCORIGINFOLDER", nullable = false)
	public Docoriginfolder getDocoriginfolder() {
		return this.docoriginfolder;
	}

	public void setDocoriginfolder(Docoriginfolder docoriginfolder) {
		this.docoriginfolder = docoriginfolder;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "PRIMARYUSER", length = 19)
	public String getPrimaryuser() {
		return this.primaryuser;
	}

	public void setPrimaryuser(String primaryuser) {
		this.primaryuser = primaryuser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "FNAME")
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "HEAD", length = 50)
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Column(name = "MERGE", length = 1)
	public Character getMerge() {
		return this.merge;
	}

	public void setMerge(Character merge) {
		this.merge = merge;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "PRIMARYUSERDEPARTMENT", length = 19)
	public String getPrimaryuserdepartment() {
		return this.primaryuserdepartment;
	}

	public void setPrimaryuserdepartment(String primaryuserdepartment) {
		this.primaryuserdepartment = primaryuserdepartment;
	}

	@Column(name = "CLASS", length = 80)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "PRIMARYKLUDOKTYPE", length = 19)
	public String getPrimarykludoktype() {
		return this.primarykludoktype;
	}

	public void setPrimarykludoktype(String primarykludoktype) {
		this.primarykludoktype = primarykludoktype;
	}

	@Column(name = "MERGEDEFINITION", precision = 10, scale = 0)
	public Long getMergedefinition() {
		return this.mergedefinition;
	}

	public void setMergedefinition(Long mergedefinition) {
		this.mergedefinition = mergedefinition;
	}

	@Column(name = "CODE", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "SAVEFILENAME", unique = true, nullable = false, length = 50)
	public String getSavefilename() {
		return this.savefilename;
	}

	public void setSavefilename(String savefilename) {
		this.savefilename = savefilename;
	}

	@Column(name = "FRITEKST", length = 1)
	public Character getFritekst() {
		return this.fritekst;
	}

	public void setFritekst(Character fritekst) {
		this.fritekst = fritekst;
	}

	@Column(name = "DOCEXT", length = 3)
	public String getDocext() {
		return this.docext;
	}

	public void setDocext(String docext) {
		this.docext = docext;
	}

	@Column(name = "WEBSERVICE")
	public String getWebservice() {
		return this.webservice;
	}

	public void setWebservice(String webservice) {
		this.webservice = webservice;
	}

	@Column(name = "INCLUDESPROGRAMS", length = 1)
	public Character getIncludesprograms() {
		return this.includesprograms;
	}

	public void setIncludesprograms(Character includesprograms) {
		this.includesprograms = includesprograms;
	}

	@Column(name = "ISCONTRACT", length = 1)
	public Character getIscontract() {
		return this.iscontract;
	}

	public void setIscontract(Character iscontract) {
		this.iscontract = iscontract;
	}

	@Column(name = "WITHTS", length = 1)
	public Character getWithts() {
		return this.withts;
	}

	public void setWithts(Character withts) {
		this.withts = withts;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "LOGTRACE", length = 19)
	public String getLogtrace() {
		return this.logtrace;
	}

	public void setLogtrace(String logtrace) {
		this.logtrace = logtrace;
	}

	@Column(name = "ISNUMERATIONON", length = 1)
	public Character getIsnumerationon() {
		return this.isnumerationon;
	}

	public void setIsnumerationon(Character isnumerationon) {
		this.isnumerationon = isnumerationon;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VERSIONDATE", length = 7)
	public Date getVersiondate() {
		return this.versiondate;
	}

	public void setVersiondate(Date versiondate) {
		this.versiondate = versiondate;
	}

	@Column(name = "CONTRACTTITLE", length = 2000)
	public String getContracttitle() {
		return this.contracttitle;
	}

	public void setContracttitle(String contracttitle) {
		this.contracttitle = contracttitle;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docorigin")
	public Set<CrDocorigin2concept> getCrDocorigin2concepts() {
		return this.crDocorigin2concepts;
	}

	public void setCrDocorigin2concepts(
			Set<CrDocorigin2concept> crDocorigin2concepts) {
		this.crDocorigin2concepts = crDocorigin2concepts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docorigin")
	public Set<Docfieldproperty> getDocfieldproperties() {
		return this.docfieldproperties;
	}

	public void setDocfieldproperties(Set<Docfieldproperty> docfieldproperties) {
		this.docfieldproperties = docfieldproperties;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docorigin")
	public Set<Doccomment> getDoccomments() {
		return this.doccomments;
	}

	public void setDoccomments(Set<Doccomment> doccomments) {
		this.doccomments = doccomments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docorigin")
	public Set<Docdeptaccess> getDocdeptaccesses() {
		return this.docdeptaccesses;
	}

	public void setDocdeptaccesses(Set<Docdeptaccess> docdeptaccesses) {
		this.docdeptaccesses = docdeptaccesses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docorigin")
	public Set<ContractversionOld> getContractversionOlds() {
		return this.contractversionOlds;
	}

	public void setContractversionOlds(
			Set<ContractversionOld> contractversionOlds) {
		this.contractversionOlds = contractversionOlds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docorigin")
	public Set<Salesconceptdoc> getSalesconceptdocs() {
		return this.salesconceptdocs;
	}

	public void setSalesconceptdocs(Set<Salesconceptdoc> salesconceptdocs) {
		this.salesconceptdocs = salesconceptdocs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docorigin")
	public Set<CrDocsection2origin> getCrDocsection2origins() {
		return this.crDocsection2origins;
	}

	public void setCrDocsection2origins(
			Set<CrDocsection2origin> crDocsection2origins) {
		this.crDocsection2origins = crDocsection2origins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docorigin")
	public Set<CrDocorigin2measurepoint> getCrDocorigin2measurepoints() {
		return this.crDocorigin2measurepoints;
	}

	public void setCrDocorigin2measurepoints(
			Set<CrDocorigin2measurepoint> crDocorigin2measurepoints) {
		this.crDocorigin2measurepoints = crDocorigin2measurepoints;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docorigin")
	public Set<CrDocorigin2generaltypevalue> getCrDocorigin2generaltypevalues() {
		return this.crDocorigin2generaltypevalues;
	}

	public void setCrDocorigin2generaltypevalues(
			Set<CrDocorigin2generaltypevalue> crDocorigin2generaltypevalues) {
		this.crDocorigin2generaltypevalues = crDocorigin2generaltypevalues;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docorigin")
	public Set<CrDocsectionhead2origin> getCrDocsectionhead2origins() {
		return this.crDocsectionhead2origins;
	}

	public void setCrDocsectionhead2origins(
			Set<CrDocsectionhead2origin> crDocsectionhead2origins) {
		this.crDocsectionhead2origins = crDocsectionhead2origins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docorigin")
	public Set<CrDoccomment2origin> getCrDoccomment2origins() {
		return this.crDoccomment2origins;
	}

	public void setCrDoccomment2origins(
			Set<CrDoccomment2origin> crDoccomment2origins) {
		this.crDoccomment2origins = crDoccomment2origins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docorigin")
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

}
