package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DocoriginChghist generated by hbm2java
 */
@Entity
@Table(name = "DOCORIGIN_CHGHIST", schema = "PCRM")
public class DocoriginChghist implements java.io.Serializable {

	private String audId;
	private String audAction;
	private Serializable audTimestamp;
	private String audOsuser;
	private String audDbuser;
	private String audUserterminal;
	private String id;
	private Date crd;
	private String primaryuser;
	private Date impt;
	private Date expt;
	private Date impd;
	private Date expd;
	private Date modt;
	private String cru;
	private Date delt;
	private Date modd;
	private String impu;
	private String expu;
	private Date deld;
	private String modu;
	private String fname;
	private String head;
	private String delu;
	private Character merge;
	private Date crt;
	private String primaryuserdepartment;
	private String class_;
	private String primarykludoktype;
	private Long mergedefinition;
	private String primdoctopic;
	private String code;
	private String savefilename;
	private Character fritekst;
	private String docext;
	private String webservice;
	private Character includesprograms;
	private Character iscontract;
	private Character withts;
	private String primdocoriginfolder;
	private Date startDate;
	private Date endDate;
	private String logtrace;
	private Character isnumerationon;
	private Date versiondate;
	private String contracttitle;

	public DocoriginChghist() {
	}

	public DocoriginChghist(String audId, String id) {
		this.audId = audId;
		this.id = id;
	}

	public DocoriginChghist(String audId, String audAction,
			Serializable audTimestamp, String audOsuser, String audDbuser,
			String audUserterminal, String id, Date crd, String primaryuser,
			Date impt, Date expt, Date impd, Date expd, Date modt, String cru,
			Date delt, Date modd, String impu, String expu, Date deld,
			String modu, String fname, String head, String delu,
			Character merge, Date crt, String primaryuserdepartment,
			String class_, String primarykludoktype, Long mergedefinition,
			String primdoctopic, String code, String savefilename,
			Character fritekst, String docext, String webservice,
			Character includesprograms, Character iscontract, Character withts,
			String primdocoriginfolder, Date startDate, Date endDate,
			String logtrace, Character isnumerationon, Date versiondate,
			String contracttitle) {
		this.audId = audId;
		this.audAction = audAction;
		this.audTimestamp = audTimestamp;
		this.audOsuser = audOsuser;
		this.audDbuser = audDbuser;
		this.audUserterminal = audUserterminal;
		this.id = id;
		this.crd = crd;
		this.primaryuser = primaryuser;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.cru = cru;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.modu = modu;
		this.fname = fname;
		this.head = head;
		this.delu = delu;
		this.merge = merge;
		this.crt = crt;
		this.primaryuserdepartment = primaryuserdepartment;
		this.class_ = class_;
		this.primarykludoktype = primarykludoktype;
		this.mergedefinition = mergedefinition;
		this.primdoctopic = primdoctopic;
		this.code = code;
		this.savefilename = savefilename;
		this.fritekst = fritekst;
		this.docext = docext;
		this.webservice = webservice;
		this.includesprograms = includesprograms;
		this.iscontract = iscontract;
		this.withts = withts;
		this.primdocoriginfolder = primdocoriginfolder;
		this.startDate = startDate;
		this.endDate = endDate;
		this.logtrace = logtrace;
		this.isnumerationon = isnumerationon;
		this.versiondate = versiondate;
		this.contracttitle = contracttitle;
	}

	@Id
	@Column(name = "AUD_ID", unique = true, nullable = false, length = 19)
	public String getAudId() {
		return this.audId;
	}

	public void setAudId(String audId) {
		this.audId = audId;
	}

	@Column(name = "AUD_ACTION", length = 50)
	public String getAudAction() {
		return this.audAction;
	}

	public void setAudAction(String audAction) {
		this.audAction = audAction;
	}

	@Column(name = "AUD_TIMESTAMP")
	public Serializable getAudTimestamp() {
		return this.audTimestamp;
	}

	public void setAudTimestamp(Serializable audTimestamp) {
		this.audTimestamp = audTimestamp;
	}

	@Column(name = "AUD_OSUSER", length = 50)
	public String getAudOsuser() {
		return this.audOsuser;
	}

	public void setAudOsuser(String audOsuser) {
		this.audOsuser = audOsuser;
	}

	@Column(name = "AUD_DBUSER", length = 50)
	public String getAudDbuser() {
		return this.audDbuser;
	}

	public void setAudDbuser(String audDbuser) {
		this.audDbuser = audDbuser;
	}

	@Column(name = "AUD_USERTERMINAL", length = 50)
	public String getAudUserterminal() {
		return this.audUserterminal;
	}

	public void setAudUserterminal(String audUserterminal) {
		this.audUserterminal = audUserterminal;
	}

	@Column(name = "ID", nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "PRIMARYUSER", length = 19)
	public String getPrimaryuser() {
		return this.primaryuser;
	}

	public void setPrimaryuser(String primaryuser) {
		this.primaryuser = primaryuser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "FNAME")
	public String getFname() {
		return this.fname;
	}

	public void setFname(String fname) {
		this.fname = fname;
	}

	@Column(name = "HEAD", length = 50)
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Column(name = "MERGE", length = 1)
	public Character getMerge() {
		return this.merge;
	}

	public void setMerge(Character merge) {
		this.merge = merge;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "PRIMARYUSERDEPARTMENT", length = 19)
	public String getPrimaryuserdepartment() {
		return this.primaryuserdepartment;
	}

	public void setPrimaryuserdepartment(String primaryuserdepartment) {
		this.primaryuserdepartment = primaryuserdepartment;
	}

	@Column(name = "CLASS", length = 80)
	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	@Column(name = "PRIMARYKLUDOKTYPE", length = 19)
	public String getPrimarykludoktype() {
		return this.primarykludoktype;
	}

	public void setPrimarykludoktype(String primarykludoktype) {
		this.primarykludoktype = primarykludoktype;
	}

	@Column(name = "MERGEDEFINITION", precision = 10, scale = 0)
	public Long getMergedefinition() {
		return this.mergedefinition;
	}

	public void setMergedefinition(Long mergedefinition) {
		this.mergedefinition = mergedefinition;
	}

	@Column(name = "PRIMDOCTOPIC", length = 19)
	public String getPrimdoctopic() {
		return this.primdoctopic;
	}

	public void setPrimdoctopic(String primdoctopic) {
		this.primdoctopic = primdoctopic;
	}

	@Column(name = "CODE", length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "SAVEFILENAME", length = 50)
	public String getSavefilename() {
		return this.savefilename;
	}

	public void setSavefilename(String savefilename) {
		this.savefilename = savefilename;
	}

	@Column(name = "FRITEKST", length = 1)
	public Character getFritekst() {
		return this.fritekst;
	}

	public void setFritekst(Character fritekst) {
		this.fritekst = fritekst;
	}

	@Column(name = "DOCEXT", length = 3)
	public String getDocext() {
		return this.docext;
	}

	public void setDocext(String docext) {
		this.docext = docext;
	}

	@Column(name = "WEBSERVICE")
	public String getWebservice() {
		return this.webservice;
	}

	public void setWebservice(String webservice) {
		this.webservice = webservice;
	}

	@Column(name = "INCLUDESPROGRAMS", length = 1)
	public Character getIncludesprograms() {
		return this.includesprograms;
	}

	public void setIncludesprograms(Character includesprograms) {
		this.includesprograms = includesprograms;
	}

	@Column(name = "ISCONTRACT", length = 1)
	public Character getIscontract() {
		return this.iscontract;
	}

	public void setIscontract(Character iscontract) {
		this.iscontract = iscontract;
	}

	@Column(name = "WITHTS", length = 1)
	public Character getWithts() {
		return this.withts;
	}

	public void setWithts(Character withts) {
		this.withts = withts;
	}

	@Column(name = "PRIMDOCORIGINFOLDER", length = 19)
	public String getPrimdocoriginfolder() {
		return this.primdocoriginfolder;
	}

	public void setPrimdocoriginfolder(String primdocoriginfolder) {
		this.primdocoriginfolder = primdocoriginfolder;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "LOGTRACE", length = 19)
	public String getLogtrace() {
		return this.logtrace;
	}

	public void setLogtrace(String logtrace) {
		this.logtrace = logtrace;
	}

	@Column(name = "ISNUMERATIONON", length = 1)
	public Character getIsnumerationon() {
		return this.isnumerationon;
	}

	public void setIsnumerationon(Character isnumerationon) {
		this.isnumerationon = isnumerationon;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VERSIONDATE", length = 7)
	public Date getVersiondate() {
		return this.versiondate;
	}

	public void setVersiondate(Date versiondate) {
		this.versiondate = versiondate;
	}

	@Column(name = "CONTRACTTITLE", length = 2000)
	public String getContracttitle() {
		return this.contracttitle;
	}

	public void setContracttitle(String contracttitle) {
		this.contracttitle = contracttitle;
	}

}
