package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmailParams generated by hbm2java
 */
@Entity
@Table(name = "EMAIL_PARAMS", schema = "PCRM")
public class EmailParams implements java.io.Serializable {

	private long paramId;
	private String paramName;
	private String paramValue;
	private String paramDescription;

	public EmailParams() {
	}

	public EmailParams(long paramId, String paramName, String paramValue) {
		this.paramId = paramId;
		this.paramName = paramName;
		this.paramValue = paramValue;
	}

	public EmailParams(long paramId, String paramName, String paramValue,
			String paramDescription) {
		this.paramId = paramId;
		this.paramName = paramName;
		this.paramValue = paramValue;
		this.paramDescription = paramDescription;
	}

	@Id
	@Column(name = "PARAM_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getParamId() {
		return this.paramId;
	}

	public void setParamId(long paramId) {
		this.paramId = paramId;
	}

	@Column(name = "PARAM_NAME", nullable = false, length = 50)
	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	@Column(name = "PARAM_VALUE", nullable = false, length = 500)
	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

	@Column(name = "PARAM_DESCRIPTION", length = 500)
	public String getParamDescription() {
		return this.paramDescription;
	}

	public void setParamDescription(String paramDescription) {
		this.paramDescription = paramDescription;
	}

}
