package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Esdhdossierbase generated by hbm2java
 */
@Entity
@Table(name = "ESDHDOSSIERBASE", schema = "PCRM")
public class Esdhdossierbase implements java.io.Serializable {

	private BigDecimal nodeid;
	private String title;
	private Long createdby;
	private Date createddate;
	private Date deadline;
	private Date mailreceiveddate;
	private Long dossiertype;
	private Long closed;
	private Long displayindex;
	private Long dossiernumber;
	private String mailreceivedfrom;
	private Date mailsenddate;
	private BigDecimal replytodossier;
	private Long storagetype;
	private Long classification;
	private Long mailisdigitallysigned;
	private String signeremail;
	private Long documentnametype;
	private String creatordepartment;
	private Date changeddate;
	private Long changedby;
	private Long documenttypefixed;
	private String worksmartid;

	public Esdhdossierbase() {
	}

	public Esdhdossierbase(BigDecimal nodeid) {
		this.nodeid = nodeid;
	}

	public Esdhdossierbase(BigDecimal nodeid, String title, Long createdby,
			Date createddate, Date deadline, Date mailreceiveddate,
			Long dossiertype, Long closed, Long displayindex,
			Long dossiernumber, String mailreceivedfrom, Date mailsenddate,
			BigDecimal replytodossier, Long storagetype, Long classification,
			Long mailisdigitallysigned, String signeremail,
			Long documentnametype, String creatordepartment, Date changeddate,
			Long changedby, Long documenttypefixed, String worksmartid) {
		this.nodeid = nodeid;
		this.title = title;
		this.createdby = createdby;
		this.createddate = createddate;
		this.deadline = deadline;
		this.mailreceiveddate = mailreceiveddate;
		this.dossiertype = dossiertype;
		this.closed = closed;
		this.displayindex = displayindex;
		this.dossiernumber = dossiernumber;
		this.mailreceivedfrom = mailreceivedfrom;
		this.mailsenddate = mailsenddate;
		this.replytodossier = replytodossier;
		this.storagetype = storagetype;
		this.classification = classification;
		this.mailisdigitallysigned = mailisdigitallysigned;
		this.signeremail = signeremail;
		this.documentnametype = documentnametype;
		this.creatordepartment = creatordepartment;
		this.changeddate = changeddate;
		this.changedby = changedby;
		this.documenttypefixed = documenttypefixed;
		this.worksmartid = worksmartid;
	}

	@Id
	@Column(name = "NODEID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getNodeid() {
		return this.nodeid;
	}

	public void setNodeid(BigDecimal nodeid) {
		this.nodeid = nodeid;
	}

	@Column(name = "TITLE", length = 256)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "CREATEDBY", precision = 10, scale = 0)
	public Long getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Long createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDDATE", length = 7)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DEADLINE", length = 7)
	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MAILRECEIVEDDATE", length = 7)
	public Date getMailreceiveddate() {
		return this.mailreceiveddate;
	}

	public void setMailreceiveddate(Date mailreceiveddate) {
		this.mailreceiveddate = mailreceiveddate;
	}

	@Column(name = "DOSSIERTYPE", precision = 10, scale = 0)
	public Long getDossiertype() {
		return this.dossiertype;
	}

	public void setDossiertype(Long dossiertype) {
		this.dossiertype = dossiertype;
	}

	@Column(name = "CLOSED", precision = 10, scale = 0)
	public Long getClosed() {
		return this.closed;
	}

	public void setClosed(Long closed) {
		this.closed = closed;
	}

	@Column(name = "DISPLAYINDEX", precision = 10, scale = 0)
	public Long getDisplayindex() {
		return this.displayindex;
	}

	public void setDisplayindex(Long displayindex) {
		this.displayindex = displayindex;
	}

	@Column(name = "DOSSIERNUMBER", precision = 10, scale = 0)
	public Long getDossiernumber() {
		return this.dossiernumber;
	}

	public void setDossiernumber(Long dossiernumber) {
		this.dossiernumber = dossiernumber;
	}

	@Column(name = "MAILRECEIVEDFROM", length = 100)
	public String getMailreceivedfrom() {
		return this.mailreceivedfrom;
	}

	public void setMailreceivedfrom(String mailreceivedfrom) {
		this.mailreceivedfrom = mailreceivedfrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MAILSENDDATE", length = 7)
	public Date getMailsenddate() {
		return this.mailsenddate;
	}

	public void setMailsenddate(Date mailsenddate) {
		this.mailsenddate = mailsenddate;
	}

	@Column(name = "REPLYTODOSSIER", precision = 22, scale = 0)
	public BigDecimal getReplytodossier() {
		return this.replytodossier;
	}

	public void setReplytodossier(BigDecimal replytodossier) {
		this.replytodossier = replytodossier;
	}

	@Column(name = "STORAGETYPE", precision = 10, scale = 0)
	public Long getStoragetype() {
		return this.storagetype;
	}

	public void setStoragetype(Long storagetype) {
		this.storagetype = storagetype;
	}

	@Column(name = "CLASSIFICATION", precision = 10, scale = 0)
	public Long getClassification() {
		return this.classification;
	}

	public void setClassification(Long classification) {
		this.classification = classification;
	}

	@Column(name = "MAILISDIGITALLYSIGNED", precision = 10, scale = 0)
	public Long getMailisdigitallysigned() {
		return this.mailisdigitallysigned;
	}

	public void setMailisdigitallysigned(Long mailisdigitallysigned) {
		this.mailisdigitallysigned = mailisdigitallysigned;
	}

	@Column(name = "SIGNEREMAIL", length = 100)
	public String getSigneremail() {
		return this.signeremail;
	}

	public void setSigneremail(String signeremail) {
		this.signeremail = signeremail;
	}

	@Column(name = "DOCUMENTNAMETYPE", precision = 10, scale = 0)
	public Long getDocumentnametype() {
		return this.documentnametype;
	}

	public void setDocumentnametype(Long documentnametype) {
		this.documentnametype = documentnametype;
	}

	@Column(name = "CREATORDEPARTMENT", length = 50)
	public String getCreatordepartment() {
		return this.creatordepartment;
	}

	public void setCreatordepartment(String creatordepartment) {
		this.creatordepartment = creatordepartment;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHANGEDDATE", length = 7)
	public Date getChangeddate() {
		return this.changeddate;
	}

	public void setChangeddate(Date changeddate) {
		this.changeddate = changeddate;
	}

	@Column(name = "CHANGEDBY", precision = 10, scale = 0)
	public Long getChangedby() {
		return this.changedby;
	}

	public void setChangedby(Long changedby) {
		this.changedby = changedby;
	}

	@Column(name = "DOCUMENTTYPEFIXED", precision = 10, scale = 0)
	public Long getDocumenttypefixed() {
		return this.documenttypefixed;
	}

	public void setDocumenttypefixed(Long documenttypefixed) {
		this.documenttypefixed = documenttypefixed;
	}

	@Column(name = "WORKSMARTID")
	public String getWorksmartid() {
		return this.worksmartid;
	}

	public void setWorksmartid(String worksmartid) {
		this.worksmartid = worksmartid;
	}

}
