package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FutureSubscription generated by hbm2java
 */
@Entity
@Table(name = "FUTURE_SUBSCRIPTION", schema = "PCRM")
public class FutureSubscription implements java.io.Serializable {

	private String id;
	private Long addressid;
	private BigDecimal installationseq;
	private String cableunitid;
	private String installationstatus;
	private Date subscriptionEnddate;
	private String dbJobflag;
	private String dbJobremark;

	public FutureSubscription() {
	}

	public FutureSubscription(String id) {
		this.id = id;
	}

	public FutureSubscription(String id, Long addressid,
			BigDecimal installationseq, String cableunitid,
			String installationstatus, Date subscriptionEnddate,
			String dbJobflag, String dbJobremark) {
		this.id = id;
		this.addressid = addressid;
		this.installationseq = installationseq;
		this.cableunitid = cableunitid;
		this.installationstatus = installationstatus;
		this.subscriptionEnddate = subscriptionEnddate;
		this.dbJobflag = dbJobflag;
		this.dbJobremark = dbJobremark;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ADDRESSID", precision = 10, scale = 0)
	public Long getAddressid() {
		return this.addressid;
	}

	public void setAddressid(Long addressid) {
		this.addressid = addressid;
	}

	@Column(name = "INSTALLATIONSEQ", precision = 22, scale = 0)
	public BigDecimal getInstallationseq() {
		return this.installationseq;
	}

	public void setInstallationseq(BigDecimal installationseq) {
		this.installationseq = installationseq;
	}

	@Column(name = "CABLEUNITID", length = 10)
	public String getCableunitid() {
		return this.cableunitid;
	}

	public void setCableunitid(String cableunitid) {
		this.cableunitid = cableunitid;
	}

	@Column(name = "INSTALLATIONSTATUS", length = 19)
	public String getInstallationstatus() {
		return this.installationstatus;
	}

	public void setInstallationstatus(String installationstatus) {
		this.installationstatus = installationstatus;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SUBSCRIPTION_ENDDATE", length = 7)
	public Date getSubscriptionEnddate() {
		return this.subscriptionEnddate;
	}

	public void setSubscriptionEnddate(Date subscriptionEnddate) {
		this.subscriptionEnddate = subscriptionEnddate;
	}

	@Column(name = "DB_JOBFLAG", length = 1)
	public String getDbJobflag() {
		return this.dbJobflag;
	}

	public void setDbJobflag(String dbJobflag) {
		this.dbJobflag = dbJobflag;
	}

	@Column(name = "DB_JOBREMARK", length = 500)
	public String getDbJobremark() {
		return this.dbJobremark;
	}

	public void setDbJobremark(String dbJobremark) {
		this.dbJobremark = dbJobremark;
	}

}
