package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * HtmlReplace generated by hbm2java
 */
@Entity
@Table(name = "HTML_REPLACE", schema = "PCRM")
public class HtmlReplace implements java.io.Serializable {

	private HtmlReplaceId id;

	public HtmlReplace() {
	}

	public HtmlReplace(HtmlReplaceId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "find", column = @Column(name = "FIND", length = 10)),
			@AttributeOverride(name = "substitute", column = @Column(name = "SUBSTITUTE", length = 10)) })
	public HtmlReplaceId getId() {
		return this.id;
	}

	public void setId(HtmlReplaceId id) {
		this.id = id;
	}

}
