package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * JobStatus generated by hbm2java
 */
@Entity
@Table(name = "JOB_STATUS", schema = "PCRM")
public class JobStatus implements java.io.Serializable {

	private JobStatusId id;

	public JobStatus() {
	}

	public JobStatus(JobStatusId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", length = 19)),
			@AttributeOverride(name = "crd", column = @Column(name = "CRD", length = 7)),
			@AttributeOverride(name = "impd", column = @Column(name = "IMPD", length = 7)),
			@AttributeOverride(name = "expd", column = @Column(name = "EXPD", length = 7)),
			@AttributeOverride(name = "cru", column = @Column(name = "CRU", length = 19)),
			@AttributeOverride(name = "modd", column = @Column(name = "MODD", length = 7)),
			@AttributeOverride(name = "impu", column = @Column(name = "IMPU", length = 19)),
			@AttributeOverride(name = "expu", column = @Column(name = "EXPU", length = 19)),
			@AttributeOverride(name = "modu", column = @Column(name = "MODU", length = 19)),
			@AttributeOverride(name = "jobname", column = @Column(name = "JOBNAME", length = 50)),
			@AttributeOverride(name = "executionDate", column = @Column(name = "EXECUTION_DATE", length = 7)),
			@AttributeOverride(name = "jobstatus", column = @Column(name = "JOBSTATUS", length = 20)),
			@AttributeOverride(name = "errDesc", column = @Column(name = "ERR_DESC", length = 200)) })
	public JobStatusId getId() {
		return this.id;
	}

	public void setId(JobStatusId id) {
		this.id = id;
	}

}
