package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JunkCharError generated by hbm2java
 */
@Entity
@Table(name = "JUNK_CHAR_ERROR", schema = "PCRM")
public class JunkCharError implements java.io.Serializable {

	private JunkCharErrorId id;
	private JunkCharTabCols junkCharTabCols;

	public JunkCharError() {
	}

	public JunkCharError(JunkCharErrorId id) {
		this.id = id;
	}

	public JunkCharError(JunkCharErrorId id, JunkCharTabCols junkCharTabCols) {
		this.id = id;
		this.junkCharTabCols = junkCharTabCols;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", precision = 10, scale = 0)),
			@AttributeOverride(name = "jctId", column = @Column(name = "JCT_ID", precision = 10, scale = 0)),
			@AttributeOverride(name = "errorText", column = @Column(name = "ERROR_TEXT", length = 2000)) })
	public JunkCharErrorId getId() {
		return this.id;
	}

	public void setId(JunkCharErrorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "JCT_ID", insertable = false, updatable = false)
	public JunkCharTabCols getJunkCharTabCols() {
		return this.junkCharTabCols;
	}

	public void setJunkCharTabCols(JunkCharTabCols junkCharTabCols) {
		this.junkCharTabCols = junkCharTabCols;
	}

}
