package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JunkCharTabCols generated by hbm2java
 */
@Entity
@Table(name = "JUNK_CHAR_TAB_COLS", schema = "PCRM")
public class JunkCharTabCols implements java.io.Serializable {

	private long id;
	private long runId;
	private String tableName;
	private String columnName;
	private String datatype;
	private Integer noOfRows;
	private Date foundOn;
	private String purpose;
	private Set<JunkCharError> junkCharErrors = new HashSet<JunkCharError>(0);

	public JunkCharTabCols() {
	}

	public JunkCharTabCols(long id, long runId) {
		this.id = id;
		this.runId = runId;
	}

	public JunkCharTabCols(long id, long runId, String tableName,
			String columnName, String datatype, Integer noOfRows, Date foundOn,
			String purpose, Set<JunkCharError> junkCharErrors) {
		this.id = id;
		this.runId = runId;
		this.tableName = tableName;
		this.columnName = columnName;
		this.datatype = datatype;
		this.noOfRows = noOfRows;
		this.foundOn = foundOn;
		this.purpose = purpose;
		this.junkCharErrors = junkCharErrors;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "RUN_ID", nullable = false, precision = 10, scale = 0)
	public long getRunId() {
		return this.runId;
	}

	public void setRunId(long runId) {
		this.runId = runId;
	}

	@Column(name = "TABLE_NAME", length = 30)
	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	@Column(name = "COLUMN_NAME", length = 30)
	public String getColumnName() {
		return this.columnName;
	}

	public void setColumnName(String columnName) {
		this.columnName = columnName;
	}

	@Column(name = "DATATYPE", length = 30)
	public String getDatatype() {
		return this.datatype;
	}

	public void setDatatype(String datatype) {
		this.datatype = datatype;
	}

	@Column(name = "NO_OF_ROWS", precision = 5, scale = 0)
	public Integer getNoOfRows() {
		return this.noOfRows;
	}

	public void setNoOfRows(Integer noOfRows) {
		this.noOfRows = noOfRows;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FOUND_ON", length = 7)
	public Date getFoundOn() {
		return this.foundOn;
	}

	public void setFoundOn(Date foundOn) {
		this.foundOn = foundOn;
	}

	@Column(name = "PURPOSE", length = 20)
	public String getPurpose() {
		return this.purpose;
	}

	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "junkCharTabCols")
	public Set<JunkCharError> getJunkCharErrors() {
		return this.junkCharErrors;
	}

	public void setJunkCharErrors(Set<JunkCharError> junkCharErrors) {
		this.junkCharErrors = junkCharErrors;
	}

}
