package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KtvBuc2xalChghist generated by hbm2java
 */
@Entity
@Table(name = "KTV_BUC2XAL_CHGHIST", schema = "PCRM")
public class KtvBuc2xalChghist implements java.io.Serializable {

	private String audId;
	private String audAction;
	private Serializable audTimestamp;
	private String audOsuser;
	private String audDbuser;
	private String audUserterminal;
	private String id;
	private String dataset;
	private BigDecimal lxbenummer;
	private Date sidstrettet;
	private String transaktionstype;
	private Date afsendtdato;
	private String afsendtklokken;
	private String terminalid;
	private Date behandletdato;
	private String behandletklokken;
	private BigDecimal behandletstatus;
	private BigDecimal xrsagskode;
	private String kundeemneId;
	private String adresseId;
	private String instLbnr;
	private String adresseIdny;
	private String instLbnrny;
	private short grundpakkekode;
	private short tillxgspakkekode;
	private String anlxg;
	private Date fradato;
	private String anlxgny;
	private String installation;

	public KtvBuc2xalChghist() {
	}

	public KtvBuc2xalChghist(String audId, String dataset,
			BigDecimal lxbenummer, Date sidstrettet, String transaktionstype,
			Date afsendtdato, String afsendtklokken, String terminalid,
			Date behandletdato, String behandletklokken,
			BigDecimal behandletstatus, BigDecimal xrsagskode,
			String kundeemneId, String adresseId, String instLbnr,
			String adresseIdny, String instLbnrny, short grundpakkekode,
			short tillxgspakkekode, String anlxg, Date fradato, String anlxgny,
			String installation) {
		this.audId = audId;
		this.dataset = dataset;
		this.lxbenummer = lxbenummer;
		this.sidstrettet = sidstrettet;
		this.transaktionstype = transaktionstype;
		this.afsendtdato = afsendtdato;
		this.afsendtklokken = afsendtklokken;
		this.terminalid = terminalid;
		this.behandletdato = behandletdato;
		this.behandletklokken = behandletklokken;
		this.behandletstatus = behandletstatus;
		this.xrsagskode = xrsagskode;
		this.kundeemneId = kundeemneId;
		this.adresseId = adresseId;
		this.instLbnr = instLbnr;
		this.adresseIdny = adresseIdny;
		this.instLbnrny = instLbnrny;
		this.grundpakkekode = grundpakkekode;
		this.tillxgspakkekode = tillxgspakkekode;
		this.anlxg = anlxg;
		this.fradato = fradato;
		this.anlxgny = anlxgny;
		this.installation = installation;
	}

	public KtvBuc2xalChghist(String audId, String audAction,
			Serializable audTimestamp, String audOsuser, String audDbuser,
			String audUserterminal, String id, String dataset,
			BigDecimal lxbenummer, Date sidstrettet, String transaktionstype,
			Date afsendtdato, String afsendtklokken, String terminalid,
			Date behandletdato, String behandletklokken,
			BigDecimal behandletstatus, BigDecimal xrsagskode,
			String kundeemneId, String adresseId, String instLbnr,
			String adresseIdny, String instLbnrny, short grundpakkekode,
			short tillxgspakkekode, String anlxg, Date fradato, String anlxgny,
			String installation) {
		this.audId = audId;
		this.audAction = audAction;
		this.audTimestamp = audTimestamp;
		this.audOsuser = audOsuser;
		this.audDbuser = audDbuser;
		this.audUserterminal = audUserterminal;
		this.id = id;
		this.dataset = dataset;
		this.lxbenummer = lxbenummer;
		this.sidstrettet = sidstrettet;
		this.transaktionstype = transaktionstype;
		this.afsendtdato = afsendtdato;
		this.afsendtklokken = afsendtklokken;
		this.terminalid = terminalid;
		this.behandletdato = behandletdato;
		this.behandletklokken = behandletklokken;
		this.behandletstatus = behandletstatus;
		this.xrsagskode = xrsagskode;
		this.kundeemneId = kundeemneId;
		this.adresseId = adresseId;
		this.instLbnr = instLbnr;
		this.adresseIdny = adresseIdny;
		this.instLbnrny = instLbnrny;
		this.grundpakkekode = grundpakkekode;
		this.tillxgspakkekode = tillxgspakkekode;
		this.anlxg = anlxg;
		this.fradato = fradato;
		this.anlxgny = anlxgny;
		this.installation = installation;
	}

	@Id
	@Column(name = "AUD_ID", unique = true, nullable = false, length = 19)
	public String getAudId() {
		return this.audId;
	}

	public void setAudId(String audId) {
		this.audId = audId;
	}

	@Column(name = "AUD_ACTION", length = 50)
	public String getAudAction() {
		return this.audAction;
	}

	public void setAudAction(String audAction) {
		this.audAction = audAction;
	}

	@Column(name = "AUD_TIMESTAMP")
	public Serializable getAudTimestamp() {
		return this.audTimestamp;
	}

	public void setAudTimestamp(Serializable audTimestamp) {
		this.audTimestamp = audTimestamp;
	}

	@Column(name = "AUD_OSUSER", length = 50)
	public String getAudOsuser() {
		return this.audOsuser;
	}

	public void setAudOsuser(String audOsuser) {
		this.audOsuser = audOsuser;
	}

	@Column(name = "AUD_DBUSER", length = 50)
	public String getAudDbuser() {
		return this.audDbuser;
	}

	public void setAudDbuser(String audDbuser) {
		this.audDbuser = audDbuser;
	}

	@Column(name = "AUD_USERTERMINAL", length = 50)
	public String getAudUserterminal() {
		return this.audUserterminal;
	}

	public void setAudUserterminal(String audUserterminal) {
		this.audUserterminal = audUserterminal;
	}

	@Column(name = "ID", length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "DATASET", nullable = false, length = 3)
	public String getDataset() {
		return this.dataset;
	}

	public void setDataset(String dataset) {
		this.dataset = dataset;
	}

	@Column(name = "LXBENUMMER", nullable = false, precision = 22, scale = 0)
	public BigDecimal getLxbenummer() {
		return this.lxbenummer;
	}

	public void setLxbenummer(BigDecimal lxbenummer) {
		this.lxbenummer = lxbenummer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SIDSTRETTET", nullable = false, length = 7)
	public Date getSidstrettet() {
		return this.sidstrettet;
	}

	public void setSidstrettet(Date sidstrettet) {
		this.sidstrettet = sidstrettet;
	}

	@Column(name = "TRANSAKTIONSTYPE", nullable = false, length = 4)
	public String getTransaktionstype() {
		return this.transaktionstype;
	}

	public void setTransaktionstype(String transaktionstype) {
		this.transaktionstype = transaktionstype;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "AFSENDTDATO", nullable = false, length = 7)
	public Date getAfsendtdato() {
		return this.afsendtdato;
	}

	public void setAfsendtdato(Date afsendtdato) {
		this.afsendtdato = afsendtdato;
	}

	@Column(name = "AFSENDTKLOKKEN", nullable = false, length = 8)
	public String getAfsendtklokken() {
		return this.afsendtklokken;
	}

	public void setAfsendtklokken(String afsendtklokken) {
		this.afsendtklokken = afsendtklokken;
	}

	@Column(name = "TERMINALID", nullable = false, length = 10)
	public String getTerminalid() {
		return this.terminalid;
	}

	public void setTerminalid(String terminalid) {
		this.terminalid = terminalid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BEHANDLETDATO", nullable = false, length = 7)
	public Date getBehandletdato() {
		return this.behandletdato;
	}

	public void setBehandletdato(Date behandletdato) {
		this.behandletdato = behandletdato;
	}

	@Column(name = "BEHANDLETKLOKKEN", nullable = false, length = 8)
	public String getBehandletklokken() {
		return this.behandletklokken;
	}

	public void setBehandletklokken(String behandletklokken) {
		this.behandletklokken = behandletklokken;
	}

	@Column(name = "BEHANDLETSTATUS", nullable = false, precision = 22, scale = 0)
	public BigDecimal getBehandletstatus() {
		return this.behandletstatus;
	}

	public void setBehandletstatus(BigDecimal behandletstatus) {
		this.behandletstatus = behandletstatus;
	}

	@Column(name = "XRSAGSKODE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getXrsagskode() {
		return this.xrsagskode;
	}

	public void setXrsagskode(BigDecimal xrsagskode) {
		this.xrsagskode = xrsagskode;
	}

	@Column(name = "KUNDEEMNE_ID", nullable = false, length = 10)
	public String getKundeemneId() {
		return this.kundeemneId;
	}

	public void setKundeemneId(String kundeemneId) {
		this.kundeemneId = kundeemneId;
	}

	@Column(name = "ADRESSE_ID", nullable = false, length = 10)
	public String getAdresseId() {
		return this.adresseId;
	}

	public void setAdresseId(String adresseId) {
		this.adresseId = adresseId;
	}

	@Column(name = "INST_LBNR", nullable = false, length = 10)
	public String getInstLbnr() {
		return this.instLbnr;
	}

	public void setInstLbnr(String instLbnr) {
		this.instLbnr = instLbnr;
	}

	@Column(name = "ADRESSE_IDNY", nullable = false, length = 10)
	public String getAdresseIdny() {
		return this.adresseIdny;
	}

	public void setAdresseIdny(String adresseIdny) {
		this.adresseIdny = adresseIdny;
	}

	@Column(name = "INST_LBNRNY", nullable = false, length = 10)
	public String getInstLbnrny() {
		return this.instLbnrny;
	}

	public void setInstLbnrny(String instLbnrny) {
		this.instLbnrny = instLbnrny;
	}

	@Column(name = "GRUNDPAKKEKODE", nullable = false, precision = 3, scale = 0)
	public short getGrundpakkekode() {
		return this.grundpakkekode;
	}

	public void setGrundpakkekode(short grundpakkekode) {
		this.grundpakkekode = grundpakkekode;
	}

	@Column(name = "TILLXGSPAKKEKODE", nullable = false, precision = 3, scale = 0)
	public short getTillxgspakkekode() {
		return this.tillxgspakkekode;
	}

	public void setTillxgspakkekode(short tillxgspakkekode) {
		this.tillxgspakkekode = tillxgspakkekode;
	}

	@Column(name = "ANLXG", nullable = false, length = 10)
	public String getAnlxg() {
		return this.anlxg;
	}

	public void setAnlxg(String anlxg) {
		this.anlxg = anlxg;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FRADATO", nullable = false, length = 7)
	public Date getFradato() {
		return this.fradato;
	}

	public void setFradato(Date fradato) {
		this.fradato = fradato;
	}

	@Column(name = "ANLXGNY", nullable = false, length = 10)
	public String getAnlxgny() {
		return this.anlxgny;
	}

	public void setAnlxgny(String anlxgny) {
		this.anlxgny = anlxgny;
	}

	@Column(name = "INSTALLATION", nullable = false, length = 19)
	public String getInstallation() {
		return this.installation;
	}

	public void setInstallation(String installation) {
		this.installation = installation;
	}

}
