package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MailData generated by hbm2java
 */
@Entity
@Table(name = "MAIL_DATA", schema = "PCRM")
public class MailData implements java.io.Serializable {

	private MailDataId id;

	public MailData() {
	}

	public MailData(MailDataId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "sender", column = @Column(name = "SENDER", length = 3000)),
			@AttributeOverride(name = "recipients", column = @Column(name = "RECIPIENTS", length = 3000)),
			@AttributeOverride(name = "subject", column = @Column(name = "SUBJECT", length = 3000)),
			@AttributeOverride(name = "message", column = @Column(name = "MESSAGE", length = 3000)),
			@AttributeOverride(name = "crd", column = @Column(name = "CRD", length = 7)) })
	public MailDataId getId() {
		return this.id;
	}

	public void setId(MailDataId id) {
		this.id = id;
	}

}
