package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NodeTypes generated by hbm2java
 */
@Entity
@Table(name = "NODE_TYPES", schema = "PCRM")
public class NodeTypes implements java.io.Serializable {

	private String nodeType;
	private String cru;
	private Date crd;
	private String modu;
	private Date modd;
	private String nodeDescription;
	private Date startDate;
	private Date endDate;
	private char lockStatus;
	private Set<DistributionNodes> distributionNodeses = new HashSet<DistributionNodes>(
			0);

	public NodeTypes() {
	}

	public NodeTypes(String nodeType, char lockStatus) {
		this.nodeType = nodeType;
		this.lockStatus = lockStatus;
	}

	public NodeTypes(String nodeType, String cru, Date crd, String modu,
			Date modd, String nodeDescription, Date startDate, Date endDate,
			char lockStatus, Set<DistributionNodes> distributionNodeses) {
		this.nodeType = nodeType;
		this.cru = cru;
		this.crd = crd;
		this.modu = modu;
		this.modd = modd;
		this.nodeDescription = nodeDescription;
		this.startDate = startDate;
		this.endDate = endDate;
		this.lockStatus = lockStatus;
		this.distributionNodeses = distributionNodeses;
	}

	@Id
	@Column(name = "NODE_TYPE", unique = true, nullable = false, length = 8)
	public String getNodeType() {
		return this.nodeType;
	}

	public void setNodeType(String nodeType) {
		this.nodeType = nodeType;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "NODE_DESCRIPTION", length = 20)
	public String getNodeDescription() {
		return this.nodeDescription;
	}

	public void setNodeDescription(String nodeDescription) {
		this.nodeDescription = nodeDescription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "LOCK_STATUS", nullable = false, length = 1)
	public char getLockStatus() {
		return this.lockStatus;
	}

	public void setLockStatus(char lockStatus) {
		this.lockStatus = lockStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nodeTypes")
	public Set<DistributionNodes> getDistributionNodeses() {
		return this.distributionNodeses;
	}

	public void setDistributionNodeses(
			Set<DistributionNodes> distributionNodeses) {
		this.distributionNodeses = distributionNodeses;
	}

}
