package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Opcableunituser generated by hbm2java
 */
@Entity
@Table(name = "OPCABLEUNITUSER", schema = "PCRM")
public class Opcableunituser implements java.io.Serializable {

	private String id;
	private Opuseraccount opuseraccount;
	private Opcableunituser opcableunituser;
	private Date crd;
	private String cru;
	private Date modd;
	private String modu;
	private Date deld;
	private String delu;
	private Date impd;
	private String impu;
	private Date expd;
	private String expu;
	private Date invalidated;
	private String primcableunit;
	private String primuserprofile;
	private String primuserrole;
	private String itemcode;
	private Set<Opcableunituser> opcableunitusers = new HashSet<Opcableunituser>(
			0);

	public Opcableunituser() {
	}

	public Opcableunituser(String id) {
		this.id = id;
	}

	public Opcableunituser(String id, Opuseraccount opuseraccount,
			Opcableunituser opcableunituser, Date crd, String cru, Date modd,
			String modu, Date deld, String delu, Date impd, String impu,
			Date expd, String expu, Date invalidated, String primcableunit,
			String primuserprofile, String primuserrole, String itemcode,
			Set<Opcableunituser> opcableunitusers) {
		this.id = id;
		this.opuseraccount = opuseraccount;
		this.opcableunituser = opcableunituser;
		this.crd = crd;
		this.cru = cru;
		this.modd = modd;
		this.modu = modu;
		this.deld = deld;
		this.delu = delu;
		this.impd = impd;
		this.impu = impu;
		this.expd = expd;
		this.expu = expu;
		this.invalidated = invalidated;
		this.primcableunit = primcableunit;
		this.primuserprofile = primuserprofile;
		this.primuserrole = primuserrole;
		this.itemcode = itemcode;
		this.opcableunitusers = opcableunitusers;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMUSERACCOUNT")
	public Opuseraccount getOpuseraccount() {
		return this.opuseraccount;
	}

	public void setOpuseraccount(Opuseraccount opuseraccount) {
		this.opuseraccount = opuseraccount;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMCABLEUNITUSER")
	public Opcableunituser getOpcableunituser() {
		return this.opcableunituser;
	}

	public void setOpcableunituser(Opcableunituser opcableunituser) {
		this.opcableunituser = opcableunituser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INVALIDATED", length = 7)
	public Date getInvalidated() {
		return this.invalidated;
	}

	public void setInvalidated(Date invalidated) {
		this.invalidated = invalidated;
	}

	@Column(name = "PRIMCABLEUNIT", length = 19)
	public String getPrimcableunit() {
		return this.primcableunit;
	}

	public void setPrimcableunit(String primcableunit) {
		this.primcableunit = primcableunit;
	}

	@Column(name = "PRIMUSERPROFILE", length = 19)
	public String getPrimuserprofile() {
		return this.primuserprofile;
	}

	public void setPrimuserprofile(String primuserprofile) {
		this.primuserprofile = primuserprofile;
	}

	@Column(name = "PRIMUSERROLE", length = 19)
	public String getPrimuserrole() {
		return this.primuserrole;
	}

	public void setPrimuserrole(String primuserrole) {
		this.primuserrole = primuserrole;
	}

	@Column(name = "ITEMCODE", length = 50)
	public String getItemcode() {
		return this.itemcode;
	}

	public void setItemcode(String itemcode) {
		this.itemcode = itemcode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opcableunituser")
	public Set<Opcableunituser> getOpcableunitusers() {
		return this.opcableunitusers;
	}

	public void setOpcableunitusers(Set<Opcableunituser> opcableunitusers) {
		this.opcableunitusers = opcableunitusers;
	}

}
