package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PackagesUnderProject generated by hbm2java
 */
@Entity
@Table(name = "PACKAGES_UNDER_PROJECT", schema = "PCRM")
public class PackagesUnderProject implements java.io.Serializable {

	private PackagesUnderProjectId id;
	private Products products;
	private String createdByUser;
	private Date createdDateTime;
	private String changeByUser;
	private Date changeDateTime;
	private BigDecimal freqStart;
	private BigDecimal freqEnd;

	public PackagesUnderProject() {
	}

	public PackagesUnderProject(PackagesUnderProjectId id, Products products) {
		this.id = id;
		this.products = products;
	}

	public PackagesUnderProject(PackagesUnderProjectId id, Products products,
			String createdByUser, Date createdDateTime, String changeByUser,
			Date changeDateTime, BigDecimal freqStart, BigDecimal freqEnd) {
		this.id = id;
		this.products = products;
		this.createdByUser = createdByUser;
		this.createdDateTime = createdDateTime;
		this.changeByUser = changeByUser;
		this.changeDateTime = changeDateTime;
		this.freqStart = freqStart;
		this.freqEnd = freqEnd;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "PRODUCT_ID", nullable = false, precision = 7, scale = 0)),
			@AttributeOverride(name = "projectId", column = @Column(name = "PROJECT_ID", nullable = false, precision = 22, scale = 0)) })
	public PackagesUnderProjectId getId() {
		return this.id;
	}

	public void setId(PackagesUnderProjectId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID", nullable = false, insertable = false, updatable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "CREATED_BY_USER", length = 20)
	public String getCreatedByUser() {
		return this.createdByUser;
	}

	public void setCreatedByUser(String createdByUser) {
		this.createdByUser = createdByUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE_TIME", length = 7)
	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	@Column(name = "CHANGE_BY_USER", length = 20)
	public String getChangeByUser() {
		return this.changeByUser;
	}

	public void setChangeByUser(String changeByUser) {
		this.changeByUser = changeByUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHANGE_DATE_TIME", length = 7)
	public Date getChangeDateTime() {
		return this.changeDateTime;
	}

	public void setChangeDateTime(Date changeDateTime) {
		this.changeDateTime = changeDateTime;
	}

	@Column(name = "FREQ_START", precision = 22, scale = 0)
	public BigDecimal getFreqStart() {
		return this.freqStart;
	}

	public void setFreqStart(BigDecimal freqStart) {
		this.freqStart = freqStart;
	}

	@Column(name = "FREQ_END", precision = 22, scale = 0)
	public BigDecimal getFreqEnd() {
		return this.freqEnd;
	}

	public void setFreqEnd(BigDecimal freqEnd) {
		this.freqEnd = freqEnd;
	}

}
