package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PricecalculationChghist generated by hbm2java
 */
@Entity
@Table(name = "PRICECALCULATION_CHGHIST", schema = "PCRM")
public class PricecalculationChghist implements java.io.Serializable {

	private String audId;
	private String audAction;
	private Serializable audTimestamp;
	private String audOsuser;
	private String audDbuser;
	private String audUserterminal;
	private String id;
	private Date crd;
	private String code;
	private Date impt;
	private Date expt;
	private Date impd;
	private Date expd;
	private Date modt;
	private String cru;
	private Date delt;
	private Date modd;
	private String impu;
	private String expu;
	private Date deld;
	private String modu;
	private String head;
	private String delu;
	private Date crt;
	private String primarysag;
	private Long gpantal;
	private BigDecimal gppris;
	private BigDecimal gptotal;
	private Long mpantal;
	private BigDecimal mppris;
	private BigDecimal mptotal;
	private Long fpantal;
	private BigDecimal fppris;
	private BigDecimal fptotal;
	private Long ltpantal;
	private BigDecimal ltppris;
	private BigDecimal ltptotal;
	private Long stpantal;
	private BigDecimal stppris;
	private BigDecimal stptotal;
	private Long agtantal;
	private BigDecimal agtpris;
	private BigDecimal agttotal;
	private Character agtsalg;
	private BigDecimal rabatkroner;
	private Long lejeantal;
	private BigDecimal lejepris;
	private BigDecimal lejetotal;
	private Long servaftantal;
	private BigDecimal servaftpris;
	private BigDecimal servafttotal;
	private BigDecimal admgebyr;
	private BigDecimal mdlincome;
	private BigDecimal operfee;
	private BigDecimal fiberleje;
	private BigDecimal salgsprisanl;
	private Long leasaar;
	private BigDecimal tilslafgforening;
	private BigDecimal tilslafgnormpris;
	private BigDecimal tilslafgkamppris;
	private Long antservdekoder;
	private Long antfridekoder;
	private BigDecimal nutidsvaerdi;
	private Long paybacktid;
	private String documentextension;
	private String heading;
	private String primtilbkontr;
	private String anlaegsnr;
	private String lifecycle;
	private String projektlobenr;
	private Long fn1fn2;
	private Long fn3;
	private String fn1;
	private String fn2;
	private Long tpantal;
	private BigDecimal tppris;
	private BigDecimal tptotal;
	private BigDecimal gprabat;
	private BigDecimal mprabat;
	private BigDecimal fprabat;
	private BigDecimal ltprabat;
	private BigDecimal stprabat;
	private BigDecimal tprabat;
	private BigDecimal gpkcd;
	private BigDecimal mpkcd;
	private BigDecimal fpkcd;
	private BigDecimal ltpkcd;
	private BigDecimal stpkcd;
	private BigDecimal tpkcd;
	private Character gpkcdincl;
	private Character mpkcdincl;
	private Character fpkcdincl;
	private Character ltpkcdincl;
	private Character stpkcdincl;
	private Character tpkcdincl;
	private Character inklmoms;
	private BigDecimal etablafgift;
	private Long internetantal;
	private BigDecimal internetpris;
	private BigDecimal internetrabat;
	private BigDecimal internettotal;
	private BigDecimal internetforpris;
	private BigDecimal internetforrabat;
	private BigDecimal internetfortotal;
	private BigDecimal internetoprhusstpris;
	private BigDecimal internetoprforpris;
	private BigDecimal wnpoStdA;
	private BigDecimal wnpoStdEga;
	private BigDecimal wnpoStdEr;
	private BigDecimal wnpoExA;
	private BigDecimal wnpoExEga;
	private BigDecimal wnpoExEr;
	private String primarykluWnmoV;
	private BigDecimal wnmoA;
	private BigDecimal wnmoEga;
	private BigDecimal wnmoLba;
	private BigDecimal wnmoEr;
	private BigDecimal wnmoLr;
	private String primarykluWnpoKapcV01;
	private BigDecimal wnpoKapcA01;
	private BigDecimal wnpoKapcEga01;
	private BigDecimal wnpoKapcLba01;
	private BigDecimal wnpoKapcEr01;
	private BigDecimal wnpoKapcLr01;
	private String primarykluWnpoKapcV02;
	private BigDecimal wnpoKapcA02;
	private BigDecimal wnpoKapcEga02;
	private BigDecimal wnpoKapcLba02;
	private BigDecimal wnpoKapcEr02;
	private BigDecimal wnpoKapcLr02;
	private BigDecimal wnpoInetA;
	private BigDecimal wnpoInetLba;
	private BigDecimal wnpoInetLr;
	private String primarykluWnoSV01;
	private BigDecimal wnoSA01;
	private BigDecimal wnoSEga01;
	private BigDecimal wnoSLba01;
	private BigDecimal wnoSEr01;
	private BigDecimal wnoSLr01;
	private String primarykluWneV01;
	private BigDecimal wneA01;
	private BigDecimal wneEga01;
	private BigDecimal wneLba01;
	private BigDecimal wneEr01;
	private BigDecimal wneLr01;
	private String primarykluWneV02;
	private BigDecimal wneA02;
	private BigDecimal wneEga02;
	private BigDecimal wneLba02;
	private BigDecimal wneEr02;
	private BigDecimal wneLr02;
	private String primarykluWneSV01;
	private BigDecimal wneSA01;
	private BigDecimal wneSEga01;
	private BigDecimal wneSLba01;
	private BigDecimal wneSEr01;
	private BigDecimal wneSLr01;
	private String primarykluWneSV02;
	private BigDecimal wneSA02;
	private BigDecimal wneSEga02;
	private BigDecimal wneSLba02;
	private BigDecimal wneSEr02;
	private BigDecimal wneSLr02;
	private String primarykluWneSV03;
	private BigDecimal wneSA03;
	private BigDecimal wneSEga03;
	private BigDecimal wneSLba03;
	private BigDecimal wneSEr03;
	private BigDecimal wneSLr03;
	private Character hascalculation;
	private Date kampagnedate;
	private Date ITakst;
	private Short ophavsret;
	private Character ophavsretIncl;
	private Date svarfrist;

	public PricecalculationChghist() {
	}

	public PricecalculationChghist(String audId) {
		this.audId = audId;
	}

	public PricecalculationChghist(String audId, String audAction,
			Serializable audTimestamp, String audOsuser, String audDbuser,
			String audUserterminal, String id, Date crd, String code,
			Date impt, Date expt, Date impd, Date expd, Date modt, String cru,
			Date delt, Date modd, String impu, String expu, Date deld,
			String modu, String head, String delu, Date crt, String primarysag,
			Long gpantal, BigDecimal gppris, BigDecimal gptotal, Long mpantal,
			BigDecimal mppris, BigDecimal mptotal, Long fpantal,
			BigDecimal fppris, BigDecimal fptotal, Long ltpantal,
			BigDecimal ltppris, BigDecimal ltptotal, Long stpantal,
			BigDecimal stppris, BigDecimal stptotal, Long agtantal,
			BigDecimal agtpris, BigDecimal agttotal, Character agtsalg,
			BigDecimal rabatkroner, Long lejeantal, BigDecimal lejepris,
			BigDecimal lejetotal, Long servaftantal, BigDecimal servaftpris,
			BigDecimal servafttotal, BigDecimal admgebyr, BigDecimal mdlincome,
			BigDecimal operfee, BigDecimal fiberleje, BigDecimal salgsprisanl,
			Long leasaar, BigDecimal tilslafgforening,
			BigDecimal tilslafgnormpris, BigDecimal tilslafgkamppris,
			Long antservdekoder, Long antfridekoder, BigDecimal nutidsvaerdi,
			Long paybacktid, String documentextension, String heading,
			String primtilbkontr, String anlaegsnr, String lifecycle,
			String projektlobenr, Long fn1fn2, Long fn3, String fn1,
			String fn2, Long tpantal, BigDecimal tppris, BigDecimal tptotal,
			BigDecimal gprabat, BigDecimal mprabat, BigDecimal fprabat,
			BigDecimal ltprabat, BigDecimal stprabat, BigDecimal tprabat,
			BigDecimal gpkcd, BigDecimal mpkcd, BigDecimal fpkcd,
			BigDecimal ltpkcd, BigDecimal stpkcd, BigDecimal tpkcd,
			Character gpkcdincl, Character mpkcdincl, Character fpkcdincl,
			Character ltpkcdincl, Character stpkcdincl, Character tpkcdincl,
			Character inklmoms, BigDecimal etablafgift, Long internetantal,
			BigDecimal internetpris, BigDecimal internetrabat,
			BigDecimal internettotal, BigDecimal internetforpris,
			BigDecimal internetforrabat, BigDecimal internetfortotal,
			BigDecimal internetoprhusstpris, BigDecimal internetoprforpris,
			BigDecimal wnpoStdA, BigDecimal wnpoStdEga, BigDecimal wnpoStdEr,
			BigDecimal wnpoExA, BigDecimal wnpoExEga, BigDecimal wnpoExEr,
			String primarykluWnmoV, BigDecimal wnmoA, BigDecimal wnmoEga,
			BigDecimal wnmoLba, BigDecimal wnmoEr, BigDecimal wnmoLr,
			String primarykluWnpoKapcV01, BigDecimal wnpoKapcA01,
			BigDecimal wnpoKapcEga01, BigDecimal wnpoKapcLba01,
			BigDecimal wnpoKapcEr01, BigDecimal wnpoKapcLr01,
			String primarykluWnpoKapcV02, BigDecimal wnpoKapcA02,
			BigDecimal wnpoKapcEga02, BigDecimal wnpoKapcLba02,
			BigDecimal wnpoKapcEr02, BigDecimal wnpoKapcLr02,
			BigDecimal wnpoInetA, BigDecimal wnpoInetLba,
			BigDecimal wnpoInetLr, String primarykluWnoSV01,
			BigDecimal wnoSA01, BigDecimal wnoSEga01, BigDecimal wnoSLba01,
			BigDecimal wnoSEr01, BigDecimal wnoSLr01, String primarykluWneV01,
			BigDecimal wneA01, BigDecimal wneEga01, BigDecimal wneLba01,
			BigDecimal wneEr01, BigDecimal wneLr01, String primarykluWneV02,
			BigDecimal wneA02, BigDecimal wneEga02, BigDecimal wneLba02,
			BigDecimal wneEr02, BigDecimal wneLr02, String primarykluWneSV01,
			BigDecimal wneSA01, BigDecimal wneSEga01, BigDecimal wneSLba01,
			BigDecimal wneSEr01, BigDecimal wneSLr01, String primarykluWneSV02,
			BigDecimal wneSA02, BigDecimal wneSEga02, BigDecimal wneSLba02,
			BigDecimal wneSEr02, BigDecimal wneSLr02, String primarykluWneSV03,
			BigDecimal wneSA03, BigDecimal wneSEga03, BigDecimal wneSLba03,
			BigDecimal wneSEr03, BigDecimal wneSLr03, Character hascalculation,
			Date kampagnedate, Date ITakst, Short ophavsret,
			Character ophavsretIncl, Date svarfrist) {
		this.audId = audId;
		this.audAction = audAction;
		this.audTimestamp = audTimestamp;
		this.audOsuser = audOsuser;
		this.audDbuser = audDbuser;
		this.audUserterminal = audUserterminal;
		this.id = id;
		this.crd = crd;
		this.code = code;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.cru = cru;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.modu = modu;
		this.head = head;
		this.delu = delu;
		this.crt = crt;
		this.primarysag = primarysag;
		this.gpantal = gpantal;
		this.gppris = gppris;
		this.gptotal = gptotal;
		this.mpantal = mpantal;
		this.mppris = mppris;
		this.mptotal = mptotal;
		this.fpantal = fpantal;
		this.fppris = fppris;
		this.fptotal = fptotal;
		this.ltpantal = ltpantal;
		this.ltppris = ltppris;
		this.ltptotal = ltptotal;
		this.stpantal = stpantal;
		this.stppris = stppris;
		this.stptotal = stptotal;
		this.agtantal = agtantal;
		this.agtpris = agtpris;
		this.agttotal = agttotal;
		this.agtsalg = agtsalg;
		this.rabatkroner = rabatkroner;
		this.lejeantal = lejeantal;
		this.lejepris = lejepris;
		this.lejetotal = lejetotal;
		this.servaftantal = servaftantal;
		this.servaftpris = servaftpris;
		this.servafttotal = servafttotal;
		this.admgebyr = admgebyr;
		this.mdlincome = mdlincome;
		this.operfee = operfee;
		this.fiberleje = fiberleje;
		this.salgsprisanl = salgsprisanl;
		this.leasaar = leasaar;
		this.tilslafgforening = tilslafgforening;
		this.tilslafgnormpris = tilslafgnormpris;
		this.tilslafgkamppris = tilslafgkamppris;
		this.antservdekoder = antservdekoder;
		this.antfridekoder = antfridekoder;
		this.nutidsvaerdi = nutidsvaerdi;
		this.paybacktid = paybacktid;
		this.documentextension = documentextension;
		this.heading = heading;
		this.primtilbkontr = primtilbkontr;
		this.anlaegsnr = anlaegsnr;
		this.lifecycle = lifecycle;
		this.projektlobenr = projektlobenr;
		this.fn1fn2 = fn1fn2;
		this.fn3 = fn3;
		this.fn1 = fn1;
		this.fn2 = fn2;
		this.tpantal = tpantal;
		this.tppris = tppris;
		this.tptotal = tptotal;
		this.gprabat = gprabat;
		this.mprabat = mprabat;
		this.fprabat = fprabat;
		this.ltprabat = ltprabat;
		this.stprabat = stprabat;
		this.tprabat = tprabat;
		this.gpkcd = gpkcd;
		this.mpkcd = mpkcd;
		this.fpkcd = fpkcd;
		this.ltpkcd = ltpkcd;
		this.stpkcd = stpkcd;
		this.tpkcd = tpkcd;
		this.gpkcdincl = gpkcdincl;
		this.mpkcdincl = mpkcdincl;
		this.fpkcdincl = fpkcdincl;
		this.ltpkcdincl = ltpkcdincl;
		this.stpkcdincl = stpkcdincl;
		this.tpkcdincl = tpkcdincl;
		this.inklmoms = inklmoms;
		this.etablafgift = etablafgift;
		this.internetantal = internetantal;
		this.internetpris = internetpris;
		this.internetrabat = internetrabat;
		this.internettotal = internettotal;
		this.internetforpris = internetforpris;
		this.internetforrabat = internetforrabat;
		this.internetfortotal = internetfortotal;
		this.internetoprhusstpris = internetoprhusstpris;
		this.internetoprforpris = internetoprforpris;
		this.wnpoStdA = wnpoStdA;
		this.wnpoStdEga = wnpoStdEga;
		this.wnpoStdEr = wnpoStdEr;
		this.wnpoExA = wnpoExA;
		this.wnpoExEga = wnpoExEga;
		this.wnpoExEr = wnpoExEr;
		this.primarykluWnmoV = primarykluWnmoV;
		this.wnmoA = wnmoA;
		this.wnmoEga = wnmoEga;
		this.wnmoLba = wnmoLba;
		this.wnmoEr = wnmoEr;
		this.wnmoLr = wnmoLr;
		this.primarykluWnpoKapcV01 = primarykluWnpoKapcV01;
		this.wnpoKapcA01 = wnpoKapcA01;
		this.wnpoKapcEga01 = wnpoKapcEga01;
		this.wnpoKapcLba01 = wnpoKapcLba01;
		this.wnpoKapcEr01 = wnpoKapcEr01;
		this.wnpoKapcLr01 = wnpoKapcLr01;
		this.primarykluWnpoKapcV02 = primarykluWnpoKapcV02;
		this.wnpoKapcA02 = wnpoKapcA02;
		this.wnpoKapcEga02 = wnpoKapcEga02;
		this.wnpoKapcLba02 = wnpoKapcLba02;
		this.wnpoKapcEr02 = wnpoKapcEr02;
		this.wnpoKapcLr02 = wnpoKapcLr02;
		this.wnpoInetA = wnpoInetA;
		this.wnpoInetLba = wnpoInetLba;
		this.wnpoInetLr = wnpoInetLr;
		this.primarykluWnoSV01 = primarykluWnoSV01;
		this.wnoSA01 = wnoSA01;
		this.wnoSEga01 = wnoSEga01;
		this.wnoSLba01 = wnoSLba01;
		this.wnoSEr01 = wnoSEr01;
		this.wnoSLr01 = wnoSLr01;
		this.primarykluWneV01 = primarykluWneV01;
		this.wneA01 = wneA01;
		this.wneEga01 = wneEga01;
		this.wneLba01 = wneLba01;
		this.wneEr01 = wneEr01;
		this.wneLr01 = wneLr01;
		this.primarykluWneV02 = primarykluWneV02;
		this.wneA02 = wneA02;
		this.wneEga02 = wneEga02;
		this.wneLba02 = wneLba02;
		this.wneEr02 = wneEr02;
		this.wneLr02 = wneLr02;
		this.primarykluWneSV01 = primarykluWneSV01;
		this.wneSA01 = wneSA01;
		this.wneSEga01 = wneSEga01;
		this.wneSLba01 = wneSLba01;
		this.wneSEr01 = wneSEr01;
		this.wneSLr01 = wneSLr01;
		this.primarykluWneSV02 = primarykluWneSV02;
		this.wneSA02 = wneSA02;
		this.wneSEga02 = wneSEga02;
		this.wneSLba02 = wneSLba02;
		this.wneSEr02 = wneSEr02;
		this.wneSLr02 = wneSLr02;
		this.primarykluWneSV03 = primarykluWneSV03;
		this.wneSA03 = wneSA03;
		this.wneSEga03 = wneSEga03;
		this.wneSLba03 = wneSLba03;
		this.wneSEr03 = wneSEr03;
		this.wneSLr03 = wneSLr03;
		this.hascalculation = hascalculation;
		this.kampagnedate = kampagnedate;
		this.ITakst = ITakst;
		this.ophavsret = ophavsret;
		this.ophavsretIncl = ophavsretIncl;
		this.svarfrist = svarfrist;
	}

	@Id
	@Column(name = "AUD_ID", unique = true, nullable = false, length = 19)
	public String getAudId() {
		return this.audId;
	}

	public void setAudId(String audId) {
		this.audId = audId;
	}

	@Column(name = "AUD_ACTION", length = 50)
	public String getAudAction() {
		return this.audAction;
	}

	public void setAudAction(String audAction) {
		this.audAction = audAction;
	}

	@Column(name = "AUD_TIMESTAMP")
	public Serializable getAudTimestamp() {
		return this.audTimestamp;
	}

	public void setAudTimestamp(Serializable audTimestamp) {
		this.audTimestamp = audTimestamp;
	}

	@Column(name = "AUD_OSUSER", length = 50)
	public String getAudOsuser() {
		return this.audOsuser;
	}

	public void setAudOsuser(String audOsuser) {
		this.audOsuser = audOsuser;
	}

	@Column(name = "AUD_DBUSER", length = 50)
	public String getAudDbuser() {
		return this.audDbuser;
	}

	public void setAudDbuser(String audDbuser) {
		this.audDbuser = audDbuser;
	}

	@Column(name = "AUD_USERTERMINAL", length = 50)
	public String getAudUserterminal() {
		return this.audUserterminal;
	}

	public void setAudUserterminal(String audUserterminal) {
		this.audUserterminal = audUserterminal;
	}

	@Column(name = "ID", length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CODE", length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "HEAD")
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "PRIMARYSAG", length = 19)
	public String getPrimarysag() {
		return this.primarysag;
	}

	public void setPrimarysag(String primarysag) {
		this.primarysag = primarysag;
	}

	@Column(name = "GPANTAL", precision = 10, scale = 0)
	public Long getGpantal() {
		return this.gpantal;
	}

	public void setGpantal(Long gpantal) {
		this.gpantal = gpantal;
	}

	@Column(name = "GPPRIS", precision = 12)
	public BigDecimal getGppris() {
		return this.gppris;
	}

	public void setGppris(BigDecimal gppris) {
		this.gppris = gppris;
	}

	@Column(name = "GPTOTAL", precision = 12)
	public BigDecimal getGptotal() {
		return this.gptotal;
	}

	public void setGptotal(BigDecimal gptotal) {
		this.gptotal = gptotal;
	}

	@Column(name = "MPANTAL", precision = 10, scale = 0)
	public Long getMpantal() {
		return this.mpantal;
	}

	public void setMpantal(Long mpantal) {
		this.mpantal = mpantal;
	}

	@Column(name = "MPPRIS", precision = 12)
	public BigDecimal getMppris() {
		return this.mppris;
	}

	public void setMppris(BigDecimal mppris) {
		this.mppris = mppris;
	}

	@Column(name = "MPTOTAL", precision = 12)
	public BigDecimal getMptotal() {
		return this.mptotal;
	}

	public void setMptotal(BigDecimal mptotal) {
		this.mptotal = mptotal;
	}

	@Column(name = "FPANTAL", precision = 10, scale = 0)
	public Long getFpantal() {
		return this.fpantal;
	}

	public void setFpantal(Long fpantal) {
		this.fpantal = fpantal;
	}

	@Column(name = "FPPRIS", precision = 12)
	public BigDecimal getFppris() {
		return this.fppris;
	}

	public void setFppris(BigDecimal fppris) {
		this.fppris = fppris;
	}

	@Column(name = "FPTOTAL", precision = 12)
	public BigDecimal getFptotal() {
		return this.fptotal;
	}

	public void setFptotal(BigDecimal fptotal) {
		this.fptotal = fptotal;
	}

	@Column(name = "LTPANTAL", precision = 10, scale = 0)
	public Long getLtpantal() {
		return this.ltpantal;
	}

	public void setLtpantal(Long ltpantal) {
		this.ltpantal = ltpantal;
	}

	@Column(name = "LTPPRIS", precision = 12)
	public BigDecimal getLtppris() {
		return this.ltppris;
	}

	public void setLtppris(BigDecimal ltppris) {
		this.ltppris = ltppris;
	}

	@Column(name = "LTPTOTAL", precision = 12)
	public BigDecimal getLtptotal() {
		return this.ltptotal;
	}

	public void setLtptotal(BigDecimal ltptotal) {
		this.ltptotal = ltptotal;
	}

	@Column(name = "STPANTAL", precision = 10, scale = 0)
	public Long getStpantal() {
		return this.stpantal;
	}

	public void setStpantal(Long stpantal) {
		this.stpantal = stpantal;
	}

	@Column(name = "STPPRIS", precision = 12)
	public BigDecimal getStppris() {
		return this.stppris;
	}

	public void setStppris(BigDecimal stppris) {
		this.stppris = stppris;
	}

	@Column(name = "STPTOTAL", precision = 12)
	public BigDecimal getStptotal() {
		return this.stptotal;
	}

	public void setStptotal(BigDecimal stptotal) {
		this.stptotal = stptotal;
	}

	@Column(name = "AGTANTAL", precision = 10, scale = 0)
	public Long getAgtantal() {
		return this.agtantal;
	}

	public void setAgtantal(Long agtantal) {
		this.agtantal = agtantal;
	}

	@Column(name = "AGTPRIS", precision = 12)
	public BigDecimal getAgtpris() {
		return this.agtpris;
	}

	public void setAgtpris(BigDecimal agtpris) {
		this.agtpris = agtpris;
	}

	@Column(name = "AGTTOTAL", precision = 12)
	public BigDecimal getAgttotal() {
		return this.agttotal;
	}

	public void setAgttotal(BigDecimal agttotal) {
		this.agttotal = agttotal;
	}

	@Column(name = "AGTSALG", length = 1)
	public Character getAgtsalg() {
		return this.agtsalg;
	}

	public void setAgtsalg(Character agtsalg) {
		this.agtsalg = agtsalg;
	}

	@Column(name = "RABATKRONER", precision = 12)
	public BigDecimal getRabatkroner() {
		return this.rabatkroner;
	}

	public void setRabatkroner(BigDecimal rabatkroner) {
		this.rabatkroner = rabatkroner;
	}

	@Column(name = "LEJEANTAL", precision = 10, scale = 0)
	public Long getLejeantal() {
		return this.lejeantal;
	}

	public void setLejeantal(Long lejeantal) {
		this.lejeantal = lejeantal;
	}

	@Column(name = "LEJEPRIS", precision = 12)
	public BigDecimal getLejepris() {
		return this.lejepris;
	}

	public void setLejepris(BigDecimal lejepris) {
		this.lejepris = lejepris;
	}

	@Column(name = "LEJETOTAL", precision = 12)
	public BigDecimal getLejetotal() {
		return this.lejetotal;
	}

	public void setLejetotal(BigDecimal lejetotal) {
		this.lejetotal = lejetotal;
	}

	@Column(name = "SERVAFTANTAL", precision = 10, scale = 0)
	public Long getServaftantal() {
		return this.servaftantal;
	}

	public void setServaftantal(Long servaftantal) {
		this.servaftantal = servaftantal;
	}

	@Column(name = "SERVAFTPRIS", precision = 12)
	public BigDecimal getServaftpris() {
		return this.servaftpris;
	}

	public void setServaftpris(BigDecimal servaftpris) {
		this.servaftpris = servaftpris;
	}

	@Column(name = "SERVAFTTOTAL", precision = 12)
	public BigDecimal getServafttotal() {
		return this.servafttotal;
	}

	public void setServafttotal(BigDecimal servafttotal) {
		this.servafttotal = servafttotal;
	}

	@Column(name = "ADMGEBYR", precision = 12)
	public BigDecimal getAdmgebyr() {
		return this.admgebyr;
	}

	public void setAdmgebyr(BigDecimal admgebyr) {
		this.admgebyr = admgebyr;
	}

	@Column(name = "MDLINCOME", precision = 12)
	public BigDecimal getMdlincome() {
		return this.mdlincome;
	}

	public void setMdlincome(BigDecimal mdlincome) {
		this.mdlincome = mdlincome;
	}

	@Column(name = "OPERFEE", precision = 12)
	public BigDecimal getOperfee() {
		return this.operfee;
	}

	public void setOperfee(BigDecimal operfee) {
		this.operfee = operfee;
	}

	@Column(name = "FIBERLEJE", precision = 12)
	public BigDecimal getFiberleje() {
		return this.fiberleje;
	}

	public void setFiberleje(BigDecimal fiberleje) {
		this.fiberleje = fiberleje;
	}

	@Column(name = "SALGSPRISANL", precision = 12)
	public BigDecimal getSalgsprisanl() {
		return this.salgsprisanl;
	}

	public void setSalgsprisanl(BigDecimal salgsprisanl) {
		this.salgsprisanl = salgsprisanl;
	}

	@Column(name = "LEASAAR", precision = 10, scale = 0)
	public Long getLeasaar() {
		return this.leasaar;
	}

	public void setLeasaar(Long leasaar) {
		this.leasaar = leasaar;
	}

	@Column(name = "TILSLAFGFORENING", precision = 12)
	public BigDecimal getTilslafgforening() {
		return this.tilslafgforening;
	}

	public void setTilslafgforening(BigDecimal tilslafgforening) {
		this.tilslafgforening = tilslafgforening;
	}

	@Column(name = "TILSLAFGNORMPRIS", precision = 12)
	public BigDecimal getTilslafgnormpris() {
		return this.tilslafgnormpris;
	}

	public void setTilslafgnormpris(BigDecimal tilslafgnormpris) {
		this.tilslafgnormpris = tilslafgnormpris;
	}

	@Column(name = "TILSLAFGKAMPPRIS", precision = 12)
	public BigDecimal getTilslafgkamppris() {
		return this.tilslafgkamppris;
	}

	public void setTilslafgkamppris(BigDecimal tilslafgkamppris) {
		this.tilslafgkamppris = tilslafgkamppris;
	}

	@Column(name = "ANTSERVDEKODER", precision = 10, scale = 0)
	public Long getAntservdekoder() {
		return this.antservdekoder;
	}

	public void setAntservdekoder(Long antservdekoder) {
		this.antservdekoder = antservdekoder;
	}

	@Column(name = "ANTFRIDEKODER", precision = 10, scale = 0)
	public Long getAntfridekoder() {
		return this.antfridekoder;
	}

	public void setAntfridekoder(Long antfridekoder) {
		this.antfridekoder = antfridekoder;
	}

	@Column(name = "NUTIDSVAERDI", precision = 12)
	public BigDecimal getNutidsvaerdi() {
		return this.nutidsvaerdi;
	}

	public void setNutidsvaerdi(BigDecimal nutidsvaerdi) {
		this.nutidsvaerdi = nutidsvaerdi;
	}

	@Column(name = "PAYBACKTID", precision = 10, scale = 0)
	public Long getPaybacktid() {
		return this.paybacktid;
	}

	public void setPaybacktid(Long paybacktid) {
		this.paybacktid = paybacktid;
	}

	@Column(name = "DOCUMENTEXTENSION")
	public String getDocumentextension() {
		return this.documentextension;
	}

	public void setDocumentextension(String documentextension) {
		this.documentextension = documentextension;
	}

	@Column(name = "HEADING")
	public String getHeading() {
		return this.heading;
	}

	public void setHeading(String heading) {
		this.heading = heading;
	}

	@Column(name = "PRIMTILBKONTR", length = 19)
	public String getPrimtilbkontr() {
		return this.primtilbkontr;
	}

	public void setPrimtilbkontr(String primtilbkontr) {
		this.primtilbkontr = primtilbkontr;
	}

	@Column(name = "ANLAEGSNR", length = 10)
	public String getAnlaegsnr() {
		return this.anlaegsnr;
	}

	public void setAnlaegsnr(String anlaegsnr) {
		this.anlaegsnr = anlaegsnr;
	}

	@Column(name = "LIFECYCLE", length = 10)
	public String getLifecycle() {
		return this.lifecycle;
	}

	public void setLifecycle(String lifecycle) {
		this.lifecycle = lifecycle;
	}

	@Column(name = "PROJEKTLOBENR", length = 10)
	public String getProjektlobenr() {
		return this.projektlobenr;
	}

	public void setProjektlobenr(String projektlobenr) {
		this.projektlobenr = projektlobenr;
	}

	@Column(name = "FN1FN2", precision = 10, scale = 0)
	public Long getFn1fn2() {
		return this.fn1fn2;
	}

	public void setFn1fn2(Long fn1fn2) {
		this.fn1fn2 = fn1fn2;
	}

	@Column(name = "FN3", precision = 10, scale = 0)
	public Long getFn3() {
		return this.fn3;
	}

	public void setFn3(Long fn3) {
		this.fn3 = fn3;
	}

	@Column(name = "FN1", length = 10)
	public String getFn1() {
		return this.fn1;
	}

	public void setFn1(String fn1) {
		this.fn1 = fn1;
	}

	@Column(name = "FN2", length = 10)
	public String getFn2() {
		return this.fn2;
	}

	public void setFn2(String fn2) {
		this.fn2 = fn2;
	}

	@Column(name = "TPANTAL", precision = 10, scale = 0)
	public Long getTpantal() {
		return this.tpantal;
	}

	public void setTpantal(Long tpantal) {
		this.tpantal = tpantal;
	}

	@Column(name = "TPPRIS", precision = 12)
	public BigDecimal getTppris() {
		return this.tppris;
	}

	public void setTppris(BigDecimal tppris) {
		this.tppris = tppris;
	}

	@Column(name = "TPTOTAL", precision = 12)
	public BigDecimal getTptotal() {
		return this.tptotal;
	}

	public void setTptotal(BigDecimal tptotal) {
		this.tptotal = tptotal;
	}

	@Column(name = "GPRABAT", precision = 12)
	public BigDecimal getGprabat() {
		return this.gprabat;
	}

	public void setGprabat(BigDecimal gprabat) {
		this.gprabat = gprabat;
	}

	@Column(name = "MPRABAT", precision = 12)
	public BigDecimal getMprabat() {
		return this.mprabat;
	}

	public void setMprabat(BigDecimal mprabat) {
		this.mprabat = mprabat;
	}

	@Column(name = "FPRABAT", precision = 12)
	public BigDecimal getFprabat() {
		return this.fprabat;
	}

	public void setFprabat(BigDecimal fprabat) {
		this.fprabat = fprabat;
	}

	@Column(name = "LTPRABAT", precision = 12)
	public BigDecimal getLtprabat() {
		return this.ltprabat;
	}

	public void setLtprabat(BigDecimal ltprabat) {
		this.ltprabat = ltprabat;
	}

	@Column(name = "STPRABAT", precision = 12)
	public BigDecimal getStprabat() {
		return this.stprabat;
	}

	public void setStprabat(BigDecimal stprabat) {
		this.stprabat = stprabat;
	}

	@Column(name = "TPRABAT", precision = 12)
	public BigDecimal getTprabat() {
		return this.tprabat;
	}

	public void setTprabat(BigDecimal tprabat) {
		this.tprabat = tprabat;
	}

	@Column(name = "GPKCD", precision = 12)
	public BigDecimal getGpkcd() {
		return this.gpkcd;
	}

	public void setGpkcd(BigDecimal gpkcd) {
		this.gpkcd = gpkcd;
	}

	@Column(name = "MPKCD", precision = 12)
	public BigDecimal getMpkcd() {
		return this.mpkcd;
	}

	public void setMpkcd(BigDecimal mpkcd) {
		this.mpkcd = mpkcd;
	}

	@Column(name = "FPKCD", precision = 12)
	public BigDecimal getFpkcd() {
		return this.fpkcd;
	}

	public void setFpkcd(BigDecimal fpkcd) {
		this.fpkcd = fpkcd;
	}

	@Column(name = "LTPKCD", precision = 12)
	public BigDecimal getLtpkcd() {
		return this.ltpkcd;
	}

	public void setLtpkcd(BigDecimal ltpkcd) {
		this.ltpkcd = ltpkcd;
	}

	@Column(name = "STPKCD", precision = 12)
	public BigDecimal getStpkcd() {
		return this.stpkcd;
	}

	public void setStpkcd(BigDecimal stpkcd) {
		this.stpkcd = stpkcd;
	}

	@Column(name = "TPKCD", precision = 12)
	public BigDecimal getTpkcd() {
		return this.tpkcd;
	}

	public void setTpkcd(BigDecimal tpkcd) {
		this.tpkcd = tpkcd;
	}

	@Column(name = "GPKCDINCL", length = 1)
	public Character getGpkcdincl() {
		return this.gpkcdincl;
	}

	public void setGpkcdincl(Character gpkcdincl) {
		this.gpkcdincl = gpkcdincl;
	}

	@Column(name = "MPKCDINCL", length = 1)
	public Character getMpkcdincl() {
		return this.mpkcdincl;
	}

	public void setMpkcdincl(Character mpkcdincl) {
		this.mpkcdincl = mpkcdincl;
	}

	@Column(name = "FPKCDINCL", length = 1)
	public Character getFpkcdincl() {
		return this.fpkcdincl;
	}

	public void setFpkcdincl(Character fpkcdincl) {
		this.fpkcdincl = fpkcdincl;
	}

	@Column(name = "LTPKCDINCL", length = 1)
	public Character getLtpkcdincl() {
		return this.ltpkcdincl;
	}

	public void setLtpkcdincl(Character ltpkcdincl) {
		this.ltpkcdincl = ltpkcdincl;
	}

	@Column(name = "STPKCDINCL", length = 1)
	public Character getStpkcdincl() {
		return this.stpkcdincl;
	}

	public void setStpkcdincl(Character stpkcdincl) {
		this.stpkcdincl = stpkcdincl;
	}

	@Column(name = "TPKCDINCL", length = 1)
	public Character getTpkcdincl() {
		return this.tpkcdincl;
	}

	public void setTpkcdincl(Character tpkcdincl) {
		this.tpkcdincl = tpkcdincl;
	}

	@Column(name = "INKLMOMS", length = 1)
	public Character getInklmoms() {
		return this.inklmoms;
	}

	public void setInklmoms(Character inklmoms) {
		this.inklmoms = inklmoms;
	}

	@Column(name = "ETABLAFGIFT", precision = 12)
	public BigDecimal getEtablafgift() {
		return this.etablafgift;
	}

	public void setEtablafgift(BigDecimal etablafgift) {
		this.etablafgift = etablafgift;
	}

	@Column(name = "INTERNETANTAL", precision = 10, scale = 0)
	public Long getInternetantal() {
		return this.internetantal;
	}

	public void setInternetantal(Long internetantal) {
		this.internetantal = internetantal;
	}

	@Column(name = "INTERNETPRIS", precision = 10)
	public BigDecimal getInternetpris() {
		return this.internetpris;
	}

	public void setInternetpris(BigDecimal internetpris) {
		this.internetpris = internetpris;
	}

	@Column(name = "INTERNETRABAT", precision = 10)
	public BigDecimal getInternetrabat() {
		return this.internetrabat;
	}

	public void setInternetrabat(BigDecimal internetrabat) {
		this.internetrabat = internetrabat;
	}

	@Column(name = "INTERNETTOTAL", precision = 10)
	public BigDecimal getInternettotal() {
		return this.internettotal;
	}

	public void setInternettotal(BigDecimal internettotal) {
		this.internettotal = internettotal;
	}

	@Column(name = "INTERNETFORPRIS", precision = 10)
	public BigDecimal getInternetforpris() {
		return this.internetforpris;
	}

	public void setInternetforpris(BigDecimal internetforpris) {
		this.internetforpris = internetforpris;
	}

	@Column(name = "INTERNETFORRABAT", precision = 10)
	public BigDecimal getInternetforrabat() {
		return this.internetforrabat;
	}

	public void setInternetforrabat(BigDecimal internetforrabat) {
		this.internetforrabat = internetforrabat;
	}

	@Column(name = "INTERNETFORTOTAL", precision = 10)
	public BigDecimal getInternetfortotal() {
		return this.internetfortotal;
	}

	public void setInternetfortotal(BigDecimal internetfortotal) {
		this.internetfortotal = internetfortotal;
	}

	@Column(name = "INTERNETOPRHUSSTPRIS", precision = 10)
	public BigDecimal getInternetoprhusstpris() {
		return this.internetoprhusstpris;
	}

	public void setInternetoprhusstpris(BigDecimal internetoprhusstpris) {
		this.internetoprhusstpris = internetoprhusstpris;
	}

	@Column(name = "INTERNETOPRFORPRIS", precision = 10)
	public BigDecimal getInternetoprforpris() {
		return this.internetoprforpris;
	}

	public void setInternetoprforpris(BigDecimal internetoprforpris) {
		this.internetoprforpris = internetoprforpris;
	}

	@Column(name = "WNPO_STD_A", precision = 22, scale = 0)
	public BigDecimal getWnpoStdA() {
		return this.wnpoStdA;
	}

	public void setWnpoStdA(BigDecimal wnpoStdA) {
		this.wnpoStdA = wnpoStdA;
	}

	@Column(name = "WNPO_STD_EGA", precision = 12)
	public BigDecimal getWnpoStdEga() {
		return this.wnpoStdEga;
	}

	public void setWnpoStdEga(BigDecimal wnpoStdEga) {
		this.wnpoStdEga = wnpoStdEga;
	}

	@Column(name = "WNPO_STD_ER", precision = 12)
	public BigDecimal getWnpoStdEr() {
		return this.wnpoStdEr;
	}

	public void setWnpoStdEr(BigDecimal wnpoStdEr) {
		this.wnpoStdEr = wnpoStdEr;
	}

	@Column(name = "WNPO_EX_A", precision = 22, scale = 0)
	public BigDecimal getWnpoExA() {
		return this.wnpoExA;
	}

	public void setWnpoExA(BigDecimal wnpoExA) {
		this.wnpoExA = wnpoExA;
	}

	@Column(name = "WNPO_EX_EGA", precision = 12)
	public BigDecimal getWnpoExEga() {
		return this.wnpoExEga;
	}

	public void setWnpoExEga(BigDecimal wnpoExEga) {
		this.wnpoExEga = wnpoExEga;
	}

	@Column(name = "WNPO_EX_ER", precision = 12)
	public BigDecimal getWnpoExEr() {
		return this.wnpoExEr;
	}

	public void setWnpoExEr(BigDecimal wnpoExEr) {
		this.wnpoExEr = wnpoExEr;
	}

	@Column(name = "PRIMARYKLU_WNMO_V", length = 19)
	public String getPrimarykluWnmoV() {
		return this.primarykluWnmoV;
	}

	public void setPrimarykluWnmoV(String primarykluWnmoV) {
		this.primarykluWnmoV = primarykluWnmoV;
	}

	@Column(name = "WNMO_A", precision = 22, scale = 0)
	public BigDecimal getWnmoA() {
		return this.wnmoA;
	}

	public void setWnmoA(BigDecimal wnmoA) {
		this.wnmoA = wnmoA;
	}

	@Column(name = "WNMO_EGA", precision = 12)
	public BigDecimal getWnmoEga() {
		return this.wnmoEga;
	}

	public void setWnmoEga(BigDecimal wnmoEga) {
		this.wnmoEga = wnmoEga;
	}

	@Column(name = "WNMO_LBA", precision = 12)
	public BigDecimal getWnmoLba() {
		return this.wnmoLba;
	}

	public void setWnmoLba(BigDecimal wnmoLba) {
		this.wnmoLba = wnmoLba;
	}

	@Column(name = "WNMO_ER", precision = 12)
	public BigDecimal getWnmoEr() {
		return this.wnmoEr;
	}

	public void setWnmoEr(BigDecimal wnmoEr) {
		this.wnmoEr = wnmoEr;
	}

	@Column(name = "WNMO_LR", precision = 12)
	public BigDecimal getWnmoLr() {
		return this.wnmoLr;
	}

	public void setWnmoLr(BigDecimal wnmoLr) {
		this.wnmoLr = wnmoLr;
	}

	@Column(name = "PRIMARYKLU_WNPO_KAPC_V01", length = 19)
	public String getPrimarykluWnpoKapcV01() {
		return this.primarykluWnpoKapcV01;
	}

	public void setPrimarykluWnpoKapcV01(String primarykluWnpoKapcV01) {
		this.primarykluWnpoKapcV01 = primarykluWnpoKapcV01;
	}

	@Column(name = "WNPO_KAPC_A01", precision = 22, scale = 0)
	public BigDecimal getWnpoKapcA01() {
		return this.wnpoKapcA01;
	}

	public void setWnpoKapcA01(BigDecimal wnpoKapcA01) {
		this.wnpoKapcA01 = wnpoKapcA01;
	}

	@Column(name = "WNPO_KAPC_EGA01", precision = 12)
	public BigDecimal getWnpoKapcEga01() {
		return this.wnpoKapcEga01;
	}

	public void setWnpoKapcEga01(BigDecimal wnpoKapcEga01) {
		this.wnpoKapcEga01 = wnpoKapcEga01;
	}

	@Column(name = "WNPO_KAPC_LBA01", precision = 12)
	public BigDecimal getWnpoKapcLba01() {
		return this.wnpoKapcLba01;
	}

	public void setWnpoKapcLba01(BigDecimal wnpoKapcLba01) {
		this.wnpoKapcLba01 = wnpoKapcLba01;
	}

	@Column(name = "WNPO_KAPC_ER01", precision = 12)
	public BigDecimal getWnpoKapcEr01() {
		return this.wnpoKapcEr01;
	}

	public void setWnpoKapcEr01(BigDecimal wnpoKapcEr01) {
		this.wnpoKapcEr01 = wnpoKapcEr01;
	}

	@Column(name = "WNPO_KAPC_LR01", precision = 12)
	public BigDecimal getWnpoKapcLr01() {
		return this.wnpoKapcLr01;
	}

	public void setWnpoKapcLr01(BigDecimal wnpoKapcLr01) {
		this.wnpoKapcLr01 = wnpoKapcLr01;
	}

	@Column(name = "PRIMARYKLU_WNPO_KAPC_V02", length = 19)
	public String getPrimarykluWnpoKapcV02() {
		return this.primarykluWnpoKapcV02;
	}

	public void setPrimarykluWnpoKapcV02(String primarykluWnpoKapcV02) {
		this.primarykluWnpoKapcV02 = primarykluWnpoKapcV02;
	}

	@Column(name = "WNPO_KAPC_A02", precision = 22, scale = 0)
	public BigDecimal getWnpoKapcA02() {
		return this.wnpoKapcA02;
	}

	public void setWnpoKapcA02(BigDecimal wnpoKapcA02) {
		this.wnpoKapcA02 = wnpoKapcA02;
	}

	@Column(name = "WNPO_KAPC_EGA02", precision = 12)
	public BigDecimal getWnpoKapcEga02() {
		return this.wnpoKapcEga02;
	}

	public void setWnpoKapcEga02(BigDecimal wnpoKapcEga02) {
		this.wnpoKapcEga02 = wnpoKapcEga02;
	}

	@Column(name = "WNPO_KAPC_LBA02", precision = 12)
	public BigDecimal getWnpoKapcLba02() {
		return this.wnpoKapcLba02;
	}

	public void setWnpoKapcLba02(BigDecimal wnpoKapcLba02) {
		this.wnpoKapcLba02 = wnpoKapcLba02;
	}

	@Column(name = "WNPO_KAPC_ER02", precision = 12)
	public BigDecimal getWnpoKapcEr02() {
		return this.wnpoKapcEr02;
	}

	public void setWnpoKapcEr02(BigDecimal wnpoKapcEr02) {
		this.wnpoKapcEr02 = wnpoKapcEr02;
	}

	@Column(name = "WNPO_KAPC_LR02", precision = 12)
	public BigDecimal getWnpoKapcLr02() {
		return this.wnpoKapcLr02;
	}

	public void setWnpoKapcLr02(BigDecimal wnpoKapcLr02) {
		this.wnpoKapcLr02 = wnpoKapcLr02;
	}

	@Column(name = "WNPO_INET_A", precision = 22, scale = 0)
	public BigDecimal getWnpoInetA() {
		return this.wnpoInetA;
	}

	public void setWnpoInetA(BigDecimal wnpoInetA) {
		this.wnpoInetA = wnpoInetA;
	}

	@Column(name = "WNPO_INET_LBA", precision = 12)
	public BigDecimal getWnpoInetLba() {
		return this.wnpoInetLba;
	}

	public void setWnpoInetLba(BigDecimal wnpoInetLba) {
		this.wnpoInetLba = wnpoInetLba;
	}

	@Column(name = "WNPO_INET_LR", precision = 12)
	public BigDecimal getWnpoInetLr() {
		return this.wnpoInetLr;
	}

	public void setWnpoInetLr(BigDecimal wnpoInetLr) {
		this.wnpoInetLr = wnpoInetLr;
	}

	@Column(name = "PRIMARYKLU_WNO_S_V01", length = 19)
	public String getPrimarykluWnoSV01() {
		return this.primarykluWnoSV01;
	}

	public void setPrimarykluWnoSV01(String primarykluWnoSV01) {
		this.primarykluWnoSV01 = primarykluWnoSV01;
	}

	@Column(name = "WNO_S_A01", precision = 22, scale = 0)
	public BigDecimal getWnoSA01() {
		return this.wnoSA01;
	}

	public void setWnoSA01(BigDecimal wnoSA01) {
		this.wnoSA01 = wnoSA01;
	}

	@Column(name = "WNO_S_EGA01", precision = 12)
	public BigDecimal getWnoSEga01() {
		return this.wnoSEga01;
	}

	public void setWnoSEga01(BigDecimal wnoSEga01) {
		this.wnoSEga01 = wnoSEga01;
	}

	@Column(name = "WNO_S_LBA01", precision = 12)
	public BigDecimal getWnoSLba01() {
		return this.wnoSLba01;
	}

	public void setWnoSLba01(BigDecimal wnoSLba01) {
		this.wnoSLba01 = wnoSLba01;
	}

	@Column(name = "WNO_S_ER01", precision = 12)
	public BigDecimal getWnoSEr01() {
		return this.wnoSEr01;
	}

	public void setWnoSEr01(BigDecimal wnoSEr01) {
		this.wnoSEr01 = wnoSEr01;
	}

	@Column(name = "WNO_S_LR01", precision = 12)
	public BigDecimal getWnoSLr01() {
		return this.wnoSLr01;
	}

	public void setWnoSLr01(BigDecimal wnoSLr01) {
		this.wnoSLr01 = wnoSLr01;
	}

	@Column(name = "PRIMARYKLU_WNE_V01", length = 19)
	public String getPrimarykluWneV01() {
		return this.primarykluWneV01;
	}

	public void setPrimarykluWneV01(String primarykluWneV01) {
		this.primarykluWneV01 = primarykluWneV01;
	}

	@Column(name = "WNE_A01", precision = 22, scale = 0)
	public BigDecimal getWneA01() {
		return this.wneA01;
	}

	public void setWneA01(BigDecimal wneA01) {
		this.wneA01 = wneA01;
	}

	@Column(name = "WNE_EGA01", precision = 12)
	public BigDecimal getWneEga01() {
		return this.wneEga01;
	}

	public void setWneEga01(BigDecimal wneEga01) {
		this.wneEga01 = wneEga01;
	}

	@Column(name = "WNE_LBA01", precision = 12)
	public BigDecimal getWneLba01() {
		return this.wneLba01;
	}

	public void setWneLba01(BigDecimal wneLba01) {
		this.wneLba01 = wneLba01;
	}

	@Column(name = "WNE_ER01", precision = 12)
	public BigDecimal getWneEr01() {
		return this.wneEr01;
	}

	public void setWneEr01(BigDecimal wneEr01) {
		this.wneEr01 = wneEr01;
	}

	@Column(name = "WNE_LR01", precision = 12)
	public BigDecimal getWneLr01() {
		return this.wneLr01;
	}

	public void setWneLr01(BigDecimal wneLr01) {
		this.wneLr01 = wneLr01;
	}

	@Column(name = "PRIMARYKLU_WNE_V02", length = 19)
	public String getPrimarykluWneV02() {
		return this.primarykluWneV02;
	}

	public void setPrimarykluWneV02(String primarykluWneV02) {
		this.primarykluWneV02 = primarykluWneV02;
	}

	@Column(name = "WNE_A02", precision = 22, scale = 0)
	public BigDecimal getWneA02() {
		return this.wneA02;
	}

	public void setWneA02(BigDecimal wneA02) {
		this.wneA02 = wneA02;
	}

	@Column(name = "WNE_EGA02", precision = 12)
	public BigDecimal getWneEga02() {
		return this.wneEga02;
	}

	public void setWneEga02(BigDecimal wneEga02) {
		this.wneEga02 = wneEga02;
	}

	@Column(name = "WNE_LBA02", precision = 12)
	public BigDecimal getWneLba02() {
		return this.wneLba02;
	}

	public void setWneLba02(BigDecimal wneLba02) {
		this.wneLba02 = wneLba02;
	}

	@Column(name = "WNE_ER02", precision = 12)
	public BigDecimal getWneEr02() {
		return this.wneEr02;
	}

	public void setWneEr02(BigDecimal wneEr02) {
		this.wneEr02 = wneEr02;
	}

	@Column(name = "WNE_LR02", precision = 12)
	public BigDecimal getWneLr02() {
		return this.wneLr02;
	}

	public void setWneLr02(BigDecimal wneLr02) {
		this.wneLr02 = wneLr02;
	}

	@Column(name = "PRIMARYKLU_WNE_S_V01", length = 19)
	public String getPrimarykluWneSV01() {
		return this.primarykluWneSV01;
	}

	public void setPrimarykluWneSV01(String primarykluWneSV01) {
		this.primarykluWneSV01 = primarykluWneSV01;
	}

	@Column(name = "WNE_S_A01", precision = 22, scale = 0)
	public BigDecimal getWneSA01() {
		return this.wneSA01;
	}

	public void setWneSA01(BigDecimal wneSA01) {
		this.wneSA01 = wneSA01;
	}

	@Column(name = "WNE_S_EGA01", precision = 12)
	public BigDecimal getWneSEga01() {
		return this.wneSEga01;
	}

	public void setWneSEga01(BigDecimal wneSEga01) {
		this.wneSEga01 = wneSEga01;
	}

	@Column(name = "WNE_S_LBA01", precision = 12)
	public BigDecimal getWneSLba01() {
		return this.wneSLba01;
	}

	public void setWneSLba01(BigDecimal wneSLba01) {
		this.wneSLba01 = wneSLba01;
	}

	@Column(name = "WNE_S_ER01", precision = 12)
	public BigDecimal getWneSEr01() {
		return this.wneSEr01;
	}

	public void setWneSEr01(BigDecimal wneSEr01) {
		this.wneSEr01 = wneSEr01;
	}

	@Column(name = "WNE_S_LR01", precision = 12)
	public BigDecimal getWneSLr01() {
		return this.wneSLr01;
	}

	public void setWneSLr01(BigDecimal wneSLr01) {
		this.wneSLr01 = wneSLr01;
	}

	@Column(name = "PRIMARYKLU_WNE_S_V02", length = 19)
	public String getPrimarykluWneSV02() {
		return this.primarykluWneSV02;
	}

	public void setPrimarykluWneSV02(String primarykluWneSV02) {
		this.primarykluWneSV02 = primarykluWneSV02;
	}

	@Column(name = "WNE_S_A02", precision = 22, scale = 0)
	public BigDecimal getWneSA02() {
		return this.wneSA02;
	}

	public void setWneSA02(BigDecimal wneSA02) {
		this.wneSA02 = wneSA02;
	}

	@Column(name = "WNE_S_EGA02", precision = 12)
	public BigDecimal getWneSEga02() {
		return this.wneSEga02;
	}

	public void setWneSEga02(BigDecimal wneSEga02) {
		this.wneSEga02 = wneSEga02;
	}

	@Column(name = "WNE_S_LBA02", precision = 12)
	public BigDecimal getWneSLba02() {
		return this.wneSLba02;
	}

	public void setWneSLba02(BigDecimal wneSLba02) {
		this.wneSLba02 = wneSLba02;
	}

	@Column(name = "WNE_S_ER02", precision = 12)
	public BigDecimal getWneSEr02() {
		return this.wneSEr02;
	}

	public void setWneSEr02(BigDecimal wneSEr02) {
		this.wneSEr02 = wneSEr02;
	}

	@Column(name = "WNE_S_LR02", precision = 12)
	public BigDecimal getWneSLr02() {
		return this.wneSLr02;
	}

	public void setWneSLr02(BigDecimal wneSLr02) {
		this.wneSLr02 = wneSLr02;
	}

	@Column(name = "PRIMARYKLU_WNE_S_V03", length = 19)
	public String getPrimarykluWneSV03() {
		return this.primarykluWneSV03;
	}

	public void setPrimarykluWneSV03(String primarykluWneSV03) {
		this.primarykluWneSV03 = primarykluWneSV03;
	}

	@Column(name = "WNE_S_A03", precision = 22, scale = 0)
	public BigDecimal getWneSA03() {
		return this.wneSA03;
	}

	public void setWneSA03(BigDecimal wneSA03) {
		this.wneSA03 = wneSA03;
	}

	@Column(name = "WNE_S_EGA03", precision = 12)
	public BigDecimal getWneSEga03() {
		return this.wneSEga03;
	}

	public void setWneSEga03(BigDecimal wneSEga03) {
		this.wneSEga03 = wneSEga03;
	}

	@Column(name = "WNE_S_LBA03", precision = 12)
	public BigDecimal getWneSLba03() {
		return this.wneSLba03;
	}

	public void setWneSLba03(BigDecimal wneSLba03) {
		this.wneSLba03 = wneSLba03;
	}

	@Column(name = "WNE_S_ER03", precision = 12)
	public BigDecimal getWneSEr03() {
		return this.wneSEr03;
	}

	public void setWneSEr03(BigDecimal wneSEr03) {
		this.wneSEr03 = wneSEr03;
	}

	@Column(name = "WNE_S_LR03", precision = 12)
	public BigDecimal getWneSLr03() {
		return this.wneSLr03;
	}

	public void setWneSLr03(BigDecimal wneSLr03) {
		this.wneSLr03 = wneSLr03;
	}

	@Column(name = "HASCALCULATION", length = 1)
	public Character getHascalculation() {
		return this.hascalculation;
	}

	public void setHascalculation(Character hascalculation) {
		this.hascalculation = hascalculation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "KAMPAGNEDATE", length = 7)
	public Date getKampagnedate() {
		return this.kampagnedate;
	}

	public void setKampagnedate(Date kampagnedate) {
		this.kampagnedate = kampagnedate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "I_TAKST", length = 7)
	public Date getITakst() {
		return this.ITakst;
	}

	public void setITakst(Date ITakst) {
		this.ITakst = ITakst;
	}

	@Column(name = "OPHAVSRET", precision = 4, scale = 0)
	public Short getOphavsret() {
		return this.ophavsret;
	}

	public void setOphavsret(Short ophavsret) {
		this.ophavsret = ophavsret;
	}

	@Column(name = "OPHAVSRET_INCL", length = 1)
	public Character getOphavsretIncl() {
		return this.ophavsretIncl;
	}

	public void setOphavsretIncl(Character ophavsretIncl) {
		this.ophavsretIncl = ophavsretIncl;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SVARFRIST", length = 7)
	public Date getSvarfrist() {
		return this.svarfrist;
	}

	public void setSvarfrist(Date svarfrist) {
		this.svarfrist = svarfrist;
	}

}
