package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "PRODUCTS", schema = "PCRM")
public class Products implements java.io.Serializable {

	private int productId;
	private ProductGroups productGroups;
	private String createdByUser;
	private Date createdDateTime;
	private String changeByUser;
	private Date changeDateTime;
	private String shortName;
	private BigDecimal oldProductId;
	private Integer agProductId;
	private String overlap;
	private Integer packagerelation;
	private Set<ChNodeKeys> chNodeKeyses = new HashSet<ChNodeKeys>(0);
	private Set<PackagesUnderProject> packagesUnderProjects = new HashSet<PackagesUnderProject>(
			0);

	public Products() {
	}

	public Products(int productId) {
		this.productId = productId;
	}

	public Products(int productId, ProductGroups productGroups,
			String createdByUser, Date createdDateTime, String changeByUser,
			Date changeDateTime, String shortName, BigDecimal oldProductId,
			Integer agProductId, String overlap, Integer packagerelation,
			Set<ChNodeKeys> chNodeKeyses,
			Set<PackagesUnderProject> packagesUnderProjects) {
		this.productId = productId;
		this.productGroups = productGroups;
		this.createdByUser = createdByUser;
		this.createdDateTime = createdDateTime;
		this.changeByUser = changeByUser;
		this.changeDateTime = changeDateTime;
		this.shortName = shortName;
		this.oldProductId = oldProductId;
		this.agProductId = agProductId;
		this.overlap = overlap;
		this.packagerelation = packagerelation;
		this.chNodeKeyses = chNodeKeyses;
		this.packagesUnderProjects = packagesUnderProjects;
	}

	@Id
	@Column(name = "PRODUCT_ID", unique = true, nullable = false, precision = 7, scale = 0)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_GROUP")
	public ProductGroups getProductGroups() {
		return this.productGroups;
	}

	public void setProductGroups(ProductGroups productGroups) {
		this.productGroups = productGroups;
	}

	@Column(name = "CREATED_BY_USER", length = 20)
	public String getCreatedByUser() {
		return this.createdByUser;
	}

	public void setCreatedByUser(String createdByUser) {
		this.createdByUser = createdByUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE_TIME", length = 7)
	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	@Column(name = "CHANGE_BY_USER", length = 20)
	public String getChangeByUser() {
		return this.changeByUser;
	}

	public void setChangeByUser(String changeByUser) {
		this.changeByUser = changeByUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHANGE_DATE_TIME", length = 7)
	public Date getChangeDateTime() {
		return this.changeDateTime;
	}

	public void setChangeDateTime(Date changeDateTime) {
		this.changeDateTime = changeDateTime;
	}

	@Column(name = "SHORT_NAME", length = 32)
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@Column(name = "OLD_PRODUCT_ID", precision = 22, scale = 0)
	public BigDecimal getOldProductId() {
		return this.oldProductId;
	}

	public void setOldProductId(BigDecimal oldProductId) {
		this.oldProductId = oldProductId;
	}

	@Column(name = "AG_PRODUCT_ID", precision = 7, scale = 0)
	public Integer getAgProductId() {
		return this.agProductId;
	}

	public void setAgProductId(Integer agProductId) {
		this.agProductId = agProductId;
	}

	@Column(name = "OVERLAP", length = 3)
	public String getOverlap() {
		return this.overlap;
	}

	public void setOverlap(String overlap) {
		this.overlap = overlap;
	}

	@Column(name = "PACKAGERELATION", precision = 7, scale = 0)
	public Integer getPackagerelation() {
		return this.packagerelation;
	}

	public void setPackagerelation(Integer packagerelation) {
		this.packagerelation = packagerelation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<ChNodeKeys> getChNodeKeyses() {
		return this.chNodeKeyses;
	}

	public void setChNodeKeyses(Set<ChNodeKeys> chNodeKeyses) {
		this.chNodeKeyses = chNodeKeyses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "products")
	public Set<PackagesUnderProject> getPackagesUnderProjects() {
		return this.packagesUnderProjects;
	}

	public void setPackagesUnderProjects(
			Set<PackagesUnderProject> packagesUnderProjects) {
		this.packagesUnderProjects = packagesUnderProjects;
	}

}
