package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Progoffer generated by hbm2java
 */
@Entity
@Table(name = "PROGOFFER", schema = "PCRM")
public class Progoffer implements java.io.Serializable {

	private String id;
	private Progofferselection progofferselection;
	private Progoffer progoffer;
	private String anlaegsnr;
	private String pakkenr;
	private String programnr;
	private String varenavn;
	private String varegruppe;
	private String signalleverandxr;
	private String leveringsform;
	private Date fradato;
	private Date tildato;
	private String frekvens;
	private String kanalnxgle;
	private String fratid;
	private String tiltid;
	private Date udtrxksdato;
	private Date sidstrettet;
	private Date opdateretbuc;
	private Date crd;
	private Date impt;
	private Date expt;
	private Date impd;
	private Date expd;
	private Date modt;
	private String cru;
	private Date delt;
	private Date modd;
	private String impu;
	private String expu;
	private Date deld;
	private String modu;
	private String delu;
	private Date crt;
	private String primprogrpakke;
	private String code;
	private String head;
	private String primarysag;
	private String primtilbkontr;
	private String primprogrtype;
	private Character lokalkilde;
	private Character tdckilde;
	private String primprogram;
	private Character prxve;
	private String primklulevudst;
	private String primklufors;
	private String primkludist;
	private String primklutfe;
	private BigDecimal ktvHovedgruppe;
	private BigDecimal ktvProduktgruppe;
	private BigDecimal ktvPakkegruppe;
	private BigDecimal markedspris;
	private BigDecimal minimumSalesprice;
	private BigDecimal customerPrice;
	private Date bestiltFaktureret;
	private Date idriftdato;
	private Date lukketdato;
	private String primkluafregnesaf;
	private String primklukoda;
	private Character notincontract;
	private Character prispaakontrakt;
	private String primprodprogramfilter;
	private Set<Progoffer> progoffers = new HashSet<Progoffer>(0);
	private Set<Progoffervaluelink> progoffervaluelinks = new HashSet<Progoffervaluelink>(
			0);

	public Progoffer() {
	}

	public Progoffer(String id) {
		this.id = id;
	}

	public Progoffer(String id, Progofferselection progofferselection,
			Progoffer progoffer, String anlaegsnr, String pakkenr,
			String programnr, String varenavn, String varegruppe,
			String signalleverandxr, String leveringsform, Date fradato,
			Date tildato, String frekvens, String kanalnxgle, String fratid,
			String tiltid, Date udtrxksdato, Date sidstrettet,
			Date opdateretbuc, Date crd, Date impt, Date expt, Date impd,
			Date expd, Date modt, String cru, Date delt, Date modd,
			String impu, String expu, Date deld, String modu, String delu,
			Date crt, String primprogrpakke, String code, String head,
			String primarysag, String primtilbkontr, String primprogrtype,
			Character lokalkilde, Character tdckilde, String primprogram,
			Character prxve, String primklulevudst, String primklufors,
			String primkludist, String primklutfe, BigDecimal ktvHovedgruppe,
			BigDecimal ktvProduktgruppe, BigDecimal ktvPakkegruppe,
			BigDecimal markedspris, BigDecimal minimumSalesprice,
			BigDecimal customerPrice, Date bestiltFaktureret, Date idriftdato,
			Date lukketdato, String primkluafregnesaf, String primklukoda,
			Character notincontract, Character prispaakontrakt,
			String primprodprogramfilter, Set<Progoffer> progoffers,
			Set<Progoffervaluelink> progoffervaluelinks) {
		this.id = id;
		this.progofferselection = progofferselection;
		this.progoffer = progoffer;
		this.anlaegsnr = anlaegsnr;
		this.pakkenr = pakkenr;
		this.programnr = programnr;
		this.varenavn = varenavn;
		this.varegruppe = varegruppe;
		this.signalleverandxr = signalleverandxr;
		this.leveringsform = leveringsform;
		this.fradato = fradato;
		this.tildato = tildato;
		this.frekvens = frekvens;
		this.kanalnxgle = kanalnxgle;
		this.fratid = fratid;
		this.tiltid = tiltid;
		this.udtrxksdato = udtrxksdato;
		this.sidstrettet = sidstrettet;
		this.opdateretbuc = opdateretbuc;
		this.crd = crd;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.cru = cru;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.modu = modu;
		this.delu = delu;
		this.crt = crt;
		this.primprogrpakke = primprogrpakke;
		this.code = code;
		this.head = head;
		this.primarysag = primarysag;
		this.primtilbkontr = primtilbkontr;
		this.primprogrtype = primprogrtype;
		this.lokalkilde = lokalkilde;
		this.tdckilde = tdckilde;
		this.primprogram = primprogram;
		this.prxve = prxve;
		this.primklulevudst = primklulevudst;
		this.primklufors = primklufors;
		this.primkludist = primkludist;
		this.primklutfe = primklutfe;
		this.ktvHovedgruppe = ktvHovedgruppe;
		this.ktvProduktgruppe = ktvProduktgruppe;
		this.ktvPakkegruppe = ktvPakkegruppe;
		this.markedspris = markedspris;
		this.minimumSalesprice = minimumSalesprice;
		this.customerPrice = customerPrice;
		this.bestiltFaktureret = bestiltFaktureret;
		this.idriftdato = idriftdato;
		this.lukketdato = lukketdato;
		this.primkluafregnesaf = primkluafregnesaf;
		this.primklukoda = primklukoda;
		this.notincontract = notincontract;
		this.prispaakontrakt = prispaakontrakt;
		this.primprodprogramfilter = primprodprogramfilter;
		this.progoffers = progoffers;
		this.progoffervaluelinks = progoffervaluelinks;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMCHOSPROGPACK")
	public Progofferselection getProgofferselection() {
		return this.progofferselection;
	}

	public void setProgofferselection(Progofferselection progofferselection) {
		this.progofferselection = progofferselection;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMPROGOFFER")
	public Progoffer getProgoffer() {
		return this.progoffer;
	}

	public void setProgoffer(Progoffer progoffer) {
		this.progoffer = progoffer;
	}

	@Column(name = "ANLAEGSNR", length = 10)
	public String getAnlaegsnr() {
		return this.anlaegsnr;
	}

	public void setAnlaegsnr(String anlaegsnr) {
		this.anlaegsnr = anlaegsnr;
	}

	@Column(name = "PAKKENR", length = 10)
	public String getPakkenr() {
		return this.pakkenr;
	}

	public void setPakkenr(String pakkenr) {
		this.pakkenr = pakkenr;
	}

	@Column(name = "PROGRAMNR", length = 20)
	public String getProgramnr() {
		return this.programnr;
	}

	public void setProgramnr(String programnr) {
		this.programnr = programnr;
	}

	@Column(name = "VARENAVN", length = 50)
	public String getVarenavn() {
		return this.varenavn;
	}

	public void setVarenavn(String varenavn) {
		this.varenavn = varenavn;
	}

	@Column(name = "VAREGRUPPE", length = 10)
	public String getVaregruppe() {
		return this.varegruppe;
	}

	public void setVaregruppe(String varegruppe) {
		this.varegruppe = varegruppe;
	}

	@Column(name = "SIGNALLEVERANDXR", length = 8)
	public String getSignalleverandxr() {
		return this.signalleverandxr;
	}

	public void setSignalleverandxr(String signalleverandxr) {
		this.signalleverandxr = signalleverandxr;
	}

	@Column(name = "LEVERINGSFORM", length = 9)
	public String getLeveringsform() {
		return this.leveringsform;
	}

	public void setLeveringsform(String leveringsform) {
		this.leveringsform = leveringsform;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FRADATO", length = 7)
	public Date getFradato() {
		return this.fradato;
	}

	public void setFradato(Date fradato) {
		this.fradato = fradato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "TILDATO", length = 7)
	public Date getTildato() {
		return this.tildato;
	}

	public void setTildato(Date tildato) {
		this.tildato = tildato;
	}

	@Column(name = "FREKVENS", length = 10)
	public String getFrekvens() {
		return this.frekvens;
	}

	public void setFrekvens(String frekvens) {
		this.frekvens = frekvens;
	}

	@Column(name = "KANALNXGLE", length = 10)
	public String getKanalnxgle() {
		return this.kanalnxgle;
	}

	public void setKanalnxgle(String kanalnxgle) {
		this.kanalnxgle = kanalnxgle;
	}

	@Column(name = "FRATID", length = 5)
	public String getFratid() {
		return this.fratid;
	}

	public void setFratid(String fratid) {
		this.fratid = fratid;
	}

	@Column(name = "TILTID", length = 5)
	public String getTiltid() {
		return this.tiltid;
	}

	public void setTiltid(String tiltid) {
		this.tiltid = tiltid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UDTRXKSDATO", length = 7)
	public Date getUdtrxksdato() {
		return this.udtrxksdato;
	}

	public void setUdtrxksdato(Date udtrxksdato) {
		this.udtrxksdato = udtrxksdato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SIDSTRETTET", length = 7)
	public Date getSidstrettet() {
		return this.sidstrettet;
	}

	public void setSidstrettet(Date sidstrettet) {
		this.sidstrettet = sidstrettet;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "OPDATERETBUC", length = 7)
	public Date getOpdateretbuc() {
		return this.opdateretbuc;
	}

	public void setOpdateretbuc(Date opdateretbuc) {
		this.opdateretbuc = opdateretbuc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "PRIMPROGRPAKKE", length = 19)
	public String getPrimprogrpakke() {
		return this.primprogrpakke;
	}

	public void setPrimprogrpakke(String primprogrpakke) {
		this.primprogrpakke = primprogrpakke;
	}

	@Column(name = "CODE", length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "HEAD")
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "PRIMARYSAG", length = 19)
	public String getPrimarysag() {
		return this.primarysag;
	}

	public void setPrimarysag(String primarysag) {
		this.primarysag = primarysag;
	}

	@Column(name = "PRIMTILBKONTR", length = 19)
	public String getPrimtilbkontr() {
		return this.primtilbkontr;
	}

	public void setPrimtilbkontr(String primtilbkontr) {
		this.primtilbkontr = primtilbkontr;
	}

	@Column(name = "PRIMPROGRTYPE", length = 19)
	public String getPrimprogrtype() {
		return this.primprogrtype;
	}

	public void setPrimprogrtype(String primprogrtype) {
		this.primprogrtype = primprogrtype;
	}

	@Column(name = "LOKALKILDE", length = 1)
	public Character getLokalkilde() {
		return this.lokalkilde;
	}

	public void setLokalkilde(Character lokalkilde) {
		this.lokalkilde = lokalkilde;
	}

	@Column(name = "TDCKILDE", length = 1)
	public Character getTdckilde() {
		return this.tdckilde;
	}

	public void setTdckilde(Character tdckilde) {
		this.tdckilde = tdckilde;
	}

	@Column(name = "PRIMPROGRAM", length = 19)
	public String getPrimprogram() {
		return this.primprogram;
	}

	public void setPrimprogram(String primprogram) {
		this.primprogram = primprogram;
	}

	@Column(name = "PRXVE", length = 1)
	public Character getPrxve() {
		return this.prxve;
	}

	public void setPrxve(Character prxve) {
		this.prxve = prxve;
	}

	@Column(name = "PRIMKLULEVUDST", length = 19)
	public String getPrimklulevudst() {
		return this.primklulevudst;
	}

	public void setPrimklulevudst(String primklulevudst) {
		this.primklulevudst = primklulevudst;
	}

	@Column(name = "PRIMKLUFORS", length = 19)
	public String getPrimklufors() {
		return this.primklufors;
	}

	public void setPrimklufors(String primklufors) {
		this.primklufors = primklufors;
	}

	@Column(name = "PRIMKLUDIST", length = 19)
	public String getPrimkludist() {
		return this.primkludist;
	}

	public void setPrimkludist(String primkludist) {
		this.primkludist = primkludist;
	}

	@Column(name = "PRIMKLUTFE", length = 19)
	public String getPrimklutfe() {
		return this.primklutfe;
	}

	public void setPrimklutfe(String primklutfe) {
		this.primklutfe = primklutfe;
	}

	@Column(name = "KTV_HOVEDGRUPPE", precision = 22, scale = 0)
	public BigDecimal getKtvHovedgruppe() {
		return this.ktvHovedgruppe;
	}

	public void setKtvHovedgruppe(BigDecimal ktvHovedgruppe) {
		this.ktvHovedgruppe = ktvHovedgruppe;
	}

	@Column(name = "KTV_PRODUKTGRUPPE", precision = 22, scale = 0)
	public BigDecimal getKtvProduktgruppe() {
		return this.ktvProduktgruppe;
	}

	public void setKtvProduktgruppe(BigDecimal ktvProduktgruppe) {
		this.ktvProduktgruppe = ktvProduktgruppe;
	}

	@Column(name = "KTV_PAKKEGRUPPE", precision = 22, scale = 0)
	public BigDecimal getKtvPakkegruppe() {
		return this.ktvPakkegruppe;
	}

	public void setKtvPakkegruppe(BigDecimal ktvPakkegruppe) {
		this.ktvPakkegruppe = ktvPakkegruppe;
	}

	@Column(name = "MARKEDSPRIS", precision = 10)
	public BigDecimal getMarkedspris() {
		return this.markedspris;
	}

	public void setMarkedspris(BigDecimal markedspris) {
		this.markedspris = markedspris;
	}

	@Column(name = "MINIMUM_SALESPRICE", precision = 10)
	public BigDecimal getMinimumSalesprice() {
		return this.minimumSalesprice;
	}

	public void setMinimumSalesprice(BigDecimal minimumSalesprice) {
		this.minimumSalesprice = minimumSalesprice;
	}

	@Column(name = "CUSTOMER_PRICE", precision = 10)
	public BigDecimal getCustomerPrice() {
		return this.customerPrice;
	}

	public void setCustomerPrice(BigDecimal customerPrice) {
		this.customerPrice = customerPrice;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BESTILT_FAKTURERET", length = 7)
	public Date getBestiltFaktureret() {
		return this.bestiltFaktureret;
	}

	public void setBestiltFaktureret(Date bestiltFaktureret) {
		this.bestiltFaktureret = bestiltFaktureret;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IDRIFTDATO", length = 7)
	public Date getIdriftdato() {
		return this.idriftdato;
	}

	public void setIdriftdato(Date idriftdato) {
		this.idriftdato = idriftdato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LUKKETDATO", length = 7)
	public Date getLukketdato() {
		return this.lukketdato;
	}

	public void setLukketdato(Date lukketdato) {
		this.lukketdato = lukketdato;
	}

	@Column(name = "PRIMKLUAFREGNESAF", length = 19)
	public String getPrimkluafregnesaf() {
		return this.primkluafregnesaf;
	}

	public void setPrimkluafregnesaf(String primkluafregnesaf) {
		this.primkluafregnesaf = primkluafregnesaf;
	}

	@Column(name = "PRIMKLUKODA", length = 19)
	public String getPrimklukoda() {
		return this.primklukoda;
	}

	public void setPrimklukoda(String primklukoda) {
		this.primklukoda = primklukoda;
	}

	@Column(name = "NOTINCONTRACT", length = 1)
	public Character getNotincontract() {
		return this.notincontract;
	}

	public void setNotincontract(Character notincontract) {
		this.notincontract = notincontract;
	}

	@Column(name = "PRISPAAKONTRAKT", length = 1)
	public Character getPrispaakontrakt() {
		return this.prispaakontrakt;
	}

	public void setPrispaakontrakt(Character prispaakontrakt) {
		this.prispaakontrakt = prispaakontrakt;
	}

	@Column(name = "PRIMPRODPROGRAMFILTER", length = 50)
	public String getPrimprodprogramfilter() {
		return this.primprodprogramfilter;
	}

	public void setPrimprodprogramfilter(String primprodprogramfilter) {
		this.primprodprogramfilter = primprodprogramfilter;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "progoffer")
	public Set<Progoffer> getProgoffers() {
		return this.progoffers;
	}

	public void setProgoffers(Set<Progoffer> progoffers) {
		this.progoffers = progoffers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "progoffer")
	public Set<Progoffervaluelink> getProgoffervaluelinks() {
		return this.progoffervaluelinks;
	}

	public void setProgoffervaluelinks(
			Set<Progoffervaluelink> progoffervaluelinks) {
		this.progoffervaluelinks = progoffervaluelinks;
	}

}
