package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Progofferselection generated by hbm2java
 */
@Entity
@Table(name = "PROGOFFERSELECTION", schema = "PCRM")
public class Progofferselection implements java.io.Serializable {

	private String id;
	private Offer offer;
	private Date crd;
	private String code;
	private Date impt;
	private Date expt;
	private Date impd;
	private Date expd;
	private Date modt;
	private String cru;
	private Date delt;
	private Date modd;
	private String impu;
	private String expu;
	private Date deld;
	private String modu;
	private String head;
	private String delu;
	private Date crt;
	private String primprogpak;
	private String primpakchos;
	private String primhfinfo;
	private String primanlaeg;
	private String primcontract;
	private String packagename;
	private String key2rule;
	private String primprodpackagefilter;
	private Short sortingKey;
	private BigDecimal freqStart;
	private BigDecimal freqEnd;
	private Set<Progoffer> progoffers = new HashSet<Progoffer>(0);
	private Set<Price> prices = new HashSet<Price>(0);

	public Progofferselection() {
	}

	public Progofferselection(String id) {
		this.id = id;
	}

	public Progofferselection(String id, Offer offer, Date crd, String code,
			Date impt, Date expt, Date impd, Date expd, Date modt, String cru,
			Date delt, Date modd, String impu, String expu, Date deld,
			String modu, String head, String delu, Date crt,
			String primprogpak, String primpakchos, String primhfinfo,
			String primanlaeg, String primcontract, String packagename,
			String key2rule, String primprodpackagefilter, Short sortingKey,
			BigDecimal freqStart, BigDecimal freqEnd,
			Set<Progoffer> progoffers, Set<Price> prices) {
		this.id = id;
		this.offer = offer;
		this.crd = crd;
		this.code = code;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.cru = cru;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.modu = modu;
		this.head = head;
		this.delu = delu;
		this.crt = crt;
		this.primprogpak = primprogpak;
		this.primpakchos = primpakchos;
		this.primhfinfo = primhfinfo;
		this.primanlaeg = primanlaeg;
		this.primcontract = primcontract;
		this.packagename = packagename;
		this.key2rule = key2rule;
		this.primprodpackagefilter = primprodpackagefilter;
		this.sortingKey = sortingKey;
		this.freqStart = freqStart;
		this.freqEnd = freqEnd;
		this.progoffers = progoffers;
		this.prices = prices;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMOFFER")
	public Offer getOffer() {
		return this.offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CODE", length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "HEAD")
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "PRIMPROGPAK", length = 19)
	public String getPrimprogpak() {
		return this.primprogpak;
	}

	public void setPrimprogpak(String primprogpak) {
		this.primprogpak = primprogpak;
	}

	@Column(name = "PRIMPAKCHOS", length = 19)
	public String getPrimpakchos() {
		return this.primpakchos;
	}

	public void setPrimpakchos(String primpakchos) {
		this.primpakchos = primpakchos;
	}

	@Column(name = "PRIMHFINFO", length = 19)
	public String getPrimhfinfo() {
		return this.primhfinfo;
	}

	public void setPrimhfinfo(String primhfinfo) {
		this.primhfinfo = primhfinfo;
	}

	@Column(name = "PRIMANLAEG", length = 19)
	public String getPrimanlaeg() {
		return this.primanlaeg;
	}

	public void setPrimanlaeg(String primanlaeg) {
		this.primanlaeg = primanlaeg;
	}

	@Column(name = "PRIMCONTRACT", length = 19)
	public String getPrimcontract() {
		return this.primcontract;
	}

	public void setPrimcontract(String primcontract) {
		this.primcontract = primcontract;
	}

	@Column(name = "PACKAGENAME")
	public String getPackagename() {
		return this.packagename;
	}

	public void setPackagename(String packagename) {
		this.packagename = packagename;
	}

	@Column(name = "KEY2RULE")
	public String getKey2rule() {
		return this.key2rule;
	}

	public void setKey2rule(String key2rule) {
		this.key2rule = key2rule;
	}

	@Column(name = "PRIMPRODPACKAGEFILTER", length = 50)
	public String getPrimprodpackagefilter() {
		return this.primprodpackagefilter;
	}

	public void setPrimprodpackagefilter(String primprodpackagefilter) {
		this.primprodpackagefilter = primprodpackagefilter;
	}

	@Column(name = "SORTING_KEY", precision = 3, scale = 0)
	public Short getSortingKey() {
		return this.sortingKey;
	}

	public void setSortingKey(Short sortingKey) {
		this.sortingKey = sortingKey;
	}

	@Column(name = "FREQ_START", precision = 22, scale = 0)
	public BigDecimal getFreqStart() {
		return this.freqStart;
	}

	public void setFreqStart(BigDecimal freqStart) {
		this.freqStart = freqStart;
	}

	@Column(name = "FREQ_END", precision = 22, scale = 0)
	public BigDecimal getFreqEnd() {
		return this.freqEnd;
	}

	public void setFreqEnd(BigDecimal freqEnd) {
		this.freqEnd = freqEnd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "progofferselection")
	public Set<Progoffer> getProgoffers() {
		return this.progoffers;
	}

	public void setProgoffers(Set<Progoffer> progoffers) {
		this.progoffers = progoffers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "progofferselection")
	public Set<Price> getPrices() {
		return this.prices;
	}

	public void setPrices(Set<Price> prices) {
		this.prices = prices;
	}

}
