package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Salesconceptcontlink generated by hbm2java
 */
@Entity
@Table(name = "SALESCONCEPTCONTLINK", schema = "PCRM")
public class Salesconceptcontlink implements java.io.Serializable {

	private String id;
	private Salesconcept salesconcept;
	private Date crd;
	private String cru;
	private Date modd;
	private String modu;
	private Date impd;
	private String impu;
	private Date expd;
	private String expu;
	private String primcontent00;
	private String primcontent01;
	private Date validfrom;
	private Date validto;

	public Salesconceptcontlink() {
	}

	public Salesconceptcontlink(String id) {
		this.id = id;
	}

	public Salesconceptcontlink(String id, Salesconcept salesconcept, Date crd,
			String cru, Date modd, String modu, Date impd, String impu,
			Date expd, String expu, String primcontent00, String primcontent01,
			Date validfrom, Date validto) {
		this.id = id;
		this.salesconcept = salesconcept;
		this.crd = crd;
		this.cru = cru;
		this.modd = modd;
		this.modu = modu;
		this.impd = impd;
		this.impu = impu;
		this.expd = expd;
		this.expu = expu;
		this.primcontent00 = primcontent00;
		this.primcontent01 = primcontent01;
		this.validfrom = validfrom;
		this.validto = validto;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMSALESCONCEPT")
	public Salesconcept getSalesconcept() {
		return this.salesconcept;
	}

	public void setSalesconcept(Salesconcept salesconcept) {
		this.salesconcept = salesconcept;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "PRIMCONTENT00", length = 19)
	public String getPrimcontent00() {
		return this.primcontent00;
	}

	public void setPrimcontent00(String primcontent00) {
		this.primcontent00 = primcontent00;
	}

	@Column(name = "PRIMCONTENT01", length = 128)
	public String getPrimcontent01() {
		return this.primcontent01;
	}

	public void setPrimcontent01(String primcontent01) {
		this.primcontent01 = primcontent01;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VALIDFROM", length = 7)
	public Date getValidfrom() {
		return this.validfrom;
	}

	public void setValidfrom(Date validfrom) {
		this.validfrom = validfrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VALIDTO", length = 7)
	public Date getValidto() {
		return this.validto;
	}

	public void setValidto(Date validto) {
		this.validto = validto;
	}

}
