package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sfdcquery generated by hbm2java
 */
@Entity
@Table(name = "SFDCQUERY", schema = "PCRM")
public class Sfdcquery implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private String objectName;
	private String selectors;
	private String whereClauses;
	private BigDecimal lastUpdate;
	private BigDecimal scheduleStart;
	private BigDecimal interval;
	private Set<JobLog> jobLogs = new HashSet<JobLog>(0);
	private Set<ArchivedFiles> archivedFileses = new HashSet<ArchivedFiles>(0);

	public Sfdcquery() {
	}

	public Sfdcquery(BigDecimal id) {
		this.id = id;
	}

	public Sfdcquery(BigDecimal id, String name, String objectName,
			String selectors, String whereClauses, BigDecimal lastUpdate,
			BigDecimal scheduleStart, BigDecimal interval, Set<JobLog> jobLogs,
			Set<ArchivedFiles> archivedFileses) {
		this.id = id;
		this.name = name;
		this.objectName = objectName;
		this.selectors = selectors;
		this.whereClauses = whereClauses;
		this.lastUpdate = lastUpdate;
		this.scheduleStart = scheduleStart;
		this.interval = interval;
		this.jobLogs = jobLogs;
		this.archivedFileses = archivedFileses;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "OBJECT_NAME")
	public String getObjectName() {
		return this.objectName;
	}

	public void setObjectName(String objectName) {
		this.objectName = objectName;
	}

	@Column(name = "SELECTORS", length = 4000)
	public String getSelectors() {
		return this.selectors;
	}

	public void setSelectors(String selectors) {
		this.selectors = selectors;
	}

	@Column(name = "WHERE_CLAUSES", length = 4000)
	public String getWhereClauses() {
		return this.whereClauses;
	}

	public void setWhereClauses(String whereClauses) {
		this.whereClauses = whereClauses;
	}

	@Column(name = "LAST_UPDATE", scale = 0)
	public BigDecimal getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(BigDecimal lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	@Column(name = "SCHEDULE_START", scale = 0)
	public BigDecimal getScheduleStart() {
		return this.scheduleStart;
	}

	public void setScheduleStart(BigDecimal scheduleStart) {
		this.scheduleStart = scheduleStart;
	}

	@Column(name = "INTERVAL", scale = 0)
	public BigDecimal getInterval() {
		return this.interval;
	}

	public void setInterval(BigDecimal interval) {
		this.interval = interval;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sfdcquery")
	public Set<JobLog> getJobLogs() {
		return this.jobLogs;
	}

	public void setJobLogs(Set<JobLog> jobLogs) {
		this.jobLogs = jobLogs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sfdcquery")
	public Set<ArchivedFiles> getArchivedFileses() {
		return this.archivedFileses;
	}

	public void setArchivedFileses(Set<ArchivedFiles> archivedFileses) {
		this.archivedFileses = archivedFileses;
	}

}
