package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sglocation generated by hbm2java
 */
@Entity
@Table(name = "SGLOCATION", schema = "PCRM")
public class Sglocation implements java.io.Serializable {

	private String id;
	private Date crd;
	private String cru;
	private Date modd;
	private String modu;
	private Date impd;
	private String impu;
	private Date expd;
	private String expu;
	private Date impt;
	private Date expt;
	private Date modt;
	private Date delt;
	private Date deld;
	private String delu;
	private Date crt;
	private String head;
	private Date startDate;
	private Date endDate;
	private String code;
	private Byte columnNumber;
	private String primbusinesssphere;
	private Boolean rowWrapping;
	private String tooltip;
	private Set<Sgicon> sgicons = new HashSet<Sgicon>(0);
	private Set<CrSglocation2parametertype> crSglocation2parametertypes = new HashSet<CrSglocation2parametertype>(
			0);

	public Sglocation() {
	}

	public Sglocation(String id, String code, String primbusinesssphere) {
		this.id = id;
		this.code = code;
		this.primbusinesssphere = primbusinesssphere;
	}

	public Sglocation(String id, Date crd, String cru, Date modd, String modu,
			Date impd, String impu, Date expd, String expu, Date impt,
			Date expt, Date modt, Date delt, Date deld, String delu, Date crt,
			String head, Date startDate, Date endDate, String code,
			Byte columnNumber, String primbusinesssphere, Boolean rowWrapping,
			String tooltip, Set<Sgicon> sgicons,
			Set<CrSglocation2parametertype> crSglocation2parametertypes) {
		this.id = id;
		this.crd = crd;
		this.cru = cru;
		this.modd = modd;
		this.modu = modu;
		this.impd = impd;
		this.impu = impu;
		this.expd = expd;
		this.expu = expu;
		this.impt = impt;
		this.expt = expt;
		this.modt = modt;
		this.delt = delt;
		this.deld = deld;
		this.delu = delu;
		this.crt = crt;
		this.head = head;
		this.startDate = startDate;
		this.endDate = endDate;
		this.code = code;
		this.columnNumber = columnNumber;
		this.primbusinesssphere = primbusinesssphere;
		this.rowWrapping = rowWrapping;
		this.tooltip = tooltip;
		this.sgicons = sgicons;
		this.crSglocation2parametertypes = crSglocation2parametertypes;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "HEAD")
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "CODE", nullable = false, length = 8)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "COLUMN_NUMBER", precision = 2, scale = 0)
	public Byte getColumnNumber() {
		return this.columnNumber;
	}

	public void setColumnNumber(Byte columnNumber) {
		this.columnNumber = columnNumber;
	}

	@Column(name = "PRIMBUSINESSSPHERE", nullable = false, length = 19)
	public String getPrimbusinesssphere() {
		return this.primbusinesssphere;
	}

	public void setPrimbusinesssphere(String primbusinesssphere) {
		this.primbusinesssphere = primbusinesssphere;
	}

	@Column(name = "ROW_WRAPPING", precision = 1, scale = 0)
	public Boolean getRowWrapping() {
		return this.rowWrapping;
	}

	public void setRowWrapping(Boolean rowWrapping) {
		this.rowWrapping = rowWrapping;
	}

	@Column(name = "TOOLTIP", length = 4000)
	public String getTooltip() {
		return this.tooltip;
	}

	public void setTooltip(String tooltip) {
		this.tooltip = tooltip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sglocation")
	public Set<Sgicon> getSgicons() {
		return this.sgicons;
	}

	public void setSgicons(Set<Sgicon> sgicons) {
		this.sgicons = sgicons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sglocation")
	public Set<CrSglocation2parametertype> getCrSglocation2parametertypes() {
		return this.crSglocation2parametertypes;
	}

	public void setCrSglocation2parametertypes(
			Set<CrSglocation2parametertype> crSglocation2parametertypes) {
		this.crSglocation2parametertypes = crSglocation2parametertypes;
	}

}
