package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Staff generated by hbm2java
 */
@Entity
@Table(name = "STAFF", schema = "PCRM", uniqueConstraints = {
		@UniqueConstraint(columnNames = "OSUNAME") })
public class Staff implements java.io.Serializable {

	private String id;
	private Staffimage staffimage;
	private String primuser;
	private String kompetance2;
	private Date impt;
	private Date deld;
	private String education2;
	private Date crd;
	private String expu;
	private String primlang;
	private Date crt;
	private String kompetance3;
	private String email;
	private String modu;
	private String cru;
	private Date impd;
	private String private_;
	private String ext;
	private String primdept;
	private String sidsteudd;
	private String direct;
	private String uname;
	private String mailname;
	private String delu;
	private String firstn;
	private Date expt;
	private Date modd;
	private String kompetance4;
	private String education;
	private Integer leveluser;
	private String mailpassword;
	private String lastn;
	private Date modt;
	private String voicel;
	private String title;
	private String fax;
	private Date passwordexpiredate;
	private Character useractive;
	private String imagefile;
	private String kompetance1;
	private String impu;
	private String osuname;
	private Date expd;
	private String pword;
	private Date delt;
	private String kompetance5;
	private String mobile;
	private String primaryteam;
	private Character mayupdatessh;
	private Character mayeditactivities;
	private String primarylocation;
	private BigDecimal beloeb;
	private BigDecimal beloebko;
	private String fullname;
	private Set<StaffpostalcodeRange> staffpostalcodeRanges = new HashSet<StaffpostalcodeRange>(
			0);
	private Set<CustomerDrop> customerDrops = new HashSet<CustomerDrop>(0);
	private Set<Casefolder> casefoldersForPrimaryrevuser = new HashSet<Casefolder>(
			0);
	private Set<Casefolder> casefoldersForPrimarysalgsansvarlig = new HashSet<Casefolder>(
			0);
	private Set<StaffactorDrop> staffactorDrops = new HashSet<StaffactorDrop>(0);
	private Set<Staffimage> staffimages = new HashSet<Staffimage>(0);
	private Set<Constructionproject> constructionprojects = new HashSet<Constructionproject>(
			0);

	public Staff() {
	}

	public Staff(String id) {
		this.id = id;
	}

	public Staff(String id, Staffimage staffimage, String primuser,
			String kompetance2, Date impt, Date deld, String education2,
			Date crd, String expu, String primlang, Date crt,
			String kompetance3, String email, String modu, String cru,
			Date impd, String private_, String ext, String primdept,
			String sidsteudd, String direct, String uname, String mailname,
			String delu, String firstn, Date expt, Date modd,
			String kompetance4, String education, Integer leveluser,
			String mailpassword, String lastn, Date modt, String voicel,
			String title, String fax, Date passwordexpiredate,
			Character useractive, String imagefile, String kompetance1,
			String impu, String osuname, Date expd, String pword, Date delt,
			String kompetance5, String mobile, String primaryteam,
			Character mayupdatessh, Character mayeditactivities,
			String primarylocation, BigDecimal beloeb, BigDecimal beloebko,
			String fullname, Set<StaffpostalcodeRange> staffpostalcodeRanges,
			Set<CustomerDrop> customerDrops,
			Set<Casefolder> casefoldersForPrimaryrevuser,
			Set<Casefolder> casefoldersForPrimarysalgsansvarlig,
			Set<StaffactorDrop> staffactorDrops, Set<Staffimage> staffimages,
			Set<Constructionproject> constructionprojects) {
		this.id = id;
		this.staffimage = staffimage;
		this.primuser = primuser;
		this.kompetance2 = kompetance2;
		this.impt = impt;
		this.deld = deld;
		this.education2 = education2;
		this.crd = crd;
		this.expu = expu;
		this.primlang = primlang;
		this.crt = crt;
		this.kompetance3 = kompetance3;
		this.email = email;
		this.modu = modu;
		this.cru = cru;
		this.impd = impd;
		this.private_ = private_;
		this.ext = ext;
		this.primdept = primdept;
		this.sidsteudd = sidsteudd;
		this.direct = direct;
		this.uname = uname;
		this.mailname = mailname;
		this.delu = delu;
		this.firstn = firstn;
		this.expt = expt;
		this.modd = modd;
		this.kompetance4 = kompetance4;
		this.education = education;
		this.leveluser = leveluser;
		this.mailpassword = mailpassword;
		this.lastn = lastn;
		this.modt = modt;
		this.voicel = voicel;
		this.title = title;
		this.fax = fax;
		this.passwordexpiredate = passwordexpiredate;
		this.useractive = useractive;
		this.imagefile = imagefile;
		this.kompetance1 = kompetance1;
		this.impu = impu;
		this.osuname = osuname;
		this.expd = expd;
		this.pword = pword;
		this.delt = delt;
		this.kompetance5 = kompetance5;
		this.mobile = mobile;
		this.primaryteam = primaryteam;
		this.mayupdatessh = mayupdatessh;
		this.mayeditactivities = mayeditactivities;
		this.primarylocation = primarylocation;
		this.beloeb = beloeb;
		this.beloebko = beloebko;
		this.fullname = fullname;
		this.staffpostalcodeRanges = staffpostalcodeRanges;
		this.customerDrops = customerDrops;
		this.casefoldersForPrimaryrevuser = casefoldersForPrimaryrevuser;
		this.casefoldersForPrimarysalgsansvarlig = casefoldersForPrimarysalgsansvarlig;
		this.staffactorDrops = staffactorDrops;
		this.staffimages = staffimages;
		this.constructionprojects = constructionprojects;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMSTAFFIMAGE")
	public Staffimage getStaffimage() {
		return this.staffimage;
	}

	public void setStaffimage(Staffimage staffimage) {
		this.staffimage = staffimage;
	}

	@Column(name = "PRIMUSER", length = 19)
	public String getPrimuser() {
		return this.primuser;
	}

	public void setPrimuser(String primuser) {
		this.primuser = primuser;
	}

	@Column(name = "KOMPETANCE2", length = 20)
	public String getKompetance2() {
		return this.kompetance2;
	}

	public void setKompetance2(String kompetance2) {
		this.kompetance2 = kompetance2;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "EDUCATION2", length = 20)
	public String getEducation2() {
		return this.education2;
	}

	public void setEducation2(String education2) {
		this.education2 = education2;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "PRIMLANG", length = 19)
	public String getPrimlang() {
		return this.primlang;
	}

	public void setPrimlang(String primlang) {
		this.primlang = primlang;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "KOMPETANCE3", length = 20)
	public String getKompetance3() {
		return this.kompetance3;
	}

	public void setKompetance3(String kompetance3) {
		this.kompetance3 = kompetance3;
	}

	@Column(name = "EMAIL", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Column(name = "PRIVATE", length = 20)
	public String getPrivate_() {
		return this.private_;
	}

	public void setPrivate_(String private_) {
		this.private_ = private_;
	}

	@Column(name = "EXT", length = 20)
	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	@Column(name = "PRIMDEPT", length = 19)
	public String getPrimdept() {
		return this.primdept;
	}

	public void setPrimdept(String primdept) {
		this.primdept = primdept;
	}

	@Column(name = "SIDSTEUDD", length = 20)
	public String getSidsteudd() {
		return this.sidsteudd;
	}

	public void setSidsteudd(String sidsteudd) {
		this.sidsteudd = sidsteudd;
	}

	@Column(name = "DIRECT", length = 20)
	public String getDirect() {
		return this.direct;
	}

	public void setDirect(String direct) {
		this.direct = direct;
	}

	@Column(name = "UNAME", length = 32)
	public String getUname() {
		return this.uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	@Column(name = "MAILNAME", length = 100)
	public String getMailname() {
		return this.mailname;
	}

	public void setMailname(String mailname) {
		this.mailname = mailname;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Column(name = "FIRSTN", length = 35)
	public String getFirstn() {
		return this.firstn;
	}

	public void setFirstn(String firstn) {
		this.firstn = firstn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "KOMPETANCE4", length = 20)
	public String getKompetance4() {
		return this.kompetance4;
	}

	public void setKompetance4(String kompetance4) {
		this.kompetance4 = kompetance4;
	}

	@Column(name = "EDUCATION", length = 20)
	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	@Column(name = "LEVELUSER", precision = 6, scale = 0)
	public Integer getLeveluser() {
		return this.leveluser;
	}

	public void setLeveluser(Integer leveluser) {
		this.leveluser = leveluser;
	}

	@Column(name = "MAILPASSWORD", length = 100)
	public String getMailpassword() {
		return this.mailpassword;
	}

	public void setMailpassword(String mailpassword) {
		this.mailpassword = mailpassword;
	}

	@Column(name = "LASTN", length = 35)
	public String getLastn() {
		return this.lastn;
	}

	public void setLastn(String lastn) {
		this.lastn = lastn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "VOICEL", length = 20)
	public String getVoicel() {
		return this.voicel;
	}

	public void setVoicel(String voicel) {
		this.voicel = voicel;
	}

	@Column(name = "TITLE", length = 35)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "FAX", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PASSWORDEXPIREDATE", length = 7)
	public Date getPasswordexpiredate() {
		return this.passwordexpiredate;
	}

	public void setPasswordexpiredate(Date passwordexpiredate) {
		this.passwordexpiredate = passwordexpiredate;
	}

	@Column(name = "USERACTIVE", length = 1)
	public Character getUseractive() {
		return this.useractive;
	}

	public void setUseractive(Character useractive) {
		this.useractive = useractive;
	}

	@Column(name = "IMAGEFILE", length = 12)
	public String getImagefile() {
		return this.imagefile;
	}

	public void setImagefile(String imagefile) {
		this.imagefile = imagefile;
	}

	@Column(name = "KOMPETANCE1", length = 20)
	public String getKompetance1() {
		return this.kompetance1;
	}

	public void setKompetance1(String kompetance1) {
		this.kompetance1 = kompetance1;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "OSUNAME", unique = true, length = 50)
	public String getOsuname() {
		return this.osuname;
	}

	public void setOsuname(String osuname) {
		this.osuname = osuname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "PWORD", length = 20)
	public String getPword() {
		return this.pword;
	}

	public void setPword(String pword) {
		this.pword = pword;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Column(name = "KOMPETANCE5", length = 20)
	public String getKompetance5() {
		return this.kompetance5;
	}

	public void setKompetance5(String kompetance5) {
		this.kompetance5 = kompetance5;
	}

	@Column(name = "MOBILE", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "PRIMARYTEAM", length = 19)
	public String getPrimaryteam() {
		return this.primaryteam;
	}

	public void setPrimaryteam(String primaryteam) {
		this.primaryteam = primaryteam;
	}

	@Column(name = "MAYUPDATESSH", length = 1)
	public Character getMayupdatessh() {
		return this.mayupdatessh;
	}

	public void setMayupdatessh(Character mayupdatessh) {
		this.mayupdatessh = mayupdatessh;
	}

	@Column(name = "MAYEDITACTIVITIES", length = 1)
	public Character getMayeditactivities() {
		return this.mayeditactivities;
	}

	public void setMayeditactivities(Character mayeditactivities) {
		this.mayeditactivities = mayeditactivities;
	}

	@Column(name = "PRIMARYLOCATION", length = 19)
	public String getPrimarylocation() {
		return this.primarylocation;
	}

	public void setPrimarylocation(String primarylocation) {
		this.primarylocation = primarylocation;
	}

	@Column(name = "BELOEB", precision = 12)
	public BigDecimal getBeloeb() {
		return this.beloeb;
	}

	public void setBeloeb(BigDecimal beloeb) {
		this.beloeb = beloeb;
	}

	@Column(name = "BELOEBKO", precision = 12)
	public BigDecimal getBeloebko() {
		return this.beloebko;
	}

	public void setBeloebko(BigDecimal beloebko) {
		this.beloebko = beloebko;
	}

	@Column(name = "FULLNAME", length = 100)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<StaffpostalcodeRange> getStaffpostalcodeRanges() {
		return this.staffpostalcodeRanges;
	}

	public void setStaffpostalcodeRanges(
			Set<StaffpostalcodeRange> staffpostalcodeRanges) {
		this.staffpostalcodeRanges = staffpostalcodeRanges;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<CustomerDrop> getCustomerDrops() {
		return this.customerDrops;
	}

	public void setCustomerDrops(Set<CustomerDrop> customerDrops) {
		this.customerDrops = customerDrops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staffByPrimaryrevuser")
	public Set<Casefolder> getCasefoldersForPrimaryrevuser() {
		return this.casefoldersForPrimaryrevuser;
	}

	public void setCasefoldersForPrimaryrevuser(
			Set<Casefolder> casefoldersForPrimaryrevuser) {
		this.casefoldersForPrimaryrevuser = casefoldersForPrimaryrevuser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staffByPrimarysalgsansvarlig")
	public Set<Casefolder> getCasefoldersForPrimarysalgsansvarlig() {
		return this.casefoldersForPrimarysalgsansvarlig;
	}

	public void setCasefoldersForPrimarysalgsansvarlig(
			Set<Casefolder> casefoldersForPrimarysalgsansvarlig) {
		this.casefoldersForPrimarysalgsansvarlig = casefoldersForPrimarysalgsansvarlig;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<StaffactorDrop> getStaffactorDrops() {
		return this.staffactorDrops;
	}

	public void setStaffactorDrops(Set<StaffactorDrop> staffactorDrops) {
		this.staffactorDrops = staffactorDrops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<Staffimage> getStaffimages() {
		return this.staffimages;
	}

	public void setStaffimages(Set<Staffimage> staffimages) {
		this.staffimages = staffimages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "staff")
	public Set<Constructionproject> getConstructionprojects() {
		return this.constructionprojects;
	}

	public void setConstructionprojects(
			Set<Constructionproject> constructionprojects) {
		this.constructionprojects = constructionprojects;
	}

}
