package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Supplierproductspec generated by hbm2java
 */
@Entity
@Table(name = "SUPPLIERPRODUCTSPEC", schema = "PCRM")
public class Supplierproductspec implements java.io.Serializable {

	private String id;
	private Supplier supplier;
	private Constructionproductspec constructionproductspec;
	private Date crd;
	private Date impt;
	private Date expt;
	private Date impd;
	private Date expd;
	private Date modt;
	private String cru;
	private Date delt;
	private Date modd;
	private String impu;
	private String expu;
	private Date deld;
	private String modu;
	private String delu;
	private Date crt;
	private String code;
	private String head;
	private String vare;
	private String leverandor;
	private BigDecimal prisprcolli;
	private String colli;
	private String primomktype;
	private Character aktiv;
	private String oldcode;
	private Date startDate;
	private Date endDate;
	private Set<Supplierrequestitem> supplierrequestitems = new HashSet<Supplierrequestitem>(
			0);

	public Supplierproductspec() {
	}

	public Supplierproductspec(String id) {
		this.id = id;
	}

	public Supplierproductspec(String id, Supplier supplier,
			Constructionproductspec constructionproductspec, Date crd,
			Date impt, Date expt, Date impd, Date expd, Date modt, String cru,
			Date delt, Date modd, String impu, String expu, Date deld,
			String modu, String delu, Date crt, String code, String head,
			String vare, String leverandor, BigDecimal prisprcolli,
			String colli, String primomktype, Character aktiv, String oldcode,
			Date startDate, Date endDate,
			Set<Supplierrequestitem> supplierrequestitems) {
		this.id = id;
		this.supplier = supplier;
		this.constructionproductspec = constructionproductspec;
		this.crd = crd;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.cru = cru;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.modu = modu;
		this.delu = delu;
		this.crt = crt;
		this.code = code;
		this.head = head;
		this.vare = vare;
		this.leverandor = leverandor;
		this.prisprcolli = prisprcolli;
		this.colli = colli;
		this.primomktype = primomktype;
		this.aktiv = aktiv;
		this.oldcode = oldcode;
		this.startDate = startDate;
		this.endDate = endDate;
		this.supplierrequestitems = supplierrequestitems;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMLEV")
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMARYVARE")
	public Constructionproductspec getConstructionproductspec() {
		return this.constructionproductspec;
	}

	public void setConstructionproductspec(
			Constructionproductspec constructionproductspec) {
		this.constructionproductspec = constructionproductspec;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "CODE", length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "HEAD")
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "VARE", length = 30)
	public String getVare() {
		return this.vare;
	}

	public void setVare(String vare) {
		this.vare = vare;
	}

	@Column(name = "LEVERANDOR", length = 30)
	public String getLeverandor() {
		return this.leverandor;
	}

	public void setLeverandor(String leverandor) {
		this.leverandor = leverandor;
	}

	@Column(name = "PRISPRCOLLI", precision = 22, scale = 0)
	public BigDecimal getPrisprcolli() {
		return this.prisprcolli;
	}

	public void setPrisprcolli(BigDecimal prisprcolli) {
		this.prisprcolli = prisprcolli;
	}

	@Column(name = "COLLI")
	public String getColli() {
		return this.colli;
	}

	public void setColli(String colli) {
		this.colli = colli;
	}

	@Column(name = "PRIMOMKTYPE", length = 19)
	public String getPrimomktype() {
		return this.primomktype;
	}

	public void setPrimomktype(String primomktype) {
		this.primomktype = primomktype;
	}

	@Column(name = "AKTIV", length = 1)
	public Character getAktiv() {
		return this.aktiv;
	}

	public void setAktiv(Character aktiv) {
		this.aktiv = aktiv;
	}

	@Column(name = "OLDCODE", length = 15)
	public String getOldcode() {
		return this.oldcode;
	}

	public void setOldcode(String oldcode) {
		this.oldcode = oldcode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "supplierproductspec")
	public Set<Supplierrequestitem> getSupplierrequestitems() {
		return this.supplierrequestitems;
	}

	public void setSupplierrequestitems(
			Set<Supplierrequestitem> supplierrequestitems) {
		this.supplierrequestitems = supplierrequestitems;
	}

}
