package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TabFutureContractClsoffr generated by hbm2java
 */
@Entity
@Table(name = "TAB_FUTURE_CONTRACT_CLSOFFR", schema = "PCRM", uniqueConstraints = @UniqueConstraint(columnNames = "CONTRACTID"))
public class TabFutureContractClsoffr implements java.io.Serializable {

	private TabFutureContractClsoffrId id;

	public TabFutureContractClsoffr() {
	}

	public TabFutureContractClsoffr(TabFutureContractClsoffrId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "contractid", column = @Column(name = "CONTRACTID", unique = true, length = 19)),
			@AttributeOverride(name = "primclosingtilbkontr", column = @Column(name = "PRIMCLOSINGTILBKONTR", length = 19)),
			@AttributeOverride(name = "opsdato", column = @Column(name = "OPSDATO", length = 7)),
			@AttributeOverride(name = "uiInsertdate", column = @Column(name = "UI_INSERTDATE", length = 7)),
			@AttributeOverride(name = "dbProcessedDate", column = @Column(name = "DB_PROCESSED_DATE", length = 7)),
			@AttributeOverride(name = "dbProcessStatus", column = @Column(name = "DB_PROCESS_STATUS", length = 1)) })
	public TabFutureContractClsoffrId getId() {
		return this.id;
	}

	public void setId(TabFutureContractClsoffrId id) {
		this.id = id;
	}

}
