package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TemplateStore generated by hbm2java
 */
@Entity
@Table(name = "TEMPLATE_STORE", schema = "PCRM")
public class TemplateStore implements java.io.Serializable {

	private String templateId;
	private String templateName;
	private String templateType;
	private String fileName;
	private String fileType;
	private Blob content;
	private Set<CrTemplateCasetype> crTemplateCasetypes = new HashSet<CrTemplateCasetype>(
			0);

	public TemplateStore() {
	}

	public TemplateStore(String templateId) {
		this.templateId = templateId;
	}

	public TemplateStore(String templateId, String templateName,
			String templateType, String fileName, String fileType,
			Blob content, Set<CrTemplateCasetype> crTemplateCasetypes) {
		this.templateId = templateId;
		this.templateName = templateName;
		this.templateType = templateType;
		this.fileName = fileName;
		this.fileType = fileType;
		this.content = content;
		this.crTemplateCasetypes = crTemplateCasetypes;
	}

	@Id
	@Column(name = "TEMPLATE_ID", unique = true, nullable = false, length = 19)
	public String getTemplateId() {
		return this.templateId;
	}

	public void setTemplateId(String templateId) {
		this.templateId = templateId;
	}

	@Column(name = "TEMPLATE_NAME", length = 50)
	public String getTemplateName() {
		return this.templateName;
	}

	public void setTemplateName(String templateName) {
		this.templateName = templateName;
	}

	@Column(name = "TEMPLATE_TYPE", length = 50)
	public String getTemplateType() {
		return this.templateType;
	}

	public void setTemplateType(String templateType) {
		this.templateType = templateType;
	}

	@Column(name = "FILE_NAME")
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "FILE_TYPE", length = 10)
	public String getFileType() {
		return this.fileType;
	}

	public void setFileType(String fileType) {
		this.fileType = fileType;
	}

	@Column(name = "CONTENT")
	public Blob getContent() {
		return this.content;
	}

	public void setContent(Blob content) {
		this.content = content;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "templateStore")
	public Set<CrTemplateCasetype> getCrTemplateCasetypes() {
		return this.crTemplateCasetypes;
	}

	public void setCrTemplateCasetypes(
			Set<CrTemplateCasetype> crTemplateCasetypes) {
		this.crTemplateCasetypes = crTemplateCasetypes;
	}

}
