package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TransferredCableunitsV generated by hbm2java
 */
@Entity
@Table(name = "TRANSFERRED_CABLEUNITS_V", schema = "PCRM")
public class TransferredCableunitsV implements java.io.Serializable {

	private TransferredCableunitsVId id;

	public TransferredCableunitsV() {
	}

	public TransferredCableunitsV(TransferredCableunitsVId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "anlAnlaegsnr", column = @Column(name = "ANL_ANLAEGSNR", length = 10)),
			@AttributeOverride(name = "kissCode", column = @Column(name = "KISS_CODE", length = 50)),
			@AttributeOverride(name = "kissDescription", column = @Column(name = "KISS_DESCRIPTION", length = 50)),
			@AttributeOverride(name = "casperCode", column = @Column(name = "CASPER_CODE", length = 50)),
			@AttributeOverride(name = "casperDescription", column = @Column(name = "CASPER_DESCRIPTION", length = 50)) })
	public TransferredCableunitsVId getId() {
		return this.id;
	}

	public void setId(TransferredCableunitsVId id) {
		this.id = id;
	}

}
