package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VFdbGeonodes generated by hbm2java
 */
@Entity
@Table(name = "V_FDB_GEONODES", schema = "PCRM")
public class VFdbGeonodes implements java.io.Serializable {

	private VFdbGeonodesId id;

	public VFdbGeonodes() {
	}

	public VFdbGeonodes(VFdbGeonodesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "municipalitycode", column = @Column(name = "MUNICIPALITYCODE", precision = 3, scale = 0)),
			@AttributeOverride(name = "municipalityname", column = @Column(name = "MUNICIPALITYNAME", length = 50)),
			@AttributeOverride(name = "regnode", column = @Column(name = "REGNODE", precision = 22, scale = 0)) })
	public VFdbGeonodesId getId() {
		return this.id;
	}

	public void setId(VFdbGeonodesId id) {
		this.id = id;
	}

}
