package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VFdbCableunitprogsupply generated by hbm2java
 */
@Entity
@Table(name = "V_FDB_CABLEUNITPROGSUPPLY", schema = "PCRM")
public class VFdbCableunitprogsupply implements java.io.Serializable {

	private VFdbCableunitprogsupplyId id;

	public VFdbCableunitprogsupply() {
	}

	public VFdbCableunitprogsupply(VFdbCableunitprogsupplyId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nodeId", column = @Column(name = "NODE_ID", nullable = false, precision = 9, scale = 0)),
			@AttributeOverride(name = "hfnr", column = @Column(name = "HFNR", length = 11)),
			@AttributeOverride(name = "anlaegsnr", column = @Column(name = "ANLAEGSNR", length = 10)),
			@AttributeOverride(name = "startFrekvens", column = @Column(name = "START_FREKVENS", precision = 22, scale = 0)),
			@AttributeOverride(name = "slutFrekvens", column = @Column(name = "SLUT_FREKVENS", precision = 22, scale = 0)),
			@AttributeOverride(name = "pakkeGruppering", column = @Column(name = "PAKKE_GRUPPERING", length = 50)),
			@AttributeOverride(name = "pakkenr", column = @Column(name = "PAKKENR", nullable = false, precision = 7, scale = 0)),
			@AttributeOverride(name = "pakkenavn", column = @Column(name = "PAKKENAVN")),
			@AttributeOverride(name = "leveringstype", column = @Column(name = "LEVERINGSTYPE", length = 8)),
			@AttributeOverride(name = "proveprogram", column = @Column(name = "PROVEPROGRAM", length = 1)),
			@AttributeOverride(name = "area", column = @Column(name = "AREA", length = 6)),
			@AttributeOverride(name = "band", column = @Column(name = "BAND", length = 6)),
			@AttributeOverride(name = "kanal", column = @Column(name = "KANAL", length = 10)),
			@AttributeOverride(name = "frekvens", column = @Column(name = "FREKVENS", precision = 22, scale = 0)),
			@AttributeOverride(name = "gruppering", column = @Column(name = "GRUPPERING", length = 50)),
			@AttributeOverride(name = "varenummer", column = @Column(name = "VARENUMMER", precision = 7, scale = 0)),
			@AttributeOverride(name = "varenavn", column = @Column(name = "VARENAVN")),
			@AttributeOverride(name = "overlap", column = @Column(name = "OVERLAP", length = 3)),
			@AttributeOverride(name = "validFrom", column = @Column(name = "VALID_FROM", length = 7)),
			@AttributeOverride(name = "validTo", column = @Column(name = "VALID_TO", length = 7)),
			@AttributeOverride(name = "parentChKeySeq", column = @Column(name = "PARENT_CH_KEY_SEQ", precision = 22, scale = 0)),
			@AttributeOverride(name = "vendor", column = @Column(name = "VENDOR", length = 20)) })
	public VFdbCableunitprogsupplyId getId() {
		return this.id;
	}

	public void setId(VFdbCableunitprogsupplyId id) {
		this.id = id;
	}

}
