package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VFdbproducts generated by hbm2java
 */
@Entity
@Table(name = "V_FDBPRODUCTS", schema = "PCRM")
public class VFdbproducts implements java.io.Serializable {

	private VFdbproductsId id;

	public VFdbproducts() {
	}

	public VFdbproducts(VFdbproductsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, length = 19)),
			@AttributeOverride(name = "sourcesystem", column = @Column(name = "SOURCESYSTEM", length = 15)),
			@AttributeOverride(name = "crd", column = @Column(name = "CRD", length = 7)),
			@AttributeOverride(name = "cru", column = @Column(name = "CRU", length = 19)),
			@AttributeOverride(name = "modd", column = @Column(name = "MODD", length = 7)),
			@AttributeOverride(name = "modu", column = @Column(name = "MODU", length = 19)),
			@AttributeOverride(name = "deld", column = @Column(name = "DELD", length = 7)),
			@AttributeOverride(name = "delu", column = @Column(name = "DELU", length = 19)),
			@AttributeOverride(name = "impd", column = @Column(name = "IMPD", length = 7)),
			@AttributeOverride(name = "impu", column = @Column(name = "IMPU", length = 19)),
			@AttributeOverride(name = "expd", column = @Column(name = "EXPD", length = 7)),
			@AttributeOverride(name = "expu", column = @Column(name = "EXPU", length = 19)),
			@AttributeOverride(name = "code", column = @Column(name = "CODE", length = 50)),
			@AttributeOverride(name = "head", column = @Column(name = "HEAD")),
			@AttributeOverride(name = "groupCode", column = @Column(name = "GROUP_CODE", length = 50)),
			@AttributeOverride(name = "groupHead", column = @Column(name = "GROUP_HEAD")),
			@AttributeOverride(name = "sourcesystemId", column = @Column(name = "SOURCESYSTEM_ID", length = 19)),
			@AttributeOverride(name = "sourcesystemCrd", column = @Column(name = "SOURCESYSTEM_CRD", length = 7)),
			@AttributeOverride(name = "sourcesystemModd", column = @Column(name = "SOURCESYSTEM_MODD", length = 7)),
			@AttributeOverride(name = "productcode", column = @Column(name = "PRODUCTCODE", length = 50)),
			@AttributeOverride(name = "productname", column = @Column(name = "PRODUCTNAME")),
			@AttributeOverride(name = "productabbreviation", column = @Column(name = "PRODUCTABBREVIATION", length = 50)),
			@AttributeOverride(name = "basicproductcode", column = @Column(name = "BASICPRODUCTCODE", length = 50)),
			@AttributeOverride(name = "deliverycontract", column = @Column(name = "DELIVERYCONTRACT", length = 5)),
			@AttributeOverride(name = "salesstart", column = @Column(name = "SALESSTART", length = 7)),
			@AttributeOverride(name = "salesexpiry", column = @Column(name = "SALESEXPIRY", length = 7)),
			@AttributeOverride(name = "businessspherecode", column = @Column(name = "BUSINESSSPHERECODE", length = 15)),
			@AttributeOverride(name = "productlinecode", column = @Column(name = "PRODUCTLINECODE", length = 15)),
			@AttributeOverride(name = "productline", column = @Column(name = "PRODUCTLINE")),
			@AttributeOverride(name = "productgroupcode", column = @Column(name = "PRODUCTGROUPCODE", length = 15)),
			@AttributeOverride(name = "productgroup", column = @Column(name = "PRODUCTGROUP")),
			@AttributeOverride(name = "producttypecode", column = @Column(name = "PRODUCTTYPECODE", length = 15)),
			@AttributeOverride(name = "incomeclasscode", column = @Column(name = "INCOMECLASSCODE", length = 15)),
			@AttributeOverride(name = "incomeclass", column = @Column(name = "INCOMECLASS")),
			@AttributeOverride(name = "markedspris", column = @Column(name = "MARKEDSPRIS", precision = 10)),
			@AttributeOverride(name = "minimumSalesprice", column = @Column(name = "MINIMUM_SALESPRICE", precision = 10)),
			@AttributeOverride(name = "customerPrice", column = @Column(name = "CUSTOMER_PRICE", precision = 10)),
			@AttributeOverride(name = "primbusinesssphere", column = @Column(name = "PRIMBUSINESSSPHERE", length = 15)),
			@AttributeOverride(name = "logtrace", column = @Column(name = "LOGTRACE", length = 19)),
			@AttributeOverride(name = "productId", column = @Column(name = "PRODUCT_ID", length = 40)),
			@AttributeOverride(name = "shortName", column = @Column(name = "SHORT_NAME", length = 32)),
			@AttributeOverride(name = "overlap", column = @Column(name = "OVERLAP", length = 3)),
			@AttributeOverride(name = "productGroup", column = @Column(name = "PRODUCT_GROUP", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "groupName", column = @Column(name = "GROUP_NAME", length = 50)) })
	public VFdbproductsId getId() {
		return this.id;
	}

	public void setId(VFdbproductsId id) {
		this.id = id;
	}

}
