package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WAnlbem generated by hbm2java
 */
@Entity
@Table(name = "W_ANLBEM", schema = "PCRM")
public class WAnlbem implements java.io.Serializable {

	private WAnlbemId id;

	public WAnlbem() {
	}

	public WAnlbem(WAnlbemId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "WPk", column = @Column(name = "W_PK", length = 19)),
			@AttributeOverride(name = "abemAnlxgsnr", column = @Column(name = "ABEM_ANLXGSNR", length = 10)),
			@AttributeOverride(name = "abemLbnr", column = @Column(name = "ABEM_LBNR", precision = 4, scale = 0)),
			@AttributeOverride(name = "abemType", column = @Column(name = "ABEM_TYPE", length = 20)),
			@AttributeOverride(name = "abemBemtekst", column = @Column(name = "ABEM_BEMTEKST", length = 2000)),
			@AttributeOverride(name = "abemCrd", column = @Column(name = "ABEM_CRD", length = 7)),
			@AttributeOverride(name = "abemModd", column = @Column(name = "ABEM_MODD", length = 7)) })
	public WAnlbemId getId() {
		return this.id;
	}

	public void setId(WAnlbemId id) {
		this.id = id;
	}

}
