package com.tdc.persistence.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WSalgskoncept generated by hbm2java
 */
@Entity
@Table(name = "W_SALGSKONCEPT", schema = "PCRM")
public class WSalgskoncept implements java.io.Serializable {

	private WSalgskonceptId id;

	public WSalgskoncept() {
	}

	public WSalgskoncept(WSalgskonceptId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "salgskonceptNavn", column = @Column(name = "SALGSKONCEPT_NAVN", length = 50)),
			@AttributeOverride(name = "infoKategoriKey", column = @Column(name = "INFO_KATEGORI_KEY", nullable = false, length = 19)),
			@AttributeOverride(name = "infoKategori", column = @Column(name = "INFO_KATEGORI")),
			@AttributeOverride(name = "salgskonceptInfoKey", column = @Column(name = "SALGSKONCEPT_INFO_KEY", nullable = false, length = 19)),
			@AttributeOverride(name = "salgskonceptInfo", column = @Column(name = "SALGSKONCEPT_INFO", length = 40)) })
	public WSalgskonceptId getId() {
		return this.id;
	}

	public void setId(WSalgskonceptId id) {
		this.id = id;
	}

}
