package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AccessOrigin generated by hbm2java
 */
@Entity
@Table(name = "ACCESS_ORIGIN", schema = "AMS")
public class AccessOrigin implements java.io.Serializable {

	private BigDecimal code;
	private boolean bbrProperty;
	private boolean bbrBuilding;
	private boolean krr;
	private boolean kmsBak;
	private boolean teleatlas;
	private boolean osak;
	private boolean krrNoLetter;
	private boolean interpolated;
	private boolean extrapolated;
	private boolean ficticious;
	private boolean bbrUnit;
	private boolean bbrChangeproperty;
	private boolean bbrChangebuilding;
	private boolean bbrChangeunit;
	private boolean esrProperty;
	private boolean osakUnit;
	private boolean dgsMissing;
	private boolean dgsModified;
	private boolean cpr;
	private boolean robinson;
	private Set<Addresses> addresseses = new HashSet<Addresses>(0);

	public AccessOrigin() {
	}

	public AccessOrigin(BigDecimal code, boolean bbrProperty,
			boolean bbrBuilding, boolean krr, boolean kmsBak,
			boolean teleatlas, boolean osak, boolean krrNoLetter,
			boolean interpolated, boolean extrapolated, boolean ficticious,
			boolean bbrUnit, boolean bbrChangeproperty,
			boolean bbrChangebuilding, boolean bbrChangeunit,
			boolean esrProperty, boolean osakUnit, boolean dgsMissing,
			boolean dgsModified, boolean cpr, boolean robinson) {
		this.code = code;
		this.bbrProperty = bbrProperty;
		this.bbrBuilding = bbrBuilding;
		this.krr = krr;
		this.kmsBak = kmsBak;
		this.teleatlas = teleatlas;
		this.osak = osak;
		this.krrNoLetter = krrNoLetter;
		this.interpolated = interpolated;
		this.extrapolated = extrapolated;
		this.ficticious = ficticious;
		this.bbrUnit = bbrUnit;
		this.bbrChangeproperty = bbrChangeproperty;
		this.bbrChangebuilding = bbrChangebuilding;
		this.bbrChangeunit = bbrChangeunit;
		this.esrProperty = esrProperty;
		this.osakUnit = osakUnit;
		this.dgsMissing = dgsMissing;
		this.dgsModified = dgsModified;
		this.cpr = cpr;
		this.robinson = robinson;
	}

	public AccessOrigin(BigDecimal code, boolean bbrProperty,
			boolean bbrBuilding, boolean krr, boolean kmsBak,
			boolean teleatlas, boolean osak, boolean krrNoLetter,
			boolean interpolated, boolean extrapolated, boolean ficticious,
			boolean bbrUnit, boolean bbrChangeproperty,
			boolean bbrChangebuilding, boolean bbrChangeunit,
			boolean esrProperty, boolean osakUnit, boolean dgsMissing,
			boolean dgsModified, boolean cpr, boolean robinson,
			Set<Addresses> addresseses) {
		this.code = code;
		this.bbrProperty = bbrProperty;
		this.bbrBuilding = bbrBuilding;
		this.krr = krr;
		this.kmsBak = kmsBak;
		this.teleatlas = teleatlas;
		this.osak = osak;
		this.krrNoLetter = krrNoLetter;
		this.interpolated = interpolated;
		this.extrapolated = extrapolated;
		this.ficticious = ficticious;
		this.bbrUnit = bbrUnit;
		this.bbrChangeproperty = bbrChangeproperty;
		this.bbrChangebuilding = bbrChangebuilding;
		this.bbrChangeunit = bbrChangeunit;
		this.esrProperty = esrProperty;
		this.osakUnit = osakUnit;
		this.dgsMissing = dgsMissing;
		this.dgsModified = dgsModified;
		this.cpr = cpr;
		this.robinson = robinson;
		this.addresseses = addresseses;
	}

	@Id
	@Column(name = "CODE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCode() {
		return this.code;
	}

	public void setCode(BigDecimal code) {
		this.code = code;
	}

	@Column(name = "BBR_PROPERTY", nullable = false, precision = 1, scale = 0)
	public boolean isBbrProperty() {
		return this.bbrProperty;
	}

	public void setBbrProperty(boolean bbrProperty) {
		this.bbrProperty = bbrProperty;
	}

	@Column(name = "BBR_BUILDING", nullable = false, precision = 1, scale = 0)
	public boolean isBbrBuilding() {
		return this.bbrBuilding;
	}

	public void setBbrBuilding(boolean bbrBuilding) {
		this.bbrBuilding = bbrBuilding;
	}

	@Column(name = "KRR", nullable = false, precision = 1, scale = 0)
	public boolean isKrr() {
		return this.krr;
	}

	public void setKrr(boolean krr) {
		this.krr = krr;
	}

	@Column(name = "KMS_BAK", nullable = false, precision = 1, scale = 0)
	public boolean isKmsBak() {
		return this.kmsBak;
	}

	public void setKmsBak(boolean kmsBak) {
		this.kmsBak = kmsBak;
	}

	@Column(name = "TELEATLAS", nullable = false, precision = 1, scale = 0)
	public boolean isTeleatlas() {
		return this.teleatlas;
	}

	public void setTeleatlas(boolean teleatlas) {
		this.teleatlas = teleatlas;
	}

	@Column(name = "OSAK", nullable = false, precision = 1, scale = 0)
	public boolean isOsak() {
		return this.osak;
	}

	public void setOsak(boolean osak) {
		this.osak = osak;
	}

	@Column(name = "KRR_NO_LETTER", nullable = false, precision = 1, scale = 0)
	public boolean isKrrNoLetter() {
		return this.krrNoLetter;
	}

	public void setKrrNoLetter(boolean krrNoLetter) {
		this.krrNoLetter = krrNoLetter;
	}

	@Column(name = "INTERPOLATED", nullable = false, precision = 1, scale = 0)
	public boolean isInterpolated() {
		return this.interpolated;
	}

	public void setInterpolated(boolean interpolated) {
		this.interpolated = interpolated;
	}

	@Column(name = "EXTRAPOLATED", nullable = false, precision = 1, scale = 0)
	public boolean isExtrapolated() {
		return this.extrapolated;
	}

	public void setExtrapolated(boolean extrapolated) {
		this.extrapolated = extrapolated;
	}

	@Column(name = "FICTICIOUS", nullable = false, precision = 1, scale = 0)
	public boolean isFicticious() {
		return this.ficticious;
	}

	public void setFicticious(boolean ficticious) {
		this.ficticious = ficticious;
	}

	@Column(name = "BBR_UNIT", nullable = false, precision = 1, scale = 0)
	public boolean isBbrUnit() {
		return this.bbrUnit;
	}

	public void setBbrUnit(boolean bbrUnit) {
		this.bbrUnit = bbrUnit;
	}

	@Column(name = "BBR_CHANGEPROPERTY", nullable = false, precision = 1, scale = 0)
	public boolean isBbrChangeproperty() {
		return this.bbrChangeproperty;
	}

	public void setBbrChangeproperty(boolean bbrChangeproperty) {
		this.bbrChangeproperty = bbrChangeproperty;
	}

	@Column(name = "BBR_CHANGEBUILDING", nullable = false, precision = 1, scale = 0)
	public boolean isBbrChangebuilding() {
		return this.bbrChangebuilding;
	}

	public void setBbrChangebuilding(boolean bbrChangebuilding) {
		this.bbrChangebuilding = bbrChangebuilding;
	}

	@Column(name = "BBR_CHANGEUNIT", nullable = false, precision = 1, scale = 0)
	public boolean isBbrChangeunit() {
		return this.bbrChangeunit;
	}

	public void setBbrChangeunit(boolean bbrChangeunit) {
		this.bbrChangeunit = bbrChangeunit;
	}

	@Column(name = "ESR_PROPERTY", nullable = false, precision = 1, scale = 0)
	public boolean isEsrProperty() {
		return this.esrProperty;
	}

	public void setEsrProperty(boolean esrProperty) {
		this.esrProperty = esrProperty;
	}

	@Column(name = "OSAK_UNIT", nullable = false, precision = 1, scale = 0)
	public boolean isOsakUnit() {
		return this.osakUnit;
	}

	public void setOsakUnit(boolean osakUnit) {
		this.osakUnit = osakUnit;
	}

	@Column(name = "DGS_MISSING", nullable = false, precision = 1, scale = 0)
	public boolean isDgsMissing() {
		return this.dgsMissing;
	}

	public void setDgsMissing(boolean dgsMissing) {
		this.dgsMissing = dgsMissing;
	}

	@Column(name = "DGS_MODIFIED", nullable = false, precision = 1, scale = 0)
	public boolean isDgsModified() {
		return this.dgsModified;
	}

	public void setDgsModified(boolean dgsModified) {
		this.dgsModified = dgsModified;
	}

	@Column(name = "CPR", nullable = false, precision = 1, scale = 0)
	public boolean isCpr() {
		return this.cpr;
	}

	public void setCpr(boolean cpr) {
		this.cpr = cpr;
	}

	@Column(name = "ROBINSON", nullable = false, precision = 1, scale = 0)
	public boolean isRobinson() {
		return this.robinson;
	}

	public void setRobinson(boolean robinson) {
		this.robinson = robinson;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accessOrigin")
	public Set<Addresses> getAddresseses() {
		return this.addresseses;
	}

	public void setAddresseses(Set<Addresses> addresseses) {
		this.addresseses = addresseses;
	}

}
