package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AddressesNotused generated by hbm2java
 */
@Entity
@Table(name = "ADDRESSES_NOTUSED", schema = "AMS")
public class AddressesNotused implements java.io.Serializable {

	private AddressesNotusedId id;

	public AddressesNotused() {
	}

	public AddressesNotused(AddressesNotusedId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "addressId", column = @Column(name = "ADDRESS_ID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "startdate", column = @Column(name = "STARTDATE", nullable = false, length = 7)),
			@AttributeOverride(name = "streetId", column = @Column(name = "STREET_ID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "streetsStartdate", column = @Column(name = "STREETS_STARTDATE", nullable = false, length = 7)),
			@AttributeOverride(name = "houseno", column = @Column(name = "HOUSENO", length = 5)),
			@AttributeOverride(name = "floor", column = @Column(name = "FLOOR", length = 2)),
			@AttributeOverride(name = "door", column = @Column(name = "DOOR", length = 6)),
			@AttributeOverride(name = "placename", column = @Column(name = "PLACENAME", length = 34)),
			@AttributeOverride(name = "postalcode", column = @Column(name = "POSTALCODE", length = 4)),
			@AttributeOverride(name = "accessClass", column = @Column(name = "ACCESS_CLASS", nullable = false, precision = 1, scale = 0)),
			@AttributeOverride(name = "userAccessClass", column = @Column(name = "USER_ACCESS_CLASS", precision = 1, scale = 0)),
			@AttributeOverride(name = "propertyidBbr", column = @Column(name = "PROPERTYID_BBR", precision = 10, scale = 0)),
			@AttributeOverride(name = "propertyidEsr", column = @Column(name = "PROPERTYID_ESR", precision = 10, scale = 0)),
			@AttributeOverride(name = "zapKvhX", column = @Column(name = "ZAP_KVH_X", length = 17)),
			@AttributeOverride(name = "accessOriginCode", column = @Column(name = "ACCESS_ORIGIN_CODE", precision = 10, scale = 0)),
			@AttributeOverride(name = "unitOriginCode", column = @Column(name = "UNIT_ORIGIN_CODE", precision = 10, scale = 0)),
			@AttributeOverride(name = "bbrUse", column = @Column(name = "BBR_USE", precision = 5, scale = 0)),
			@AttributeOverride(name = "coordQ", column = @Column(name = "COORD_Q", precision = 5, scale = 0)),
			@AttributeOverride(name = "coordX", column = @Column(name = "COORD_X", precision = 10, scale = 0)),
			@AttributeOverride(name = "coordY", column = @Column(name = "COORD_Y", precision = 10, scale = 0)),
			@AttributeOverride(name = "latitude", column = @Column(name = "LATITUDE", precision = 21, scale = 18)),
			@AttributeOverride(name = "longitude", column = @Column(name = "LONGITUDE", precision = 21, scale = 18)),
			@AttributeOverride(name = "source", column = @Column(name = "SOURCE", nullable = false, length = 6)),
			@AttributeOverride(name = "zapFictive", column = @Column(name = "ZAP_FICTIVE", precision = 1, scale = 0)),
			@AttributeOverride(name = "enddate", column = @Column(name = "ENDDATE", length = 7)),
			@AttributeOverride(name = "initials", column = @Column(name = "INITIALS", nullable = false, length = 10)),
			@AttributeOverride(name = "transferredToAddressId", column = @Column(name = "TRANSFERRED_TO_ADDRESS_ID", precision = 10, scale = 0)),
			@AttributeOverride(name = "createddate", column = @Column(name = "CREATEDDATE", nullable = false, length = 7)) })
	public AddressesNotusedId getId() {
		return this.id;
	}

	public void setId(AddressesNotusedId id) {
		this.id = id;
	}

}
