package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AddressesLog generated by hbm2java
 */
@Entity
@Table(name = "ADDRESSES_LOG", schema = "AMS")
public class AddressesLog implements java.io.Serializable {

	private AddressesLogId id;

	public AddressesLog() {
	}

	public AddressesLog(AddressesLogId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "addressId", column = @Column(name = "ADDRESS_ID", precision = 10, scale = 0)),
			@AttributeOverride(name = "oldaddressId", column = @Column(name = "OLDADDRESS_ID", precision = 10, scale = 0)),
			@AttributeOverride(name = "errortext", column = @Column(name = "ERRORTEXT", length = 400)) })
	public AddressesLogId getId() {
		return this.id;
	}

	public void setId(AddressesLogId id) {
		this.id = id;
	}

}
