package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AmsUpdateLog generated by hbm2java
 */
@Entity
@Table(name = "AMS_UPDATE_LOG", schema = "AMS")
public class AmsUpdateLog implements java.io.Serializable {

	private AmsUpdateLogId id;

	public AmsUpdateLog() {
	}

	public AmsUpdateLog(AmsUpdateLogId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "amsid", column = @Column(name = "AMSID", precision = 10, scale = 0)),
			@AttributeOverride(name = "casperid", column = @Column(name = "CASPERID", length = 10)),
			@AttributeOverride(name = "rowidentifier", column = @Column(name = "ROWIDENTIFIER", length = 20)),
			@AttributeOverride(name = "fejl", column = @Column(name = "FEJL", length = 200)),
			@AttributeOverride(name = "createddate", column = @Column(name = "CREATEDDATE", length = 7)) })
	public AmsUpdateLogId getId() {
		return this.id;
	}

	public void setId(AmsUpdateLogId id) {
		this.id = id;
	}

}
