package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AmsZapUpdateLog generated by hbm2java
 */
@Entity
@Table(name = "AMS_ZAP_UPDATE_LOG", schema = "AMS")
public class AmsZapUpdateLog implements java.io.Serializable {

	private AmsZapUpdateLogId id;

	public AmsZapUpdateLog() {
	}

	public AmsZapUpdateLog(AmsZapUpdateLogId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "zapKey", column = @Column(name = "ZAP_KEY", length = 17)),
			@AttributeOverride(name = "amsSystemKeyCurrent", column = @Column(name = "AMS_SYSTEM_KEY_CURRENT", length = 100)),
			@AttributeOverride(name = "casperSystemKeyBefore", column = @Column(name = "CASPER_SYSTEM_KEY_BEFORE", length = 100)),
			@AttributeOverride(name = "casperSystemKeyAfter", column = @Column(name = "CASPER_SYSTEM_KEY_AFTER", length = 100)),
			@AttributeOverride(name = "postalDistrictCodeBefore", column = @Column(name = "POSTAL_DISTRICT_CODE_BEFORE", length = 200)),
			@AttributeOverride(name = "postalDistrictCodeAfter", column = @Column(name = "POSTAL_DISTRICT_CODE_AFTER", length = 200)),
			@AttributeOverride(name = "streetNameBefore", column = @Column(name = "STREET_NAME_BEFORE", length = 200)),
			@AttributeOverride(name = "streetNameAfter", column = @Column(name = "STREET_NAME_AFTER", length = 200)),
			@AttributeOverride(name = "placeNameBefore", column = @Column(name = "PLACE_NAME_BEFORE", length = 200)),
			@AttributeOverride(name = "placeNameAfter", column = @Column(name = "PLACE_NAME_AFTER", length = 200)),
			@AttributeOverride(name = "additionalInfo", column = @Column(name = "ADDITIONAL_INFO", length = 2000)) })
	public AmsZapUpdateLogId getId() {
		return this.id;
	}

	public void setId(AmsZapUpdateLogId id) {
		this.id = id;
	}

}
