package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Errorcodes generated by hbm2java
 */
@Entity
@Table(name = "ERRORCODES", schema = "AMS")
public class Errorcodes implements java.io.Serializable {

	private int errorcode;
	private String errortext;
	private Set<Log> logs = new HashSet<Log>(0);

	public Errorcodes() {
	}

	public Errorcodes(int errorcode) {
		this.errorcode = errorcode;
	}

	public Errorcodes(int errorcode, String errortext, Set<Log> logs) {
		this.errorcode = errorcode;
		this.errortext = errortext;
		this.logs = logs;
	}

	@Id
	@Column(name = "ERRORCODE", unique = true, nullable = false, precision = 6, scale = 0)
	public int getErrorcode() {
		return this.errorcode;
	}

	public void setErrorcode(int errorcode) {
		this.errorcode = errorcode;
	}

	@Column(name = "ERRORTEXT", length = 100)
	public String getErrortext() {
		return this.errortext;
	}

	public void setErrortext(String errortext) {
		this.errortext = errortext;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "errorcodes")
	public Set<Log> getLogs() {
		return this.logs;
	}

	public void setLogs(Set<Log> logs) {
		this.logs = logs;
	}

}
