package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Log generated by hbm2java
 */
@Entity
@Table(name = "LOG", schema = "AMS", uniqueConstraints = @UniqueConstraint(columnNames = {
		"SESSIONNO", "LINENO" }))
public class Log implements java.io.Serializable {

	private LogId id;
	private Errorcodes errorcodes;

	public Log() {
	}

	public Log(LogId id, Errorcodes errorcodes) {
		this.id = id;
		this.errorcodes = errorcodes;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "sessionno", column = @Column(name = "SESSIONNO", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "lineno", column = @Column(name = "LINENO", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "time", column = @Column(name = "TIME", length = 7)),
			@AttributeOverride(name = "proc", column = @Column(name = "PROC", length = 61)),
			@AttributeOverride(name = "text", column = @Column(name = "TEXT", length = 552)),
			@AttributeOverride(name = "codeN", column = @Column(name = "CODE_N", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "codeV", column = @Column(name = "CODE_V", length = 20)),
			@AttributeOverride(name = "systemCode", column = @Column(name = "SYSTEM_CODE", length = 20)) })
	public LogId getId() {
		return this.id;
	}

	public void setId(LogId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_N", nullable = false, insertable = false, updatable = false)
	public Errorcodes getErrorcodes() {
		return this.errorcodes;
	}

	public void setErrorcodes(Errorcodes errorcodes) {
		this.errorcodes = errorcodes;
	}

}
