package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Municipalities generated by hbm2java
 */
@Entity
@Table(name = "MUNICIPALITIES", schema = "AMS")
public class Municipalities implements java.io.Serializable {

	private short municipalitycode;
	private AccessClasses accessClasses;
	private Regions regions;
	private String municipalityname;
	private Set<Streets> streetses = new HashSet<Streets>(0);
	private Set<StreetsSearch> streetsSearches = new HashSet<StreetsSearch>(0);

	public Municipalities() {
	}

	public Municipalities(short municipalitycode, AccessClasses accessClasses,
			Regions regions, String municipalityname) {
		this.municipalitycode = municipalitycode;
		this.accessClasses = accessClasses;
		this.regions = regions;
		this.municipalityname = municipalityname;
	}

	public Municipalities(short municipalitycode, AccessClasses accessClasses,
			Regions regions, String municipalityname, Set<Streets> streetses,
			Set<StreetsSearch> streetsSearches) {
		this.municipalitycode = municipalitycode;
		this.accessClasses = accessClasses;
		this.regions = regions;
		this.municipalityname = municipalityname;
		this.streetses = streetses;
		this.streetsSearches = streetsSearches;
	}

	@Id
	@Column(name = "MUNICIPALITYCODE", unique = true, nullable = false, precision = 3, scale = 0)
	public short getMunicipalitycode() {
		return this.municipalitycode;
	}

	public void setMunicipalitycode(short municipalitycode) {
		this.municipalitycode = municipalitycode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCESS_CLASS", nullable = false)
	public AccessClasses getAccessClasses() {
		return this.accessClasses;
	}

	public void setAccessClasses(AccessClasses accessClasses) {
		this.accessClasses = accessClasses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REGIONID", nullable = false)
	public Regions getRegions() {
		return this.regions;
	}

	public void setRegions(Regions regions) {
		this.regions = regions;
	}

	@Column(name = "MUNICIPALITYNAME", nullable = false, length = 50)
	public String getMunicipalityname() {
		return this.municipalityname;
	}

	public void setMunicipalityname(String municipalityname) {
		this.municipalityname = municipalityname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipalities")
	public Set<Streets> getStreetses() {
		return this.streetses;
	}

	public void setStreetses(Set<Streets> streetses) {
		this.streetses = streetses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipalities")
	public Set<StreetsSearch> getStreetsSearches() {
		return this.streetsSearches;
	}

	public void setStreetsSearches(Set<StreetsSearch> streetsSearches) {
		this.streetsSearches = streetsSearches;
	}

}
