package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Postnummerfil generated by hbm2java
 */
@Entity
@Table(name = "POSTNUMMERFIL", schema = "AMS")
public class Postnummerfil implements java.io.Serializable {

	private PostnummerfilId id;

	public Postnummerfil() {
	}

	public Postnummerfil(PostnummerfilId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "postnr", column = @Column(name = "POSTNR", length = 4)),
			@AttributeOverride(name = "bynavn", column = @Column(name = "BYNAVN", length = 40)),
			@AttributeOverride(name = "gade", column = @Column(name = "GADE", length = 40)),
			@AttributeOverride(name = "firma", column = @Column(name = "FIRMA", length = 100)),
			@AttributeOverride(name = "provins", column = @Column(name = "PROVINS", length = 5)),
			@AttributeOverride(name = "land", column = @Column(name = "LAND", length = 1)) })
	public PostnummerfilId getId() {
		return this.id;
	}

	public void setId(PostnummerfilId id) {
		this.id = id;
	}

}
