package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Regions generated by hbm2java
 */
@Entity
@Table(name = "REGIONS", schema = "AMS")
public class Regions implements java.io.Serializable {

	private BigDecimal regionid;
	private String regionname;
	private boolean accessClass;
	private Set<Municipalities> municipalitieses = new HashSet<Municipalities>(
			0);

	public Regions() {
	}

	public Regions(BigDecimal regionid, String regionname, boolean accessClass) {
		this.regionid = regionid;
		this.regionname = regionname;
		this.accessClass = accessClass;
	}

	public Regions(BigDecimal regionid, String regionname, boolean accessClass,
			Set<Municipalities> municipalitieses) {
		this.regionid = regionid;
		this.regionname = regionname;
		this.accessClass = accessClass;
		this.municipalitieses = municipalitieses;
	}

	@Id
	@Column(name = "REGIONID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRegionid() {
		return this.regionid;
	}

	public void setRegionid(BigDecimal regionid) {
		this.regionid = regionid;
	}

	@Column(name = "REGIONNAME", nullable = false, length = 50)
	public String getRegionname() {
		return this.regionname;
	}

	public void setRegionname(String regionname) {
		this.regionname = regionname;
	}

	@Column(name = "ACCESS_CLASS", nullable = false, precision = 1, scale = 0)
	public boolean isAccessClass() {
		return this.accessClass;
	}

	public void setAccessClass(boolean accessClass) {
		this.accessClass = accessClass;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regions")
	public Set<Municipalities> getMunicipalitieses() {
		return this.municipalitieses;
	}

	public void setMunicipalitieses(Set<Municipalities> municipalitieses) {
		this.municipalitieses = municipalitieses;
	}

}
