package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * StreetnameMapping generated by hbm2java
 */
@Entity
@Table(name = "STREETNAME_MAPPING", schema = "AMS", uniqueConstraints = @UniqueConstraint(columnNames = {
		"MUNICIPALITYCODE", "STREETCODE" }))
public class StreetnameMapping implements java.io.Serializable {

	private StreetnameMappingId id;

	public StreetnameMapping() {
	}

	public StreetnameMapping(StreetnameMappingId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "municipalitycode", column = @Column(name = "MUNICIPALITYCODE", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "streetcode", column = @Column(name = "STREETCODE", nullable = false, precision = 4, scale = 0)),
			@AttributeOverride(name = "fromValue", column = @Column(name = "FROM_VALUE", nullable = false, length = 20)),
			@AttributeOverride(name = "toValue", column = @Column(name = "TO_VALUE", nullable = false, length = 40)) })
	public StreetnameMappingId getId() {
		return this.id;
	}

	public void setId(StreetnameMappingId id) {
		this.id = id;
	}

}
