package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StreetsSearch generated by hbm2java
 */
@Entity
@Table(name = "STREETS_SEARCH", schema = "AMS")
public class StreetsSearch implements java.io.Serializable {

	private StreetsSearchId id;
	private Postaldistricts postaldistricts;
	private Municipalities municipalities;
	private AccessClasses accessClasses;

	public StreetsSearch() {
	}

	public StreetsSearch(StreetsSearchId id, AccessClasses accessClasses) {
		this.id = id;
		this.accessClasses = accessClasses;
	}

	public StreetsSearch(StreetsSearchId id, Postaldistricts postaldistricts,
			Municipalities municipalities, AccessClasses accessClasses) {
		this.id = id;
		this.postaldistricts = postaldistricts;
		this.municipalities = municipalities;
		this.accessClasses = accessClasses;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "streetId", column = @Column(name = "STREET_ID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "municipalitycode", column = @Column(name = "MUNICIPALITYCODE", precision = 3, scale = 0)),
			@AttributeOverride(name = "streetcode", column = @Column(name = "STREETCODE", precision = 4, scale = 0)),
			@AttributeOverride(name = "postalcode", column = @Column(name = "POSTALCODE", length = 10)),
			@AttributeOverride(name = "streetname", column = @Column(name = "STREETNAME", length = 40)),
			@AttributeOverride(name = "streetnameSearch", column = @Column(name = "STREETNAME_SEARCH", length = 40)),
			@AttributeOverride(name = "placename", column = @Column(name = "PLACENAME", length = 40)),
			@AttributeOverride(name = "accessClass", column = @Column(name = "ACCESS_CLASS", nullable = false, precision = 1, scale = 0)) })
	public StreetsSearchId getId() {
		return this.id;
	}

	public void setId(StreetsSearchId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "POSTALCODE", insertable = false, updatable = false)
	public Postaldistricts getPostaldistricts() {
		return this.postaldistricts;
	}

	public void setPostaldistricts(Postaldistricts postaldistricts) {
		this.postaldistricts = postaldistricts;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MUNICIPALITYCODE", insertable = false, updatable = false)
	public Municipalities getMunicipalities() {
		return this.municipalities;
	}

	public void setMunicipalities(Municipalities municipalities) {
		this.municipalities = municipalities;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACCESS_CLASS", nullable = false, insertable = false, updatable = false)
	public AccessClasses getAccessClasses() {
		return this.accessClasses;
	}

	public void setAccessClasses(AccessClasses accessClasses) {
		this.accessClasses = accessClasses;
	}

}
