package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Strukturreform generated by hbm2java
 */
@Entity
@Table(name = "STRUKTURREFORM", schema = "AMS")
public class Strukturreform implements java.io.Serializable {

	private StrukturreformId id;

	public Strukturreform() {
	}

	public Strukturreform(StrukturreformId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "fraNr", column = @Column(name = "FRA_NR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "fraNavn", column = @Column(name = "FRA_NAVN", nullable = false, length = 40)),
			@AttributeOverride(name = "tilNr", column = @Column(name = "TIL_NR", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "tilNavn", column = @Column(name = "TIL_NAVN", nullable = false, length = 40)),
			@AttributeOverride(name = "fraSplittes", column = @Column(name = "FRA_SPLITTES", precision = 1, scale = 0)),
			@AttributeOverride(name = "tilSamles", column = @Column(name = "TIL_SAMLES", precision = 1, scale = 0)) })
	public StrukturreformId getId() {
		return this.id;
	}

	public void setId(StrukturreformId id) {
		this.id = id;
	}

}
