package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "TEST", schema = "AMS")
public class Test implements java.io.Serializable {

	private TestId id;

	public Test() {
	}

	public Test(TestId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dato", column = @Column(name = "DATO", length = 7)),
			@AttributeOverride(name = "kvhx", column = @Column(name = "KVHX", length = 20)),
			@AttributeOverride(name = "tekst", column = @Column(name = "TEKST", length = 200)) })
	public TestId getId() {
		return this.id;
	}

	public void setId(TestId id) {
		this.id = id;
	}

}
