package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Test2 generated by hbm2java
 */
@Entity
@Table(name = "TEST2", schema = "AMS")
public class Test2 implements java.io.Serializable {

	private Test2Id id;

	public Test2() {
	}

	public Test2(Test2Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "dato", column = @Column(name = "DATO", length = 7)),
			@AttributeOverride(name = "tekst", column = @Column(name = "TEKST", length = 200)),
			@AttributeOverride(name = "casperid", column = @Column(name = "CASPERID", length = 10)),
			@AttributeOverride(name = "status", column = @Column(name = "STATUS", length = 1)) })
	public Test2Id getId() {
		return this.id;
	}

	public void setId(Test2Id id) {
		this.id = id;
	}

}
