package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Tmpadresse generated by hbm2java
 */
@Entity
@Table(name = "TMPADRESSE", schema = "AMS")
public class Tmpadresse implements java.io.Serializable {

	private TmpadresseId id;

	public Tmpadresse() {
	}

	public Tmpadresse(TmpadresseId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "husnoegle", column = @Column(name = "HUSNOEGLE", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "adresseId", column = @Column(name = "ADRESSE_ID", nullable = false, length = 10)),
			@AttributeOverride(name = "gadestykkeId", column = @Column(name = "GADESTYKKE_ID", nullable = false, length = 10)),
			@AttributeOverride(name = "husnr", column = @Column(name = "HUSNR", nullable = false, precision = 4, scale = 0)),
			@AttributeOverride(name = "opgang", column = @Column(name = "OPGANG", length = 1)),
			@AttributeOverride(name = "stednavn", column = @Column(name = "STEDNAVN", length = 20)),
			@AttributeOverride(name = "etage", column = @Column(name = "ETAGE", length = 2)),
			@AttributeOverride(name = "side", column = @Column(name = "SIDE", length = 2)),
			@AttributeOverride(name = "doernr", column = @Column(name = "DOERNR", precision = 5, scale = 0)),
			@AttributeOverride(name = "husnavn", column = @Column(name = "HUSNAVN", length = 15)),
			@AttributeOverride(name = "boligtypeKode", column = @Column(name = "BOLIGTYPE_KODE", length = 1)),
			@AttributeOverride(name = "udgaaetDato", column = @Column(name = "UDGAAET_DATO", length = 7)),
			@AttributeOverride(name = "opdateretDato", column = @Column(name = "OPDATERET_DATO", length = 7)),
			@AttributeOverride(name = "opdateretAf", column = @Column(name = "OPDATERET_AF", length = 10)),
			@AttributeOverride(name = "opdateretFkt", column = @Column(name = "OPDATERET_FKT", length = 20)),
			@AttributeOverride(name = "oprettetDato", column = @Column(name = "OPRETTET_DATO", length = 7)),
			@AttributeOverride(name = "oprettetAf", column = @Column(name = "OPRETTET_AF", length = 10)),
			@AttributeOverride(name = "oprettetFkt", column = @Column(name = "OPRETTET_FKT", length = 20)),
			@AttributeOverride(name = "cprAdresseId", column = @Column(name = "CPR_ADRESSE_ID")),
			@AttributeOverride(name = "oprettetSys", column = @Column(name = "OPRETTET_SYS", length = 10)),
			@AttributeOverride(name = "opdateretSys", column = @Column(name = "OPDATERET_SYS", length = 10)) })
	public TmpadresseId getId() {
		return this.id;
	}

	public void setId(TmpadresseId id) {
		this.id = id;
	}

}
