package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TmpStreets generated by hbm2java
 */
@Entity
@Table(name = "TMP_STREETS", schema = "AMS")
public class TmpStreets implements java.io.Serializable {

	private TmpStreetsId id;

	public TmpStreets() {
	}

	public TmpStreets(TmpStreetsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "streetId", column = @Column(name = "STREET_ID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "startdate", column = @Column(name = "STARTDATE", nullable = false, length = 7)),
			@AttributeOverride(name = "municipalitycode", column = @Column(name = "MUNICIPALITYCODE", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "streetcode", column = @Column(name = "STREETCODE", precision = 4, scale = 0)),
			@AttributeOverride(name = "streetname", column = @Column(name = "STREETNAME", nullable = false, length = 40)),
			@AttributeOverride(name = "streetnameAbbreviated", column = @Column(name = "STREETNAME_ABBREVIATED", length = 20)),
			@AttributeOverride(name = "accessClass", column = @Column(name = "ACCESS_CLASS", nullable = false, precision = 1, scale = 0)),
			@AttributeOverride(name = "userAccessClass", column = @Column(name = "USER_ACCESS_CLASS", precision = 1, scale = 0)),
			@AttributeOverride(name = "source", column = @Column(name = "SOURCE", nullable = false, length = 6)),
			@AttributeOverride(name = "enddate", column = @Column(name = "ENDDATE", length = 7)),
			@AttributeOverride(name = "initials", column = @Column(name = "INITIALS", nullable = false, length = 10)),
			@AttributeOverride(name = "createddate", column = @Column(name = "CREATEDDATE", length = 7)),
			@AttributeOverride(name = "matchStreetname", column = @Column(name = "MATCH_STREETNAME", length = 40)),
			@AttributeOverride(name = "matchStreetnameA", column = @Column(name = "MATCH_STREETNAME_A", length = 40)) })
	public TmpStreetsId getId() {
		return this.id;
	}

	public void setId(TmpStreetsId id) {
		this.id = id;
	}

}
