package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UnitOrigin generated by hbm2java
 */
@Entity
@Table(name = "UNIT_ORIGIN", schema = "AMS")
public class UnitOrigin implements java.io.Serializable {

	private BigDecimal code;
	private boolean esr;
	private boolean kmsBak;
	private boolean krr;
	private boolean bbrUnit;
	private boolean osakUnitaddress;
	private boolean interpolated;
	private boolean extrapolated;
	private boolean basedOnAccessaddress;
	private boolean dgsAbbreviated;
	private boolean dgsCreated;
	private boolean dgsMissing;
	private boolean dgsModified;
	private boolean bbrChangeunit;
	private boolean robinson;
	private Set<Addresses> addresseses = new HashSet<Addresses>(0);

	public UnitOrigin() {
	}

	public UnitOrigin(BigDecimal code, boolean esr, boolean kmsBak,
			boolean krr, boolean bbrUnit, boolean osakUnitaddress,
			boolean interpolated, boolean extrapolated,
			boolean basedOnAccessaddress, boolean dgsAbbreviated,
			boolean dgsCreated, boolean dgsMissing, boolean dgsModified,
			boolean bbrChangeunit, boolean robinson) {
		this.code = code;
		this.esr = esr;
		this.kmsBak = kmsBak;
		this.krr = krr;
		this.bbrUnit = bbrUnit;
		this.osakUnitaddress = osakUnitaddress;
		this.interpolated = interpolated;
		this.extrapolated = extrapolated;
		this.basedOnAccessaddress = basedOnAccessaddress;
		this.dgsAbbreviated = dgsAbbreviated;
		this.dgsCreated = dgsCreated;
		this.dgsMissing = dgsMissing;
		this.dgsModified = dgsModified;
		this.bbrChangeunit = bbrChangeunit;
		this.robinson = robinson;
	}

	public UnitOrigin(BigDecimal code, boolean esr, boolean kmsBak,
			boolean krr, boolean bbrUnit, boolean osakUnitaddress,
			boolean interpolated, boolean extrapolated,
			boolean basedOnAccessaddress, boolean dgsAbbreviated,
			boolean dgsCreated, boolean dgsMissing, boolean dgsModified,
			boolean bbrChangeunit, boolean robinson, Set<Addresses> addresseses) {
		this.code = code;
		this.esr = esr;
		this.kmsBak = kmsBak;
		this.krr = krr;
		this.bbrUnit = bbrUnit;
		this.osakUnitaddress = osakUnitaddress;
		this.interpolated = interpolated;
		this.extrapolated = extrapolated;
		this.basedOnAccessaddress = basedOnAccessaddress;
		this.dgsAbbreviated = dgsAbbreviated;
		this.dgsCreated = dgsCreated;
		this.dgsMissing = dgsMissing;
		this.dgsModified = dgsModified;
		this.bbrChangeunit = bbrChangeunit;
		this.robinson = robinson;
		this.addresseses = addresseses;
	}

	@Id
	@Column(name = "CODE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCode() {
		return this.code;
	}

	public void setCode(BigDecimal code) {
		this.code = code;
	}

	@Column(name = "ESR", nullable = false, precision = 1, scale = 0)
	public boolean isEsr() {
		return this.esr;
	}

	public void setEsr(boolean esr) {
		this.esr = esr;
	}

	@Column(name = "KMS_BAK", nullable = false, precision = 1, scale = 0)
	public boolean isKmsBak() {
		return this.kmsBak;
	}

	public void setKmsBak(boolean kmsBak) {
		this.kmsBak = kmsBak;
	}

	@Column(name = "KRR", nullable = false, precision = 1, scale = 0)
	public boolean isKrr() {
		return this.krr;
	}

	public void setKrr(boolean krr) {
		this.krr = krr;
	}

	@Column(name = "BBR_UNIT", nullable = false, precision = 1, scale = 0)
	public boolean isBbrUnit() {
		return this.bbrUnit;
	}

	public void setBbrUnit(boolean bbrUnit) {
		this.bbrUnit = bbrUnit;
	}

	@Column(name = "OSAK_UNITADDRESS", nullable = false, precision = 1, scale = 0)
	public boolean isOsakUnitaddress() {
		return this.osakUnitaddress;
	}

	public void setOsakUnitaddress(boolean osakUnitaddress) {
		this.osakUnitaddress = osakUnitaddress;
	}

	@Column(name = "INTERPOLATED", nullable = false, precision = 1, scale = 0)
	public boolean isInterpolated() {
		return this.interpolated;
	}

	public void setInterpolated(boolean interpolated) {
		this.interpolated = interpolated;
	}

	@Column(name = "EXTRAPOLATED", nullable = false, precision = 1, scale = 0)
	public boolean isExtrapolated() {
		return this.extrapolated;
	}

	public void setExtrapolated(boolean extrapolated) {
		this.extrapolated = extrapolated;
	}

	@Column(name = "BASED_ON_ACCESSADDRESS", nullable = false, precision = 1, scale = 0)
	public boolean isBasedOnAccessaddress() {
		return this.basedOnAccessaddress;
	}

	public void setBasedOnAccessaddress(boolean basedOnAccessaddress) {
		this.basedOnAccessaddress = basedOnAccessaddress;
	}

	@Column(name = "DGS_ABBREVIATED", nullable = false, precision = 1, scale = 0)
	public boolean isDgsAbbreviated() {
		return this.dgsAbbreviated;
	}

	public void setDgsAbbreviated(boolean dgsAbbreviated) {
		this.dgsAbbreviated = dgsAbbreviated;
	}

	@Column(name = "DGS_CREATED", nullable = false, precision = 1, scale = 0)
	public boolean isDgsCreated() {
		return this.dgsCreated;
	}

	public void setDgsCreated(boolean dgsCreated) {
		this.dgsCreated = dgsCreated;
	}

	@Column(name = "DGS_MISSING", nullable = false, precision = 1, scale = 0)
	public boolean isDgsMissing() {
		return this.dgsMissing;
	}

	public void setDgsMissing(boolean dgsMissing) {
		this.dgsMissing = dgsMissing;
	}

	@Column(name = "DGS_MODIFIED", nullable = false, precision = 1, scale = 0)
	public boolean isDgsModified() {
		return this.dgsModified;
	}

	public void setDgsModified(boolean dgsModified) {
		this.dgsModified = dgsModified;
	}

	@Column(name = "BBR_CHANGEUNIT", nullable = false, precision = 1, scale = 0)
	public boolean isBbrChangeunit() {
		return this.bbrChangeunit;
	}

	public void setBbrChangeunit(boolean bbrChangeunit) {
		this.bbrChangeunit = bbrChangeunit;
	}

	@Column(name = "ROBINSON", nullable = false, precision = 1, scale = 0)
	public boolean isRobinson() {
		return this.robinson;
	}

	public void setRobinson(boolean robinson) {
		this.robinson = robinson;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unitOrigin")
	public Set<Addresses> getAddresseses() {
		return this.addresseses;
	}

	public void setAddresseses(Set<Addresses> addresseses) {
		this.addresseses = addresseses;
	}

}
