package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * XAmsZapUpdateWarnings generated by hbm2java
 */
@Entity
@Table(name = "X_AMS_ZAP_UPDATE_WARNINGS", schema = "AMS")
public class XAmsZapUpdateWarnings implements java.io.Serializable {

	private XAmsZapUpdateWarningsId id;

	public XAmsZapUpdateWarnings() {
	}

	public XAmsZapUpdateWarnings(XAmsZapUpdateWarningsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "primeAmsIdRef", column = @Column(name = "PRIME_AMS_ID_REF", precision = 22, scale = 0)),
			@AttributeOverride(name = "secondAmsIdRef", column = @Column(name = "SECOND_AMS_ID_REF", precision = 22, scale = 0)),
			@AttributeOverride(name = "warningText", column = @Column(name = "WARNING_TEXT", length = 200)),
			@AttributeOverride(name = "updatedate", column = @Column(name = "UPDATEDATE", length = 7)) })
	public XAmsZapUpdateWarningsId getId() {
		return this.id;
	}

	public void setId(XAmsZapUpdateWarningsId id) {
		this.id = id;
	}

}
