package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ZapParish generated by hbm2java
 */
@Entity
@Table(name = "ZAP_PARISH", schema = "AMS")
public class ZapParish implements java.io.Serializable {

	private BigDecimal parishid;
	private String parishname;
	private Set<ZapAddressPoints> zapAddressPointses = new HashSet<ZapAddressPoints>(
			0);

	public ZapParish() {
	}

	public ZapParish(BigDecimal parishid) {
		this.parishid = parishid;
	}

	public ZapParish(BigDecimal parishid, String parishname,
			Set<ZapAddressPoints> zapAddressPointses) {
		this.parishid = parishid;
		this.parishname = parishname;
		this.zapAddressPointses = zapAddressPointses;
	}

	@Id
	@Column(name = "PARISHID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getParishid() {
		return this.parishid;
	}

	public void setParishid(BigDecimal parishid) {
		this.parishid = parishid;
	}

	@Column(name = "PARISHNAME", length = 50)
	public String getParishname() {
		return this.parishname;
	}

	public void setParishname(String parishname) {
		this.parishname = parishname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zapParish")
	public Set<ZapAddressPoints> getZapAddressPointses() {
		return this.zapAddressPointses;
	}

	public void setZapAddressPointses(Set<ZapAddressPoints> zapAddressPointses) {
		this.zapAddressPointses = zapAddressPointses;
	}

}
