package com.tdc.persistence.ams.dao.entity;

// Generated 09-04-2015 18:59:20 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ZapRegions generated by hbm2java
 */
@Entity
@Table(name = "ZAP_REGIONS", schema = "AMS")
public class ZapRegions implements java.io.Serializable {

	private BigDecimal regionid;
	private String regionname;
	private Set<ZapMunicipalities> zapMunicipalitieses = new HashSet<ZapMunicipalities>(
			0);

	public ZapRegions() {
	}

	public ZapRegions(BigDecimal regionid, String regionname) {
		this.regionid = regionid;
		this.regionname = regionname;
	}

	public ZapRegions(BigDecimal regionid, String regionname,
			Set<ZapMunicipalities> zapMunicipalitieses) {
		this.regionid = regionid;
		this.regionname = regionname;
		this.zapMunicipalitieses = zapMunicipalitieses;
	}

	@Id
	@Column(name = "REGIONID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getRegionid() {
		return this.regionid;
	}

	public void setRegionid(BigDecimal regionid) {
		this.regionid = regionid;
	}

	@Column(name = "REGIONNAME", nullable = false, length = 50)
	public String getRegionname() {
		return this.regionname;
	}

	public void setRegionname(String regionname) {
		this.regionname = regionname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zapRegions")
	public Set<ZapMunicipalities> getZapMunicipalitieses() {
		return this.zapMunicipalitieses;
	}

	public void setZapMunicipalitieses(
			Set<ZapMunicipalities> zapMunicipalitieses) {
		this.zapMunicipalitieses = zapMunicipalitieses;
	}

}
