package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CableunitChghistFdb generated by hbm2java
 */
@Entity
@Table(name = "CABLEUNIT_CHGHIST_FDB", schema = "PCRM", uniqueConstraints = @UniqueConstraint(columnNames = "AUD_ID"))
public class CableunitChghistFdb implements java.io.Serializable {

	private CableunitChghistFdbId id;

	public CableunitChghistFdb() {
	}

	public CableunitChghistFdb(CableunitChghistFdbId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "audId", column = @Column(name = "AUD_ID", unique = true, length = 19)),
			@AttributeOverride(name = "audAction", column = @Column(name = "AUD_ACTION", length = 50)),
			@AttributeOverride(name = "audTimestamp", column = @Column(name = "AUD_TIMESTAMP")),
			@AttributeOverride(name = "audOsuser", column = @Column(name = "AUD_OSUSER", length = 50)),
			@AttributeOverride(name = "audDbuser", column = @Column(name = "AUD_DBUSER", length = 50)),
			@AttributeOverride(name = "audUserterminal", column = @Column(name = "AUD_USERTERMINAL", length = 50)),
			@AttributeOverride(name = "id", column = @Column(name = "ID", length = 19)),
			@AttributeOverride(name = "crd", column = @Column(name = "CRD", length = 7)),
			@AttributeOverride(name = "crt", column = @Column(name = "CRT", length = 7)),
			@AttributeOverride(name = "cru", column = @Column(name = "CRU", length = 19)),
			@AttributeOverride(name = "modd", column = @Column(name = "MODD", length = 7)),
			@AttributeOverride(name = "modt", column = @Column(name = "MODT", length = 7)),
			@AttributeOverride(name = "modu", column = @Column(name = "MODU", length = 19)),
			@AttributeOverride(name = "deld", column = @Column(name = "DELD", length = 7)),
			@AttributeOverride(name = "delt", column = @Column(name = "DELT", length = 7)),
			@AttributeOverride(name = "delu", column = @Column(name = "DELU", length = 19)),
			@AttributeOverride(name = "impd", column = @Column(name = "IMPD", length = 7)),
			@AttributeOverride(name = "impt", column = @Column(name = "IMPT", length = 7)),
			@AttributeOverride(name = "impu", column = @Column(name = "IMPU", length = 19)),
			@AttributeOverride(name = "expd", column = @Column(name = "EXPD", length = 7)),
			@AttributeOverride(name = "expt", column = @Column(name = "EXPT", length = 7)),
			@AttributeOverride(name = "expu", column = @Column(name = "EXPU", length = 19)),
			@AttributeOverride(name = "anlAnlaegsnr", column = @Column(name = "ANL_ANLAEGSNR", length = 10)),
			@AttributeOverride(name = "anlAnlaegsnavn", column = @Column(name = "ANL_ANLAEGSNAVN", length = 40)),
			@AttributeOverride(name = "anlKommunenr", column = @Column(name = "ANL_KOMMUNENR", precision = 3, scale = 0)),
			@AttributeOverride(name = "anlEjerkode", column = @Column(name = "ANL_EJERKODE", precision = 1, scale = 0)),
			@AttributeOverride(name = "anlAdmKode", column = @Column(name = "ANL_ADM_KODE", precision = 1, scale = 0)),
			@AttributeOverride(name = "anlAnlaegsform", column = @Column(name = "ANL_ANLAEGSFORM", precision = 1, scale = 0)),
			@AttributeOverride(name = "anlHovedanlaegsnr", column = @Column(name = "ANL_HOVEDANLAEGSNR", length = 11)),
			@AttributeOverride(name = "anlAfleveringspunkt", column = @Column(name = "ANL_AFLEVERINGSPUNKT", length = 60)),
			@AttributeOverride(name = "anlNoegleboks", column = @Column(name = "ANL_NOEGLEBOKS", length = 60)),
			@AttributeOverride(name = "anlIdriftDato", column = @Column(name = "ANL_IDRIFT_DATO", length = 7)),
			@AttributeOverride(name = "anlForvIdriftDato", column = @Column(name = "ANL_FORV_IDRIFT_DATO", length = 7)),
			@AttributeOverride(name = "anlAnlaegsStatus", column = @Column(name = "ANL_ANLAEGS_STATUS", precision = 2, scale = 0)),
			@AttributeOverride(name = "anlSalgskoncept", column = @Column(name = "ANL_SALGSKONCEPT", length = 20)),
			@AttributeOverride(name = "RRating", column = @Column(name = "R_RATING", precision = 22, scale = 0)),
			@AttributeOverride(name = "RRatingDate", column = @Column(name = "R_RATING_DATE", length = 7)),
			@AttributeOverride(name = "RNextRating", column = @Column(name = "R_NEXT_RATING", precision = 22, scale = 0)),
			@AttributeOverride(name = "RNextRatingDate", column = @Column(name = "R_NEXT_RATING_DATE", length = 7)),
			@AttributeOverride(name = "sourceChgDate", column = @Column(name = "SOURCE_CHG_DATE", length = 7)),
			@AttributeOverride(name = "sourceChgCode", column = @Column(name = "SOURCE_CHG_CODE", length = 50)),
			@AttributeOverride(name = "noInst", column = @Column(name = "NO_INST", precision = 22, scale = 0)),
			@AttributeOverride(name = "noDumInst", column = @Column(name = "NO_DUM_INST", precision = 22, scale = 0)),
			@AttributeOverride(name = "noAllInst", column = @Column(name = "NO_ALL_INST", precision = 22, scale = 0)),
			@AttributeOverride(name = "reforhandlFlag", column = @Column(name = "REFORHANDL_FLAG", length = 1)),
			@AttributeOverride(name = "reforhandlDate", column = @Column(name = "REFORHANDL_DATE", length = 7)),
			@AttributeOverride(name = "anlGenberegnetdato", column = @Column(name = "ANL_GENBEREGNETDATO", length = 7)),
			@AttributeOverride(name = "anlForhandlingsdato", column = @Column(name = "ANL_FORHANDLINGSDATO", length = 7)),
			@AttributeOverride(name = "primhfinfo", column = @Column(name = "PRIMHFINFO", length = 19)),
			@AttributeOverride(name = "primanltype", column = @Column(name = "PRIMANLTYPE", length = 19)),
			@AttributeOverride(name = "primarykontrakt", column = @Column(name = "PRIMARYKONTRAKT", length = 19)),
			@AttributeOverride(name = "aflpunkt", column = @Column(name = "AFLPUNKT")),
			@AttributeOverride(name = "nglboxopsat", column = @Column(name = "NGLBOXOPSAT")),
			@AttributeOverride(name = "paralleldatanet", column = @Column(name = "PARALLELDATANET")),
			@AttributeOverride(name = "coaxloesning", column = @Column(name = "COAXLOESNING")),
			@AttributeOverride(name = "fwaloesning", column = @Column(name = "FWALOESNING")),
			@AttributeOverride(name = "retvejsduelfn3", column = @Column(name = "RETVEJSDUELFN3", length = 1)),
			@AttributeOverride(name = "primservlev", column = @Column(name = "PRIMSERVLEV", length = 19)),
			@AttributeOverride(name = "primarytidllev", column = @Column(name = "PRIMARYTIDLLEV", length = 19)),
			@AttributeOverride(name = "priminternetlev", column = @Column(name = "PRIMINTERNETLEV", length = 19)),
			@AttributeOverride(name = "primarytelefonilev", column = @Column(name = "PRIMARYTELEFONILEV", length = 19)),
			@AttributeOverride(name = "primarydigstblev", column = @Column(name = "PRIMARYDIGSTBLEV", length = 19)),
			@AttributeOverride(name = "primaryfrekvens", column = @Column(name = "PRIMARYFREKVENS", length = 19)),
			@AttributeOverride(name = "primkommune", column = @Column(name = "PRIMKOMMUNE", length = 19)),
			@AttributeOverride(name = "primanlstatus", column = @Column(name = "PRIMANLSTATUS", length = 19)),
			@AttributeOverride(name = "expdate", column = @Column(name = "EXPDATE", length = 7)),
			@AttributeOverride(name = "signalforskilde", column = @Column(name = "SIGNALFORSKILDE")),
			@AttributeOverride(name = "noInstAbnm", column = @Column(name = "NO_INST_ABNM", precision = 22, scale = 0)),
			@AttributeOverride(name = "pottilsl", column = @Column(name = "POTTILSL", precision = 10, scale = 0)),
			@AttributeOverride(name = "akttilsl", column = @Column(name = "AKTTILSL", precision = 10, scale = 0)),
			@AttributeOverride(name = "mainZip", column = @Column(name = "MAIN_ZIP", length = 4)),
			@AttributeOverride(name = "sloejfe", column = @Column(name = "SLOEJFE", length = 1)),
			@AttributeOverride(name = "stik", column = @Column(name = "STIK", length = 1)),
			@AttributeOverride(name = "nyoprettet", column = @Column(name = "NYOPRETTET", length = 1)),
			@AttributeOverride(name = "quickpot", column = @Column(name = "QUICKPOT", length = 1)),
			@AttributeOverride(name = "primsf", column = @Column(name = "PRIMSF", length = 19)),
			@AttributeOverride(name = "returfrekvens", column = @Column(name = "RETURFREKVENS", length = 20)),
			@AttributeOverride(name = "amheadend", column = @Column(name = "AMHEADEND", length = 5)),
			@AttributeOverride(name = "prevAnlaegsnr", column = @Column(name = "PREV_ANLAEGSNR", length = 20)),
			@AttributeOverride(name = "primsegmgroup", column = @Column(name = "PRIMSEGMGROUP", length = 19)),
			@AttributeOverride(name = "primpostcode", column = @Column(name = "PRIMPOSTCODE", length = 19)),
			@AttributeOverride(name = "primcurrlev", column = @Column(name = "PRIMCURRLEV", length = 19)),
			@AttributeOverride(name = "REtabldate", column = @Column(name = "R_ETABLDATE", length = 7)),
			@AttributeOverride(name = "aktivSag", column = @Column(name = "AKTIV_SAG", length = 1)),
			@AttributeOverride(name = "calcKommune", column = @Column(name = "CALC_KOMMUNE", length = 19)),
			@AttributeOverride(name = "returvejokfn2", column = @Column(name = "RETURVEJOKFN2", length = 1)),
			@AttributeOverride(name = "returvejokfn3", column = @Column(name = "RETURVEJOKFN3", length = 1)),
			@AttributeOverride(name = "returvejok", column = @Column(name = "RETURVEJOK", length = 1)),
			@AttributeOverride(name = "anlIHusleje", column = @Column(name = "ANL_I_HUSLEJE", precision = 22, scale = 0)),
			@AttributeOverride(name = "primaryklumaxhast", column = @Column(name = "PRIMARYKLUMAXHAST", length = 19)),
			@AttributeOverride(name = "primaryklulntype", column = @Column(name = "PRIMARYKLULNTYPE", length = 19)),
			@AttributeOverride(name = "primaryklulnejer", column = @Column(name = "PRIMARYKLULNEJER", length = 19)),
			@AttributeOverride(name = "primarykluintype", column = @Column(name = "PRIMARYKLUINTYPE", length = 19)),
			@AttributeOverride(name = "primarykluaftkap", column = @Column(name = "PRIMARYKLUAFTKAP", length = 19)),
			@AttributeOverride(name = "primproj", column = @Column(name = "PRIMPROJ", length = 19)),
			@AttributeOverride(name = "primfap", column = @Column(name = "PRIMFAP", length = 19)),
			@AttributeOverride(name = "decAslKapacitet", column = @Column(name = "DEC_ASL_KAPACITET")),
			@AttributeOverride(name = "voip", column = @Column(name = "VOIP", length = 1)),
			@AttributeOverride(name = "udtagetvoip", column = @Column(name = "UDTAGETVOIP", precision = 22, scale = 0)),
			@AttributeOverride(name = "annr", column = @Column(name = "ANNR", precision = 10, scale = 0)),
			@AttributeOverride(name = "primdekoder", column = @Column(name = "PRIMDEKODER", length = 19)),
			@AttributeOverride(name = "primcompany", column = @Column(name = "PRIMCOMPANY", length = 19)),
			@AttributeOverride(name = "sourceChgBool", column = @Column(name = "SOURCE_CHG_BOOL", length = 1)),
			@AttributeOverride(name = "leasaar", column = @Column(name = "LEASAAR", precision = 10, scale = 0)),
			@AttributeOverride(name = "refdebnr", column = @Column(name = "REFDEBNR", length = 10)),
			@AttributeOverride(name = "refanlnr", column = @Column(name = "REFANLNR", length = 10)),
			@AttributeOverride(name = "anlDatoinaktiv", column = @Column(name = "ANL_DATOINAKTIV", length = 7)),
			@AttributeOverride(name = "primmunicipality", column = @Column(name = "PRIMMUNICIPALITY", length = 19)),
			@AttributeOverride(name = "allowPresale", column = @Column(name = "ALLOW_PRESALE", length = 1)),
			@AttributeOverride(name = "logtrace", column = @Column(name = "LOGTRACE", length = 19)),
			@AttributeOverride(name = "dktv", column = @Column(name = "DKTV", length = 1)) })
	public CableunitChghistFdbId getId() {
		return this.id;
	}

	public void setId(CableunitChghistFdbId id) {
		this.id = id;
	}

}
