package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Casetomeasurepoint generated by hbm2java
 */
@Entity
@Table(name = "CASETOMEASUREPOINT", schema = "PCRM")
public class Casetomeasurepoint implements java.io.Serializable {

	private String id;
	private Casetomeasurepoint casetomeasurepoint;
	private Date crd;
	private Date impd;
	private Date expd;
	private String cru;
	private Date modd;
	private String impu;
	private String expu;
	private String modu;
	private String nameDa;
	private String nameEn;
	private Byte lvl;
	private Integer seq;
	private String deptname;
	private Set<CrDocorigin2measurepoint> crDocorigin2measurepointsForPrimtomeasurepoint = new HashSet<CrDocorigin2measurepoint>(
			0);
	private Set<CrDocorigin2measurepoint> crDocorigin2measurepointsForPrimfrommeasurepoint = new HashSet<CrDocorigin2measurepoint>(
			0);
	private Set<Casetomeasurepoint> casetomeasurepoints = new HashSet<Casetomeasurepoint>(
			0);

	public Casetomeasurepoint() {
	}

	public Casetomeasurepoint(String id) {
		this.id = id;
	}

	public Casetomeasurepoint(
			String id,
			Casetomeasurepoint casetomeasurepoint,
			Date crd,
			Date impd,
			Date expd,
			String cru,
			Date modd,
			String impu,
			String expu,
			String modu,
			String nameDa,
			String nameEn,
			Byte lvl,
			Integer seq,
			String deptname,
			Set<CrDocorigin2measurepoint> crDocorigin2measurepointsForPrimtomeasurepoint,
			Set<CrDocorigin2measurepoint> crDocorigin2measurepointsForPrimfrommeasurepoint,
			Set<Casetomeasurepoint> casetomeasurepoints) {
		this.id = id;
		this.casetomeasurepoint = casetomeasurepoint;
		this.crd = crd;
		this.impd = impd;
		this.expd = expd;
		this.cru = cru;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.modu = modu;
		this.nameDa = nameDa;
		this.nameEn = nameEn;
		this.lvl = lvl;
		this.seq = seq;
		this.deptname = deptname;
		this.crDocorigin2measurepointsForPrimtomeasurepoint = crDocorigin2measurepointsForPrimtomeasurepoint;
		this.crDocorigin2measurepointsForPrimfrommeasurepoint = crDocorigin2measurepointsForPrimfrommeasurepoint;
		this.casetomeasurepoints = casetomeasurepoints;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMCASETOMEASUREPOINT")
	public Casetomeasurepoint getCasetomeasurepoint() {
		return this.casetomeasurepoint;
	}

	public void setCasetomeasurepoint(Casetomeasurepoint casetomeasurepoint) {
		this.casetomeasurepoint = casetomeasurepoint;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "NAME_DA", length = 100)
	public String getNameDa() {
		return this.nameDa;
	}

	public void setNameDa(String nameDa) {
		this.nameDa = nameDa;
	}

	@Column(name = "NAME_EN", length = 100)
	public String getNameEn() {
		return this.nameEn;
	}

	public void setNameEn(String nameEn) {
		this.nameEn = nameEn;
	}

	@Column(name = "LVL", precision = 2, scale = 0)
	public Byte getLvl() {
		return this.lvl;
	}

	public void setLvl(Byte lvl) {
		this.lvl = lvl;
	}

	@Column(name = "SEQ", precision = 8, scale = 0)
	public Integer getSeq() {
		return this.seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	@Column(name = "DEPTNAME", length = 4)
	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casetomeasurepointByPrimtomeasurepoint")
	public Set<CrDocorigin2measurepoint> getCrDocorigin2measurepointsForPrimtomeasurepoint() {
		return this.crDocorigin2measurepointsForPrimtomeasurepoint;
	}

	public void setCrDocorigin2measurepointsForPrimtomeasurepoint(
			Set<CrDocorigin2measurepoint> crDocorigin2measurepointsForPrimtomeasurepoint) {
		this.crDocorigin2measurepointsForPrimtomeasurepoint = crDocorigin2measurepointsForPrimtomeasurepoint;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casetomeasurepointByPrimfrommeasurepoint")
	public Set<CrDocorigin2measurepoint> getCrDocorigin2measurepointsForPrimfrommeasurepoint() {
		return this.crDocorigin2measurepointsForPrimfrommeasurepoint;
	}

	public void setCrDocorigin2measurepointsForPrimfrommeasurepoint(
			Set<CrDocorigin2measurepoint> crDocorigin2measurepointsForPrimfrommeasurepoint) {
		this.crDocorigin2measurepointsForPrimfrommeasurepoint = crDocorigin2measurepointsForPrimfrommeasurepoint;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "casetomeasurepoint")
	public Set<Casetomeasurepoint> getCasetomeasurepoints() {
		return this.casetomeasurepoints;
	}

	public void setCasetomeasurepoints(
			Set<Casetomeasurepoint> casetomeasurepoints) {
		this.casetomeasurepoints = casetomeasurepoints;
	}

}
