package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cdmacti generated by hbm2java
 */
@Entity
@Table(name = "CDMACTI", schema = "PCRM", uniqueConstraints = @UniqueConstraint(columnNames = "ID"))
public class Cdmacti implements java.io.Serializable {

	private CdmactiId id;

	public Cdmacti() {
	}

	public Cdmacti(CdmactiId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", unique = true, length = 19)),
			@AttributeOverride(name = "primuser", column = @Column(name = "PRIMUSER", length = 19)),
			@AttributeOverride(name = "primcont", column = @Column(name = "PRIMCONT", length = 19)),
			@AttributeOverride(name = "impt", column = @Column(name = "IMPT", length = 7)),
			@AttributeOverride(name = "deld", column = @Column(name = "DELD", length = 7)),
			@AttributeOverride(name = "primtype", column = @Column(name = "PRIMTYPE", length = 19)),
			@AttributeOverride(name = "endtime", column = @Column(name = "ENDTIME", length = 7)),
			@AttributeOverride(name = "done", column = @Column(name = "DONE", length = 1)),
			@AttributeOverride(name = "expu", column = @Column(name = "EXPU", length = 19)),
			@AttributeOverride(name = "startdate", column = @Column(name = "STARTDATE", length = 7)),
			@AttributeOverride(name = "crd", column = @Column(name = "CRD", length = 7)),
			@AttributeOverride(name = "crt", column = @Column(name = "CRT", length = 7)),
			@AttributeOverride(name = "primcomp", column = @Column(name = "PRIMCOMP", length = 19)),
			@AttributeOverride(name = "docext", column = @Column(name = "DOCEXT", length = 12)),
			@AttributeOverride(name = "modu", column = @Column(name = "MODU", length = 19)),
			@AttributeOverride(name = "primrepe", column = @Column(name = "PRIMREPE", length = 19)),
			@AttributeOverride(name = "cru", column = @Column(name = "CRU", length = 19)),
			@AttributeOverride(name = "impd", column = @Column(name = "IMPD", length = 7)),
			@AttributeOverride(name = "primproj", column = @Column(name = "PRIMPROJ", length = 19)),
			@AttributeOverride(name = "primfore", column = @Column(name = "PRIMFORE", length = 19)),
			@AttributeOverride(name = "delu", column = @Column(name = "DELU", length = 19)),
			@AttributeOverride(name = "expt", column = @Column(name = "EXPT", length = 7)),
			@AttributeOverride(name = "modd", column = @Column(name = "MODD", length = 7)),
			@AttributeOverride(name = "primcamp", column = @Column(name = "PRIMCAMP", length = 19)),
			@AttributeOverride(name = "starttime", column = @Column(name = "STARTTIME", length = 7)),
			@AttributeOverride(name = "modt", column = @Column(name = "MODT", length = 7)),
			@AttributeOverride(name = "head", column = @Column(name = "HEAD")),
			@AttributeOverride(name = "deadchan", column = @Column(name = "DEADCHAN", precision = 10, scale = 0)),
			@AttributeOverride(name = "impu", column = @Column(name = "IMPU", length = 19)),
			@AttributeOverride(name = "inhouse", column = @Column(name = "INHOUSE", length = 1)),
			@AttributeOverride(name = "expd", column = @Column(name = "EXPD", length = 7)),
			@AttributeOverride(name = "primcstep", column = @Column(name = "PRIMCSTEP", length = 19)),
			@AttributeOverride(name = "delt", column = @Column(name = "DELT", length = 7)),
			@AttributeOverride(name = "primarybeboer", column = @Column(name = "PRIMARYBEBOER", length = 19)),
			@AttributeOverride(name = "primprosp", column = @Column(name = "PRIMPROSP", length = 19)),
			@AttributeOverride(name = "primdwa", column = @Column(name = "PRIMDWA", length = 22)),
			@AttributeOverride(name = "primaryfaseaktivitet", column = @Column(name = "PRIMARYFASEAKTIVITET", length = 19)),
			@AttributeOverride(name = "primaryteam", column = @Column(name = "PRIMARYTEAM", length = 19)),
			@AttributeOverride(name = "primarysalesforecast", column = @Column(name = "PRIMARYSALESFORECAST", length = 19)),
			@AttributeOverride(name = "primaryreceiver", column = @Column(name = "PRIMARYRECEIVER", length = 19)),
			@AttributeOverride(name = "acceptts", column = @Column(name = "ACCEPTTS", length = 7)),
			@AttributeOverride(name = "sent", column = @Column(name = "SENT", length = 7)),
			@AttributeOverride(name = "rejectts", column = @Column(name = "REJECTTS", length = 7)),
			@AttributeOverride(name = "primaryorganisation", column = @Column(name = "PRIMARYORGANISATION", length = 19)),
			@AttributeOverride(name = "primanltbo", column = @Column(name = "PRIMANLTBO", length = 19)),
			@AttributeOverride(name = "primtilbkontr", column = @Column(name = "PRIMTILBKONTR", length = 19)),
			@AttributeOverride(name = "timeLeft", column = @Column(name = "TIME_LEFT", precision = 4, scale = 0)),
			@AttributeOverride(name = "casenumber", column = @Column(name = "CASENUMBER", length = 19)),
			@AttributeOverride(name = "team", column = @Column(name = "TEAM", length = 75)),
			@AttributeOverride(name = "cableunitnumber", column = @Column(name = "CABLEUNITNUMBER", length = 19)) })
	public CdmactiId getId() {
		return this.id;
	}

	public void setId(CdmactiId id) {
		this.id = id;
	}

}
