package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cdmcustprojectowner generated by hbm2java
 */
@Entity
@Table(name = "CDMCUSTPROJECTOWNER", schema = "PCRM")
public class Cdmcustprojectowner implements java.io.Serializable {

	private CdmcustprojectownerId id;

	public Cdmcustprojectowner() {
	}

	public Cdmcustprojectowner(CdmcustprojectownerId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", length = 19)),
			@AttributeOverride(name = "crd", column = @Column(name = "CRD", length = 7)),
			@AttributeOverride(name = "crt", column = @Column(name = "CRT", length = 7)),
			@AttributeOverride(name = "cru", column = @Column(name = "CRU", length = 19)),
			@AttributeOverride(name = "modd", column = @Column(name = "MODD", length = 7)),
			@AttributeOverride(name = "modt", column = @Column(name = "MODT", length = 7)),
			@AttributeOverride(name = "modu", column = @Column(name = "MODU", length = 19)),
			@AttributeOverride(name = "deld", column = @Column(name = "DELD", length = 7)),
			@AttributeOverride(name = "delt", column = @Column(name = "DELT", length = 7)),
			@AttributeOverride(name = "delu", column = @Column(name = "DELU", length = 19)),
			@AttributeOverride(name = "impd", column = @Column(name = "IMPD", length = 7)),
			@AttributeOverride(name = "impt", column = @Column(name = "IMPT", length = 7)),
			@AttributeOverride(name = "impu", column = @Column(name = "IMPU", length = 19)),
			@AttributeOverride(name = "expd", column = @Column(name = "EXPD", length = 7)),
			@AttributeOverride(name = "expt", column = @Column(name = "EXPT", length = 7)),
			@AttributeOverride(name = "expu", column = @Column(name = "EXPU", length = 19)),
			@AttributeOverride(name = "primportaluser", column = @Column(name = "PRIMPORTALUSER", length = 50)),
			@AttributeOverride(name = "sourceSystem", column = @Column(name = "SOURCE_SYSTEM", length = 5)),
			@AttributeOverride(name = "firstn", column = @Column(name = "FIRSTN", length = 35)),
			@AttributeOverride(name = "lastn", column = @Column(name = "LASTN", length = 35)),
			@AttributeOverride(name = "vejnvn", column = @Column(name = "VEJNVN", length = 40)),
			@AttributeOverride(name = "husnr", column = @Column(name = "HUSNR", length = 3)),
			@AttributeOverride(name = "husnrbogstav", column = @Column(name = "HUSNRBOGSTAV", length = 1)),
			@AttributeOverride(name = "etage", column = @Column(name = "ETAGE", length = 2)),
			@AttributeOverride(name = "sidedoer", column = @Column(name = "SIDEDOER", length = 4)),
			@AttributeOverride(name = "postnr", column = @Column(name = "POSTNR", length = 4)),
			@AttributeOverride(name = "postdisttxt", column = @Column(name = "POSTDISTTXT", length = 20)),
			@AttributeOverride(name = "phoneday", column = @Column(name = "PHONEDAY", length = 20)),
			@AttributeOverride(name = "accountmgrId", column = @Column(name = "ACCOUNTMGR_ID", length = 19)),
			@AttributeOverride(name = "email", column = @Column(name = "EMAIL")),
			@AttributeOverride(name = "mobilnr", column = @Column(name = "MOBILNR", length = 15)),
			@AttributeOverride(name = "foreningsnavn", column = @Column(name = "FORENINGSNAVN")),
			@AttributeOverride(name = "rolle", column = @Column(name = "ROLLE")),
			@AttributeOverride(name = "becontacted", column = @Column(name = "BECONTACTED", length = 1)),
			@AttributeOverride(name = "havenews", column = @Column(name = "HAVENEWS", length = 1)) })
	public CdmcustprojectownerId getId() {
		return this.id;
	}

	public void setId(CdmcustprojectownerId id) {
		this.id = id;
	}

}
