package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Cdmopslag generated by hbm2java
 */
@Entity
@Table(name = "CDMOPSLAG", schema = "PCRM")
public class Cdmopslag implements java.io.Serializable {

	private CdmopslagId id;

	public Cdmopslag() {
	}

	public Cdmopslag(CdmopslagId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", length = 19)),
			@AttributeOverride(name = "crd", column = @Column(name = "CRD", length = 7)),
			@AttributeOverride(name = "code", column = @Column(name = "CODE")),
			@AttributeOverride(name = "impt", column = @Column(name = "IMPT", length = 7)),
			@AttributeOverride(name = "expt", column = @Column(name = "EXPT", length = 7)),
			@AttributeOverride(name = "impd", column = @Column(name = "IMPD", length = 7)),
			@AttributeOverride(name = "expd", column = @Column(name = "EXPD", length = 7)),
			@AttributeOverride(name = "modt", column = @Column(name = "MODT", length = 7)),
			@AttributeOverride(name = "cru", column = @Column(name = "CRU", length = 19)),
			@AttributeOverride(name = "delt", column = @Column(name = "DELT", length = 7)),
			@AttributeOverride(name = "modd", column = @Column(name = "MODD", length = 7)),
			@AttributeOverride(name = "impu", column = @Column(name = "IMPU", length = 19)),
			@AttributeOverride(name = "expu", column = @Column(name = "EXPU", length = 19)),
			@AttributeOverride(name = "deld", column = @Column(name = "DELD", length = 7)),
			@AttributeOverride(name = "modu", column = @Column(name = "MODU", length = 19)),
			@AttributeOverride(name = "head", column = @Column(name = "HEAD")),
			@AttributeOverride(name = "delu", column = @Column(name = "DELU", length = 19)),
			@AttributeOverride(name = "crt", column = @Column(name = "CRT", length = 7)),
			@AttributeOverride(name = "primaryopslagstype", column = @Column(name = "PRIMARYOPSLAGSTYPE", length = 19)),
			@AttributeOverride(name = "numvari", column = @Column(name = "NUMVARI", precision = 12)),
			@AttributeOverride(name = "charvari", column = @Column(name = "CHARVARI")),
			@AttributeOverride(name = "tsvari", column = @Column(name = "TSVARI", length = 7)),
			@AttributeOverride(name = "rebmun", column = @Column(name = "REBMUN", precision = 10, scale = 0)) })
	public CdmopslagId getId() {
		return this.id;
	}

	public void setId(CdmopslagId id) {
		this.id = id;
	}

}
