package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Cdmrolerule generated by hbm2java
 */
@Entity
@Table(name = "CDMROLERULE", schema = "PCRM", uniqueConstraints = @UniqueConstraint(columnNames = "ID"))
public class Cdmrolerule implements java.io.Serializable {

	private CdmroleruleId id;

	public Cdmrolerule() {
	}

	public Cdmrolerule(CdmroleruleId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", unique = true, length = 19)),
			@AttributeOverride(name = "crd", column = @Column(name = "CRD", length = 7)),
			@AttributeOverride(name = "crt", column = @Column(name = "CRT", length = 7)),
			@AttributeOverride(name = "cru", column = @Column(name = "CRU", length = 19)),
			@AttributeOverride(name = "modd", column = @Column(name = "MODD", length = 7)),
			@AttributeOverride(name = "modt", column = @Column(name = "MODT", length = 7)),
			@AttributeOverride(name = "modu", column = @Column(name = "MODU", length = 19)),
			@AttributeOverride(name = "deld", column = @Column(name = "DELD", length = 7)),
			@AttributeOverride(name = "delt", column = @Column(name = "DELT", length = 7)),
			@AttributeOverride(name = "delu", column = @Column(name = "DELU", length = 19)),
			@AttributeOverride(name = "impd", column = @Column(name = "IMPD", length = 7)),
			@AttributeOverride(name = "impt", column = @Column(name = "IMPT", length = 7)),
			@AttributeOverride(name = "impu", column = @Column(name = "IMPU", length = 19)),
			@AttributeOverride(name = "expd", column = @Column(name = "EXPD", length = 7)),
			@AttributeOverride(name = "expt", column = @Column(name = "EXPT", length = 7)),
			@AttributeOverride(name = "expu", column = @Column(name = "EXPU", length = 19)),
			@AttributeOverride(name = "primarytablename", column = @Column(name = "PRIMARYTABLENAME")),
			@AttributeOverride(name = "primaryrole", column = @Column(name = "PRIMARYROLE", length = 19)),
			@AttributeOverride(name = "begr", column = @Column(name = "BEGR", length = 1)),
			@AttributeOverride(name = "ubegr", column = @Column(name = "UBEGR", length = 1)),
			@AttributeOverride(name = "antalmulige", column = @Column(name = "ANTALMULIGE", precision = 10, scale = 0)),
			@AttributeOverride(name = "antalneeded", column = @Column(name = "ANTALNEEDED", precision = 10, scale = 0)) })
	public CdmroleruleId getId() {
		return this.id;
	}

	public void setId(CdmroleruleId id) {
		this.id = id;
	}

}
