package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CharPatterns generated by hbm2java
 */
@Entity
@Table(name = "CHAR_PATTERNS", schema = "PCRM")
public class CharPatterns implements java.io.Serializable {

	private CharPatternsId id;

	public CharPatterns() {
	}

	public CharPatterns(CharPatternsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "sourcePattern", column = @Column(name = "SOURCE_PATTERN", length = 100)),
			@AttributeOverride(name = "sourcePatternType", column = @Column(name = "SOURCE_PATTERN_TYPE", length = 100)),
			@AttributeOverride(name = "targetPattern", column = @Column(name = "TARGET_PATTERN", length = 100)),
			@AttributeOverride(name = "targetPatternType", column = @Column(name = "TARGET_PATTERN_TYPE", length = 100)) })
	public CharPatternsId getId() {
		return this.id;
	}

	public void setId(CharPatternsId id) {
		this.id = id;
	}

}
