package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ChNodeKeys generated by hbm2java
 */
@Entity
@Table(name = "CH_NODE_KEYS", schema = "PCRM", uniqueConstraints = @UniqueConstraint(columnNames = {
		"NODE_ID", "FREQ_HZ", "PRODUCT_ID" }))
public class ChNodeKeys implements java.io.Serializable {

	private BigDecimal chKeySeq;
	private Products products;
	private DeliveryTypes deliveryTypes;
	private DistributionNodes distributionNodes;
	private BigDecimal freqHz;
	private String vendor;
	private String note;
	private Date validFrom;
	private Date validTo;
	private String changeByUser;
	private Date changeDateTime;
	private Date createdDateTime;
	private String createdByUser;
	private BigDecimal parentChKeySeq;

	public ChNodeKeys() {
	}

	public ChNodeKeys(BigDecimal chKeySeq, Products products) {
		this.chKeySeq = chKeySeq;
		this.products = products;
	}

	public ChNodeKeys(BigDecimal chKeySeq, Products products,
			DeliveryTypes deliveryTypes, DistributionNodes distributionNodes,
			BigDecimal freqHz, String vendor, String note, Date validFrom,
			Date validTo, String changeByUser, Date changeDateTime,
			Date createdDateTime, String createdByUser,
			BigDecimal parentChKeySeq) {
		this.chKeySeq = chKeySeq;
		this.products = products;
		this.deliveryTypes = deliveryTypes;
		this.distributionNodes = distributionNodes;
		this.freqHz = freqHz;
		this.vendor = vendor;
		this.note = note;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.changeByUser = changeByUser;
		this.changeDateTime = changeDateTime;
		this.createdDateTime = createdDateTime;
		this.createdByUser = createdByUser;
		this.parentChKeySeq = parentChKeySeq;
	}

	@Id
	@Column(name = "CH_KEY_SEQ", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getChKeySeq() {
		return this.chKeySeq;
	}

	public void setChKeySeq(BigDecimal chKeySeq) {
		this.chKeySeq = chKeySeq;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DELIVERY_TYPE")
	public DeliveryTypes getDeliveryTypes() {
		return this.deliveryTypes;
	}

	public void setDeliveryTypes(DeliveryTypes deliveryTypes) {
		this.deliveryTypes = deliveryTypes;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NODE_ID")
	public DistributionNodes getDistributionNodes() {
		return this.distributionNodes;
	}

	public void setDistributionNodes(DistributionNodes distributionNodes) {
		this.distributionNodes = distributionNodes;
	}

	@Column(name = "FREQ_HZ", precision = 22, scale = 0)
	public BigDecimal getFreqHz() {
		return this.freqHz;
	}

	public void setFreqHz(BigDecimal freqHz) {
		this.freqHz = freqHz;
	}

	@Column(name = "VENDOR", length = 20)
	public String getVendor() {
		return this.vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	@Column(name = "NOTE")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VALID_FROM", length = 7)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VALID_TO", length = 7)
	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	@Column(name = "CHANGE_BY_USER", length = 20)
	public String getChangeByUser() {
		return this.changeByUser;
	}

	public void setChangeByUser(String changeByUser) {
		this.changeByUser = changeByUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHANGE_DATE_TIME", length = 7)
	public Date getChangeDateTime() {
		return this.changeDateTime;
	}

	public void setChangeDateTime(Date changeDateTime) {
		this.changeDateTime = changeDateTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE_TIME", length = 7)
	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	@Column(name = "CREATED_BY_USER", length = 20)
	public String getCreatedByUser() {
		return this.createdByUser;
	}

	public void setCreatedByUser(String createdByUser) {
		this.createdByUser = createdByUser;
	}

	@Column(name = "PARENT_CH_KEY_SEQ", precision = 22, scale = 0)
	public BigDecimal getParentChKeySeq() {
		return this.parentChKeySeq;
	}

	public void setParentChKeySeq(BigDecimal parentChKeySeq) {
		this.parentChKeySeq = parentChKeySeq;
	}

}
