package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChNodeKeysChghist generated by hbm2java
 */
@Entity
@Table(name = "CH_NODE_KEYS_CHGHIST", schema = "PCRM")
public class ChNodeKeysChghist implements java.io.Serializable {

	private String audId;
	private String audAction;
	private Serializable audTimestamp;
	private String audOsuser;
	private String audDbuser;
	private String audUserterminal;
	private BigDecimal chKeySeq;
	private BigDecimal freqHz;
	private int productId;
	private String vendor;
	private String deliveryType;
	private String note;
	private Date validFrom;
	private Date validTo;
	private String changeByUser;
	private Date changeDateTime;
	private Date createdDateTime;
	private String createdByUser;
	private Integer nodeId;
	private BigDecimal parentChKeySeq;

	public ChNodeKeysChghist() {
	}

	public ChNodeKeysChghist(String audId, int productId) {
		this.audId = audId;
		this.productId = productId;
	}

	public ChNodeKeysChghist(String audId, String audAction,
			Serializable audTimestamp, String audOsuser, String audDbuser,
			String audUserterminal, BigDecimal chKeySeq, BigDecimal freqHz,
			int productId, String vendor, String deliveryType, String note,
			Date validFrom, Date validTo, String changeByUser,
			Date changeDateTime, Date createdDateTime, String createdByUser,
			Integer nodeId, BigDecimal parentChKeySeq) {
		this.audId = audId;
		this.audAction = audAction;
		this.audTimestamp = audTimestamp;
		this.audOsuser = audOsuser;
		this.audDbuser = audDbuser;
		this.audUserterminal = audUserterminal;
		this.chKeySeq = chKeySeq;
		this.freqHz = freqHz;
		this.productId = productId;
		this.vendor = vendor;
		this.deliveryType = deliveryType;
		this.note = note;
		this.validFrom = validFrom;
		this.validTo = validTo;
		this.changeByUser = changeByUser;
		this.changeDateTime = changeDateTime;
		this.createdDateTime = createdDateTime;
		this.createdByUser = createdByUser;
		this.nodeId = nodeId;
		this.parentChKeySeq = parentChKeySeq;
	}

	@Id
	@Column(name = "AUD_ID", unique = true, nullable = false, length = 19)
	public String getAudId() {
		return this.audId;
	}

	public void setAudId(String audId) {
		this.audId = audId;
	}

	@Column(name = "AUD_ACTION", length = 50)
	public String getAudAction() {
		return this.audAction;
	}

	public void setAudAction(String audAction) {
		this.audAction = audAction;
	}

	@Column(name = "AUD_TIMESTAMP")
	public Serializable getAudTimestamp() {
		return this.audTimestamp;
	}

	public void setAudTimestamp(Serializable audTimestamp) {
		this.audTimestamp = audTimestamp;
	}

	@Column(name = "AUD_OSUSER", length = 50)
	public String getAudOsuser() {
		return this.audOsuser;
	}

	public void setAudOsuser(String audOsuser) {
		this.audOsuser = audOsuser;
	}

	@Column(name = "AUD_DBUSER", length = 50)
	public String getAudDbuser() {
		return this.audDbuser;
	}

	public void setAudDbuser(String audDbuser) {
		this.audDbuser = audDbuser;
	}

	@Column(name = "AUD_USERTERMINAL", length = 50)
	public String getAudUserterminal() {
		return this.audUserterminal;
	}

	public void setAudUserterminal(String audUserterminal) {
		this.audUserterminal = audUserterminal;
	}

	@Column(name = "CH_KEY_SEQ", precision = 22, scale = 0)
	public BigDecimal getChKeySeq() {
		return this.chKeySeq;
	}

	public void setChKeySeq(BigDecimal chKeySeq) {
		this.chKeySeq = chKeySeq;
	}

	@Column(name = "FREQ_HZ", precision = 22, scale = 0)
	public BigDecimal getFreqHz() {
		return this.freqHz;
	}

	public void setFreqHz(BigDecimal freqHz) {
		this.freqHz = freqHz;
	}

	@Column(name = "PRODUCT_ID", nullable = false, precision = 7, scale = 0)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "VENDOR", length = 20)
	public String getVendor() {
		return this.vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	@Column(name = "DELIVERY_TYPE", length = 20)
	public String getDeliveryType() {
		return this.deliveryType;
	}

	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}

	@Column(name = "NOTE")
	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VALID_FROM", length = 7)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VALID_TO", length = 7)
	public Date getValidTo() {
		return this.validTo;
	}

	public void setValidTo(Date validTo) {
		this.validTo = validTo;
	}

	@Column(name = "CHANGE_BY_USER", length = 20)
	public String getChangeByUser() {
		return this.changeByUser;
	}

	public void setChangeByUser(String changeByUser) {
		this.changeByUser = changeByUser;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CHANGE_DATE_TIME", length = 7)
	public Date getChangeDateTime() {
		return this.changeDateTime;
	}

	public void setChangeDateTime(Date changeDateTime) {
		this.changeDateTime = changeDateTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATED_DATE_TIME", length = 7)
	public Date getCreatedDateTime() {
		return this.createdDateTime;
	}

	public void setCreatedDateTime(Date createdDateTime) {
		this.createdDateTime = createdDateTime;
	}

	@Column(name = "CREATED_BY_USER", length = 20)
	public String getCreatedByUser() {
		return this.createdByUser;
	}

	public void setCreatedByUser(String createdByUser) {
		this.createdByUser = createdByUser;
	}

	@Column(name = "NODE_ID", precision = 9, scale = 0)
	public Integer getNodeId() {
		return this.nodeId;
	}

	public void setNodeId(Integer nodeId) {
		this.nodeId = nodeId;
	}

	@Column(name = "PARENT_CH_KEY_SEQ", precision = 22, scale = 0)
	public BigDecimal getParentChKeySeq() {
		return this.parentChKeySeq;
	}

	public void setParentChKeySeq(BigDecimal parentChKeySeq) {
		this.parentChKeySeq = parentChKeySeq;
	}

}
