package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Conceptconfig generated by hbm2java
 */
@Entity
@Table(name = "CONCEPTCONFIG", schema = "PCRM")
public class Conceptconfig implements java.io.Serializable {

	private String id;
	private Salesconcept salesconcept;
	private Configparameter configparameter;
	private Date crd;
	private String code;
	private Date impt;
	private Date expt;
	private Date impd;
	private Date expd;
	private Date modt;
	private String cru;
	private Date delt;
	private Date modd;
	private String impu;
	private String expu;
	private Date deld;
	private String modu;
	private String head;
	private String delu;
	private Date crt;
	private String infokategori;
	private String infogruppe;
	private String infovalgt;
	private Long sortering;
	private Character indgikonc;
	private Character chosen;
	private String primsalesprod;
	private String contentkey;
	private Set<Contractconfig> contractconfigs = new HashSet<Contractconfig>(0);

	public Conceptconfig() {
	}

	public Conceptconfig(String id) {
		this.id = id;
	}

	public Conceptconfig(String id, Salesconcept salesconcept,
			Configparameter configparameter, Date crd, String code, Date impt,
			Date expt, Date impd, Date expd, Date modt, String cru, Date delt,
			Date modd, String impu, String expu, Date deld, String modu,
			String head, String delu, Date crt, String infokategori,
			String infogruppe, String infovalgt, Long sortering,
			Character indgikonc, Character chosen, String primsalesprod,
			String contentkey, Set<Contractconfig> contractconfigs) {
		this.id = id;
		this.salesconcept = salesconcept;
		this.configparameter = configparameter;
		this.crd = crd;
		this.code = code;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.cru = cru;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.modu = modu;
		this.head = head;
		this.delu = delu;
		this.crt = crt;
		this.infokategori = infokategori;
		this.infogruppe = infogruppe;
		this.infovalgt = infovalgt;
		this.sortering = sortering;
		this.indgikonc = indgikonc;
		this.chosen = chosen;
		this.primsalesprod = primsalesprod;
		this.contentkey = contentkey;
		this.contractconfigs = contractconfigs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMSALGSKONC")
	public Salesconcept getSalesconcept() {
		return this.salesconcept;
	}

	public void setSalesconcept(Salesconcept salesconcept) {
		this.salesconcept = salesconcept;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMARYSALGSKONCEPTMULIGHED")
	public Configparameter getConfigparameter() {
		return this.configparameter;
	}

	public void setConfigparameter(Configparameter configparameter) {
		this.configparameter = configparameter;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CODE", length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "HEAD")
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "INFOKATEGORI", length = 30)
	public String getInfokategori() {
		return this.infokategori;
	}

	public void setInfokategori(String infokategori) {
		this.infokategori = infokategori;
	}

	@Column(name = "INFOGRUPPE", length = 30)
	public String getInfogruppe() {
		return this.infogruppe;
	}

	public void setInfogruppe(String infogruppe) {
		this.infogruppe = infogruppe;
	}

	@Column(name = "INFOVALGT", length = 40)
	public String getInfovalgt() {
		return this.infovalgt;
	}

	public void setInfovalgt(String infovalgt) {
		this.infovalgt = infovalgt;
	}

	@Column(name = "SORTERING", precision = 10, scale = 0)
	public Long getSortering() {
		return this.sortering;
	}

	public void setSortering(Long sortering) {
		this.sortering = sortering;
	}

	@Column(name = "INDGIKONC", length = 1)
	public Character getIndgikonc() {
		return this.indgikonc;
	}

	public void setIndgikonc(Character indgikonc) {
		this.indgikonc = indgikonc;
	}

	@Column(name = "CHOSEN", length = 1)
	public Character getChosen() {
		return this.chosen;
	}

	public void setChosen(Character chosen) {
		this.chosen = chosen;
	}

	@Column(name = "PRIMSALESPROD", length = 19)
	public String getPrimsalesprod() {
		return this.primsalesprod;
	}

	public void setPrimsalesprod(String primsalesprod) {
		this.primsalesprod = primsalesprod;
	}

	@Column(name = "CONTENTKEY", length = 128)
	public String getContentkey() {
		return this.contentkey;
	}

	public void setContentkey(String contentkey) {
		this.contentkey = contentkey;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conceptconfig")
	public Set<Contractconfig> getContractconfigs() {
		return this.contractconfigs;
	}

	public void setContractconfigs(Set<Contractconfig> contractconfigs) {
		this.contractconfigs = contractconfigs;
	}

}
