package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Configparametertype generated by hbm2java
 */
@Entity
@Table(name = "CONFIGPARAMETERTYPE", schema = "PCRM", uniqueConstraints = @UniqueConstraint(columnNames = "ORDER_NUMBER"))
public class Configparametertype implements java.io.Serializable {

	private String id;
	private Configparameter configparameter;
	private Date crd;
	private String code;
	private Date impt;
	private Date expt;
	private Date impd;
	private Date expd;
	private Date modt;
	private String cru;
	private Date delt;
	private Date modd;
	private String impu;
	private String expu;
	private Date deld;
	private String modu;
	private String head;
	private String delu;
	private Date crt;
	private Long sortering;
	private Character portalactive;
	private String contentkey;
	private String primsalesprod;
	private String oldcode;
	private Date startDate;
	private Date endDate;
	private String logtrace;
	private String primbusinesssphere;
	private Short priority;
	private Integer orderNumber;
	private String tooltip;
	private Character sgportal;
	private Set<Configparamtypecontlink> configparamtypecontlinks = new HashSet<Configparamtypecontlink>(
			0);
	private Set<Configparameter> configparameters = new HashSet<Configparameter>(
			0);
	private Set<CrSglocation2parametertype> crSglocation2parametertypes = new HashSet<CrSglocation2parametertype>(
			0);
	private Set<SolutionparametertypeOld> solutionparametertypeOlds = new HashSet<SolutionparametertypeOld>(
			0);

	public Configparametertype() {
	}

	public Configparametertype(String id) {
		this.id = id;
	}

	public Configparametertype(String id, Configparameter configparameter,
			Date crd, String code, Date impt, Date expt, Date impd, Date expd,
			Date modt, String cru, Date delt, Date modd, String impu,
			String expu, Date deld, String modu, String head, String delu,
			Date crt, Long sortering, Character portalactive,
			String contentkey, String primsalesprod, String oldcode,
			Date startDate, Date endDate, String logtrace,
			String primbusinesssphere, Short priority, Integer orderNumber,
			String tooltip, Character sgportal,
			Set<Configparamtypecontlink> configparamtypecontlinks,
			Set<Configparameter> configparameters,
			Set<CrSglocation2parametertype> crSglocation2parametertypes,
			Set<SolutionparametertypeOld> solutionparametertypeOlds) {
		this.id = id;
		this.configparameter = configparameter;
		this.crd = crd;
		this.code = code;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.cru = cru;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.modu = modu;
		this.head = head;
		this.delu = delu;
		this.crt = crt;
		this.sortering = sortering;
		this.portalactive = portalactive;
		this.contentkey = contentkey;
		this.primsalesprod = primsalesprod;
		this.oldcode = oldcode;
		this.startDate = startDate;
		this.endDate = endDate;
		this.logtrace = logtrace;
		this.primbusinesssphere = primbusinesssphere;
		this.priority = priority;
		this.orderNumber = orderNumber;
		this.tooltip = tooltip;
		this.sgportal = sgportal;
		this.configparamtypecontlinks = configparamtypecontlinks;
		this.configparameters = configparameters;
		this.crSglocation2parametertypes = crSglocation2parametertypes;
		this.solutionparametertypeOlds = solutionparametertypeOlds;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMCONFIGPARAMETER")
	public Configparameter getConfigparameter() {
		return this.configparameter;
	}

	public void setConfigparameter(Configparameter configparameter) {
		this.configparameter = configparameter;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CODE", length = 15)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "HEAD")
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "SORTERING", precision = 10, scale = 0)
	public Long getSortering() {
		return this.sortering;
	}

	public void setSortering(Long sortering) {
		this.sortering = sortering;
	}

	@Column(name = "PORTALACTIVE", length = 1)
	public Character getPortalactive() {
		return this.portalactive;
	}

	public void setPortalactive(Character portalactive) {
		this.portalactive = portalactive;
	}

	@Column(name = "CONTENTKEY", length = 128)
	public String getContentkey() {
		return this.contentkey;
	}

	public void setContentkey(String contentkey) {
		this.contentkey = contentkey;
	}

	@Column(name = "PRIMSALESPROD", length = 19)
	public String getPrimsalesprod() {
		return this.primsalesprod;
	}

	public void setPrimsalesprod(String primsalesprod) {
		this.primsalesprod = primsalesprod;
	}

	@Column(name = "OLDCODE", length = 15)
	public String getOldcode() {
		return this.oldcode;
	}

	public void setOldcode(String oldcode) {
		this.oldcode = oldcode;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "LOGTRACE", length = 19)
	public String getLogtrace() {
		return this.logtrace;
	}

	public void setLogtrace(String logtrace) {
		this.logtrace = logtrace;
	}

	@Column(name = "PRIMBUSINESSSPHERE", length = 19)
	public String getPrimbusinesssphere() {
		return this.primbusinesssphere;
	}

	public void setPrimbusinesssphere(String primbusinesssphere) {
		this.primbusinesssphere = primbusinesssphere;
	}

	@Column(name = "PRIORITY", precision = 3, scale = 0)
	public Short getPriority() {
		return this.priority;
	}

	public void setPriority(Short priority) {
		this.priority = priority;
	}

	@Column(name = "ORDER_NUMBER", unique = true, precision = 5, scale = 0)
	public Integer getOrderNumber() {
		return this.orderNumber;
	}

	public void setOrderNumber(Integer orderNumber) {
		this.orderNumber = orderNumber;
	}

	@Column(name = "TOOLTIP", length = 4000)
	public String getTooltip() {
		return this.tooltip;
	}

	public void setTooltip(String tooltip) {
		this.tooltip = tooltip;
	}

	@Column(name = "SGPORTAL", length = 1)
	public Character getSgportal() {
		return this.sgportal;
	}

	public void setSgportal(Character sgportal) {
		this.sgportal = sgportal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configparametertype")
	public Set<Configparamtypecontlink> getConfigparamtypecontlinks() {
		return this.configparamtypecontlinks;
	}

	public void setConfigparamtypecontlinks(
			Set<Configparamtypecontlink> configparamtypecontlinks) {
		this.configparamtypecontlinks = configparamtypecontlinks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configparametertype")
	public Set<Configparameter> getConfigparameters() {
		return this.configparameters;
	}

	public void setConfigparameters(Set<Configparameter> configparameters) {
		this.configparameters = configparameters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configparametertype")
	public Set<CrSglocation2parametertype> getCrSglocation2parametertypes() {
		return this.crSglocation2parametertypes;
	}

	public void setCrSglocation2parametertypes(
			Set<CrSglocation2parametertype> crSglocation2parametertypes) {
		this.crSglocation2parametertypes = crSglocation2parametertypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configparametertype")
	public Set<SolutionparametertypeOld> getSolutionparametertypeOlds() {
		return this.solutionparametertypeOlds;
	}

	public void setSolutionparametertypeOlds(
			Set<SolutionparametertypeOld> solutionparametertypeOlds) {
		this.solutionparametertypeOlds = solutionparametertypeOlds;
	}

}
