package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContractsectiontextOldId generated by hbm2java
 */
@Embeddable
public class ContractsectiontextOldId implements java.io.Serializable {

	private String id;
	private String com;
	private String seq;
	private String line;
	private String modts;
	private String modu;
	private String impts;
	private String impu;
	private String classname;

	public ContractsectiontextOldId() {
	}

	public ContractsectiontextOldId(String id, String com, String seq,
			String line, String modts, String modu, String impts, String impu,
			String classname) {
		this.id = id;
		this.com = com;
		this.seq = seq;
		this.line = line;
		this.modts = modts;
		this.modu = modu;
		this.impts = impts;
		this.impu = impu;
		this.classname = classname;
	}

	@Column(name = "ID", length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "COM", length = 15)
	public String getCom() {
		return this.com;
	}

	public void setCom(String com) {
		this.com = com;
	}

	@Column(name = "SEQ", length = 15)
	public String getSeq() {
		return this.seq;
	}

	public void setSeq(String seq) {
		this.seq = seq;
	}

	@Column(name = "LINE", length = 254)
	public String getLine() {
		return this.line;
	}

	public void setLine(String line) {
		this.line = line;
	}

	@Column(name = "MODTS", length = 13)
	public String getModts() {
		return this.modts;
	}

	public void setModts(String modts) {
		this.modts = modts;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "IMPTS", length = 13)
	public String getImpts() {
		return this.impts;
	}

	public void setImpts(String impts) {
		this.impts = impts;
	}

	@Column(name = "IMPU", length = 5)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "CLASSNAME", length = 254)
	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContractsectiontextOldId))
			return false;
		ContractsectiontextOldId castOther = (ContractsectiontextOldId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getCom() == castOther.getCom()) || (this.getCom() != null
						&& castOther.getCom() != null && this.getCom().equals(
						castOther.getCom())))
				&& ((this.getSeq() == castOther.getSeq()) || (this.getSeq() != null
						&& castOther.getSeq() != null && this.getSeq().equals(
						castOther.getSeq())))
				&& ((this.getLine() == castOther.getLine()) || (this.getLine() != null
						&& castOther.getLine() != null && this.getLine()
						.equals(castOther.getLine())))
				&& ((this.getModts() == castOther.getModts()) || (this
						.getModts() != null && castOther.getModts() != null && this
						.getModts().equals(castOther.getModts())))
				&& ((this.getModu() == castOther.getModu()) || (this.getModu() != null
						&& castOther.getModu() != null && this.getModu()
						.equals(castOther.getModu())))
				&& ((this.getImpts() == castOther.getImpts()) || (this
						.getImpts() != null && castOther.getImpts() != null && this
						.getImpts().equals(castOther.getImpts())))
				&& ((this.getImpu() == castOther.getImpu()) || (this.getImpu() != null
						&& castOther.getImpu() != null && this.getImpu()
						.equals(castOther.getImpu())))
				&& ((this.getClassname() == castOther.getClassname()) || (this
						.getClassname() != null
						&& castOther.getClassname() != null && this
						.getClassname().equals(castOther.getClassname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getCom() == null ? 0 : this.getCom().hashCode());
		result = 37 * result
				+ (getSeq() == null ? 0 : this.getSeq().hashCode());
		result = 37 * result
				+ (getLine() == null ? 0 : this.getLine().hashCode());
		result = 37 * result
				+ (getModts() == null ? 0 : this.getModts().hashCode());
		result = 37 * result
				+ (getModu() == null ? 0 : this.getModu().hashCode());
		result = 37 * result
				+ (getImpts() == null ? 0 : this.getImpts().hashCode());
		result = 37 * result
				+ (getImpu() == null ? 0 : this.getImpu().hashCode());
		result = 37 * result
				+ (getClassname() == null ? 0 : this.getClassname().hashCode());
		return result;
	}

}
