package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contract generated by hbm2java
 */
@Entity
@Table(name = "CONTRACT", schema = "PCRM")
public class Contract implements java.io.Serializable {

	private String id;
	private Offer offerByPrimtilbkontr;
	private Contract contract;
	private Generaltypevalue generaltypevalue;
	private Offer offerByPrimclosingtilbkontr;
	private CustomerDrop customerDrop;
	private String heading;
	private Date crd;
	private Date impt;
	private Date expt;
	private Date impd;
	private Date expd;
	private Date modt;
	private String cru;
	private Date delt;
	private Date modd;
	private String impu;
	private String expu;
	private Date deld;
	private String modu;
	private String delu;
	private Date crt;
	private String primanlxg;
	private Long rebmun;
	private Character active;
	private Date startdate;
	private Date enddate;
	private Set<Cableunit> cableunits = new HashSet<Cableunit>(0);
	private Set<Document> documents = new HashSet<Document>(0);
	private Set<Contract> contracts = new HashSet<Contract>(0);

	public Contract() {
	}

	public Contract(String id) {
		this.id = id;
	}

	public Contract(String id, Offer offerByPrimtilbkontr, Contract contract,
			Generaltypevalue generaltypevalue,
			Offer offerByPrimclosingtilbkontr, CustomerDrop customerDrop,
			String heading, Date crd, Date impt, Date expt, Date impd,
			Date expd, Date modt, String cru, Date delt, Date modd,
			String impu, String expu, Date deld, String modu, String delu,
			Date crt, String primanlxg, Long rebmun, Character active,
			Date startdate, Date enddate, Set<Cableunit> cableunits,
			Set<Document> documents, Set<Contract> contracts) {
		this.id = id;
		this.offerByPrimtilbkontr = offerByPrimtilbkontr;
		this.contract = contract;
		this.generaltypevalue = generaltypevalue;
		this.offerByPrimclosingtilbkontr = offerByPrimclosingtilbkontr;
		this.customerDrop = customerDrop;
		this.heading = heading;
		this.crd = crd;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.cru = cru;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.modu = modu;
		this.delu = delu;
		this.crt = crt;
		this.primanlxg = primanlxg;
		this.rebmun = rebmun;
		this.active = active;
		this.startdate = startdate;
		this.enddate = enddate;
		this.cableunits = cableunits;
		this.documents = documents;
		this.contracts = contracts;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMTILBKONTR")
	public Offer getOfferByPrimtilbkontr() {
		return this.offerByPrimtilbkontr;
	}

	public void setOfferByPrimtilbkontr(Offer offerByPrimtilbkontr) {
		this.offerByPrimtilbkontr = offerByPrimtilbkontr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMARYKONTRAKT")
	public Contract getContract() {
		return this.contract;
	}

	public void setContract(Contract contract) {
		this.contract = contract;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMGENERALTYPEVALUE")
	public Generaltypevalue getGeneraltypevalue() {
		return this.generaltypevalue;
	}

	public void setGeneraltypevalue(Generaltypevalue generaltypevalue) {
		this.generaltypevalue = generaltypevalue;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMCLOSINGTILBKONTR")
	public Offer getOfferByPrimclosingtilbkontr() {
		return this.offerByPrimclosingtilbkontr;
	}

	public void setOfferByPrimclosingtilbkontr(Offer offerByPrimclosingtilbkontr) {
		this.offerByPrimclosingtilbkontr = offerByPrimclosingtilbkontr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMARYCOMPANY")
	public CustomerDrop getCustomerDrop() {
		return this.customerDrop;
	}

	public void setCustomerDrop(CustomerDrop customerDrop) {
		this.customerDrop = customerDrop;
	}

	@Column(name = "HEADING")
	public String getHeading() {
		return this.heading;
	}

	public void setHeading(String heading) {
		this.heading = heading;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "PRIMANLXG", length = 10)
	public String getPrimanlxg() {
		return this.primanlxg;
	}

	public void setPrimanlxg(String primanlxg) {
		this.primanlxg = primanlxg;
	}

	@Column(name = "REBMUN", precision = 10, scale = 0)
	public Long getRebmun() {
		return this.rebmun;
	}

	public void setRebmun(Long rebmun) {
		this.rebmun = rebmun;
	}

	@Column(name = "ACTIVE", length = 1)
	public Character getActive() {
		return this.active;
	}

	public void setActive(Character active) {
		this.active = active;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STARTDATE", length = 7)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDATE", length = 7)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contract")
	public Set<Cableunit> getCableunits() {
		return this.cableunits;
	}

	public void setCableunits(Set<Cableunit> cableunits) {
		this.cableunits = cableunits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contract")
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contract")
	public Set<Contract> getContracts() {
		return this.contracts;
	}

	public void setContracts(Set<Contract> contracts) {
		this.contracts = contracts;
	}

}
