package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContractsectiontextOld generated by hbm2java
 */
@Entity
@Table(name = "CONTRACTSECTIONTEXT_OLD", schema = "PCRM")
public class ContractsectiontextOld implements java.io.Serializable {

	private ContractsectiontextOldId id;
	private Docsection docsection;

	public ContractsectiontextOld() {
	}

	public ContractsectiontextOld(ContractsectiontextOldId id) {
		this.id = id;
	}

	public ContractsectiontextOld(ContractsectiontextOldId id,
			Docsection docsection) {
		this.id = id;
		this.docsection = docsection;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", length = 19)),
			@AttributeOverride(name = "com", column = @Column(name = "COM", length = 15)),
			@AttributeOverride(name = "seq", column = @Column(name = "SEQ", length = 15)),
			@AttributeOverride(name = "line", column = @Column(name = "LINE", length = 254)),
			@AttributeOverride(name = "modts", column = @Column(name = "MODTS", length = 13)),
			@AttributeOverride(name = "modu", column = @Column(name = "MODU", length = 19)),
			@AttributeOverride(name = "impts", column = @Column(name = "IMPTS", length = 13)),
			@AttributeOverride(name = "impu", column = @Column(name = "IMPU", length = 5)),
			@AttributeOverride(name = "classname", column = @Column(name = "CLASSNAME", length = 254)) })
	public ContractsectiontextOldId getId() {
		return this.id;
	}

	public void setId(ContractsectiontextOldId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID", insertable = false, updatable = false)
	public Docsection getDocsection() {
		return this.docsection;
	}

	public void setDocsection(Docsection docsection) {
		this.docsection = docsection;
	}

}
