package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrDocsectionhead2origin generated by hbm2java
 */
@Entity
@Table(name = "CR_DOCSECTIONHEAD2ORIGIN", schema = "PCRM")
public class CrDocsectionhead2origin implements java.io.Serializable {

	private CrDocsectionhead2originId id;
	private Docsectionhead docsectionhead;
	private Docorigin docorigin;

	public CrDocsectionhead2origin() {
	}

	public CrDocsectionhead2origin(CrDocsectionhead2originId id,
			Docsectionhead docsectionhead, Docorigin docorigin) {
		this.id = id;
		this.docsectionhead = docsectionhead;
		this.docorigin = docorigin;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "primdocsectionhead", column = @Column(name = "PRIMDOCSECTIONHEAD", nullable = false, length = 19)),
			@AttributeOverride(name = "primdocorigin", column = @Column(name = "PRIMDOCORIGIN", nullable = false, length = 19)),
			@AttributeOverride(name = "logtrace", column = @Column(name = "LOGTRACE", length = 19)) })
	public CrDocsectionhead2originId getId() {
		return this.id;
	}

	public void setId(CrDocsectionhead2originId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMDOCSECTIONHEAD", nullable = false, insertable = false, updatable = false)
	public Docsectionhead getDocsectionhead() {
		return this.docsectionhead;
	}

	public void setDocsectionhead(Docsectionhead docsectionhead) {
		this.docsectionhead = docsectionhead;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMDOCORIGIN", nullable = false, insertable = false, updatable = false)
	public Docorigin getDocorigin() {
		return this.docorigin;
	}

	public void setDocorigin(Docorigin docorigin) {
		this.docorigin = docorigin;
	}

}
