package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrDocorigin2generaltypevalue generated by hbm2java
 */
@Entity
@Table(name = "CR_DOCORIGIN2GENERALTYPEVALUE", schema = "PCRM")
public class CrDocorigin2generaltypevalue implements java.io.Serializable {

	private CrDocorigin2generaltypevalueId id;
	private Docorigin docorigin;
	private Generaltypevalue generaltypevalue;

	public CrDocorigin2generaltypevalue() {
	}

	public CrDocorigin2generaltypevalue(CrDocorigin2generaltypevalueId id) {
		this.id = id;
	}

	public CrDocorigin2generaltypevalue(CrDocorigin2generaltypevalueId id,
			Docorigin docorigin, Generaltypevalue generaltypevalue) {
		this.id = id;
		this.docorigin = docorigin;
		this.generaltypevalue = generaltypevalue;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "primdocorigin", column = @Column(name = "PRIMDOCORIGIN", length = 19)),
			@AttributeOverride(name = "primgeneraltypevalue", column = @Column(name = "PRIMGENERALTYPEVALUE", length = 19)) })
	public CrDocorigin2generaltypevalueId getId() {
		return this.id;
	}

	public void setId(CrDocorigin2generaltypevalueId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMDOCORIGIN", insertable = false, updatable = false)
	public Docorigin getDocorigin() {
		return this.docorigin;
	}

	public void setDocorigin(Docorigin docorigin) {
		this.docorigin = docorigin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMGENERALTYPEVALUE", insertable = false, updatable = false)
	public Generaltypevalue getGeneraltypevalue() {
		return this.generaltypevalue;
	}

	public void setGeneraltypevalue(Generaltypevalue generaltypevalue) {
		this.generaltypevalue = generaltypevalue;
	}

}
