package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CrDoccomment2origin generated by hbm2java
 */
@Entity
@Table(name = "CR_DOCCOMMENT2ORIGIN", schema = "PCRM")
public class CrDoccomment2origin implements java.io.Serializable {

	private CrDoccomment2originId id;
	private Docorigin docorigin;
	private Doccomment doccomment;

	public CrDoccomment2origin() {
	}

	public CrDoccomment2origin(CrDoccomment2originId id, Docorigin docorigin,
			Doccomment doccomment) {
		this.id = id;
		this.docorigin = docorigin;
		this.doccomment = doccomment;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "primdoccomment", column = @Column(name = "PRIMDOCCOMMENT", nullable = false, length = 19)),
			@AttributeOverride(name = "primdocorigin", column = @Column(name = "PRIMDOCORIGIN", nullable = false, length = 19)),
			@AttributeOverride(name = "logtrace", column = @Column(name = "LOGTRACE", length = 19)) })
	public CrDoccomment2originId getId() {
		return this.id;
	}

	public void setId(CrDoccomment2originId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMDOCORIGIN", nullable = false, insertable = false, updatable = false)
	public Docorigin getDocorigin() {
		return this.docorigin;
	}

	public void setDocorigin(Docorigin docorigin) {
		this.docorigin = docorigin;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMDOCCOMMENT", nullable = false, insertable = false, updatable = false)
	public Doccomment getDoccomment() {
		return this.doccomment;
	}

	public void setDoccomment(Doccomment doccomment) {
		this.doccomment = doccomment;
	}

}
