package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CrSglocation2parametertype generated by hbm2java
 */
@Entity
@Table(name = "CR_SGLOCATION2PARAMETERTYPE", schema = "PCRM")
public class CrSglocation2parametertype implements java.io.Serializable {

	private String id;
	private Configparametertype configparametertype;
	private Sglocation sglocation;
	private Date crd;
	private Date impd;
	private Date expd;
	private String cru;
	private Date modd;
	private String impu;
	private String expu;
	private String modu;

	public CrSglocation2parametertype() {
	}

	public CrSglocation2parametertype(String id,
			Configparametertype configparametertype, Sglocation sglocation) {
		this.id = id;
		this.configparametertype = configparametertype;
		this.sglocation = sglocation;
	}

	public CrSglocation2parametertype(String id,
			Configparametertype configparametertype, Sglocation sglocation,
			Date crd, Date impd, Date expd, String cru, Date modd, String impu,
			String expu, String modu) {
		this.id = id;
		this.configparametertype = configparametertype;
		this.sglocation = sglocation;
		this.crd = crd;
		this.impd = impd;
		this.expd = expd;
		this.cru = cru;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.modu = modu;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMCONFIGPARAMETERTYPE", nullable = false)
	public Configparametertype getConfigparametertype() {
		return this.configparametertype;
	}

	public void setConfigparametertype(Configparametertype configparametertype) {
		this.configparametertype = configparametertype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMSGLOCATION", nullable = false)
	public Sglocation getSglocation() {
		return this.sglocation;
	}

	public void setSglocation(Sglocation sglocation) {
		this.sglocation = sglocation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

}
