package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerDrop generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMER_DROP", schema = "PCRM")
public class CustomerDrop implements java.io.Serializable {

	private String id;
	private Staff staff;
	private Segmentgroup segmentgroup;
	private CustomerDrop customerDrop;
	private String cdd;
	private String categorytotal;
	private String job;
	private String primpricelist;
	private String primlang;
	private Date crt;
	private String creditcardexpiremonth;
	private String name;
	private Long salesytd;
	private Long lysalesytd;
	private Character fokus;
	private Long prognose;
	private String addr2;
	private String creditrating;
	private String alias;
	private Date modd;
	private Character notdublet;
	private String billingaddress3;
	private String homepage;
	private String billingattention;
	private Character mailstop;
	private String primcont;
	private Character customer;
	private Date impt;
	private Long won;
	private String billingname;
	private String billingaddress4;
	private String creditcardexpireyear;
	private Date impd;
	private Date expt;
	private Integer employed;
	private Long lost;
	private String fax;
	private String custno;
	private Date expd;
	private String primcurrency;
	private String primshowaccountinthiscurrency;
	private String company;
	private String seekstring;
	private Date delt;
	private String primarybillingcountry;
	private String email;
	private String addr3;
	private Date deld;
	private String name2;
	private String secondcont;
	private String billingtown;
	private String primsour;
	private String category;
	private Long inprocess;
	private String creditcardnumber;
	private String billingaddress1;
	private Long salesly;
	private String impu;
	private String koncern;
	private String creditcardholder;
	private String telex;
	private String primgroup;
	private String primaryuserdepartment;
	private String duns;
	private String billingaddress2;
	private String expu;
	private String categorycalc;
	private Date modt;
	private Integer funk;
	private String delu;
	private String webpassword;
	private String primuser;
	private String addr1;
	private Long turnover;
	private String primcoun;
	private String creditcardverificationcode;
	private String postcode;
	private String addr4;
	private String phone;
	private Date crd;
	private String cru;
	private String town;
	private String primarypostcode;
	private String billingphone;
	private String primcreditcardtype;
	private Short cyklus;
	private String billingpostcode;
	private String modu;
	private String XSourceSystem;
	private String XKundeId;
	private String XKundeforholdId;
	private String primdwa;
	private Character active;
	private String primarykonsulent1;
	private String primarykonsulent2;
	private String primarykonsulent3;
	private String primarynysalgskonsulent;
	private String primarygensalgskonsulent;
	private String primarykam;
	private Long estkundetilfredshed;
	private Character fdamedlem;
	private Character ksbehandling;
	private String mancategory;
	private Character blmedlem;
	private Character skyggekunde;
	private String primaltdwa;
	private String primaltcomp;
	private String primarytilfredshed;
	private String logtrace;
	private Character dktvmail;
	private String dktvmailaddress;
	private Long addressid;
	private Set<Document> documents = new HashSet<Document>(0);
	private Set<Cableunit> cableunits = new HashSet<Cableunit>(0);
	private Set<Contract> contracts = new HashSet<Contract>(0);
	private Set<CustomervaluelinkDrop> customervaluelinkDrops = new HashSet<CustomervaluelinkDrop>(
			0);
	private Set<Product> products = new HashSet<Product>(0);
	private Set<CustomerDrop> customerDrops = new HashSet<CustomerDrop>(0);
	private Set<Casefolder> casefolders = new HashSet<Casefolder>(0);
	private Set<Supplierlink> supplierlinks = new HashSet<Supplierlink>(0);

	public CustomerDrop() {
	}

	public CustomerDrop(String id) {
		this.id = id;
	}

	public CustomerDrop(String id, Staff staff, Segmentgroup segmentgroup,
			CustomerDrop customerDrop, String cdd, String categorytotal,
			String job, String primpricelist, String primlang, Date crt,
			String creditcardexpiremonth, String name, Long salesytd,
			Long lysalesytd, Character fokus, Long prognose, String addr2,
			String creditrating, String alias, Date modd, Character notdublet,
			String billingaddress3, String homepage, String billingattention,
			Character mailstop, String primcont, Character customer, Date impt,
			Long won, String billingname, String billingaddress4,
			String creditcardexpireyear, Date impd, Date expt,
			Integer employed, Long lost, String fax, String custno, Date expd,
			String primcurrency, String primshowaccountinthiscurrency,
			String company, String seekstring, Date delt,
			String primarybillingcountry, String email, String addr3,
			Date deld, String name2, String secondcont, String billingtown,
			String primsour, String category, Long inprocess,
			String creditcardnumber, String billingaddress1, Long salesly,
			String impu, String koncern, String creditcardholder, String telex,
			String primgroup, String primaryuserdepartment, String duns,
			String billingaddress2, String expu, String categorycalc,
			Date modt, Integer funk, String delu, String webpassword,
			String primuser, String addr1, Long turnover, String primcoun,
			String creditcardverificationcode, String postcode, String addr4,
			String phone, Date crd, String cru, String town,
			String primarypostcode, String billingphone,
			String primcreditcardtype, Short cyklus, String billingpostcode,
			String modu, String XSourceSystem, String XKundeId,
			String XKundeforholdId, String primdwa, Character active,
			String primarykonsulent1, String primarykonsulent2,
			String primarykonsulent3, String primarynysalgskonsulent,
			String primarygensalgskonsulent, String primarykam,
			Long estkundetilfredshed, Character fdamedlem,
			Character ksbehandling, String mancategory, Character blmedlem,
			Character skyggekunde, String primaltdwa, String primaltcomp,
			String primarytilfredshed, String logtrace, Character dktvmail,
			String dktvmailaddress, Long addressid, Set<Document> documents,
			Set<Cableunit> cableunits, Set<Contract> contracts,
			Set<CustomervaluelinkDrop> customervaluelinkDrops,
			Set<Product> products, Set<CustomerDrop> customerDrops,
			Set<Casefolder> casefolders, Set<Supplierlink> supplierlinks) {
		this.id = id;
		this.staff = staff;
		this.segmentgroup = segmentgroup;
		this.customerDrop = customerDrop;
		this.cdd = cdd;
		this.categorytotal = categorytotal;
		this.job = job;
		this.primpricelist = primpricelist;
		this.primlang = primlang;
		this.crt = crt;
		this.creditcardexpiremonth = creditcardexpiremonth;
		this.name = name;
		this.salesytd = salesytd;
		this.lysalesytd = lysalesytd;
		this.fokus = fokus;
		this.prognose = prognose;
		this.addr2 = addr2;
		this.creditrating = creditrating;
		this.alias = alias;
		this.modd = modd;
		this.notdublet = notdublet;
		this.billingaddress3 = billingaddress3;
		this.homepage = homepage;
		this.billingattention = billingattention;
		this.mailstop = mailstop;
		this.primcont = primcont;
		this.customer = customer;
		this.impt = impt;
		this.won = won;
		this.billingname = billingname;
		this.billingaddress4 = billingaddress4;
		this.creditcardexpireyear = creditcardexpireyear;
		this.impd = impd;
		this.expt = expt;
		this.employed = employed;
		this.lost = lost;
		this.fax = fax;
		this.custno = custno;
		this.expd = expd;
		this.primcurrency = primcurrency;
		this.primshowaccountinthiscurrency = primshowaccountinthiscurrency;
		this.company = company;
		this.seekstring = seekstring;
		this.delt = delt;
		this.primarybillingcountry = primarybillingcountry;
		this.email = email;
		this.addr3 = addr3;
		this.deld = deld;
		this.name2 = name2;
		this.secondcont = secondcont;
		this.billingtown = billingtown;
		this.primsour = primsour;
		this.category = category;
		this.inprocess = inprocess;
		this.creditcardnumber = creditcardnumber;
		this.billingaddress1 = billingaddress1;
		this.salesly = salesly;
		this.impu = impu;
		this.koncern = koncern;
		this.creditcardholder = creditcardholder;
		this.telex = telex;
		this.primgroup = primgroup;
		this.primaryuserdepartment = primaryuserdepartment;
		this.duns = duns;
		this.billingaddress2 = billingaddress2;
		this.expu = expu;
		this.categorycalc = categorycalc;
		this.modt = modt;
		this.funk = funk;
		this.delu = delu;
		this.webpassword = webpassword;
		this.primuser = primuser;
		this.addr1 = addr1;
		this.turnover = turnover;
		this.primcoun = primcoun;
		this.creditcardverificationcode = creditcardverificationcode;
		this.postcode = postcode;
		this.addr4 = addr4;
		this.phone = phone;
		this.crd = crd;
		this.cru = cru;
		this.town = town;
		this.primarypostcode = primarypostcode;
		this.billingphone = billingphone;
		this.primcreditcardtype = primcreditcardtype;
		this.cyklus = cyklus;
		this.billingpostcode = billingpostcode;
		this.modu = modu;
		this.XSourceSystem = XSourceSystem;
		this.XKundeId = XKundeId;
		this.XKundeforholdId = XKundeforholdId;
		this.primdwa = primdwa;
		this.active = active;
		this.primarykonsulent1 = primarykonsulent1;
		this.primarykonsulent2 = primarykonsulent2;
		this.primarykonsulent3 = primarykonsulent3;
		this.primarynysalgskonsulent = primarynysalgskonsulent;
		this.primarygensalgskonsulent = primarygensalgskonsulent;
		this.primarykam = primarykam;
		this.estkundetilfredshed = estkundetilfredshed;
		this.fdamedlem = fdamedlem;
		this.ksbehandling = ksbehandling;
		this.mancategory = mancategory;
		this.blmedlem = blmedlem;
		this.skyggekunde = skyggekunde;
		this.primaltdwa = primaltdwa;
		this.primaltcomp = primaltcomp;
		this.primarytilfredshed = primarytilfredshed;
		this.logtrace = logtrace;
		this.dktvmail = dktvmail;
		this.dktvmailaddress = dktvmailaddress;
		this.addressid = addressid;
		this.documents = documents;
		this.cableunits = cableunits;
		this.contracts = contracts;
		this.customervaluelinkDrops = customervaluelinkDrops;
		this.products = products;
		this.customerDrops = customerDrops;
		this.casefolders = casefolders;
		this.supplierlinks = supplierlinks;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMSALESRESPONSIBLE")
	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMSEGMGROUP")
	public Segmentgroup getSegmentgroup() {
		return this.segmentgroup;
	}

	public void setSegmentgroup(Segmentgroup segmentgroup) {
		this.segmentgroup = segmentgroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMCOMP")
	public CustomerDrop getCustomerDrop() {
		return this.customerDrop;
	}

	public void setCustomerDrop(CustomerDrop customerDrop) {
		this.customerDrop = customerDrop;
	}

	@Column(name = "CDD", length = 19)
	public String getCdd() {
		return this.cdd;
	}

	public void setCdd(String cdd) {
		this.cdd = cdd;
	}

	@Column(name = "CATEGORYTOTAL", length = 1)
	public String getCategorytotal() {
		return this.categorytotal;
	}

	public void setCategorytotal(String categorytotal) {
		this.categorytotal = categorytotal;
	}

	@Column(name = "JOB", length = 35)
	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	@Column(name = "PRIMPRICELIST", length = 19)
	public String getPrimpricelist() {
		return this.primpricelist;
	}

	public void setPrimpricelist(String primpricelist) {
		this.primpricelist = primpricelist;
	}

	@Column(name = "PRIMLANG", length = 19)
	public String getPrimlang() {
		return this.primlang;
	}

	public void setPrimlang(String primlang) {
		this.primlang = primlang;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "CREDITCARDEXPIREMONTH", length = 2)
	public String getCreditcardexpiremonth() {
		return this.creditcardexpiremonth;
	}

	public void setCreditcardexpiremonth(String creditcardexpiremonth) {
		this.creditcardexpiremonth = creditcardexpiremonth;
	}

	@Column(name = "NAME", length = 35)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SALESYTD", precision = 10, scale = 0)
	public Long getSalesytd() {
		return this.salesytd;
	}

	public void setSalesytd(Long salesytd) {
		this.salesytd = salesytd;
	}

	@Column(name = "LYSALESYTD", precision = 10, scale = 0)
	public Long getLysalesytd() {
		return this.lysalesytd;
	}

	public void setLysalesytd(Long lysalesytd) {
		this.lysalesytd = lysalesytd;
	}

	@Column(name = "FOKUS", length = 1)
	public Character getFokus() {
		return this.fokus;
	}

	public void setFokus(Character fokus) {
		this.fokus = fokus;
	}

	@Column(name = "PROGNOSE", precision = 10, scale = 0)
	public Long getPrognose() {
		return this.prognose;
	}

	public void setPrognose(Long prognose) {
		this.prognose = prognose;
	}

	@Column(name = "ADDR2", length = 35)
	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	@Column(name = "CREDITRATING", length = 10)
	public String getCreditrating() {
		return this.creditrating;
	}

	public void setCreditrating(String creditrating) {
		this.creditrating = creditrating;
	}

	@Column(name = "ALIAS", length = 35)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "NOTDUBLET", length = 1)
	public Character getNotdublet() {
		return this.notdublet;
	}

	public void setNotdublet(Character notdublet) {
		this.notdublet = notdublet;
	}

	@Column(name = "BILLINGADDRESS3", length = 35)
	public String getBillingaddress3() {
		return this.billingaddress3;
	}

	public void setBillingaddress3(String billingaddress3) {
		this.billingaddress3 = billingaddress3;
	}

	@Column(name = "HOMEPAGE", length = 50)
	public String getHomepage() {
		return this.homepage;
	}

	public void setHomepage(String homepage) {
		this.homepage = homepage;
	}

	@Column(name = "BILLINGATTENTION", length = 35)
	public String getBillingattention() {
		return this.billingattention;
	}

	public void setBillingattention(String billingattention) {
		this.billingattention = billingattention;
	}

	@Column(name = "MAILSTOP", length = 1)
	public Character getMailstop() {
		return this.mailstop;
	}

	public void setMailstop(Character mailstop) {
		this.mailstop = mailstop;
	}

	@Column(name = "PRIMCONT", length = 19)
	public String getPrimcont() {
		return this.primcont;
	}

	public void setPrimcont(String primcont) {
		this.primcont = primcont;
	}

	@Column(name = "CUSTOMER", length = 1)
	public Character getCustomer() {
		return this.customer;
	}

	public void setCustomer(Character customer) {
		this.customer = customer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Column(name = "WON", precision = 10, scale = 0)
	public Long getWon() {
		return this.won;
	}

	public void setWon(Long won) {
		this.won = won;
	}

	@Column(name = "BILLINGNAME", length = 60)
	public String getBillingname() {
		return this.billingname;
	}

	public void setBillingname(String billingname) {
		this.billingname = billingname;
	}

	@Column(name = "BILLINGADDRESS4", length = 35)
	public String getBillingaddress4() {
		return this.billingaddress4;
	}

	public void setBillingaddress4(String billingaddress4) {
		this.billingaddress4 = billingaddress4;
	}

	@Column(name = "CREDITCARDEXPIREYEAR", length = 4)
	public String getCreditcardexpireyear() {
		return this.creditcardexpireyear;
	}

	public void setCreditcardexpireyear(String creditcardexpireyear) {
		this.creditcardexpireyear = creditcardexpireyear;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Column(name = "EMPLOYED", precision = 6, scale = 0)
	public Integer getEmployed() {
		return this.employed;
	}

	public void setEmployed(Integer employed) {
		this.employed = employed;
	}

	@Column(name = "LOST", precision = 10, scale = 0)
	public Long getLost() {
		return this.lost;
	}

	public void setLost(Long lost) {
		this.lost = lost;
	}

	@Column(name = "FAX", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "CUSTNO", length = 20)
	public String getCustno() {
		return this.custno;
	}

	public void setCustno(String custno) {
		this.custno = custno;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "PRIMCURRENCY", length = 19)
	public String getPrimcurrency() {
		return this.primcurrency;
	}

	public void setPrimcurrency(String primcurrency) {
		this.primcurrency = primcurrency;
	}

	@Column(name = "PRIMSHOWACCOUNTINTHISCURRENCY", length = 19)
	public String getPrimshowaccountinthiscurrency() {
		return this.primshowaccountinthiscurrency;
	}

	public void setPrimshowaccountinthiscurrency(
			String primshowaccountinthiscurrency) {
		this.primshowaccountinthiscurrency = primshowaccountinthiscurrency;
	}

	@Column(name = "COMPANY")
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "SEEKSTRING", length = 50)
	public String getSeekstring() {
		return this.seekstring;
	}

	public void setSeekstring(String seekstring) {
		this.seekstring = seekstring;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Column(name = "PRIMARYBILLINGCOUNTRY", length = 19)
	public String getPrimarybillingcountry() {
		return this.primarybillingcountry;
	}

	public void setPrimarybillingcountry(String primarybillingcountry) {
		this.primarybillingcountry = primarybillingcountry;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ADDR3", length = 35)
	public String getAddr3() {
		return this.addr3;
	}

	public void setAddr3(String addr3) {
		this.addr3 = addr3;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "NAME2", length = 35)
	public String getName2() {
		return this.name2;
	}

	public void setName2(String name2) {
		this.name2 = name2;
	}

	@Column(name = "SECONDCONT", length = 19)
	public String getSecondcont() {
		return this.secondcont;
	}

	public void setSecondcont(String secondcont) {
		this.secondcont = secondcont;
	}

	@Column(name = "BILLINGTOWN", length = 35)
	public String getBillingtown() {
		return this.billingtown;
	}

	public void setBillingtown(String billingtown) {
		this.billingtown = billingtown;
	}

	@Column(name = "PRIMSOUR", length = 19)
	public String getPrimsour() {
		return this.primsour;
	}

	public void setPrimsour(String primsour) {
		this.primsour = primsour;
	}

	@Column(name = "CATEGORY", length = 1)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "INPROCESS", precision = 10, scale = 0)
	public Long getInprocess() {
		return this.inprocess;
	}

	public void setInprocess(Long inprocess) {
		this.inprocess = inprocess;
	}

	@Column(name = "CREDITCARDNUMBER", length = 19)
	public String getCreditcardnumber() {
		return this.creditcardnumber;
	}

	public void setCreditcardnumber(String creditcardnumber) {
		this.creditcardnumber = creditcardnumber;
	}

	@Column(name = "BILLINGADDRESS1", length = 35)
	public String getBillingaddress1() {
		return this.billingaddress1;
	}

	public void setBillingaddress1(String billingaddress1) {
		this.billingaddress1 = billingaddress1;
	}

	@Column(name = "SALESLY", precision = 10, scale = 0)
	public Long getSalesly() {
		return this.salesly;
	}

	public void setSalesly(Long salesly) {
		this.salesly = salesly;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "KONCERN", length = 10)
	public String getKoncern() {
		return this.koncern;
	}

	public void setKoncern(String koncern) {
		this.koncern = koncern;
	}

	@Column(name = "CREDITCARDHOLDER", length = 50)
	public String getCreditcardholder() {
		return this.creditcardholder;
	}

	public void setCreditcardholder(String creditcardholder) {
		this.creditcardholder = creditcardholder;
	}

	@Column(name = "TELEX", length = 20)
	public String getTelex() {
		return this.telex;
	}

	public void setTelex(String telex) {
		this.telex = telex;
	}

	@Column(name = "PRIMGROUP", length = 19)
	public String getPrimgroup() {
		return this.primgroup;
	}

	public void setPrimgroup(String primgroup) {
		this.primgroup = primgroup;
	}

	@Column(name = "PRIMARYUSERDEPARTMENT", length = 19)
	public String getPrimaryuserdepartment() {
		return this.primaryuserdepartment;
	}

	public void setPrimaryuserdepartment(String primaryuserdepartment) {
		this.primaryuserdepartment = primaryuserdepartment;
	}

	@Column(name = "DUNS", length = 19)
	public String getDuns() {
		return this.duns;
	}

	public void setDuns(String duns) {
		this.duns = duns;
	}

	@Column(name = "BILLINGADDRESS2", length = 35)
	public String getBillingaddress2() {
		return this.billingaddress2;
	}

	public void setBillingaddress2(String billingaddress2) {
		this.billingaddress2 = billingaddress2;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "CATEGORYCALC", length = 1)
	public String getCategorycalc() {
		return this.categorycalc;
	}

	public void setCategorycalc(String categorycalc) {
		this.categorycalc = categorycalc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "FUNK", precision = 5, scale = 0)
	public Integer getFunk() {
		return this.funk;
	}

	public void setFunk(Integer funk) {
		this.funk = funk;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Column(name = "WEBPASSWORD", length = 254)
	public String getWebpassword() {
		return this.webpassword;
	}

	public void setWebpassword(String webpassword) {
		this.webpassword = webpassword;
	}

	@Column(name = "PRIMUSER", length = 19)
	public String getPrimuser() {
		return this.primuser;
	}

	public void setPrimuser(String primuser) {
		this.primuser = primuser;
	}

	@Column(name = "ADDR1", length = 35)
	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	@Column(name = "TURNOVER", precision = 10, scale = 0)
	public Long getTurnover() {
		return this.turnover;
	}

	public void setTurnover(Long turnover) {
		this.turnover = turnover;
	}

	@Column(name = "PRIMCOUN", length = 19)
	public String getPrimcoun() {
		return this.primcoun;
	}

	public void setPrimcoun(String primcoun) {
		this.primcoun = primcoun;
	}

	@Column(name = "CREDITCARDVERIFICATIONCODE", length = 3)
	public String getCreditcardverificationcode() {
		return this.creditcardverificationcode;
	}

	public void setCreditcardverificationcode(String creditcardverificationcode) {
		this.creditcardverificationcode = creditcardverificationcode;
	}

	@Column(name = "POSTCODE", length = 15)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "ADDR4", length = 35)
	public String getAddr4() {
		return this.addr4;
	}

	public void setAddr4(String addr4) {
		this.addr4 = addr4;
	}

	@Column(name = "PHONE", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Column(name = "TOWN", length = 35)
	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	@Column(name = "PRIMARYPOSTCODE", length = 19)
	public String getPrimarypostcode() {
		return this.primarypostcode;
	}

	public void setPrimarypostcode(String primarypostcode) {
		this.primarypostcode = primarypostcode;
	}

	@Column(name = "BILLINGPHONE", length = 25)
	public String getBillingphone() {
		return this.billingphone;
	}

	public void setBillingphone(String billingphone) {
		this.billingphone = billingphone;
	}

	@Column(name = "PRIMCREDITCARDTYPE", length = 19)
	public String getPrimcreditcardtype() {
		return this.primcreditcardtype;
	}

	public void setPrimcreditcardtype(String primcreditcardtype) {
		this.primcreditcardtype = primcreditcardtype;
	}

	@Column(name = "CYKLUS", precision = 3, scale = 0)
	public Short getCyklus() {
		return this.cyklus;
	}

	public void setCyklus(Short cyklus) {
		this.cyklus = cyklus;
	}

	@Column(name = "BILLINGPOSTCODE", length = 10)
	public String getBillingpostcode() {
		return this.billingpostcode;
	}

	public void setBillingpostcode(String billingpostcode) {
		this.billingpostcode = billingpostcode;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "X_SOURCE_SYSTEM", length = 5)
	public String getXSourceSystem() {
		return this.XSourceSystem;
	}

	public void setXSourceSystem(String XSourceSystem) {
		this.XSourceSystem = XSourceSystem;
	}

	@Column(name = "X_KUNDE_ID", length = 10)
	public String getXKundeId() {
		return this.XKundeId;
	}

	public void setXKundeId(String XKundeId) {
		this.XKundeId = XKundeId;
	}

	@Column(name = "X_KUNDEFORHOLD_ID", length = 10)
	public String getXKundeforholdId() {
		return this.XKundeforholdId;
	}

	public void setXKundeforholdId(String XKundeforholdId) {
		this.XKundeforholdId = XKundeforholdId;
	}

	@Column(name = "PRIMDWA", length = 22)
	public String getPrimdwa() {
		return this.primdwa;
	}

	public void setPrimdwa(String primdwa) {
		this.primdwa = primdwa;
	}

	@Column(name = "ACTIVE", length = 1)
	public Character getActive() {
		return this.active;
	}

	public void setActive(Character active) {
		this.active = active;
	}

	@Column(name = "PRIMARYKONSULENT1", length = 19)
	public String getPrimarykonsulent1() {
		return this.primarykonsulent1;
	}

	public void setPrimarykonsulent1(String primarykonsulent1) {
		this.primarykonsulent1 = primarykonsulent1;
	}

	@Column(name = "PRIMARYKONSULENT2", length = 19)
	public String getPrimarykonsulent2() {
		return this.primarykonsulent2;
	}

	public void setPrimarykonsulent2(String primarykonsulent2) {
		this.primarykonsulent2 = primarykonsulent2;
	}

	@Column(name = "PRIMARYKONSULENT3", length = 19)
	public String getPrimarykonsulent3() {
		return this.primarykonsulent3;
	}

	public void setPrimarykonsulent3(String primarykonsulent3) {
		this.primarykonsulent3 = primarykonsulent3;
	}

	@Column(name = "PRIMARYNYSALGSKONSULENT", length = 19)
	public String getPrimarynysalgskonsulent() {
		return this.primarynysalgskonsulent;
	}

	public void setPrimarynysalgskonsulent(String primarynysalgskonsulent) {
		this.primarynysalgskonsulent = primarynysalgskonsulent;
	}

	@Column(name = "PRIMARYGENSALGSKONSULENT", length = 19)
	public String getPrimarygensalgskonsulent() {
		return this.primarygensalgskonsulent;
	}

	public void setPrimarygensalgskonsulent(String primarygensalgskonsulent) {
		this.primarygensalgskonsulent = primarygensalgskonsulent;
	}

	@Column(name = "PRIMARYKAM", length = 19)
	public String getPrimarykam() {
		return this.primarykam;
	}

	public void setPrimarykam(String primarykam) {
		this.primarykam = primarykam;
	}

	@Column(name = "ESTKUNDETILFREDSHED", precision = 10, scale = 0)
	public Long getEstkundetilfredshed() {
		return this.estkundetilfredshed;
	}

	public void setEstkundetilfredshed(Long estkundetilfredshed) {
		this.estkundetilfredshed = estkundetilfredshed;
	}

	@Column(name = "FDAMEDLEM", length = 1)
	public Character getFdamedlem() {
		return this.fdamedlem;
	}

	public void setFdamedlem(Character fdamedlem) {
		this.fdamedlem = fdamedlem;
	}

	@Column(name = "KSBEHANDLING", length = 1)
	public Character getKsbehandling() {
		return this.ksbehandling;
	}

	public void setKsbehandling(Character ksbehandling) {
		this.ksbehandling = ksbehandling;
	}

	@Column(name = "MANCATEGORY", length = 1)
	public String getMancategory() {
		return this.mancategory;
	}

	public void setMancategory(String mancategory) {
		this.mancategory = mancategory;
	}

	@Column(name = "BLMEDLEM", length = 1)
	public Character getBlmedlem() {
		return this.blmedlem;
	}

	public void setBlmedlem(Character blmedlem) {
		this.blmedlem = blmedlem;
	}

	@Column(name = "SKYGGEKUNDE", length = 1)
	public Character getSkyggekunde() {
		return this.skyggekunde;
	}

	public void setSkyggekunde(Character skyggekunde) {
		this.skyggekunde = skyggekunde;
	}

	@Column(name = "PRIMALTDWA", length = 22)
	public String getPrimaltdwa() {
		return this.primaltdwa;
	}

	public void setPrimaltdwa(String primaltdwa) {
		this.primaltdwa = primaltdwa;
	}

	@Column(name = "PRIMALTCOMP", length = 19)
	public String getPrimaltcomp() {
		return this.primaltcomp;
	}

	public void setPrimaltcomp(String primaltcomp) {
		this.primaltcomp = primaltcomp;
	}

	@Column(name = "PRIMARYTILFREDSHED", length = 19)
	public String getPrimarytilfredshed() {
		return this.primarytilfredshed;
	}

	public void setPrimarytilfredshed(String primarytilfredshed) {
		this.primarytilfredshed = primarytilfredshed;
	}

	@Column(name = "LOGTRACE", length = 19)
	public String getLogtrace() {
		return this.logtrace;
	}

	public void setLogtrace(String logtrace) {
		this.logtrace = logtrace;
	}

	@Column(name = "DKTVMAIL", length = 1)
	public Character getDktvmail() {
		return this.dktvmail;
	}

	public void setDktvmail(Character dktvmail) {
		this.dktvmail = dktvmail;
	}

	@Column(name = "DKTVMAILADDRESS", length = 50)
	public String getDktvmailaddress() {
		return this.dktvmailaddress;
	}

	public void setDktvmailaddress(String dktvmailaddress) {
		this.dktvmailaddress = dktvmailaddress;
	}

	@Column(name = "ADDRESSID", precision = 10, scale = 0)
	public Long getAddressid() {
		return this.addressid;
	}

	public void setAddressid(Long addressid) {
		this.addressid = addressid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerDrop")
	public Set<Document> getDocuments() {
		return this.documents;
	}

	public void setDocuments(Set<Document> documents) {
		this.documents = documents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerDrop")
	public Set<Cableunit> getCableunits() {
		return this.cableunits;
	}

	public void setCableunits(Set<Cableunit> cableunits) {
		this.cableunits = cableunits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerDrop")
	public Set<Contract> getContracts() {
		return this.contracts;
	}

	public void setContracts(Set<Contract> contracts) {
		this.contracts = contracts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerDrop")
	public Set<CustomervaluelinkDrop> getCustomervaluelinkDrops() {
		return this.customervaluelinkDrops;
	}

	public void setCustomervaluelinkDrops(
			Set<CustomervaluelinkDrop> customervaluelinkDrops) {
		this.customervaluelinkDrops = customervaluelinkDrops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerDrop")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerDrop")
	public Set<CustomerDrop> getCustomerDrops() {
		return this.customerDrops;
	}

	public void setCustomerDrops(Set<CustomerDrop> customerDrops) {
		this.customerDrops = customerDrops;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerDrop")
	public Set<Casefolder> getCasefolders() {
		return this.casefolders;
	}

	public void setCasefolders(Set<Casefolder> casefolders) {
		this.casefolders = casefolders;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customerDrop")
	public Set<Supplierlink> getSupplierlinks() {
		return this.supplierlinks;
	}

	public void setSupplierlinks(Set<Supplierlink> supplierlinks) {
		this.supplierlinks = supplierlinks;
	}

}
