package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Decoder generated by hbm2java
 */
@Entity
@Table(name = "DECODER", schema = "PCRM")
public class Decoder implements java.io.Serializable {

	private String id;
	private Date crd;
	private Date crt;
	private String cru;
	private Date impt;
	private Date impd;
	private String impu;
	private Date expt;
	private Date expd;
	private String expu;
	private Date modd;
	private Date modt;
	private String modu;
	private Date deld;
	private Date delt;
	private String delu;
	private String primanlaeg;
	private String key2rule;
	private String code;
	private String heading;
	private String cammodul;
	private String dekodertype;
	private String dekoderserienr;
	private Set<Cableunit> cableunits = new HashSet<Cableunit>(0);

	public Decoder() {
	}

	public Decoder(String id) {
		this.id = id;
	}

	public Decoder(String id, Date crd, Date crt, String cru, Date impt,
			Date impd, String impu, Date expt, Date expd, String expu,
			Date modd, Date modt, String modu, Date deld, Date delt,
			String delu, String primanlaeg, String key2rule, String code,
			String heading, String cammodul, String dekodertype,
			String dekoderserienr, Set<Cableunit> cableunits) {
		this.id = id;
		this.crd = crd;
		this.crt = crt;
		this.cru = cru;
		this.impt = impt;
		this.impd = impd;
		this.impu = impu;
		this.expt = expt;
		this.expd = expd;
		this.expu = expu;
		this.modd = modd;
		this.modt = modt;
		this.modu = modu;
		this.deld = deld;
		this.delt = delt;
		this.delu = delu;
		this.primanlaeg = primanlaeg;
		this.key2rule = key2rule;
		this.code = code;
		this.heading = heading;
		this.cammodul = cammodul;
		this.dekodertype = dekodertype;
		this.dekoderserienr = dekoderserienr;
		this.cableunits = cableunits;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Column(name = "PRIMANLAEG", length = 10)
	public String getPrimanlaeg() {
		return this.primanlaeg;
	}

	public void setPrimanlaeg(String primanlaeg) {
		this.primanlaeg = primanlaeg;
	}

	@Column(name = "KEY2RULE", length = 65)
	public String getKey2rule() {
		return this.key2rule;
	}

	public void setKey2rule(String key2rule) {
		this.key2rule = key2rule;
	}

	@Column(name = "CODE", length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "HEADING")
	public String getHeading() {
		return this.heading;
	}

	public void setHeading(String heading) {
		this.heading = heading;
	}

	@Column(name = "CAMMODUL", length = 100)
	public String getCammodul() {
		return this.cammodul;
	}

	public void setCammodul(String cammodul) {
		this.cammodul = cammodul;
	}

	@Column(name = "DEKODERTYPE", length = 100)
	public String getDekodertype() {
		return this.dekodertype;
	}

	public void setDekodertype(String dekodertype) {
		this.dekodertype = dekodertype;
	}

	@Column(name = "DEKODERSERIENR", length = 100)
	public String getDekoderserienr() {
		return this.dekoderserienr;
	}

	public void setDekoderserienr(String dekoderserienr) {
		this.dekoderserienr = dekoderserienr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "decoder")
	public Set<Cableunit> getCableunits() {
		return this.cableunits;
	}

	public void setCableunits(Set<Cableunit> cableunits) {
		this.cableunits = cableunits;
	}

}
