package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeliveryTypes generated by hbm2java
 */
@Entity
@Table(name = "DELIVERY_TYPES", schema = "PCRM")
public class DeliveryTypes implements java.io.Serializable {

	private String deliveryType;
	private String cru;
	private Date crd;
	private String modu;
	private Date modd;
	private String deliveryDescription;
	private Date startDate;
	private Date endDate;
	private Set<ChNodeKeys> chNodeKeyses = new HashSet<ChNodeKeys>(0);

	public DeliveryTypes() {
	}

	public DeliveryTypes(String deliveryType) {
		this.deliveryType = deliveryType;
	}

	public DeliveryTypes(String deliveryType, String cru, Date crd,
			String modu, Date modd, String deliveryDescription, Date startDate,
			Date endDate, Set<ChNodeKeys> chNodeKeyses) {
		this.deliveryType = deliveryType;
		this.cru = cru;
		this.crd = crd;
		this.modu = modu;
		this.modd = modd;
		this.deliveryDescription = deliveryDescription;
		this.startDate = startDate;
		this.endDate = endDate;
		this.chNodeKeyses = chNodeKeyses;
	}

	@Id
	@Column(name = "DELIVERY_TYPE", unique = true, nullable = false, length = 8)
	public String getDeliveryType() {
		return this.deliveryType;
	}

	public void setDeliveryType(String deliveryType) {
		this.deliveryType = deliveryType;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "DELIVERY_DESCRIPTION", length = 20)
	public String getDeliveryDescription() {
		return this.deliveryDescription;
	}

	public void setDeliveryDescription(String deliveryDescription) {
		this.deliveryDescription = deliveryDescription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deliveryTypes")
	public Set<ChNodeKeys> getChNodeKeyses() {
		return this.chNodeKeyses;
	}

	public void setChNodeKeyses(Set<ChNodeKeys> chNodeKeyses) {
		this.chNodeKeyses = chNodeKeyses;
	}

}
