package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.sql.Clob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Docsection generated by hbm2java
 */
@Entity
@Table(name = "DOCSECTION", schema = "PCRM", uniqueConstraints = {
		@UniqueConstraint(columnNames = { "USERKEY", "PRIMPARAHEAD" }),
		@UniqueConstraint(columnNames = "CODE") })
public class Docsection implements java.io.Serializable {

	private String id;
	private Docsectionhead docsectionhead;
	private Date crd;
	private String code;
	private Date impt;
	private Date expt;
	private Date impd;
	private Date expd;
	private Date modt;
	private String cru;
	private Date delt;
	private Date modd;
	private String impu;
	private String expu;
	private Date deld;
	private String modu;
	private String head;
	private String delu;
	private Date crt;
	private BigDecimal versionsnr;
	private Date versioneretdato;
	private String primaryoriginal;
	private Clob afsnit;
	private String primsuccessor;
	private Date verdate;
	private Character nytafsnit;
	private Character nyversion;
	private Character nyvariant;
	private String afsnit1;
	private Date startDate;
	private Date endDate;
	private String userkey;
	private String logtrace;
	private Set<Conceptdocconfig> conceptdocconfigs = new HashSet<Conceptdocconfig>(
			0);
	private Set<CrDocsection2parameter> crDocsection2parameters = new HashSet<CrDocsection2parameter>(
			0);
	private Set<CrDocsection2origin> crDocsection2origins = new HashSet<CrDocsection2origin>(
			0);
	private Set<ContractversionsectionOld> contractversionsectionOlds = new HashSet<ContractversionsectionOld>(
			0);
	private Set<ContractsectiontextOld> contractsectiontextOlds = new HashSet<ContractsectiontextOld>(
			0);
	private Set<Contractconfig> contractconfigs = new HashSet<Contractconfig>(0);

	public Docsection() {
	}

	public Docsection(String id, String code, String userkey) {
		this.id = id;
		this.code = code;
		this.userkey = userkey;
	}

	public Docsection(String id, Docsectionhead docsectionhead, Date crd,
			String code, Date impt, Date expt, Date impd, Date expd, Date modt,
			String cru, Date delt, Date modd, String impu, String expu,
			Date deld, String modu, String head, String delu, Date crt,
			BigDecimal versionsnr, Date versioneretdato,
			String primaryoriginal, Clob afsnit, String primsuccessor,
			Date verdate, Character nytafsnit, Character nyversion,
			Character nyvariant, String afsnit1, Date startDate, Date endDate,
			String userkey, String logtrace,
			Set<Conceptdocconfig> conceptdocconfigs,
			Set<CrDocsection2parameter> crDocsection2parameters,
			Set<CrDocsection2origin> crDocsection2origins,
			Set<ContractversionsectionOld> contractversionsectionOlds,
			Set<ContractsectiontextOld> contractsectiontextOlds,
			Set<Contractconfig> contractconfigs) {
		this.id = id;
		this.docsectionhead = docsectionhead;
		this.crd = crd;
		this.code = code;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.cru = cru;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.modu = modu;
		this.head = head;
		this.delu = delu;
		this.crt = crt;
		this.versionsnr = versionsnr;
		this.versioneretdato = versioneretdato;
		this.primaryoriginal = primaryoriginal;
		this.afsnit = afsnit;
		this.primsuccessor = primsuccessor;
		this.verdate = verdate;
		this.nytafsnit = nytafsnit;
		this.nyversion = nyversion;
		this.nyvariant = nyvariant;
		this.afsnit1 = afsnit1;
		this.startDate = startDate;
		this.endDate = endDate;
		this.userkey = userkey;
		this.logtrace = logtrace;
		this.conceptdocconfigs = conceptdocconfigs;
		this.crDocsection2parameters = crDocsection2parameters;
		this.crDocsection2origins = crDocsection2origins;
		this.contractversionsectionOlds = contractversionsectionOlds;
		this.contractsectiontextOlds = contractsectiontextOlds;
		this.contractconfigs = contractconfigs;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMPARAHEAD")
	public Docsectionhead getDocsectionhead() {
		return this.docsectionhead;
	}

	public void setDocsectionhead(Docsectionhead docsectionhead) {
		this.docsectionhead = docsectionhead;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CODE", unique = true, nullable = false, length = 25)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "HEAD")
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "VERSIONSNR", precision = 10)
	public BigDecimal getVersionsnr() {
		return this.versionsnr;
	}

	public void setVersionsnr(BigDecimal versionsnr) {
		this.versionsnr = versionsnr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VERSIONERETDATO", length = 7)
	public Date getVersioneretdato() {
		return this.versioneretdato;
	}

	public void setVersioneretdato(Date versioneretdato) {
		this.versioneretdato = versioneretdato;
	}

	@Column(name = "PRIMARYORIGINAL", length = 19)
	public String getPrimaryoriginal() {
		return this.primaryoriginal;
	}

	public void setPrimaryoriginal(String primaryoriginal) {
		this.primaryoriginal = primaryoriginal;
	}

	@Column(name = "AFSNIT")
	public Clob getAfsnit() {
		return this.afsnit;
	}

	public void setAfsnit(Clob afsnit) {
		this.afsnit = afsnit;
	}

	@Column(name = "PRIMSUCCESSOR", length = 19)
	public String getPrimsuccessor() {
		return this.primsuccessor;
	}

	public void setPrimsuccessor(String primsuccessor) {
		this.primsuccessor = primsuccessor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VERDATE", length = 7)
	public Date getVerdate() {
		return this.verdate;
	}

	public void setVerdate(Date verdate) {
		this.verdate = verdate;
	}

	@Column(name = "NYTAFSNIT", length = 1)
	public Character getNytafsnit() {
		return this.nytafsnit;
	}

	public void setNytafsnit(Character nytafsnit) {
		this.nytafsnit = nytafsnit;
	}

	@Column(name = "NYVERSION", length = 1)
	public Character getNyversion() {
		return this.nyversion;
	}

	public void setNyversion(Character nyversion) {
		this.nyversion = nyversion;
	}

	@Column(name = "NYVARIANT", length = 1)
	public Character getNyvariant() {
		return this.nyvariant;
	}

	public void setNyvariant(Character nyvariant) {
		this.nyvariant = nyvariant;
	}

	@Column(name = "AFSNIT1", length = 4000)
	public String getAfsnit1() {
		return this.afsnit1;
	}

	public void setAfsnit1(String afsnit1) {
		this.afsnit1 = afsnit1;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "USERKEY", nullable = false, length = 25)
	public String getUserkey() {
		return this.userkey;
	}

	public void setUserkey(String userkey) {
		this.userkey = userkey;
	}

	@Column(name = "LOGTRACE", length = 19)
	public String getLogtrace() {
		return this.logtrace;
	}

	public void setLogtrace(String logtrace) {
		this.logtrace = logtrace;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docsection")
	public Set<Conceptdocconfig> getConceptdocconfigs() {
		return this.conceptdocconfigs;
	}

	public void setConceptdocconfigs(Set<Conceptdocconfig> conceptdocconfigs) {
		this.conceptdocconfigs = conceptdocconfigs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docsection")
	public Set<CrDocsection2parameter> getCrDocsection2parameters() {
		return this.crDocsection2parameters;
	}

	public void setCrDocsection2parameters(
			Set<CrDocsection2parameter> crDocsection2parameters) {
		this.crDocsection2parameters = crDocsection2parameters;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docsection")
	public Set<CrDocsection2origin> getCrDocsection2origins() {
		return this.crDocsection2origins;
	}

	public void setCrDocsection2origins(
			Set<CrDocsection2origin> crDocsection2origins) {
		this.crDocsection2origins = crDocsection2origins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docsection")
	public Set<ContractversionsectionOld> getContractversionsectionOlds() {
		return this.contractversionsectionOlds;
	}

	public void setContractversionsectionOlds(
			Set<ContractversionsectionOld> contractversionsectionOlds) {
		this.contractversionsectionOlds = contractversionsectionOlds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docsection")
	public Set<ContractsectiontextOld> getContractsectiontextOlds() {
		return this.contractsectiontextOlds;
	}

	public void setContractsectiontextOlds(
			Set<ContractsectiontextOld> contractsectiontextOlds) {
		this.contractsectiontextOlds = contractsectiontextOlds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docsection")
	public Set<Contractconfig> getContractconfigs() {
		return this.contractconfigs;
	}

	public void setContractconfigs(Set<Contractconfig> contractconfigs) {
		this.contractconfigs = contractconfigs;
	}

}
