package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DocumentsCenta1Id generated by hbm2java
 */
@Embeddable
public class DocumentsCenta1Id implements java.io.Serializable {

	private BigDecimal nodeid;
	private BigDecimal documentid;
	private BigDecimal contentsize;
	private String fileextension;
	private String timestampcol;
	private Long filedby;
	private Date fileddate;
	private String authortxt;
	private Date authordate;
	private Long active;
	private Long version;
	private Long parentversion;
	private String title;
	private Long documenttype;
	private String externalid;
	private Long conflicting;
	private String md5;
	private Date deleted;
	private Long conflictresolved;
	private Long storagetype;
	private String originalmd5;

	public DocumentsCenta1Id() {
	}

	public DocumentsCenta1Id(BigDecimal nodeid, BigDecimal documentid,
			BigDecimal contentsize, String fileextension, String timestampcol,
			Long filedby, Date fileddate, String authortxt, Date authordate,
			Long active, Long version, Long parentversion, String title,
			Long documenttype, String externalid, Long conflicting, String md5,
			Date deleted, Long conflictresolved, Long storagetype,
			String originalmd5) {
		this.nodeid = nodeid;
		this.documentid = documentid;
		this.contentsize = contentsize;
		this.fileextension = fileextension;
		this.timestampcol = timestampcol;
		this.filedby = filedby;
		this.fileddate = fileddate;
		this.authortxt = authortxt;
		this.authordate = authordate;
		this.active = active;
		this.version = version;
		this.parentversion = parentversion;
		this.title = title;
		this.documenttype = documenttype;
		this.externalid = externalid;
		this.conflicting = conflicting;
		this.md5 = md5;
		this.deleted = deleted;
		this.conflictresolved = conflictresolved;
		this.storagetype = storagetype;
		this.originalmd5 = originalmd5;
	}

	@Column(name = "NODEID", precision = 22, scale = 0)
	public BigDecimal getNodeid() {
		return this.nodeid;
	}

	public void setNodeid(BigDecimal nodeid) {
		this.nodeid = nodeid;
	}

	@Column(name = "DOCUMENTID", precision = 22, scale = 0)
	public BigDecimal getDocumentid() {
		return this.documentid;
	}

	public void setDocumentid(BigDecimal documentid) {
		this.documentid = documentid;
	}

	@Column(name = "CONTENTSIZE", precision = 22, scale = 0)
	public BigDecimal getContentsize() {
		return this.contentsize;
	}

	public void setContentsize(BigDecimal contentsize) {
		this.contentsize = contentsize;
	}

	@Column(name = "FILEEXTENSION", length = 10)
	public String getFileextension() {
		return this.fileextension;
	}

	public void setFileextension(String fileextension) {
		this.fileextension = fileextension;
	}

	@Column(name = "TIMESTAMPCOL", length = 3000)
	public String getTimestampcol() {
		return this.timestampcol;
	}

	public void setTimestampcol(String timestampcol) {
		this.timestampcol = timestampcol;
	}

	@Column(name = "FILEDBY", precision = 10, scale = 0)
	public Long getFiledby() {
		return this.filedby;
	}

	public void setFiledby(Long filedby) {
		this.filedby = filedby;
	}

	@Column(name = "FILEDDATE", length = 7)
	public Date getFileddate() {
		return this.fileddate;
	}

	public void setFileddate(Date fileddate) {
		this.fileddate = fileddate;
	}

	@Column(name = "AUTHORTXT")
	public String getAuthortxt() {
		return this.authortxt;
	}

	public void setAuthortxt(String authortxt) {
		this.authortxt = authortxt;
	}

	@Column(name = "AUTHORDATE", length = 7)
	public Date getAuthordate() {
		return this.authordate;
	}

	public void setAuthordate(Date authordate) {
		this.authordate = authordate;
	}

	@Column(name = "ACTIVE", precision = 10, scale = 0)
	public Long getActive() {
		return this.active;
	}

	public void setActive(Long active) {
		this.active = active;
	}

	@Column(name = "VERSION", precision = 10, scale = 0)
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(name = "PARENTVERSION", precision = 10, scale = 0)
	public Long getParentversion() {
		return this.parentversion;
	}

	public void setParentversion(Long parentversion) {
		this.parentversion = parentversion;
	}

	@Column(name = "TITLE")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "DOCUMENTTYPE", precision = 10, scale = 0)
	public Long getDocumenttype() {
		return this.documenttype;
	}

	public void setDocumenttype(Long documenttype) {
		this.documenttype = documenttype;
	}

	@Column(name = "EXTERNALID")
	public String getExternalid() {
		return this.externalid;
	}

	public void setExternalid(String externalid) {
		this.externalid = externalid;
	}

	@Column(name = "CONFLICTING", precision = 10, scale = 0)
	public Long getConflicting() {
		return this.conflicting;
	}

	public void setConflicting(Long conflicting) {
		this.conflicting = conflicting;
	}

	@Column(name = "MD5", length = 50)
	public String getMd5() {
		return this.md5;
	}

	public void setMd5(String md5) {
		this.md5 = md5;
	}

	@Column(name = "DELETED", length = 7)
	public Date getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}

	@Column(name = "CONFLICTRESOLVED", precision = 10, scale = 0)
	public Long getConflictresolved() {
		return this.conflictresolved;
	}

	public void setConflictresolved(Long conflictresolved) {
		this.conflictresolved = conflictresolved;
	}

	@Column(name = "STORAGETYPE", precision = 10, scale = 0)
	public Long getStoragetype() {
		return this.storagetype;
	}

	public void setStoragetype(Long storagetype) {
		this.storagetype = storagetype;
	}

	@Column(name = "ORIGINALMD5", length = 50)
	public String getOriginalmd5() {
		return this.originalmd5;
	}

	public void setOriginalmd5(String originalmd5) {
		this.originalmd5 = originalmd5;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DocumentsCenta1Id))
			return false;
		DocumentsCenta1Id castOther = (DocumentsCenta1Id) other;

		return ((this.getNodeid() == castOther.getNodeid()) || (this
				.getNodeid() != null && castOther.getNodeid() != null && this
				.getNodeid().equals(castOther.getNodeid())))
				&& ((this.getDocumentid() == castOther.getDocumentid()) || (this
						.getDocumentid() != null
						&& castOther.getDocumentid() != null && this
						.getDocumentid().equals(castOther.getDocumentid())))
				&& ((this.getContentsize() == castOther.getContentsize()) || (this
						.getContentsize() != null
						&& castOther.getContentsize() != null && this
						.getContentsize().equals(castOther.getContentsize())))
				&& ((this.getFileextension() == castOther.getFileextension()) || (this
						.getFileextension() != null
						&& castOther.getFileextension() != null && this
						.getFileextension()
						.equals(castOther.getFileextension())))
				&& ((this.getTimestampcol() == castOther.getTimestampcol()) || (this
						.getTimestampcol() != null
						&& castOther.getTimestampcol() != null && this
						.getTimestampcol().equals(castOther.getTimestampcol())))
				&& ((this.getFiledby() == castOther.getFiledby()) || (this
						.getFiledby() != null && castOther.getFiledby() != null && this
						.getFiledby().equals(castOther.getFiledby())))
				&& ((this.getFileddate() == castOther.getFileddate()) || (this
						.getFileddate() != null
						&& castOther.getFileddate() != null && this
						.getFileddate().equals(castOther.getFileddate())))
				&& ((this.getAuthortxt() == castOther.getAuthortxt()) || (this
						.getAuthortxt() != null
						&& castOther.getAuthortxt() != null && this
						.getAuthortxt().equals(castOther.getAuthortxt())))
				&& ((this.getAuthordate() == castOther.getAuthordate()) || (this
						.getAuthordate() != null
						&& castOther.getAuthordate() != null && this
						.getAuthordate().equals(castOther.getAuthordate())))
				&& ((this.getActive() == castOther.getActive()) || (this
						.getActive() != null && castOther.getActive() != null && this
						.getActive().equals(castOther.getActive())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getParentversion() == castOther.getParentversion()) || (this
						.getParentversion() != null
						&& castOther.getParentversion() != null && this
						.getParentversion()
						.equals(castOther.getParentversion())))
				&& ((this.getTitle() == castOther.getTitle()) || (this
						.getTitle() != null && castOther.getTitle() != null && this
						.getTitle().equals(castOther.getTitle())))
				&& ((this.getDocumenttype() == castOther.getDocumenttype()) || (this
						.getDocumenttype() != null
						&& castOther.getDocumenttype() != null && this
						.getDocumenttype().equals(castOther.getDocumenttype())))
				&& ((this.getExternalid() == castOther.getExternalid()) || (this
						.getExternalid() != null
						&& castOther.getExternalid() != null && this
						.getExternalid().equals(castOther.getExternalid())))
				&& ((this.getConflicting() == castOther.getConflicting()) || (this
						.getConflicting() != null
						&& castOther.getConflicting() != null && this
						.getConflicting().equals(castOther.getConflicting())))
				&& ((this.getMd5() == castOther.getMd5()) || (this.getMd5() != null
						&& castOther.getMd5() != null && this.getMd5().equals(
						castOther.getMd5())))
				&& ((this.getDeleted() == castOther.getDeleted()) || (this
						.getDeleted() != null && castOther.getDeleted() != null && this
						.getDeleted().equals(castOther.getDeleted())))
				&& ((this.getConflictresolved() == castOther
						.getConflictresolved()) || (this.getConflictresolved() != null
						&& castOther.getConflictresolved() != null && this
						.getConflictresolved().equals(
								castOther.getConflictresolved())))
				&& ((this.getStoragetype() == castOther.getStoragetype()) || (this
						.getStoragetype() != null
						&& castOther.getStoragetype() != null && this
						.getStoragetype().equals(castOther.getStoragetype())))
				&& ((this.getOriginalmd5() == castOther.getOriginalmd5()) || (this
						.getOriginalmd5() != null
						&& castOther.getOriginalmd5() != null && this
						.getOriginalmd5().equals(castOther.getOriginalmd5())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getNodeid() == null ? 0 : this.getNodeid().hashCode());
		result = 37
				* result
				+ (getDocumentid() == null ? 0 : this.getDocumentid()
						.hashCode());
		result = 37
				* result
				+ (getContentsize() == null ? 0 : this.getContentsize()
						.hashCode());
		result = 37
				* result
				+ (getFileextension() == null ? 0 : this.getFileextension()
						.hashCode());
		result = 37
				* result
				+ (getTimestampcol() == null ? 0 : this.getTimestampcol()
						.hashCode());
		result = 37 * result
				+ (getFiledby() == null ? 0 : this.getFiledby().hashCode());
		result = 37 * result
				+ (getFileddate() == null ? 0 : this.getFileddate().hashCode());
		result = 37 * result
				+ (getAuthortxt() == null ? 0 : this.getAuthortxt().hashCode());
		result = 37
				* result
				+ (getAuthordate() == null ? 0 : this.getAuthordate()
						.hashCode());
		result = 37 * result
				+ (getActive() == null ? 0 : this.getActive().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37
				* result
				+ (getParentversion() == null ? 0 : this.getParentversion()
						.hashCode());
		result = 37 * result
				+ (getTitle() == null ? 0 : this.getTitle().hashCode());
		result = 37
				* result
				+ (getDocumenttype() == null ? 0 : this.getDocumenttype()
						.hashCode());
		result = 37
				* result
				+ (getExternalid() == null ? 0 : this.getExternalid()
						.hashCode());
		result = 37
				* result
				+ (getConflicting() == null ? 0 : this.getConflicting()
						.hashCode());
		result = 37 * result
				+ (getMd5() == null ? 0 : this.getMd5().hashCode());
		result = 37 * result
				+ (getDeleted() == null ? 0 : this.getDeleted().hashCode());
		result = 37
				* result
				+ (getConflictresolved() == null ? 0 : this
						.getConflictresolved().hashCode());
		result = 37
				* result
				+ (getStoragetype() == null ? 0 : this.getStoragetype()
						.hashCode());
		result = 37
				* result
				+ (getOriginalmd5() == null ? 0 : this.getOriginalmd5()
						.hashCode());
		return result;
	}

}
