package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Enumtypeitems generated by hbm2java
 */
@Entity
@Table(name = "ENUMTYPEITEMS", schema = "PCRM")
public class Enumtypeitems implements java.io.Serializable {

	private EnumtypeitemsId id;

	public Enumtypeitems() {
	}

	public Enumtypeitems(EnumtypeitemsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", precision = 10, scale = 0)),
			@AttributeOverride(name = "typeid", column = @Column(name = "TYPEID", length = 40)),
			@AttributeOverride(name = "code", column = @Column(name = "CODE", precision = 10, scale = 0)),
			@AttributeOverride(name = "title", column = @Column(name = "TITLE", length = 40)),
			@AttributeOverride(name = "description", column = @Column(name = "DESCRIPTION")),
			@AttributeOverride(name = "priority", column = @Column(name = "PRIORITY", precision = 10, scale = 0)),
			@AttributeOverride(name = "active", column = @Column(name = "ACTIVE", precision = 10, scale = 0)) })
	public EnumtypeitemsId getId() {
		return this.id;
	}

	public void setId(EnumtypeitemsId id) {
		this.id = id;
	}

}
