package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Esdhcasebase generated by hbm2java
 */
@Entity
@Table(name = "ESDHCASEBASE", schema = "PCRM")
public class Esdhcasebase implements java.io.Serializable {

	private BigDecimal nodeid;
	private String title;
	private Long createdby;
	private Date createddate;
	private Long closedby;
	private Date closeddate;
	private Long status;
	private Date lastaccessed;
	private Long nextdossiernumber;
	private Long casenumber;
	private Long categoryid;
	private String casetype;
	private Date lastupdated;
	private BigDecimal cableunitno;
	private String cableunitprojno;
	private BigDecimal offereecustid;
	private String worksmartcaseno;
	private String worksmartstate;
	private String worksmartcategory;
	private BigDecimal subscribercustid;
	private BigDecimal hierarchycustid;
	private BigDecimal mainswitchid;
	private String fileserverpath;
	private Date worksmartdateupdated;

	public Esdhcasebase() {
	}

	public Esdhcasebase(BigDecimal nodeid) {
		this.nodeid = nodeid;
	}

	public Esdhcasebase(BigDecimal nodeid, String title, Long createdby,
			Date createddate, Long closedby, Date closeddate, Long status,
			Date lastaccessed, Long nextdossiernumber, Long casenumber,
			Long categoryid, String casetype, Date lastupdated,
			BigDecimal cableunitno, String cableunitprojno,
			BigDecimal offereecustid, String worksmartcaseno,
			String worksmartstate, String worksmartcategory,
			BigDecimal subscribercustid, BigDecimal hierarchycustid,
			BigDecimal mainswitchid, String fileserverpath,
			Date worksmartdateupdated) {
		this.nodeid = nodeid;
		this.title = title;
		this.createdby = createdby;
		this.createddate = createddate;
		this.closedby = closedby;
		this.closeddate = closeddate;
		this.status = status;
		this.lastaccessed = lastaccessed;
		this.nextdossiernumber = nextdossiernumber;
		this.casenumber = casenumber;
		this.categoryid = categoryid;
		this.casetype = casetype;
		this.lastupdated = lastupdated;
		this.cableunitno = cableunitno;
		this.cableunitprojno = cableunitprojno;
		this.offereecustid = offereecustid;
		this.worksmartcaseno = worksmartcaseno;
		this.worksmartstate = worksmartstate;
		this.worksmartcategory = worksmartcategory;
		this.subscribercustid = subscribercustid;
		this.hierarchycustid = hierarchycustid;
		this.mainswitchid = mainswitchid;
		this.fileserverpath = fileserverpath;
		this.worksmartdateupdated = worksmartdateupdated;
	}

	@Id
	@Column(name = "NODEID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getNodeid() {
		return this.nodeid;
	}

	public void setNodeid(BigDecimal nodeid) {
		this.nodeid = nodeid;
	}

	@Column(name = "TITLE", length = 256)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "CREATEDBY", precision = 10, scale = 0)
	public Long getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(Long createdby) {
		this.createdby = createdby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CREATEDDATE", length = 7)
	public Date getCreateddate() {
		return this.createddate;
	}

	public void setCreateddate(Date createddate) {
		this.createddate = createddate;
	}

	@Column(name = "CLOSEDBY", precision = 10, scale = 0)
	public Long getClosedby() {
		return this.closedby;
	}

	public void setClosedby(Long closedby) {
		this.closedby = closedby;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CLOSEDDATE", length = 7)
	public Date getCloseddate() {
		return this.closeddate;
	}

	public void setCloseddate(Date closeddate) {
		this.closeddate = closeddate;
	}

	@Column(name = "STATUS", precision = 10, scale = 0)
	public Long getStatus() {
		return this.status;
	}

	public void setStatus(Long status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LASTACCESSED", length = 7)
	public Date getLastaccessed() {
		return this.lastaccessed;
	}

	public void setLastaccessed(Date lastaccessed) {
		this.lastaccessed = lastaccessed;
	}

	@Column(name = "NEXTDOSSIERNUMBER", precision = 10, scale = 0)
	public Long getNextdossiernumber() {
		return this.nextdossiernumber;
	}

	public void setNextdossiernumber(Long nextdossiernumber) {
		this.nextdossiernumber = nextdossiernumber;
	}

	@Column(name = "CASENUMBER", precision = 10, scale = 0)
	public Long getCasenumber() {
		return this.casenumber;
	}

	public void setCasenumber(Long casenumber) {
		this.casenumber = casenumber;
	}

	@Column(name = "CATEGORYID", precision = 10, scale = 0)
	public Long getCategoryid() {
		return this.categoryid;
	}

	public void setCategoryid(Long categoryid) {
		this.categoryid = categoryid;
	}

	@Column(name = "CASETYPE", length = 50)
	public String getCasetype() {
		return this.casetype;
	}

	public void setCasetype(String casetype) {
		this.casetype = casetype;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LASTUPDATED", length = 7)
	public Date getLastupdated() {
		return this.lastupdated;
	}

	public void setLastupdated(Date lastupdated) {
		this.lastupdated = lastupdated;
	}

	@Column(name = "CABLEUNITNO", precision = 22, scale = 0)
	public BigDecimal getCableunitno() {
		return this.cableunitno;
	}

	public void setCableunitno(BigDecimal cableunitno) {
		this.cableunitno = cableunitno;
	}

	@Column(name = "CABLEUNITPROJNO", length = 50)
	public String getCableunitprojno() {
		return this.cableunitprojno;
	}

	public void setCableunitprojno(String cableunitprojno) {
		this.cableunitprojno = cableunitprojno;
	}

	@Column(name = "OFFEREECUSTID", precision = 22, scale = 0)
	public BigDecimal getOffereecustid() {
		return this.offereecustid;
	}

	public void setOffereecustid(BigDecimal offereecustid) {
		this.offereecustid = offereecustid;
	}

	@Column(name = "WORKSMARTCASENO", length = 50)
	public String getWorksmartcaseno() {
		return this.worksmartcaseno;
	}

	public void setWorksmartcaseno(String worksmartcaseno) {
		this.worksmartcaseno = worksmartcaseno;
	}

	@Column(name = "WORKSMARTSTATE", length = 256)
	public String getWorksmartstate() {
		return this.worksmartstate;
	}

	public void setWorksmartstate(String worksmartstate) {
		this.worksmartstate = worksmartstate;
	}

	@Column(name = "WORKSMARTCATEGORY", length = 256)
	public String getWorksmartcategory() {
		return this.worksmartcategory;
	}

	public void setWorksmartcategory(String worksmartcategory) {
		this.worksmartcategory = worksmartcategory;
	}

	@Column(name = "SUBSCRIBERCUSTID", precision = 22, scale = 0)
	public BigDecimal getSubscribercustid() {
		return this.subscribercustid;
	}

	public void setSubscribercustid(BigDecimal subscribercustid) {
		this.subscribercustid = subscribercustid;
	}

	@Column(name = "HIERARCHYCUSTID", precision = 22, scale = 0)
	public BigDecimal getHierarchycustid() {
		return this.hierarchycustid;
	}

	public void setHierarchycustid(BigDecimal hierarchycustid) {
		this.hierarchycustid = hierarchycustid;
	}

	@Column(name = "MAINSWITCHID", precision = 22, scale = 0)
	public BigDecimal getMainswitchid() {
		return this.mainswitchid;
	}

	public void setMainswitchid(BigDecimal mainswitchid) {
		this.mainswitchid = mainswitchid;
	}

	@Column(name = "FILESERVERPATH", length = 256)
	public String getFileserverpath() {
		return this.fileserverpath;
	}

	public void setFileserverpath(String fileserverpath) {
		this.fileserverpath = fileserverpath;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "WORKSMARTDATEUPDATED", length = 7)
	public Date getWorksmartdateupdated() {
		return this.worksmartdateupdated;
	}

	public void setWorksmartdateupdated(Date worksmartdateupdated) {
		this.worksmartdateupdated = worksmartdateupdated;
	}

}
