package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Expense generated by hbm2java
 */
@Entity
@Table(name = "EXPENSE", schema = "PCRM")
public class Expense implements java.io.Serializable {

	private String id;
	private Supplierrequestitem supplierrequestitem;
	private Expensetype expensetype;
	private Date crd;
	private Date crt;
	private String cru;
	private Date modd;
	private Date modt;
	private String modu;
	private Date deld;
	private Date delt;
	private String delu;
	private Date impd;
	private Date impt;
	private String impu;
	private Date expd;
	private Date expt;
	private String expu;
	private String primarycdmmodelfield;
	private String keyfieldvalue;
	private String primaryomkost;
	private String primarykontonr;
	private String primvarechosen;
	private String code;
	private String heading;
	private Character active;
	private String kontonr;
	private BigDecimal omkostning;
	private String klasse;
	private String objekt;
	private Date startdate;
	private Date enddate;
	private Date revDate;
	private String revUser;
	private String revision;
	private Character momsIncl;
	private Character fordel;
	private String primexpense;
	private String primconstructionproject;
	private Set<Expensedispersal> expensedispersals = new HashSet<Expensedispersal>(
			0);

	public Expense() {
	}

	public Expense(String id) {
		this.id = id;
	}

	public Expense(String id, Supplierrequestitem supplierrequestitem,
			Expensetype expensetype, Date crd, Date crt, String cru, Date modd,
			Date modt, String modu, Date deld, Date delt, String delu,
			Date impd, Date impt, String impu, Date expd, Date expt,
			String expu, String primarycdmmodelfield, String keyfieldvalue,
			String primaryomkost, String primarykontonr, String primvarechosen,
			String code, String heading, Character active, String kontonr,
			BigDecimal omkostning, String klasse, String objekt,
			Date startdate, Date enddate, Date revDate, String revUser,
			String revision, Character momsIncl, Character fordel,
			String primexpense, String primconstructionproject,
			Set<Expensedispersal> expensedispersals) {
		this.id = id;
		this.supplierrequestitem = supplierrequestitem;
		this.expensetype = expensetype;
		this.crd = crd;
		this.crt = crt;
		this.cru = cru;
		this.modd = modd;
		this.modt = modt;
		this.modu = modu;
		this.deld = deld;
		this.delt = delt;
		this.delu = delu;
		this.impd = impd;
		this.impt = impt;
		this.impu = impu;
		this.expd = expd;
		this.expt = expt;
		this.expu = expu;
		this.primarycdmmodelfield = primarycdmmodelfield;
		this.keyfieldvalue = keyfieldvalue;
		this.primaryomkost = primaryomkost;
		this.primarykontonr = primarykontonr;
		this.primvarechosen = primvarechosen;
		this.code = code;
		this.heading = heading;
		this.active = active;
		this.kontonr = kontonr;
		this.omkostning = omkostning;
		this.klasse = klasse;
		this.objekt = objekt;
		this.startdate = startdate;
		this.enddate = enddate;
		this.revDate = revDate;
		this.revUser = revUser;
		this.revision = revision;
		this.momsIncl = momsIncl;
		this.fordel = fordel;
		this.primexpense = primexpense;
		this.primconstructionproject = primconstructionproject;
		this.expensedispersals = expensedispersals;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMSUPPLIERREQUESTITEM")
	public Supplierrequestitem getSupplierrequestitem() {
		return this.supplierrequestitem;
	}

	public void setSupplierrequestitem(Supplierrequestitem supplierrequestitem) {
		this.supplierrequestitem = supplierrequestitem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMARYOMKOSTTYPE")
	public Expensetype getExpensetype() {
		return this.expensetype;
	}

	public void setExpensetype(Expensetype expensetype) {
		this.expensetype = expensetype;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "PRIMARYCDMMODELFIELD", length = 19)
	public String getPrimarycdmmodelfield() {
		return this.primarycdmmodelfield;
	}

	public void setPrimarycdmmodelfield(String primarycdmmodelfield) {
		this.primarycdmmodelfield = primarycdmmodelfield;
	}

	@Column(name = "KEYFIELDVALUE")
	public String getKeyfieldvalue() {
		return this.keyfieldvalue;
	}

	public void setKeyfieldvalue(String keyfieldvalue) {
		this.keyfieldvalue = keyfieldvalue;
	}

	@Column(name = "PRIMARYOMKOST", length = 19)
	public String getPrimaryomkost() {
		return this.primaryomkost;
	}

	public void setPrimaryomkost(String primaryomkost) {
		this.primaryomkost = primaryomkost;
	}

	@Column(name = "PRIMARYKONTONR", length = 19)
	public String getPrimarykontonr() {
		return this.primarykontonr;
	}

	public void setPrimarykontonr(String primarykontonr) {
		this.primarykontonr = primarykontonr;
	}

	@Column(name = "PRIMVARECHOSEN", length = 19)
	public String getPrimvarechosen() {
		return this.primvarechosen;
	}

	public void setPrimvarechosen(String primvarechosen) {
		this.primvarechosen = primvarechosen;
	}

	@Column(name = "CODE", length = 55)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "HEADING")
	public String getHeading() {
		return this.heading;
	}

	public void setHeading(String heading) {
		this.heading = heading;
	}

	@Column(name = "ACTIVE", length = 1)
	public Character getActive() {
		return this.active;
	}

	public void setActive(Character active) {
		this.active = active;
	}

	@Column(name = "KONTONR")
	public String getKontonr() {
		return this.kontonr;
	}

	public void setKontonr(String kontonr) {
		this.kontonr = kontonr;
	}

	@Column(name = "OMKOSTNING", precision = 12)
	public BigDecimal getOmkostning() {
		return this.omkostning;
	}

	public void setOmkostning(BigDecimal omkostning) {
		this.omkostning = omkostning;
	}

	@Column(name = "KLASSE", length = 64)
	public String getKlasse() {
		return this.klasse;
	}

	public void setKlasse(String klasse) {
		this.klasse = klasse;
	}

	@Column(name = "OBJEKT", length = 64)
	public String getObjekt() {
		return this.objekt;
	}

	public void setObjekt(String objekt) {
		this.objekt = objekt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STARTDATE", length = 7)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDATE", length = 7)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REV_DATE", length = 7)
	public Date getRevDate() {
		return this.revDate;
	}

	public void setRevDate(Date revDate) {
		this.revDate = revDate;
	}

	@Column(name = "REV_USER", length = 19)
	public String getRevUser() {
		return this.revUser;
	}

	public void setRevUser(String revUser) {
		this.revUser = revUser;
	}

	@Column(name = "REVISION", length = 19)
	public String getRevision() {
		return this.revision;
	}

	public void setRevision(String revision) {
		this.revision = revision;
	}

	@Column(name = "MOMS_INCL", length = 1)
	public Character getMomsIncl() {
		return this.momsIncl;
	}

	public void setMomsIncl(Character momsIncl) {
		this.momsIncl = momsIncl;
	}

	@Column(name = "FORDEL", length = 1)
	public Character getFordel() {
		return this.fordel;
	}

	public void setFordel(Character fordel) {
		this.fordel = fordel;
	}

	@Column(name = "PRIMEXPENSE", length = 19)
	public String getPrimexpense() {
		return this.primexpense;
	}

	public void setPrimexpense(String primexpense) {
		this.primexpense = primexpense;
	}

	@Column(name = "PRIMCONSTRUCTIONPROJECT", length = 19)
	public String getPrimconstructionproject() {
		return this.primconstructionproject;
	}

	public void setPrimconstructionproject(String primconstructionproject) {
		this.primconstructionproject = primconstructionproject;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expense")
	public Set<Expensedispersal> getExpensedispersals() {
		return this.expensedispersals;
	}

	public void setExpensedispersals(Set<Expensedispersal> expensedispersals) {
		this.expensedispersals = expensedispersals;
	}

}
