package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fieldexecutionlog generated by hbm2java
 */
@Entity
@Table(name = "FIELDEXECUTIONLOG", schema = "PCRM")
public class Fieldexecutionlog implements java.io.Serializable {

	private String id;
	private Date crd;
	private Date impd;
	private Date expd;
	private String cru;
	private Date modd;
	private String impu;
	private String expu;
	private String modu;
	private String screenid;
	private String fieldname;
	private String primarymodelfield;
	private String primkeyfield;
	private String reasoncodes;
	private String logid;

	public Fieldexecutionlog() {
	}

	public Fieldexecutionlog(String id) {
		this.id = id;
	}

	public Fieldexecutionlog(String id, Date crd, Date impd, Date expd,
			String cru, Date modd, String impu, String expu, String modu,
			String screenid, String fieldname, String primarymodelfield,
			String primkeyfield, String reasoncodes, String logid) {
		this.id = id;
		this.crd = crd;
		this.impd = impd;
		this.expd = expd;
		this.cru = cru;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.modu = modu;
		this.screenid = screenid;
		this.fieldname = fieldname;
		this.primarymodelfield = primarymodelfield;
		this.primkeyfield = primkeyfield;
		this.reasoncodes = reasoncodes;
		this.logid = logid;
	}

	@Id
	@Column(name = "ID", nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "SCREENID", length = 100)
	public String getScreenid() {
		return this.screenid;
	}

	public void setScreenid(String screenid) {
		this.screenid = screenid;
	}

	@Column(name = "FIELDNAME", length = 2000)
	public String getFieldname() {
		return this.fieldname;
	}

	public void setFieldname(String fieldname) {
		this.fieldname = fieldname;
	}

	@Column(name = "PRIMARYMODELFIELD", length = 50)
	public String getPrimarymodelfield() {
		return this.primarymodelfield;
	}

	public void setPrimarymodelfield(String primarymodelfield) {
		this.primarymodelfield = primarymodelfield;
	}

	@Column(name = "PRIMKEYFIELD", length = 19)
	public String getPrimkeyfield() {
		return this.primkeyfield;
	}

	public void setPrimkeyfield(String primkeyfield) {
		this.primkeyfield = primkeyfield;
	}

	@Column(name = "REASONCODES", length = 100)
	public String getReasoncodes() {
		return this.reasoncodes;
	}

	public void setReasoncodes(String reasoncodes) {
		this.reasoncodes = reasoncodes;
	}

	@Column(name = "LOGID", length = 19)
	public String getLogid() {
		return this.logid;
	}

	public void setLogid(String logid) {
		this.logid = logid;
	}

}
