package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Frequencies generated by hbm2java
 */
@Entity
@Table(name = "FREQUENCIES", schema = "PCRM", uniqueConstraints = @UniqueConstraint(columnNames = "FREQ_HZ"))
public class Frequencies implements java.io.Serializable {

	private String channel;
	private Date crd;
	private String cru;
	private Date modd;
	private String modu;
	private BigDecimal freqHz;
	private String area;
	private String band;
	private String mapChannel;
	private BigDecimal lowerFreqHz;
	private BigDecimal centerFreqHz;
	private BigDecimal upperFreqHz;
	private Date startDate;
	private Date endDate;

	public Frequencies() {
	}

	public Frequencies(String channel) {
		this.channel = channel;
	}

	public Frequencies(String channel, Date crd, String cru, Date modd,
			String modu, BigDecimal freqHz, String area, String band,
			String mapChannel, BigDecimal lowerFreqHz, BigDecimal centerFreqHz,
			BigDecimal upperFreqHz, Date startDate, Date endDate) {
		this.channel = channel;
		this.crd = crd;
		this.cru = cru;
		this.modd = modd;
		this.modu = modu;
		this.freqHz = freqHz;
		this.area = area;
		this.band = band;
		this.mapChannel = mapChannel;
		this.lowerFreqHz = lowerFreqHz;
		this.centerFreqHz = centerFreqHz;
		this.upperFreqHz = upperFreqHz;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@Column(name = "CHANNEL", unique = true, nullable = false, length = 10)
	public String getChannel() {
		return this.channel;
	}

	public void setChannel(String channel) {
		this.channel = channel;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "FREQ_HZ", unique = true, precision = 22, scale = 0)
	public BigDecimal getFreqHz() {
		return this.freqHz;
	}

	public void setFreqHz(BigDecimal freqHz) {
		this.freqHz = freqHz;
	}

	@Column(name = "AREA", length = 6)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "BAND", length = 6)
	public String getBand() {
		return this.band;
	}

	public void setBand(String band) {
		this.band = band;
	}

	@Column(name = "MAP_CHANNEL", length = 10)
	public String getMapChannel() {
		return this.mapChannel;
	}

	public void setMapChannel(String mapChannel) {
		this.mapChannel = mapChannel;
	}

	@Column(name = "LOWER_FREQ_HZ", precision = 22, scale = 0)
	public BigDecimal getLowerFreqHz() {
		return this.lowerFreqHz;
	}

	public void setLowerFreqHz(BigDecimal lowerFreqHz) {
		this.lowerFreqHz = lowerFreqHz;
	}

	@Column(name = "CENTER_FREQ_HZ", precision = 22, scale = 0)
	public BigDecimal getCenterFreqHz() {
		return this.centerFreqHz;
	}

	public void setCenterFreqHz(BigDecimal centerFreqHz) {
		this.centerFreqHz = centerFreqHz;
	}

	@Column(name = "UPPER_FREQ_HZ", precision = 22, scale = 0)
	public BigDecimal getUpperFreqHz() {
		return this.upperFreqHz;
	}

	public void setUpperFreqHz(BigDecimal upperFreqHz) {
		this.upperFreqHz = upperFreqHz;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
