package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * IcalcrequestLocal generated by hbm2java
 */
@Entity
@Table(name = "ICALCREQUEST_LOCAL", schema = "PCRM")
public class IcalcrequestLocal implements java.io.Serializable {

	private IcalcrequestLocalId id;

	public IcalcrequestLocal() {
	}

	public IcalcrequestLocal(IcalcrequestLocalId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", length = 19)),
			@AttributeOverride(name = "crd", column = @Column(name = "CRD", length = 7)),
			@AttributeOverride(name = "crt", column = @Column(name = "CRT", length = 7)),
			@AttributeOverride(name = "cru", column = @Column(name = "CRU", length = 19)),
			@AttributeOverride(name = "impt", column = @Column(name = "IMPT", length = 7)),
			@AttributeOverride(name = "impd", column = @Column(name = "IMPD", length = 7)),
			@AttributeOverride(name = "impu", column = @Column(name = "IMPU", length = 19)),
			@AttributeOverride(name = "expt", column = @Column(name = "EXPT", length = 7)),
			@AttributeOverride(name = "expd", column = @Column(name = "EXPD", length = 7)),
			@AttributeOverride(name = "expu", column = @Column(name = "EXPU", length = 19)),
			@AttributeOverride(name = "modt", column = @Column(name = "MODT", length = 7)),
			@AttributeOverride(name = "modd", column = @Column(name = "MODD", length = 7)),
			@AttributeOverride(name = "modu", column = @Column(name = "MODU", length = 19)),
			@AttributeOverride(name = "delt", column = @Column(name = "DELT", length = 7)),
			@AttributeOverride(name = "delu", column = @Column(name = "DELU", length = 19)),
			@AttributeOverride(name = "deld", column = @Column(name = "DELD", length = 7)),
			@AttributeOverride(name = "code", column = @Column(name = "CODE", length = 50)),
			@AttributeOverride(name = "heading", column = @Column(name = "HEADING")),
			@AttributeOverride(name = "calcerrstat", column = @Column(name = "CALCERRSTAT")),
			@AttributeOverride(name = "calcprogstat", column = @Column(name = "CALCPROGSTAT")),
			@AttributeOverride(name = "calcprogts", column = @Column(name = "CALCPROGTS", length = 19)),
			@AttributeOverride(name = "primicalcrequest", column = @Column(name = "PRIMICALCREQUEST", length = 19)),
			@AttributeOverride(name = "primdatapricecalc", column = @Column(name = "PRIMDATAPRICECALC", length = 19)),
			@AttributeOverride(name = "primbasicpricecalc", column = @Column(name = "PRIMBASICPRICECALC", length = 19)),
			@AttributeOverride(name = "datapricecalclock", column = @Column(name = "DATAPRICECALCLOCK", length = 19)),
			@AttributeOverride(name = "actiontype", column = @Column(name = "ACTIONTYPE", length = 19)),
			@AttributeOverride(name = "dbprojectcode", column = @Column(name = "DBPROJECTCODE", length = 19)),
			@AttributeOverride(name = "osuname", column = @Column(name = "OSUNAME", length = 10)) })
	public IcalcrequestLocalId getId() {
		return this.id;
	}

	public void setId(IcalcrequestLocalId id) {
		this.id = id;
	}

}
