package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InstallationChghist generated by hbm2java
 */
@Entity
@Table(name = "INSTALLATION_CHGHIST", schema = "PCRM")
public class InstallationChghist implements java.io.Serializable {

	private String audId;
	private String audAction;
	private Serializable audTimestamp;
	private String audOsuser;
	private String audDbuser;
	private String audUserterminal;
	private String id;
	private long addressid;
	private BigDecimal installationseq;
	private String location;
	private String cableunitid;
	private Date startdate;
	private Date enddate;
	private String installationstatusid;
	private Date controldate;
	private Long addressidmovedto;
	private String installationseqmovedto;
	private String cableunitidmovefrom;
	private String cableunitidmoveto;
	private Date movingdate;
	private Date crd;
	private String cru;
	private Date modd;
	private String modu;
	private Date deld;
	private String delu;
	private String jobflag;
	private String jobremarks;

	public InstallationChghist() {
	}

	public InstallationChghist(String audId, String id, long addressid,
			BigDecimal installationseq, String cableunitid,
			String installationstatusid) {
		this.audId = audId;
		this.id = id;
		this.addressid = addressid;
		this.installationseq = installationseq;
		this.cableunitid = cableunitid;
		this.installationstatusid = installationstatusid;
	}

	public InstallationChghist(String audId, String audAction,
			Serializable audTimestamp, String audOsuser, String audDbuser,
			String audUserterminal, String id, long addressid,
			BigDecimal installationseq, String location, String cableunitid,
			Date startdate, Date enddate, String installationstatusid,
			Date controldate, Long addressidmovedto,
			String installationseqmovedto, String cableunitidmovefrom,
			String cableunitidmoveto, Date movingdate, Date crd, String cru,
			Date modd, String modu, Date deld, String delu, String jobflag,
			String jobremarks) {
		this.audId = audId;
		this.audAction = audAction;
		this.audTimestamp = audTimestamp;
		this.audOsuser = audOsuser;
		this.audDbuser = audDbuser;
		this.audUserterminal = audUserterminal;
		this.id = id;
		this.addressid = addressid;
		this.installationseq = installationseq;
		this.location = location;
		this.cableunitid = cableunitid;
		this.startdate = startdate;
		this.enddate = enddate;
		this.installationstatusid = installationstatusid;
		this.controldate = controldate;
		this.addressidmovedto = addressidmovedto;
		this.installationseqmovedto = installationseqmovedto;
		this.cableunitidmovefrom = cableunitidmovefrom;
		this.cableunitidmoveto = cableunitidmoveto;
		this.movingdate = movingdate;
		this.crd = crd;
		this.cru = cru;
		this.modd = modd;
		this.modu = modu;
		this.deld = deld;
		this.delu = delu;
		this.jobflag = jobflag;
		this.jobremarks = jobremarks;
	}

	@Id
	@Column(name = "AUD_ID", unique = true, nullable = false, length = 19)
	public String getAudId() {
		return this.audId;
	}

	public void setAudId(String audId) {
		this.audId = audId;
	}

	@Column(name = "AUD_ACTION", length = 50)
	public String getAudAction() {
		return this.audAction;
	}

	public void setAudAction(String audAction) {
		this.audAction = audAction;
	}

	@Column(name = "AUD_TIMESTAMP")
	public Serializable getAudTimestamp() {
		return this.audTimestamp;
	}

	public void setAudTimestamp(Serializable audTimestamp) {
		this.audTimestamp = audTimestamp;
	}

	@Column(name = "AUD_OSUSER", length = 50)
	public String getAudOsuser() {
		return this.audOsuser;
	}

	public void setAudOsuser(String audOsuser) {
		this.audOsuser = audOsuser;
	}

	@Column(name = "AUD_DBUSER", length = 50)
	public String getAudDbuser() {
		return this.audDbuser;
	}

	public void setAudDbuser(String audDbuser) {
		this.audDbuser = audDbuser;
	}

	@Column(name = "AUD_USERTERMINAL", length = 50)
	public String getAudUserterminal() {
		return this.audUserterminal;
	}

	public void setAudUserterminal(String audUserterminal) {
		this.audUserterminal = audUserterminal;
	}

	@Column(name = "ID", nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "ADDRESSID", nullable = false, precision = 10, scale = 0)
	public long getAddressid() {
		return this.addressid;
	}

	public void setAddressid(long addressid) {
		this.addressid = addressid;
	}

	@Column(name = "INSTALLATIONSEQ", nullable = false, precision = 22, scale = 0)
	public BigDecimal getInstallationseq() {
		return this.installationseq;
	}

	public void setInstallationseq(BigDecimal installationseq) {
		this.installationseq = installationseq;
	}

	@Column(name = "LOCATION", length = 256)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "CABLEUNITID", nullable = false, length = 10)
	public String getCableunitid() {
		return this.cableunitid;
	}

	public void setCableunitid(String cableunitid) {
		this.cableunitid = cableunitid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STARTDATE", length = 7)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDATE", length = 7)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Column(name = "INSTALLATIONSTATUSID", nullable = false, length = 19)
	public String getInstallationstatusid() {
		return this.installationstatusid;
	}

	public void setInstallationstatusid(String installationstatusid) {
		this.installationstatusid = installationstatusid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CONTROLDATE", length = 7)
	public Date getControldate() {
		return this.controldate;
	}

	public void setControldate(Date controldate) {
		this.controldate = controldate;
	}

	@Column(name = "ADDRESSIDMOVEDTO", precision = 10, scale = 0)
	public Long getAddressidmovedto() {
		return this.addressidmovedto;
	}

	public void setAddressidmovedto(Long addressidmovedto) {
		this.addressidmovedto = addressidmovedto;
	}

	@Column(name = "INSTALLATIONSEQMOVEDTO", length = 10)
	public String getInstallationseqmovedto() {
		return this.installationseqmovedto;
	}

	public void setInstallationseqmovedto(String installationseqmovedto) {
		this.installationseqmovedto = installationseqmovedto;
	}

	@Column(name = "CABLEUNITIDMOVEFROM", length = 10)
	public String getCableunitidmovefrom() {
		return this.cableunitidmovefrom;
	}

	public void setCableunitidmovefrom(String cableunitidmovefrom) {
		this.cableunitidmovefrom = cableunitidmovefrom;
	}

	@Column(name = "CABLEUNITIDMOVETO", length = 10)
	public String getCableunitidmoveto() {
		return this.cableunitidmoveto;
	}

	public void setCableunitidmoveto(String cableunitidmoveto) {
		this.cableunitidmoveto = cableunitidmoveto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MOVINGDATE", length = 7)
	public Date getMovingdate() {
		return this.movingdate;
	}

	public void setMovingdate(Date movingdate) {
		this.movingdate = movingdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Column(name = "JOBFLAG", length = 1)
	public String getJobflag() {
		return this.jobflag;
	}

	public void setJobflag(String jobflag) {
		this.jobflag = jobflag;
	}

	@Column(name = "JOBREMARKS", length = 500)
	public String getJobremarks() {
		return this.jobremarks;
	}

	public void setJobremarks(String jobremarks) {
		this.jobremarks = jobremarks;
	}

}
