package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Installationkeycabinet generated by hbm2java
 */
@Entity
@Table(name = "INSTALLATIONKEYCABINET", schema = "PCRM")
public class Installationkeycabinet implements java.io.Serializable {

	private InstallationkeycabinetId id;
	private String casperaddressid;
	private String instLbnr;
	private BigDecimal rowid;
	private String dataset;
	private BigDecimal lxbenummer;
	private Date sidstrettet;
	private String anlxg;
	private Byte status;
	private String formidlergrund;
	private String formidlertillxg;
	private BigDecimal dummy;
	private BigDecimal underFlytning;
	private BigDecimal dummylbnr;
	private String location;

	public Installationkeycabinet() {
	}

	

	public Installationkeycabinet(InstallationkeycabinetId id,
			String casperaddressid, String instLbnr, BigDecimal rowid,
			String dataset, BigDecimal lxbenummer, Date sidstrettet,
			String anlxg, Byte status, String formidlergrund,
			String formidlertillxg, BigDecimal dummy, BigDecimal underFlytning,
			BigDecimal dummylbnr, String location) {
		this.id = id;
		this.casperaddressid = casperaddressid;
		this.instLbnr = instLbnr;
		this.rowid = rowid;
		this.dataset = dataset;
		this.lxbenummer = lxbenummer;
		this.sidstrettet = sidstrettet;
		this.anlxg = anlxg;
		this.status = status;
		this.formidlergrund = formidlergrund;
		this.formidlertillxg = formidlertillxg;
		this.dummy = dummy;
		this.underFlytning = underFlytning;
		this.dummylbnr = dummylbnr;
		this.location = location;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "addressid", column = @Column(name = "ADDRESSID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "installationseq", column = @Column(name = "INSTALLATIONSEQ", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "startdato", column = @Column(name = "STARTDATO", nullable = false, length = 7)) })
	public InstallationkeycabinetId getId() {
		return this.id;
	}

	public void setId(InstallationkeycabinetId id) {
		this.id = id;
	}

	@Column(name = "CASPERADDRESSID", nullable = false, length = 10)
	public String getCasperaddressid() {
		return this.casperaddressid;
	}

	public void setCasperaddressid(String casperaddressid) {
		this.casperaddressid = casperaddressid;
	}

	@Column(name = "INST_LBNR", length = 10)
	public String getInstLbnr() {
		return this.instLbnr;
	}

	public void setInstLbnr(String instLbnr) {
		this.instLbnr = instLbnr;
	}

	@Column(name = "rowid", precision = 22, scale = 0)
	public BigDecimal getRowid() {
		return this.rowid;
	}

	public void setRowid(BigDecimal rowid) {
		this.rowid = rowid;
	}

	@Column(name = "DATASET", length = 3)
	public String getDataset() {
		return this.dataset;
	}

	public void setDataset(String dataset) {
		this.dataset = dataset;
	}

	@Column(name = "LXBENUMMER", precision = 22, scale = 0)
	public BigDecimal getLxbenummer() {
		return this.lxbenummer;
	}

	public void setLxbenummer(BigDecimal lxbenummer) {
		this.lxbenummer = lxbenummer;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SIDSTRETTET", length = 7)
	public Date getSidstrettet() {
		return this.sidstrettet;
	}

	public void setSidstrettet(Date sidstrettet) {
		this.sidstrettet = sidstrettet;
	}

	@Column(name = "ANLXG", length = 10)
	public String getAnlxg() {
		return this.anlxg;
	}

	public void setAnlxg(String anlxg) {
		this.anlxg = anlxg;
	}

	@Column(name = "STATUS", precision = 2, scale = 0)
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "FORMIDLERGRUND", length = 10)
	public String getFormidlergrund() {
		return this.formidlergrund;
	}

	public void setFormidlergrund(String formidlergrund) {
		this.formidlergrund = formidlergrund;
	}

	@Column(name = "FORMIDLERTILLXG", length = 10)
	public String getFormidlertillxg() {
		return this.formidlertillxg;
	}

	public void setFormidlertillxg(String formidlertillxg) {
		this.formidlertillxg = formidlertillxg;
	}

	@Column(name = "DUMMY", precision = 22, scale = 0)
	public BigDecimal getDummy() {
		return this.dummy;
	}

	public void setDummy(BigDecimal dummy) {
		this.dummy = dummy;
	}

	@Column(name = "UNDER_FLYTNING", precision = 22, scale = 0)
	public BigDecimal getUnderFlytning() {
		return this.underFlytning;
	}

	public void setUnderFlytning(BigDecimal underFlytning) {
		this.underFlytning = underFlytning;
	}

	@Column(name = "DUMMYLBNR", precision = 22, scale = 0)
	public BigDecimal getDummylbnr() {
		return this.dummylbnr;
	}

	public void setDummylbnr(BigDecimal dummylbnr) {
		this.dummylbnr = dummylbnr;
	}

	@Column(name = "LOCATION", length = 256)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

}
