package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JobLog generated by hbm2java
 */
@Entity
@Table(name = "JOB_LOG", schema = "PCRM")
public class JobLog implements java.io.Serializable {

	private BigDecimal id;
	private Sfdcquery sfdcquery;
	private BigDecimal startTime;
	private BigDecimal endTime;
	private Boolean jobStatus;

	public JobLog() {
	}

	public JobLog(BigDecimal id) {
		this.id = id;
	}

	public JobLog(BigDecimal id, Sfdcquery sfdcquery, BigDecimal startTime,
			BigDecimal endTime, Boolean jobStatus) {
		this.id = id;
		this.sfdcquery = sfdcquery;
		this.startTime = startTime;
		this.endTime = endTime;
		this.jobStatus = jobStatus;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "QUERY_ID")
	public Sfdcquery getSfdcquery() {
		return this.sfdcquery;
	}

	public void setSfdcquery(Sfdcquery sfdcquery) {
		this.sfdcquery = sfdcquery;
	}

	@Column(name = "START_TIME", scale = 0)
	public BigDecimal getStartTime() {
		return this.startTime;
	}

	public void setStartTime(BigDecimal startTime) {
		this.startTime = startTime;
	}

	@Column(name = "END_TIME", scale = 0)
	public BigDecimal getEndTime() {
		return this.endTime;
	}

	public void setEndTime(BigDecimal endTime) {
		this.endTime = endTime;
	}

	@Column(name = "JOB_STATUS", precision = 1, scale = 0)
	public Boolean getJobStatus() {
		return this.jobStatus;
	}

	public void setJobStatus(Boolean jobStatus) {
		this.jobStatus = jobStatus;
	}

}
