package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Kissactiveaddvejkodnull generated by hbm2java
 */
@Entity
@Table(name = "KISSACTIVEADDVEJKODNULL", schema = "PCRM")
public class Kissactiveaddvejkodnull implements java.io.Serializable {

	private KissactiveaddvejkodnullId id;

	public Kissactiveaddvejkodnull() {
	}

	public Kissactiveaddvejkodnull(KissactiveaddvejkodnullId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", length = 19)),
			@AttributeOverride(name = "crd", column = @Column(name = "CRD", length = 7)),
			@AttributeOverride(name = "crt", column = @Column(name = "CRT", length = 7)),
			@AttributeOverride(name = "cru", column = @Column(name = "CRU", length = 19)),
			@AttributeOverride(name = "modd", column = @Column(name = "MODD", length = 7)),
			@AttributeOverride(name = "modt", column = @Column(name = "MODT", length = 7)),
			@AttributeOverride(name = "modu", column = @Column(name = "MODU", length = 19)),
			@AttributeOverride(name = "deld", column = @Column(name = "DELD", length = 7)),
			@AttributeOverride(name = "delt", column = @Column(name = "DELT", length = 7)),
			@AttributeOverride(name = "delu", column = @Column(name = "DELU", length = 19)),
			@AttributeOverride(name = "impd", column = @Column(name = "IMPD", length = 7)),
			@AttributeOverride(name = "impt", column = @Column(name = "IMPT", length = 7)),
			@AttributeOverride(name = "impu", column = @Column(name = "IMPU", length = 19)),
			@AttributeOverride(name = "expd", column = @Column(name = "EXPD", length = 7)),
			@AttributeOverride(name = "expt", column = @Column(name = "EXPT", length = 7)),
			@AttributeOverride(name = "expu", column = @Column(name = "EXPU", length = 19)),
			@AttributeOverride(name = "dwAdrid", column = @Column(name = "DW_ADRID", length = 22)),
			@AttributeOverride(name = "newDwAdrid", column = @Column(name = "NEW_DW_ADRID", length = 32)),
			@AttributeOverride(name = "komkod", column = @Column(name = "KOMKOD", length = 4)),
			@AttributeOverride(name = "vejkod", column = @Column(name = "VEJKOD", length = 4)),
			@AttributeOverride(name = "vejnvn", column = @Column(name = "VEJNVN", length = 40)),
			@AttributeOverride(name = "dwVejnvn", column = @Column(name = "DW_VEJNVN", length = 40)),
			@AttributeOverride(name = "dwHusnr", column = @Column(name = "DW_HUSNR", length = 3)),
			@AttributeOverride(name = "dwHusnrbogstav", column = @Column(name = "DW_HUSNRBOGSTAV", length = 1)),
			@AttributeOverride(name = "dwHusFritekst", column = @Column(name = "DW_HUS_FRITEKST", length = 40)),
			@AttributeOverride(name = "etage", column = @Column(name = "ETAGE", length = 2)),
			@AttributeOverride(name = "dwEtage", column = @Column(name = "DW_ETAGE", length = 2)),
			@AttributeOverride(name = "sidedoer", column = @Column(name = "SIDEDOER", length = 10)),
			@AttributeOverride(name = "dwSidedoer", column = @Column(name = "DW_SIDEDOER", length = 10)),
			@AttributeOverride(name = "dwDoerFritekst", column = @Column(name = "DW_DOER_FRITEKST", length = 40)),
			@AttributeOverride(name = "postnr", column = @Column(name = "POSTNR", length = 4)),
			@AttributeOverride(name = "postdisttxt", column = @Column(name = "POSTDISTTXT", length = 30)),
			@AttributeOverride(name = "dwPostdisttxt", column = @Column(name = "DW_POSTDISTTXT", length = 30)),
			@AttributeOverride(name = "dwLigeUlige", column = @Column(name = "DW_LIGE_ULIGE", length = 1)),
			@AttributeOverride(name = "sourceSystem", column = @Column(name = "SOURCE_SYSTEM", length = 5)),
			@AttributeOverride(name = "commRating", column = @Column(name = "COMM_RATING", precision = 22, scale = 0)),
			@AttributeOverride(name = "dwAnlaegsnr", column = @Column(name = "DW_ANLAEGSNR", length = 10)),
			@AttributeOverride(name = "husnr", column = @Column(name = "HUSNR", length = 4)),
			@AttributeOverride(name = "dwKabeltv", column = @Column(name = "DW_KABELTV", length = 1)),
			@AttributeOverride(name = "dwReturvej", column = @Column(name = "DW_RETURVEJ", length = 1)),
			@AttributeOverride(name = "compstr", column = @Column(name = "COMPSTR", length = 18)),
			@AttributeOverride(name = "opslagspostnr", column = @Column(name = "OPSLAGSPOSTNR", length = 4)),
			@AttributeOverride(name = "mailjatak", column = @Column(name = "MAILJATAK", length = 1)),
			@AttributeOverride(name = "mailnejtak", column = @Column(name = "MAILNEJTAK", length = 1)),
			@AttributeOverride(name = "mailjatakts", column = @Column(name = "MAILJATAKTS", length = 7)),
			@AttributeOverride(name = "mailnejtakts", column = @Column(name = "MAILNEJTAKTS", length = 7)),
			@AttributeOverride(name = "returAntal", column = @Column(name = "RETUR_ANTAL", precision = 5, scale = 0)),
			@AttributeOverride(name = "returDato", column = @Column(name = "RETUR_DATO", length = 7)),
			@AttributeOverride(name = "inrobinsonlist", column = @Column(name = "INROBINSONLIST", length = 1)),
			@AttributeOverride(name = "accforca", column = @Column(name = "ACCFORCA", length = 1)),
			@AttributeOverride(name = "ktasVejkode", column = @Column(name = "KTAS_VEJKODE", length = 1)),
			@AttributeOverride(name = "primconzoomtype", column = @Column(name = "PRIMCONZOOMTYPE", length = 19)),
			@AttributeOverride(name = "dwStednavn", column = @Column(name = "DW_STEDNAVN", length = 50)),
			@AttributeOverride(name = "primmunicipalitystreet", column = @Column(name = "PRIMMUNICIPALITYSTREET", length = 19)),
			@AttributeOverride(name = "dwVejnvnFunc", column = @Column(name = "DW_VEJNVN_FUNC", length = 4000)),
			@AttributeOverride(name = "postnrFunc", column = @Column(name = "POSTNR_FUNC", length = 4)),
			@AttributeOverride(name = "dwHusnrbogstavFunc", column = @Column(name = "DW_HUSNRBOGSTAV_FUNC", length = 4)),
			@AttributeOverride(name = "dwHusnrFunc", column = @Column(name = "DW_HUSNR_FUNC", length = 4)),
			@AttributeOverride(name = "dwSidedoerFunc", column = @Column(name = "DW_SIDEDOER_FUNC", length = 4000)),
			@AttributeOverride(name = "dwEtageFunc", column = @Column(name = "DW_ETAGE_FUNC", length = 4000)) })
	public KissactiveaddvejkodnullId getId() {
		return this.id;
	}

	public void setId(KissactiveaddvejkodnullId id) {
		this.id = id;
	}

}
