package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MailDataId generated by hbm2java
 */
@Embeddable
public class MailDataId implements java.io.Serializable {

	private String sender;
	private String recipients;
	private String subject;
	private String message;
	private Date crd;

	public MailDataId() {
	}

	public MailDataId(String sender, String recipients, String subject,
			String message, Date crd) {
		this.sender = sender;
		this.recipients = recipients;
		this.subject = subject;
		this.message = message;
		this.crd = crd;
	}

	@Column(name = "SENDER", length = 3000)
	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	@Column(name = "RECIPIENTS", length = 3000)
	public String getRecipients() {
		return this.recipients;
	}

	public void setRecipients(String recipients) {
		this.recipients = recipients;
	}

	@Column(name = "SUBJECT", length = 3000)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "MESSAGE", length = 3000)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MailDataId))
			return false;
		MailDataId castOther = (MailDataId) other;

		return ((this.getSender() == castOther.getSender()) || (this
				.getSender() != null && castOther.getSender() != null && this
				.getSender().equals(castOther.getSender())))
				&& ((this.getRecipients() == castOther.getRecipients()) || (this
						.getRecipients() != null
						&& castOther.getRecipients() != null && this
						.getRecipients().equals(castOther.getRecipients())))
				&& ((this.getSubject() == castOther.getSubject()) || (this
						.getSubject() != null && castOther.getSubject() != null && this
						.getSubject().equals(castOther.getSubject())))
				&& ((this.getMessage() == castOther.getMessage()) || (this
						.getMessage() != null && castOther.getMessage() != null && this
						.getMessage().equals(castOther.getMessage())))
				&& ((this.getCrd() == castOther.getCrd()) || (this.getCrd() != null
						&& castOther.getCrd() != null && this.getCrd().equals(
						castOther.getCrd())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSender() == null ? 0 : this.getSender().hashCode());
		result = 37
				* result
				+ (getRecipients() == null ? 0 : this.getRecipients()
						.hashCode());
		result = 37 * result
				+ (getSubject() == null ? 0 : this.getSubject().hashCode());
		result = 37 * result
				+ (getMessage() == null ? 0 : this.getMessage().hashCode());
		result = 37 * result
				+ (getCrd() == null ? 0 : this.getCrd().hashCode());
		return result;
	}

}
