package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * MigrationDocIDrive generated by hbm2java
 */
@Entity
@Table(name = "MIGRATION_DOC_I_DRIVE", schema = "PCRM")
public class MigrationDocIDrive implements java.io.Serializable {

	private MigrationDocIDriveId id;

	public MigrationDocIDrive() {
	}

	public MigrationDocIDrive(MigrationDocIDriveId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "centaDocumentNameC", column = @Column(name = "CENTA_DOCUMENT_NAME__C", length = 100)),
			@AttributeOverride(name = "cloudFileAccessC", column = @Column(name = "CLOUD_FILE_ACCESS__C", length = 100)),
			@AttributeOverride(name = "cloudFileAllCategoriesC", column = @Column(name = "CLOUD_FILE_ALL_CATEGORIES__C", length = 100)),
			@AttributeOverride(name = "cloudFileAllDocTypesC", column = @Column(name = "CLOUD_FILE_ALL_DOC_TYPES__C", length = 100)),
			@AttributeOverride(name = "cloudFileBucketNameC", column = @Column(name = "CLOUD_FILE_BUCKET_NAME__C", length = 100)),
			@AttributeOverride(name = "cloudFileCaseNoC", column = @Column(name = "CLOUD_FILE_CASE_NO__C", length = 100)),
			@AttributeOverride(name = "cloudFileCentaDocTypeC", column = @Column(name = "CLOUD_FILE_CENTA_DOC_TYPE__C", length = 100)),
			@AttributeOverride(name = "cloudFileContentTypeC", column = @Column(name = "CLOUD_FILE_CONTENT_TYPE__C", length = 100)),
			@AttributeOverride(name = "constructionProjectNumber", column = @Column(name = "CONSTRUCTION_PROJECT_NUMBER", length = 100)),
			@AttributeOverride(name = "cloudFileCreatedDateC", column = @Column(name = "CLOUD_FILE_CREATED_DATE__C", length = 100)),
			@AttributeOverride(name = "cloudFileCustomerNumbersC", column = @Column(name = "CLOUD_FILE_CUSTOMER_NUMBERS__C", length = 100)),
			@AttributeOverride(name = "cableunitno", column = @Column(name = "CABLEUNITNO", length = 100)),
			@AttributeOverride(name = "cloudFileDepartmentC", column = @Column(name = "CLOUD_FILE_DEPARTMENT__C", length = 100)),
			@AttributeOverride(name = "cloudFileDescriptionC", column = @Column(name = "CLOUD_FILE_DESCRIPTION__C", length = 100)),
			@AttributeOverride(name = "cloudFileDoctitleC", column = @Column(name = "CLOUD_FILE_DOCTITLE__C", length = 1000)),
			@AttributeOverride(name = "cloudFileDocumentRemarkC", column = @Column(name = "CLOUD_FILE_DOCUMENT_REMARK__C", length = 100)),
			@AttributeOverride(name = "cloudFileDocumentTagC", column = @Column(name = "CLOUD_FILE_DOCUMENT_TAG__C", length = 100)),
			@AttributeOverride(name = "cloudFileDocRemarkC", column = @Column(name = "CLOUD_FILE_DOC_REMARK__C", length = 100)),
			@AttributeOverride(name = "amazonpath", column = @Column(name = "AMAZONPATH", length = 100)),
			@AttributeOverride(name = "cloudFileHierCustNoC", column = @Column(name = "CLOUD_FILE_HIER_CUST_NO__C", length = 100)),
			@AttributeOverride(name = "cloudFileKissDocTypeC", column = @Column(name = "CLOUD_FILE_KISS_DOC_TYPE__C", length = 100)),
			@AttributeOverride(name = "cloudFileMidC", column = @Column(name = "CLOUD_FILE_MID__C", length = 100)),
			@AttributeOverride(name = "cloudFileOfferIdC", column = @Column(name = "CLOUD_FILE_OFFER_ID__C", length = 100)),
			@AttributeOverride(name = "cloudFilePathPrefixC", column = @Column(name = "CLOUD_FILE_PATH_PREFIX__C", length = 100)),
			@AttributeOverride(name = "cloudFileRelatedToIdC", column = @Column(name = "CLOUD_FILE_RELATED_TO_ID__C", length = 100)),
			@AttributeOverride(name = "cloudFileStatusC", column = @Column(name = "CLOUD_FILE_STATUS__C", length = 100)),
			@AttributeOverride(name = "cloudFileSupplierC", column = @Column(name = "CLOUD_FILE_SUPPLIER__C", length = 100)),
			@AttributeOverride(name = "cloudFileTitleC", column = @Column(name = "CLOUD_FILE_TITLE__C", length = 100)),
			@AttributeOverride(name = "cloudFileUploadedByC", column = @Column(name = "CLOUD_FILE_UPLOADED_BY__C", length = 100)),
			@AttributeOverride(name = "createdbyid", column = @Column(name = "CREATEDBYID", length = 100)),
			@AttributeOverride(name = "createddate", column = @Column(name = "CREATEDDATE", length = 100)),
			@AttributeOverride(name = "sfDocumentId", column = @Column(name = "SF_DOCUMENT_ID", length = 100)),
			@AttributeOverride(name = "isactiveC", column = @Column(name = "ISACTIVE__C", length = 100)),
			@AttributeOverride(name = "isdeleted", column = @Column(name = "ISDELETED", length = 100)),
			@AttributeOverride(name = "lastmodifiedbyid", column = @Column(name = "LASTMODIFIEDBYID", length = 100)),
			@AttributeOverride(name = "lastmodifieddate", column = @Column(name = "LASTMODIFIEDDATE", length = 100)),
			@AttributeOverride(name = "lastreferenceddate", column = @Column(name = "LASTREFERENCEDDATE", length = 100)),
			@AttributeOverride(name = "lastvieweddate", column = @Column(name = "LASTVIEWEDDATE", length = 100)),
			@AttributeOverride(name = "name", column = @Column(name = "NAME", length = 100)),
			@AttributeOverride(name = "ownerid", column = @Column(name = "OWNERID", length = 100)),
			@AttributeOverride(name = "systemmodstamp", column = @Column(name = "SYSTEMMODSTAMP", length = 100)) })
	public MigrationDocIDriveId getId() {
		return this.id;
	}

	public void setId(MigrationDocIDriveId id) {
		this.id = id;
	}

}
