package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MigrationDocIDriveOld generated by hbm2java
 */
@Entity
@Table(name = "MIGRATION_DOC_I_DRIVE_OLD", schema = "PCRM")
public class MigrationDocIDriveOld implements java.io.Serializable {

	private BigDecimal id;
	private String fileName;
	private String fullname;
	private String bucketName;
	private String cableunitno;
	private String caseno;
	private String customerNumber;
	private String constructionProjectNumber;
	private String sfid;
	private String headendnumber;
	private String contentSize;
	private String fileSizeMb;
	private String contentType;
	private String fileLabel;
	private String kissDoctype;
	private String centaDoctype;
	private String documentId;
	private String extension;
	private String offerid;
	private String supplierrequestid;
	private String mid;
	private String department;
	private String created;
	private String lastmodifieddate;
	private String docremark;
	private String systemid;
	private String amazonpath;
	private String transferstatus;
	private String idrivepath;

	public MigrationDocIDriveOld() {
	}

	public MigrationDocIDriveOld(BigDecimal id) {
		this.id = id;
	}

	public MigrationDocIDriveOld(BigDecimal id, String fileName,
			String fullname, String bucketName, String cableunitno,
			String caseno, String customerNumber,
			String constructionProjectNumber, String sfid,
			String headendnumber, String contentSize, String fileSizeMb,
			String contentType, String fileLabel, String kissDoctype,
			String centaDoctype, String documentId, String extension,
			String offerid, String supplierrequestid, String mid,
			String department, String created, String lastmodifieddate,
			String docremark, String systemid, String amazonpath,
			String transferstatus, String idrivepath) {
		this.id = id;
		this.fileName = fileName;
		this.fullname = fullname;
		this.bucketName = bucketName;
		this.cableunitno = cableunitno;
		this.caseno = caseno;
		this.customerNumber = customerNumber;
		this.constructionProjectNumber = constructionProjectNumber;
		this.sfid = sfid;
		this.headendnumber = headendnumber;
		this.contentSize = contentSize;
		this.fileSizeMb = fileSizeMb;
		this.contentType = contentType;
		this.fileLabel = fileLabel;
		this.kissDoctype = kissDoctype;
		this.centaDoctype = centaDoctype;
		this.documentId = documentId;
		this.extension = extension;
		this.offerid = offerid;
		this.supplierrequestid = supplierrequestid;
		this.mid = mid;
		this.department = department;
		this.created = created;
		this.lastmodifieddate = lastmodifieddate;
		this.docremark = docremark;
		this.systemid = systemid;
		this.amazonpath = amazonpath;
		this.transferstatus = transferstatus;
		this.idrivepath = idrivepath;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "FILE_NAME", length = 3000)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "FULLNAME", length = 3000)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "BUCKET_NAME", length = 3000)
	public String getBucketName() {
		return this.bucketName;
	}

	public void setBucketName(String bucketName) {
		this.bucketName = bucketName;
	}

	@Column(name = "CABLEUNITNO", length = 3000)
	public String getCableunitno() {
		return this.cableunitno;
	}

	public void setCableunitno(String cableunitno) {
		this.cableunitno = cableunitno;
	}

	@Column(name = "CASENO", length = 3000)
	public String getCaseno() {
		return this.caseno;
	}

	public void setCaseno(String caseno) {
		this.caseno = caseno;
	}

	@Column(name = "CUSTOMER_NUMBER", length = 3000)
	public String getCustomerNumber() {
		return this.customerNumber;
	}

	public void setCustomerNumber(String customerNumber) {
		this.customerNumber = customerNumber;
	}

	@Column(name = "CONSTRUCTION_PROJECT_NUMBER", length = 3000)
	public String getConstructionProjectNumber() {
		return this.constructionProjectNumber;
	}

	public void setConstructionProjectNumber(String constructionProjectNumber) {
		this.constructionProjectNumber = constructionProjectNumber;
	}

	@Column(name = "SFID", length = 3000)
	public String getSfid() {
		return this.sfid;
	}

	public void setSfid(String sfid) {
		this.sfid = sfid;
	}

	@Column(name = "HEADENDNUMBER", length = 3000)
	public String getHeadendnumber() {
		return this.headendnumber;
	}

	public void setHeadendnumber(String headendnumber) {
		this.headendnumber = headendnumber;
	}

	@Column(name = "CONTENT_SIZE", length = 3000)
	public String getContentSize() {
		return this.contentSize;
	}

	public void setContentSize(String contentSize) {
		this.contentSize = contentSize;
	}

	@Column(name = "FILE_SIZE_MB", length = 3000)
	public String getFileSizeMb() {
		return this.fileSizeMb;
	}

	public void setFileSizeMb(String fileSizeMb) {
		this.fileSizeMb = fileSizeMb;
	}

	@Column(name = "CONTENT_TYPE", length = 3000)
	public String getContentType() {
		return this.contentType;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	@Column(name = "FILE_LABEL", length = 3000)
	public String getFileLabel() {
		return this.fileLabel;
	}

	public void setFileLabel(String fileLabel) {
		this.fileLabel = fileLabel;
	}

	@Column(name = "KISS_DOCTYPE", length = 3000)
	public String getKissDoctype() {
		return this.kissDoctype;
	}

	public void setKissDoctype(String kissDoctype) {
		this.kissDoctype = kissDoctype;
	}

	@Column(name = "CENTA_DOCTYPE", length = 3000)
	public String getCentaDoctype() {
		return this.centaDoctype;
	}

	public void setCentaDoctype(String centaDoctype) {
		this.centaDoctype = centaDoctype;
	}

	@Column(name = "DOCUMENT_ID", length = 3000)
	public String getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(String documentId) {
		this.documentId = documentId;
	}

	@Column(name = "EXTENSION", length = 3000)
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	@Column(name = "OFFERID", length = 3000)
	public String getOfferid() {
		return this.offerid;
	}

	public void setOfferid(String offerid) {
		this.offerid = offerid;
	}

	@Column(name = "SUPPLIERREQUESTID", length = 3000)
	public String getSupplierrequestid() {
		return this.supplierrequestid;
	}

	public void setSupplierrequestid(String supplierrequestid) {
		this.supplierrequestid = supplierrequestid;
	}

	@Column(name = "MID", length = 3000)
	public String getMid() {
		return this.mid;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

	@Column(name = "DEPARTMENT", length = 3000)
	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "CREATED", length = 3000)
	public String getCreated() {
		return this.created;
	}

	public void setCreated(String created) {
		this.created = created;
	}

	@Column(name = "LASTMODIFIEDDATE", length = 3000)
	public String getLastmodifieddate() {
		return this.lastmodifieddate;
	}

	public void setLastmodifieddate(String lastmodifieddate) {
		this.lastmodifieddate = lastmodifieddate;
	}

	@Column(name = "DOCREMARK", length = 3000)
	public String getDocremark() {
		return this.docremark;
	}

	public void setDocremark(String docremark) {
		this.docremark = docremark;
	}

	@Column(name = "SYSTEMID", length = 3000)
	public String getSystemid() {
		return this.systemid;
	}

	public void setSystemid(String systemid) {
		this.systemid = systemid;
	}

	@Column(name = "AMAZONPATH", length = 3000)
	public String getAmazonpath() {
		return this.amazonpath;
	}

	public void setAmazonpath(String amazonpath) {
		this.amazonpath = amazonpath;
	}

	@Column(name = "TRANSFERSTATUS", length = 3000)
	public String getTransferstatus() {
		return this.transferstatus;
	}

	public void setTransferstatus(String transferstatus) {
		this.transferstatus = transferstatus;
	}

	@Column(name = "IDRIVEPATH", length = 3000)
	public String getIdrivepath() {
		return this.idrivepath;
	}

	public void setIdrivepath(String idrivepath) {
		this.idrivepath = idrivepath;
	}

}
