package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Node generated by hbm2java
 */
@Entity
@Table(name = "NODE", schema = "PCRM")
public class Node implements java.io.Serializable {

	private BigDecimal id;
	private String name;
	private BigDecimal parentid;
	private Long nodetype;
	private Date deleted;
	private Long inherit;

	public Node() {
	}

	public Node(BigDecimal id) {
		this.id = id;
	}

	public Node(BigDecimal id, String name, BigDecimal parentid, Long nodetype,
			Date deleted, Long inherit) {
		this.id = id;
		this.name = name;
		this.parentid = parentid;
		this.nodetype = nodetype;
		this.deleted = deleted;
		this.inherit = inherit;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PARENTID", precision = 22, scale = 0)
	public BigDecimal getParentid() {
		return this.parentid;
	}

	public void setParentid(BigDecimal parentid) {
		this.parentid = parentid;
	}

	@Column(name = "NODETYPE", precision = 10, scale = 0)
	public Long getNodetype() {
		return this.nodetype;
	}

	public void setNodetype(Long nodetype) {
		this.nodetype = nodetype;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELETED", length = 7)
	public Date getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Date deleted) {
		this.deleted = deleted;
	}

	@Column(name = "INHERIT", precision = 10, scale = 0)
	public Long getInherit() {
		return this.inherit;
	}

	public void setInherit(Long inherit) {
		this.inherit = inherit;
	}

}
