package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Note generated by hbm2java
 */
@Entity
@Table(name = "NOTE", schema = "PCRM")
public class Note implements java.io.Serializable {

	private NoteId id;
	private String line;
	private String modts;
	private String modu;
	private String impts;
	private String impu;
	private String classname;
	private String cru;
	private Date crd;
	private String delu;
	private Date deld;
	private Date modd;
	private String sagsnr;
	private String logtrace;

	public Note() {
	}

	public Note(NoteId id) {
		this.id = id;
	}

	public Note(NoteId id, String line, String modts, String modu,
			String impts, String impu, String classname, String cru, Date crd,
			String delu, Date deld, Date modd, String sagsnr, String logtrace) {
		this.id = id;
		this.line = line;
		this.modts = modts;
		this.modu = modu;
		this.impts = impts;
		this.impu = impu;
		this.classname = classname;
		this.cru = cru;
		this.crd = crd;
		this.delu = delu;
		this.deld = deld;
		this.modd = modd;
		this.sagsnr = sagsnr;
		this.logtrace = logtrace;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, length = 19)),
			@AttributeOverride(name = "com", column = @Column(name = "COM", nullable = false, length = 15)),
			@AttributeOverride(name = "seq", column = @Column(name = "SEQ", nullable = false, length = 15)) })
	public NoteId getId() {
		return this.id;
	}

	public void setId(NoteId id) {
		this.id = id;
	}

	@Column(name = "LINE", length = 254)
	public String getLine() {
		return this.line;
	}

	public void setLine(String line) {
		this.line = line;
	}

	@Column(name = "MODTS", length = 13)
	public String getModts() {
		return this.modts;
	}

	public void setModts(String modts) {
		this.modts = modts;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "IMPTS", length = 13)
	public String getImpts() {
		return this.impts;
	}

	public void setImpts(String impts) {
		this.impts = impts;
	}

	@Column(name = "IMPU", length = 5)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "CLASSNAME", length = 254)
	public String getClassname() {
		return this.classname;
	}

	public void setClassname(String classname) {
		this.classname = classname;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "SAGSNR", length = 30)
	public String getSagsnr() {
		return this.sagsnr;
	}

	public void setSagsnr(String sagsnr) {
		this.sagsnr = sagsnr;
	}

	@Column(name = "LOGTRACE", length = 19)
	public String getLogtrace() {
		return this.logtrace;
	}

	public void setLogtrace(String logtrace) {
		this.logtrace = logtrace;
	}

}
