package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Oppartyaddress generated by hbm2java
 */
@Entity
@Table(name = "OPPARTYADDRESS", schema = "PCRM")
public class Oppartyaddress implements java.io.Serializable {

	private String id;
	private Date crd;
	private String cru;
	private Date modd;
	private String modu;
	private Date deld;
	private String delu;
	private Date impd;
	private String impu;
	private Date expd;
	private String expu;
	private Date invalidated;
	private String kvhX;
	private String munid;
	private String streetid;
	private String streetname;
	private String houseno;
	private String floorid;
	private String placement;
	private String postalid;
	private String postaldistrict;
	private String placename;
	private String sourcesystem;
	private Set<Opparty> opparties = new HashSet<Opparty>(0);

	public Oppartyaddress() {
	}

	public Oppartyaddress(String id) {
		this.id = id;
	}

	public Oppartyaddress(String id, Date crd, String cru, Date modd,
			String modu, Date deld, String delu, Date impd, String impu,
			Date expd, String expu, Date invalidated, String kvhX,
			String munid, String streetid, String streetname, String houseno,
			String floorid, String placement, String postalid,
			String postaldistrict, String placename, String sourcesystem,
			Set<Opparty> opparties) {
		this.id = id;
		this.crd = crd;
		this.cru = cru;
		this.modd = modd;
		this.modu = modu;
		this.deld = deld;
		this.delu = delu;
		this.impd = impd;
		this.impu = impu;
		this.expd = expd;
		this.expu = expu;
		this.invalidated = invalidated;
		this.kvhX = kvhX;
		this.munid = munid;
		this.streetid = streetid;
		this.streetname = streetname;
		this.houseno = houseno;
		this.floorid = floorid;
		this.placement = placement;
		this.postalid = postalid;
		this.postaldistrict = postaldistrict;
		this.placename = placename;
		this.sourcesystem = sourcesystem;
		this.opparties = opparties;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INVALIDATED", length = 7)
	public Date getInvalidated() {
		return this.invalidated;
	}

	public void setInvalidated(Date invalidated) {
		this.invalidated = invalidated;
	}

	@Column(name = "KVH_X", length = 17)
	public String getKvhX() {
		return this.kvhX;
	}

	public void setKvhX(String kvhX) {
		this.kvhX = kvhX;
	}

	@Column(name = "MUNID", length = 3)
	public String getMunid() {
		return this.munid;
	}

	public void setMunid(String munid) {
		this.munid = munid;
	}

	@Column(name = "STREETID", length = 4)
	public String getStreetid() {
		return this.streetid;
	}

	public void setStreetid(String streetid) {
		this.streetid = streetid;
	}

	@Column(name = "STREETNAME", length = 100)
	public String getStreetname() {
		return this.streetname;
	}

	public void setStreetname(String streetname) {
		this.streetname = streetname;
	}

	@Column(name = "HOUSENO", length = 4)
	public String getHouseno() {
		return this.houseno;
	}

	public void setHouseno(String houseno) {
		this.houseno = houseno;
	}

	@Column(name = "FLOORID", length = 2)
	public String getFloorid() {
		return this.floorid;
	}

	public void setFloorid(String floorid) {
		this.floorid = floorid;
	}

	@Column(name = "PLACEMENT", length = 4)
	public String getPlacement() {
		return this.placement;
	}

	public void setPlacement(String placement) {
		this.placement = placement;
	}

	@Column(name = "POSTALID", length = 4)
	public String getPostalid() {
		return this.postalid;
	}

	public void setPostalid(String postalid) {
		this.postalid = postalid;
	}

	@Column(name = "POSTALDISTRICT", length = 50)
	public String getPostaldistrict() {
		return this.postaldistrict;
	}

	public void setPostaldistrict(String postaldistrict) {
		this.postaldistrict = postaldistrict;
	}

	@Column(name = "PLACENAME", length = 50)
	public String getPlacename() {
		return this.placename;
	}

	public void setPlacename(String placename) {
		this.placename = placename;
	}

	@Column(name = "SOURCESYSTEM", length = 50)
	public String getSourcesystem() {
		return this.sourcesystem;
	}

	public void setSourcesystem(String sourcesystem) {
		this.sourcesystem = sourcesystem;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "oppartyaddress")
	public Set<Opparty> getOpparties() {
		return this.opparties;
	}

	public void setOpparties(Set<Opparty> opparties) {
		this.opparties = opparties;
	}

}
