package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Opparty generated by hbm2java
 */
@Entity
@Table(name = "OPPARTY", schema = "PCRM")
public class Opparty implements java.io.Serializable {

	private String id;
	private Oppartyaddress oppartyaddress;
	private Date crd;
	private String cru;
	private Date modd;
	private String modu;
	private Date deld;
	private String delu;
	private Date impd;
	private String impu;
	private Date expd;
	private String expu;
	private Date invalidated;
	private String itemcode;
	private String title;
	private String position;
	private String firstname;
	private String surname;
	private String company;
	private String association;
	private String phone;
	private String phoneext;
	private String privatephone;
	private String mobilephone;
	private String email;
	private Character allowcontact;
	private Character allownews;
	private Set<Opuseraccount> opuseraccounts = new HashSet<Opuseraccount>(0);

	public Opparty() {
	}

	public Opparty(String id) {
		this.id = id;
	}

	public Opparty(String id, Oppartyaddress oppartyaddress, Date crd,
			String cru, Date modd, String modu, Date deld, String delu,
			Date impd, String impu, Date expd, String expu, Date invalidated,
			String itemcode, String title, String position, String firstname,
			String surname, String company, String association, String phone,
			String phoneext, String privatephone, String mobilephone,
			String email, Character allowcontact, Character allownews,
			Set<Opuseraccount> opuseraccounts) {
		this.id = id;
		this.oppartyaddress = oppartyaddress;
		this.crd = crd;
		this.cru = cru;
		this.modd = modd;
		this.modu = modu;
		this.deld = deld;
		this.delu = delu;
		this.impd = impd;
		this.impu = impu;
		this.expd = expd;
		this.expu = expu;
		this.invalidated = invalidated;
		this.itemcode = itemcode;
		this.title = title;
		this.position = position;
		this.firstname = firstname;
		this.surname = surname;
		this.company = company;
		this.association = association;
		this.phone = phone;
		this.phoneext = phoneext;
		this.privatephone = privatephone;
		this.mobilephone = mobilephone;
		this.email = email;
		this.allowcontact = allowcontact;
		this.allownews = allownews;
		this.opuseraccounts = opuseraccounts;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMPARTYADDRESS")
	public Oppartyaddress getOppartyaddress() {
		return this.oppartyaddress;
	}

	public void setOppartyaddress(Oppartyaddress oppartyaddress) {
		this.oppartyaddress = oppartyaddress;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INVALIDATED", length = 7)
	public Date getInvalidated() {
		return this.invalidated;
	}

	public void setInvalidated(Date invalidated) {
		this.invalidated = invalidated;
	}

	@Column(name = "ITEMCODE", length = 50)
	public String getItemcode() {
		return this.itemcode;
	}

	public void setItemcode(String itemcode) {
		this.itemcode = itemcode;
	}

	@Column(name = "TITLE", length = 100)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "POSITION", length = 100)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@Column(name = "FIRSTNAME", length = 100)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "SURNAME", length = 100)
	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	@Column(name = "COMPANY", length = 100)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "ASSOCIATION", length = 100)
	public String getAssociation() {
		return this.association;
	}

	public void setAssociation(String association) {
		this.association = association;
	}

	@Column(name = "PHONE", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "PHONEEXT", length = 20)
	public String getPhoneext() {
		return this.phoneext;
	}

	public void setPhoneext(String phoneext) {
		this.phoneext = phoneext;
	}

	@Column(name = "PRIVATEPHONE", length = 20)
	public String getPrivatephone() {
		return this.privatephone;
	}

	public void setPrivatephone(String privatephone) {
		this.privatephone = privatephone;
	}

	@Column(name = "MOBILEPHONE", length = 20)
	public String getMobilephone() {
		return this.mobilephone;
	}

	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "ALLOWCONTACT", length = 1)
	public Character getAllowcontact() {
		return this.allowcontact;
	}

	public void setAllowcontact(Character allowcontact) {
		this.allowcontact = allowcontact;
	}

	@Column(name = "ALLOWNEWS", length = 1)
	public Character getAllownews() {
		return this.allownews;
	}

	public void setAllownews(Character allownews) {
		this.allownews = allownews;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opparty")
	public Set<Opuseraccount> getOpuseraccounts() {
		return this.opuseraccounts;
	}

	public void setOpuseraccounts(Set<Opuseraccount> opuseraccounts) {
		this.opuseraccounts = opuseraccounts;
	}

}
