package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Opuseraccount generated by hbm2java
 */
@Entity
@Table(name = "OPUSERACCOUNT", schema = "PCRM", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PRIMOPPARTY", "INVALIDATED" }))
public class Opuseraccount implements java.io.Serializable {

	private String id;
	private Opparty opparty;
	private Date crd;
	private String cru;
	private Date modd;
	private String modu;
	private Date deld;
	private String delu;
	private Date impd;
	private String impu;
	private Date expd;
	private String expu;
	private Date invalidated;
	private String accountid;
	private String accountpw;
	private String useraccountstate;
	private String userprofile;
	private Set<Opcableunituser> opcableunitusers = new HashSet<Opcableunituser>(
			0);

	public Opuseraccount() {
	}

	public Opuseraccount(String id) {
		this.id = id;
	}

	public Opuseraccount(String id, Opparty opparty, Date crd, String cru,
			Date modd, String modu, Date deld, String delu, Date impd,
			String impu, Date expd, String expu, Date invalidated,
			String accountid, String accountpw, String useraccountstate,
			String userprofile, Set<Opcableunituser> opcableunitusers) {
		this.id = id;
		this.opparty = opparty;
		this.crd = crd;
		this.cru = cru;
		this.modd = modd;
		this.modu = modu;
		this.deld = deld;
		this.delu = delu;
		this.impd = impd;
		this.impu = impu;
		this.expd = expd;
		this.expu = expu;
		this.invalidated = invalidated;
		this.accountid = accountid;
		this.accountpw = accountpw;
		this.useraccountstate = useraccountstate;
		this.userprofile = userprofile;
		this.opcableunitusers = opcableunitusers;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMOPPARTY")
	public Opparty getOpparty() {
		return this.opparty;
	}

	public void setOpparty(Opparty opparty) {
		this.opparty = opparty;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INVALIDATED", length = 7)
	public Date getInvalidated() {
		return this.invalidated;
	}

	public void setInvalidated(Date invalidated) {
		this.invalidated = invalidated;
	}

	@Column(name = "ACCOUNTID", length = 50)
	public String getAccountid() {
		return this.accountid;
	}

	public void setAccountid(String accountid) {
		this.accountid = accountid;
	}

	@Column(name = "ACCOUNTPW", length = 50)
	public String getAccountpw() {
		return this.accountpw;
	}

	public void setAccountpw(String accountpw) {
		this.accountpw = accountpw;
	}

	@Column(name = "USERACCOUNTSTATE", length = 50)
	public String getUseraccountstate() {
		return this.useraccountstate;
	}

	public void setUseraccountstate(String useraccountstate) {
		this.useraccountstate = useraccountstate;
	}

	@Column(name = "USERPROFILE", length = 50)
	public String getUserprofile() {
		return this.userprofile;
	}

	public void setUserprofile(String userprofile) {
		this.userprofile = userprofile;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "opuseraccount")
	public Set<Opcableunituser> getOpcableunitusers() {
		return this.opcableunitusers;
	}

	public void setOpcableunitusers(Set<Opcableunituser> opcableunitusers) {
		this.opcableunitusers = opcableunitusers;
	}

}
