package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PartyactorChghistDrop generated by hbm2java
 */
@Entity
@Table(name = "PARTYACTOR_CHGHIST_DROP", schema = "PCRM")
public class PartyactorChghistDrop implements java.io.Serializable {

	private String audId;
	private String audAction;
	private Serializable audTimestamp;
	private String audOsuser;
	private String audDbuser;
	private String audUserterminal;
	private String id;
	private Date crd;
	private String primaryadresse;
	private String primarysalesforecast;
	private Date impt;
	private Date expt;
	private Date impd;
	private Date expd;
	private Date modt;
	private Character tmpcommadr;
	private String cru;
	private String primarycontact;
	private Date delt;
	private Date modd;
	private String impu;
	private String expu;
	private Date deld;
	private Character contcommadr;
	private Character custcommadr;
	private String modu;
	private String delu;
	private String primarycompany;
	private Date crt;
	private String primaryrole;
	private String primarycontactmail;
	private String phoneday;
	private String phoneevening;
	private BigDecimal antal;
	private String dwAdrid;
	private String primarykontrakt;
	private String XKundeforholdId;
	private String primaryanlaeg;
	private String company;
	private String primarycdmmodelfield;
	private String keyfieldvalue;
	private String firstn;
	private String lastn;
	private String title;
	private String attention;
	private String ext;
	private String phoneextday;
	private String phoneextevening;
	private String direct;
	private String private_;
	private String fax;
	private String mobile;
	private String email;
	private Character masterrole;
	private String sourceSystem;

	public PartyactorChghistDrop() {
	}

	public PartyactorChghistDrop(String audId) {
		this.audId = audId;
	}

	public PartyactorChghistDrop(String audId, String audAction,
			Serializable audTimestamp, String audOsuser, String audDbuser,
			String audUserterminal, String id, Date crd, String primaryadresse,
			String primarysalesforecast, Date impt, Date expt, Date impd,
			Date expd, Date modt, Character tmpcommadr, String cru,
			String primarycontact, Date delt, Date modd, String impu,
			String expu, Date deld, Character contcommadr,
			Character custcommadr, String modu, String delu,
			String primarycompany, Date crt, String primaryrole,
			String primarycontactmail, String phoneday, String phoneevening,
			BigDecimal antal, String dwAdrid, String primarykontrakt,
			String XKundeforholdId, String primaryanlaeg, String company,
			String primarycdmmodelfield, String keyfieldvalue, String firstn,
			String lastn, String title, String attention, String ext,
			String phoneextday, String phoneextevening, String direct,
			String private_, String fax, String mobile, String email,
			Character masterrole, String sourceSystem) {
		this.audId = audId;
		this.audAction = audAction;
		this.audTimestamp = audTimestamp;
		this.audOsuser = audOsuser;
		this.audDbuser = audDbuser;
		this.audUserterminal = audUserterminal;
		this.id = id;
		this.crd = crd;
		this.primaryadresse = primaryadresse;
		this.primarysalesforecast = primarysalesforecast;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.tmpcommadr = tmpcommadr;
		this.cru = cru;
		this.primarycontact = primarycontact;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.contcommadr = contcommadr;
		this.custcommadr = custcommadr;
		this.modu = modu;
		this.delu = delu;
		this.primarycompany = primarycompany;
		this.crt = crt;
		this.primaryrole = primaryrole;
		this.primarycontactmail = primarycontactmail;
		this.phoneday = phoneday;
		this.phoneevening = phoneevening;
		this.antal = antal;
		this.dwAdrid = dwAdrid;
		this.primarykontrakt = primarykontrakt;
		this.XKundeforholdId = XKundeforholdId;
		this.primaryanlaeg = primaryanlaeg;
		this.company = company;
		this.primarycdmmodelfield = primarycdmmodelfield;
		this.keyfieldvalue = keyfieldvalue;
		this.firstn = firstn;
		this.lastn = lastn;
		this.title = title;
		this.attention = attention;
		this.ext = ext;
		this.phoneextday = phoneextday;
		this.phoneextevening = phoneextevening;
		this.direct = direct;
		this.private_ = private_;
		this.fax = fax;
		this.mobile = mobile;
		this.email = email;
		this.masterrole = masterrole;
		this.sourceSystem = sourceSystem;
	}

	@Id
	@Column(name = "AUD_ID", unique = true, nullable = false, length = 19)
	public String getAudId() {
		return this.audId;
	}

	public void setAudId(String audId) {
		this.audId = audId;
	}

	@Column(name = "AUD_ACTION", length = 50)
	public String getAudAction() {
		return this.audAction;
	}

	public void setAudAction(String audAction) {
		this.audAction = audAction;
	}

	@Column(name = "AUD_TIMESTAMP")
	public Serializable getAudTimestamp() {
		return this.audTimestamp;
	}

	public void setAudTimestamp(Serializable audTimestamp) {
		this.audTimestamp = audTimestamp;
	}

	@Column(name = "AUD_OSUSER", length = 50)
	public String getAudOsuser() {
		return this.audOsuser;
	}

	public void setAudOsuser(String audOsuser) {
		this.audOsuser = audOsuser;
	}

	@Column(name = "AUD_DBUSER", length = 50)
	public String getAudDbuser() {
		return this.audDbuser;
	}

	public void setAudDbuser(String audDbuser) {
		this.audDbuser = audDbuser;
	}

	@Column(name = "AUD_USERTERMINAL", length = 50)
	public String getAudUserterminal() {
		return this.audUserterminal;
	}

	public void setAudUserterminal(String audUserterminal) {
		this.audUserterminal = audUserterminal;
	}

	@Column(name = "ID", length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "PRIMARYADRESSE", length = 22)
	public String getPrimaryadresse() {
		return this.primaryadresse;
	}

	public void setPrimaryadresse(String primaryadresse) {
		this.primaryadresse = primaryadresse;
	}

	@Column(name = "PRIMARYSALESFORECAST", length = 19)
	public String getPrimarysalesforecast() {
		return this.primarysalesforecast;
	}

	public void setPrimarysalesforecast(String primarysalesforecast) {
		this.primarysalesforecast = primarysalesforecast;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "TMPCOMMADR", length = 1)
	public Character getTmpcommadr() {
		return this.tmpcommadr;
	}

	public void setTmpcommadr(Character tmpcommadr) {
		this.tmpcommadr = tmpcommadr;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Column(name = "PRIMARYCONTACT", length = 19)
	public String getPrimarycontact() {
		return this.primarycontact;
	}

	public void setPrimarycontact(String primarycontact) {
		this.primarycontact = primarycontact;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "CONTCOMMADR", length = 1)
	public Character getContcommadr() {
		return this.contcommadr;
	}

	public void setContcommadr(Character contcommadr) {
		this.contcommadr = contcommadr;
	}

	@Column(name = "CUSTCOMMADR", length = 1)
	public Character getCustcommadr() {
		return this.custcommadr;
	}

	public void setCustcommadr(Character custcommadr) {
		this.custcommadr = custcommadr;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Column(name = "PRIMARYCOMPANY", length = 19)
	public String getPrimarycompany() {
		return this.primarycompany;
	}

	public void setPrimarycompany(String primarycompany) {
		this.primarycompany = primarycompany;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "PRIMARYROLE", length = 19)
	public String getPrimaryrole() {
		return this.primaryrole;
	}

	public void setPrimaryrole(String primaryrole) {
		this.primaryrole = primaryrole;
	}

	@Column(name = "PRIMARYCONTACTMAIL", length = 19)
	public String getPrimarycontactmail() {
		return this.primarycontactmail;
	}

	public void setPrimarycontactmail(String primarycontactmail) {
		this.primarycontactmail = primarycontactmail;
	}

	@Column(name = "PHONEDAY", length = 20)
	public String getPhoneday() {
		return this.phoneday;
	}

	public void setPhoneday(String phoneday) {
		this.phoneday = phoneday;
	}

	@Column(name = "PHONEEVENING", length = 20)
	public String getPhoneevening() {
		return this.phoneevening;
	}

	public void setPhoneevening(String phoneevening) {
		this.phoneevening = phoneevening;
	}

	@Column(name = "ANTAL", precision = 22, scale = 0)
	public BigDecimal getAntal() {
		return this.antal;
	}

	public void setAntal(BigDecimal antal) {
		this.antal = antal;
	}

	@Column(name = "DW_ADRID", length = 32)
	public String getDwAdrid() {
		return this.dwAdrid;
	}

	public void setDwAdrid(String dwAdrid) {
		this.dwAdrid = dwAdrid;
	}

	@Column(name = "PRIMARYKONTRAKT", length = 19)
	public String getPrimarykontrakt() {
		return this.primarykontrakt;
	}

	public void setPrimarykontrakt(String primarykontrakt) {
		this.primarykontrakt = primarykontrakt;
	}

	@Column(name = "X_KUNDEFORHOLD_ID", length = 10)
	public String getXKundeforholdId() {
		return this.XKundeforholdId;
	}

	public void setXKundeforholdId(String XKundeforholdId) {
		this.XKundeforholdId = XKundeforholdId;
	}

	@Column(name = "PRIMARYANLAEG", length = 10)
	public String getPrimaryanlaeg() {
		return this.primaryanlaeg;
	}

	public void setPrimaryanlaeg(String primaryanlaeg) {
		this.primaryanlaeg = primaryanlaeg;
	}

	@Column(name = "COMPANY")
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "PRIMARYCDMMODELFIELD")
	public String getPrimarycdmmodelfield() {
		return this.primarycdmmodelfield;
	}

	public void setPrimarycdmmodelfield(String primarycdmmodelfield) {
		this.primarycdmmodelfield = primarycdmmodelfield;
	}

	@Column(name = "KEYFIELDVALUE")
	public String getKeyfieldvalue() {
		return this.keyfieldvalue;
	}

	public void setKeyfieldvalue(String keyfieldvalue) {
		this.keyfieldvalue = keyfieldvalue;
	}

	@Column(name = "FIRSTN", length = 35)
	public String getFirstn() {
		return this.firstn;
	}

	public void setFirstn(String firstn) {
		this.firstn = firstn;
	}

	@Column(name = "LASTN", length = 35)
	public String getLastn() {
		return this.lastn;
	}

	public void setLastn(String lastn) {
		this.lastn = lastn;
	}

	@Column(name = "TITLE", length = 35)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "ATTENTION")
	public String getAttention() {
		return this.attention;
	}

	public void setAttention(String attention) {
		this.attention = attention;
	}

	@Column(name = "EXT", length = 20)
	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	@Column(name = "PHONEEXTDAY", length = 20)
	public String getPhoneextday() {
		return this.phoneextday;
	}

	public void setPhoneextday(String phoneextday) {
		this.phoneextday = phoneextday;
	}

	@Column(name = "PHONEEXTEVENING", length = 20)
	public String getPhoneextevening() {
		return this.phoneextevening;
	}

	public void setPhoneextevening(String phoneextevening) {
		this.phoneextevening = phoneextevening;
	}

	@Column(name = "DIRECT", length = 20)
	public String getDirect() {
		return this.direct;
	}

	public void setDirect(String direct) {
		this.direct = direct;
	}

	@Column(name = "PRIVATE", length = 20)
	public String getPrivate_() {
		return this.private_;
	}

	public void setPrivate_(String private_) {
		this.private_ = private_;
	}

	@Column(name = "FAX", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "MOBILE", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "MASTERROLE", length = 1)
	public Character getMasterrole() {
		return this.masterrole;
	}

	public void setMasterrole(Character masterrole) {
		this.masterrole = masterrole;
	}

	@Column(name = "SOURCE_SYSTEM", length = 5)
	public String getSourceSystem() {
		return this.sourceSystem;
	}

	public void setSourceSystem(String sourceSystem) {
		this.sourceSystem = sourceSystem;
	}

}
