package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PartyDrop generated by hbm2java
 */
@Entity
@Table(name = "PARTY_DROP", schema = "PCRM")
public class PartyDrop implements java.io.Serializable {

	private String id;
	private String education;
	private String primcont;
	private String town;
	private Date impt;
	private String primsour;
	private Date deld;
	private String addr3;
	private Character mailstop;
	private Date crd;
	private String expu;
	private Date crt;
	private String primcomp;
	private Byte loyalty;
	private String email;
	private String postcode;
	private String modu;
	private String addr4;
	private String cru;
	private Date impd;
	private Character notdublet;
	private String private_;
	private String ext;
	private String direct;
	private String titulation;
	private String delu;
	private String firstn;
	private Date expt;
	private Date modd;
	private String title;
	private String voicel;
	private String lastn;
	private Date modt;
	private String primcoun;
	private String addr1;
	private String fax;
	private Byte content;
	private String impu;
	private Date borndate;
	private Date expd;
	private Date delt;
	private String primarypostcode;
	private String addr2;
	private String mobile;
	private String primaryadresse;
	private String phoneday;
	private String phoneevening;
	private String postbox;
	private String company;
	private String anlaegsnr;
	private String newDwAdrid;
	private String postdisttxt;
	private String primku;
	private Long projektlobenr;
	private String phoneextday;
	private String phoneextevening;
	private String sourceSystem;
	private Long addressid;
	private Set<PartyactorDrop> partyactorDrops = new HashSet<PartyactorDrop>(0);

	public PartyDrop() {
	}

	public PartyDrop(String id) {
		this.id = id;
	}

	public PartyDrop(String id, String education, String primcont, String town,
			Date impt, String primsour, Date deld, String addr3,
			Character mailstop, Date crd, String expu, Date crt,
			String primcomp, Byte loyalty, String email, String postcode,
			String modu, String addr4, String cru, Date impd,
			Character notdublet, String private_, String ext, String direct,
			String titulation, String delu, String firstn, Date expt,
			Date modd, String title, String voicel, String lastn, Date modt,
			String primcoun, String addr1, String fax, Byte content,
			String impu, Date borndate, Date expd, Date delt,
			String primarypostcode, String addr2, String mobile,
			String primaryadresse, String phoneday, String phoneevening,
			String postbox, String company, String anlaegsnr,
			String newDwAdrid, String postdisttxt, String primku,
			Long projektlobenr, String phoneextday, String phoneextevening,
			String sourceSystem, Long addressid,
			Set<PartyactorDrop> partyactorDrops) {
		this.id = id;
		this.education = education;
		this.primcont = primcont;
		this.town = town;
		this.impt = impt;
		this.primsour = primsour;
		this.deld = deld;
		this.addr3 = addr3;
		this.mailstop = mailstop;
		this.crd = crd;
		this.expu = expu;
		this.crt = crt;
		this.primcomp = primcomp;
		this.loyalty = loyalty;
		this.email = email;
		this.postcode = postcode;
		this.modu = modu;
		this.addr4 = addr4;
		this.cru = cru;
		this.impd = impd;
		this.notdublet = notdublet;
		this.private_ = private_;
		this.ext = ext;
		this.direct = direct;
		this.titulation = titulation;
		this.delu = delu;
		this.firstn = firstn;
		this.expt = expt;
		this.modd = modd;
		this.title = title;
		this.voicel = voicel;
		this.lastn = lastn;
		this.modt = modt;
		this.primcoun = primcoun;
		this.addr1 = addr1;
		this.fax = fax;
		this.content = content;
		this.impu = impu;
		this.borndate = borndate;
		this.expd = expd;
		this.delt = delt;
		this.primarypostcode = primarypostcode;
		this.addr2 = addr2;
		this.mobile = mobile;
		this.primaryadresse = primaryadresse;
		this.phoneday = phoneday;
		this.phoneevening = phoneevening;
		this.postbox = postbox;
		this.company = company;
		this.anlaegsnr = anlaegsnr;
		this.newDwAdrid = newDwAdrid;
		this.postdisttxt = postdisttxt;
		this.primku = primku;
		this.projektlobenr = projektlobenr;
		this.phoneextday = phoneextday;
		this.phoneextevening = phoneextevening;
		this.sourceSystem = sourceSystem;
		this.addressid = addressid;
		this.partyactorDrops = partyactorDrops;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "EDUCATION", length = 35)
	public String getEducation() {
		return this.education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	@Column(name = "PRIMCONT", length = 19)
	public String getPrimcont() {
		return this.primcont;
	}

	public void setPrimcont(String primcont) {
		this.primcont = primcont;
	}

	@Column(name = "TOWN", length = 35)
	public String getTown() {
		return this.town;
	}

	public void setTown(String town) {
		this.town = town;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Column(name = "PRIMSOUR", length = 19)
	public String getPrimsour() {
		return this.primsour;
	}

	public void setPrimsour(String primsour) {
		this.primsour = primsour;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "ADDR3", length = 35)
	public String getAddr3() {
		return this.addr3;
	}

	public void setAddr3(String addr3) {
		this.addr3 = addr3;
	}

	@Column(name = "MAILSTOP", length = 1)
	public Character getMailstop() {
		return this.mailstop;
	}

	public void setMailstop(Character mailstop) {
		this.mailstop = mailstop;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "PRIMCOMP", length = 19)
	public String getPrimcomp() {
		return this.primcomp;
	}

	public void setPrimcomp(String primcomp) {
		this.primcomp = primcomp;
	}

	@Column(name = "LOYALTY", precision = 2, scale = 0)
	public Byte getLoyalty() {
		return this.loyalty;
	}

	public void setLoyalty(Byte loyalty) {
		this.loyalty = loyalty;
	}

	@Column(name = "EMAIL", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "POSTCODE", length = 15)
	public String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(String postcode) {
		this.postcode = postcode;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "ADDR4", length = 35)
	public String getAddr4() {
		return this.addr4;
	}

	public void setAddr4(String addr4) {
		this.addr4 = addr4;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Column(name = "NOTDUBLET", length = 1)
	public Character getNotdublet() {
		return this.notdublet;
	}

	public void setNotdublet(Character notdublet) {
		this.notdublet = notdublet;
	}

	@Column(name = "PRIVATE", length = 20)
	public String getPrivate_() {
		return this.private_;
	}

	public void setPrivate_(String private_) {
		this.private_ = private_;
	}

	@Column(name = "EXT", length = 20)
	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	@Column(name = "DIRECT", length = 20)
	public String getDirect() {
		return this.direct;
	}

	public void setDirect(String direct) {
		this.direct = direct;
	}

	@Column(name = "TITULATION", length = 35)
	public String getTitulation() {
		return this.titulation;
	}

	public void setTitulation(String titulation) {
		this.titulation = titulation;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Column(name = "FIRSTN", length = 35)
	public String getFirstn() {
		return this.firstn;
	}

	public void setFirstn(String firstn) {
		this.firstn = firstn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "TITLE", length = 35)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "VOICEL", length = 20)
	public String getVoicel() {
		return this.voicel;
	}

	public void setVoicel(String voicel) {
		this.voicel = voicel;
	}

	@Column(name = "LASTN", length = 35)
	public String getLastn() {
		return this.lastn;
	}

	public void setLastn(String lastn) {
		this.lastn = lastn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "PRIMCOUN", length = 19)
	public String getPrimcoun() {
		return this.primcoun;
	}

	public void setPrimcoun(String primcoun) {
		this.primcoun = primcoun;
	}

	@Column(name = "ADDR1", length = 35)
	public String getAddr1() {
		return this.addr1;
	}

	public void setAddr1(String addr1) {
		this.addr1 = addr1;
	}

	@Column(name = "FAX", length = 20)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "CONTENT", precision = 2, scale = 0)
	public Byte getContent() {
		return this.content;
	}

	public void setContent(Byte content) {
		this.content = content;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BORNDATE", length = 7)
	public Date getBorndate() {
		return this.borndate;
	}

	public void setBorndate(Date borndate) {
		this.borndate = borndate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Column(name = "PRIMARYPOSTCODE", length = 19)
	public String getPrimarypostcode() {
		return this.primarypostcode;
	}

	public void setPrimarypostcode(String primarypostcode) {
		this.primarypostcode = primarypostcode;
	}

	@Column(name = "ADDR2", length = 35)
	public String getAddr2() {
		return this.addr2;
	}

	public void setAddr2(String addr2) {
		this.addr2 = addr2;
	}

	@Column(name = "MOBILE", length = 20)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "PRIMARYADRESSE", length = 22)
	public String getPrimaryadresse() {
		return this.primaryadresse;
	}

	public void setPrimaryadresse(String primaryadresse) {
		this.primaryadresse = primaryadresse;
	}

	@Column(name = "PHONEDAY", length = 20)
	public String getPhoneday() {
		return this.phoneday;
	}

	public void setPhoneday(String phoneday) {
		this.phoneday = phoneday;
	}

	@Column(name = "PHONEEVENING", length = 20)
	public String getPhoneevening() {
		return this.phoneevening;
	}

	public void setPhoneevening(String phoneevening) {
		this.phoneevening = phoneevening;
	}

	@Column(name = "POSTBOX", length = 32)
	public String getPostbox() {
		return this.postbox;
	}

	public void setPostbox(String postbox) {
		this.postbox = postbox;
	}

	@Column(name = "COMPANY")
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "ANLAEGSNR", length = 11)
	public String getAnlaegsnr() {
		return this.anlaegsnr;
	}

	public void setAnlaegsnr(String anlaegsnr) {
		this.anlaegsnr = anlaegsnr;
	}

	@Column(name = "NEW_DW_ADRID", length = 32)
	public String getNewDwAdrid() {
		return this.newDwAdrid;
	}

	public void setNewDwAdrid(String newDwAdrid) {
		this.newDwAdrid = newDwAdrid;
	}

	@Column(name = "POSTDISTTXT", length = 20)
	public String getPostdisttxt() {
		return this.postdisttxt;
	}

	public void setPostdisttxt(String postdisttxt) {
		this.postdisttxt = postdisttxt;
	}

	@Column(name = "PRIMKU", length = 19)
	public String getPrimku() {
		return this.primku;
	}

	public void setPrimku(String primku) {
		this.primku = primku;
	}

	@Column(name = "PROJEKTLOBENR", precision = 10, scale = 0)
	public Long getProjektlobenr() {
		return this.projektlobenr;
	}

	public void setProjektlobenr(Long projektlobenr) {
		this.projektlobenr = projektlobenr;
	}

	@Column(name = "PHONEEXTDAY", length = 20)
	public String getPhoneextday() {
		return this.phoneextday;
	}

	public void setPhoneextday(String phoneextday) {
		this.phoneextday = phoneextday;
	}

	@Column(name = "PHONEEXTEVENING", length = 20)
	public String getPhoneextevening() {
		return this.phoneextevening;
	}

	public void setPhoneextevening(String phoneextevening) {
		this.phoneextevening = phoneextevening;
	}

	@Column(name = "SOURCE_SYSTEM", length = 5)
	public String getSourceSystem() {
		return this.sourceSystem;
	}

	public void setSourceSystem(String sourceSystem) {
		this.sourceSystem = sourceSystem;
	}

	@Column(name = "ADDRESSID", precision = 10, scale = 0)
	public Long getAddressid() {
		return this.addressid;
	}

	public void setAddressid(Long addressid) {
		this.addressid = addressid;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partyDrop")
	public Set<PartyactorDrop> getPartyactorDrops() {
		return this.partyactorDrops;
	}

	public void setPartyactorDrops(Set<PartyactorDrop> partyactorDrops) {
		this.partyactorDrops = partyactorDrops;
	}

}
