package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Pricelabel generated by hbm2java
 */
@Entity
@Table(name = "PRICELABEL", schema = "PCRM", uniqueConstraints = @UniqueConstraint(columnNames = "NUMBER_01"))
public class Pricelabel implements java.io.Serializable {

	private String id;
	private Pricegroup pricegroup;
	private String code;
	private Date crd;
	private String cru;
	private Date modd;
	private String modu;
	private Date impd;
	private String impu;
	private Date expd;
	private String expu;
	private Character active;
	private Date invalidated;
	private String head;
	private String pricetype;
	private String primpricetype;
	private String primproductspec;
	private BigDecimal number01;
	private Character showincontract;
	private Set<Price> prices = new HashSet<Price>(0);

	public Pricelabel() {
	}

	public Pricelabel(String id) {
		this.id = id;
	}

	public Pricelabel(String id, Pricegroup pricegroup, String code, Date crd,
			String cru, Date modd, String modu, Date impd, String impu,
			Date expd, String expu, Character active, Date invalidated,
			String head, String pricetype, String primpricetype,
			String primproductspec, BigDecimal number01,
			Character showincontract, Set<Price> prices) {
		this.id = id;
		this.pricegroup = pricegroup;
		this.code = code;
		this.crd = crd;
		this.cru = cru;
		this.modd = modd;
		this.modu = modu;
		this.impd = impd;
		this.impu = impu;
		this.expd = expd;
		this.expu = expu;
		this.active = active;
		this.invalidated = invalidated;
		this.head = head;
		this.pricetype = pricetype;
		this.primpricetype = primpricetype;
		this.primproductspec = primproductspec;
		this.number01 = number01;
		this.showincontract = showincontract;
		this.prices = prices;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMPRICEGROUP")
	public Pricegroup getPricegroup() {
		return this.pricegroup;
	}

	public void setPricegroup(Pricegroup pricegroup) {
		this.pricegroup = pricegroup;
	}

	@Column(name = "CODE", length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "ACTIVE", length = 1)
	public Character getActive() {
		return this.active;
	}

	public void setActive(Character active) {
		this.active = active;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INVALIDATED", length = 7)
	public Date getInvalidated() {
		return this.invalidated;
	}

	public void setInvalidated(Date invalidated) {
		this.invalidated = invalidated;
	}

	@Column(name = "HEAD")
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "PRICETYPE")
	public String getPricetype() {
		return this.pricetype;
	}

	public void setPricetype(String pricetype) {
		this.pricetype = pricetype;
	}

	@Column(name = "PRIMPRICETYPE", length = 19)
	public String getPrimpricetype() {
		return this.primpricetype;
	}

	public void setPrimpricetype(String primpricetype) {
		this.primpricetype = primpricetype;
	}

	@Column(name = "PRIMPRODUCTSPEC", length = 19)
	public String getPrimproductspec() {
		return this.primproductspec;
	}

	public void setPrimproductspec(String primproductspec) {
		this.primproductspec = primproductspec;
	}

	@Column(name = "NUMBER_01", unique = true, precision = 10)
	public BigDecimal getNumber01() {
		return this.number01;
	}

	public void setNumber01(BigDecimal number01) {
		this.number01 = number01;
	}

	@Column(name = "SHOWINCONTRACT", length = 1)
	public Character getShowincontract() {
		return this.showincontract;
	}

	public void setShowincontract(Character showincontract) {
		this.showincontract = showincontract;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pricelabel")
	public Set<Price> getPrices() {
		return this.prices;
	}

	public void setPrices(Set<Price> prices) {
		this.prices = prices;
	}

}
