package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PricelabelChghist generated by hbm2java
 */
@Entity
@Table(name = "PRICELABEL_CHGHIST", schema = "PCRM")
public class PricelabelChghist implements java.io.Serializable {

	private String audId;
	private String audAction;
	private Serializable audTimestamp;
	private String audOsuser;
	private String audDbuser;
	private String audUserterminal;
	private String id;
	private String code;
	private Date crd;
	private String cru;
	private Date modd;
	private String modu;
	private Date impd;
	private String impu;
	private Date expd;
	private String expu;
	private Character active;
	private Date invalidated;
	private String head;
	private String pricetype;
	private String primpricetype;
	private String primproductspec;
	private String primpricegroup;
	private BigDecimal number01;
	private Character showincontract;

	public PricelabelChghist() {
	}

	public PricelabelChghist(String audId, String id) {
		this.audId = audId;
		this.id = id;
	}

	public PricelabelChghist(String audId, String audAction,
			Serializable audTimestamp, String audOsuser, String audDbuser,
			String audUserterminal, String id, String code, Date crd,
			String cru, Date modd, String modu, Date impd, String impu,
			Date expd, String expu, Character active, Date invalidated,
			String head, String pricetype, String primpricetype,
			String primproductspec, String primpricegroup, BigDecimal number01,
			Character showincontract) {
		this.audId = audId;
		this.audAction = audAction;
		this.audTimestamp = audTimestamp;
		this.audOsuser = audOsuser;
		this.audDbuser = audDbuser;
		this.audUserterminal = audUserterminal;
		this.id = id;
		this.code = code;
		this.crd = crd;
		this.cru = cru;
		this.modd = modd;
		this.modu = modu;
		this.impd = impd;
		this.impu = impu;
		this.expd = expd;
		this.expu = expu;
		this.active = active;
		this.invalidated = invalidated;
		this.head = head;
		this.pricetype = pricetype;
		this.primpricetype = primpricetype;
		this.primproductspec = primproductspec;
		this.primpricegroup = primpricegroup;
		this.number01 = number01;
		this.showincontract = showincontract;
	}

	@Id
	@Column(name = "AUD_ID", unique = true, nullable = false, length = 19)
	public String getAudId() {
		return this.audId;
	}

	public void setAudId(String audId) {
		this.audId = audId;
	}

	@Column(name = "AUD_ACTION", length = 50)
	public String getAudAction() {
		return this.audAction;
	}

	public void setAudAction(String audAction) {
		this.audAction = audAction;
	}

	@Column(name = "AUD_TIMESTAMP")
	public Serializable getAudTimestamp() {
		return this.audTimestamp;
	}

	public void setAudTimestamp(Serializable audTimestamp) {
		this.audTimestamp = audTimestamp;
	}

	@Column(name = "AUD_OSUSER", length = 50)
	public String getAudOsuser() {
		return this.audOsuser;
	}

	public void setAudOsuser(String audOsuser) {
		this.audOsuser = audOsuser;
	}

	@Column(name = "AUD_DBUSER", length = 50)
	public String getAudDbuser() {
		return this.audDbuser;
	}

	public void setAudDbuser(String audDbuser) {
		this.audDbuser = audDbuser;
	}

	@Column(name = "AUD_USERTERMINAL", length = 50)
	public String getAudUserterminal() {
		return this.audUserterminal;
	}

	public void setAudUserterminal(String audUserterminal) {
		this.audUserterminal = audUserterminal;
	}

	@Column(name = "ID", nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "CODE", length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "ACTIVE", length = 1)
	public Character getActive() {
		return this.active;
	}

	public void setActive(Character active) {
		this.active = active;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INVALIDATED", length = 7)
	public Date getInvalidated() {
		return this.invalidated;
	}

	public void setInvalidated(Date invalidated) {
		this.invalidated = invalidated;
	}

	@Column(name = "HEAD")
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "PRICETYPE")
	public String getPricetype() {
		return this.pricetype;
	}

	public void setPricetype(String pricetype) {
		this.pricetype = pricetype;
	}

	@Column(name = "PRIMPRICETYPE", length = 19)
	public String getPrimpricetype() {
		return this.primpricetype;
	}

	public void setPrimpricetype(String primpricetype) {
		this.primpricetype = primpricetype;
	}

	@Column(name = "PRIMPRODUCTSPEC", length = 19)
	public String getPrimproductspec() {
		return this.primproductspec;
	}

	public void setPrimproductspec(String primproductspec) {
		this.primproductspec = primproductspec;
	}

	@Column(name = "PRIMPRICEGROUP", length = 19)
	public String getPrimpricegroup() {
		return this.primpricegroup;
	}

	public void setPrimpricegroup(String primpricegroup) {
		this.primpricegroup = primpricegroup;
	}

	@Column(name = "NUMBER_01", precision = 10)
	public BigDecimal getNumber01() {
		return this.number01;
	}

	public void setNumber01(BigDecimal number01) {
		this.number01 = number01;
	}

	@Column(name = "SHOWINCONTRACT", length = 1)
	public Character getShowincontract() {
		return this.showincontract;
	}

	public void setShowincontract(Character showincontract) {
		this.showincontract = showincontract;
	}

}
