package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Price generated by hbm2java
 */
@Entity
@Table(name = "PRICE", schema = "PCRM")
public class Price implements java.io.Serializable {

	private String id;
	private Progofferselection progofferselection;
	private Pricelabel pricelabel;
	private Pricegroup pricegroup;
	private Pricecalculation pricecalculation;
	private Date crd;
	private Date crt;
	private String cru;
	private Date modd;
	private Date modt;
	private String modu;
	private Date deld;
	private Date delt;
	private String delu;
	private Date impd;
	private Date impt;
	private String impu;
	private Date expd;
	private Date expt;
	private String expu;
	private String primarypristype;
	private String primarycdmmodelfield;
	private String keyfieldvalue;
	private String primarypris;
	private String primaryprisklasse;
	private String primaryprisskabelon;
	private String code;
	private String heading;
	private Character active;
	private String nr;
	private BigDecimal antal;
	private BigDecimal pris;
	private String klasse;
	private String objekt;
	private Date startdate;
	private Date enddate;
	private Date revDate;
	private String revUser;
	private String revision;
	private String string01;
	private String string02;
	private String string03;
	private Character bool01;
	private BigDecimal number01;
	private Character kcdIncl;
	private Character momsIncl;
	private String primproductchosen;
	private Character showincontract;
	private BigDecimal prisialt;
	private BigDecimal minPris;
	private String valgtnavn;
	private BigDecimal reduction;
	private BigDecimal kodacopydan;
	private String primbusinesssphere;
	private BigDecimal kampagnepris;
	private BigDecimal fremtidigpris;

	public Price() {
	}

	public Price(String id) {
		this.id = id;
	}

	public Price(String id, Progofferselection progofferselection,
			Pricelabel pricelabel, Pricegroup pricegroup,
			Pricecalculation pricecalculation, Date crd, Date crt, String cru,
			Date modd, Date modt, String modu, Date deld, Date delt,
			String delu, Date impd, Date impt, String impu, Date expd,
			Date expt, String expu, String primarypristype,
			String primarycdmmodelfield, String keyfieldvalue,
			String primarypris, String primaryprisklasse,
			String primaryprisskabelon, String code, String heading,
			Character active, String nr, BigDecimal antal, BigDecimal pris,
			String klasse, String objekt, Date startdate, Date enddate,
			Date revDate, String revUser, String revision, String string01,
			String string02, String string03, Character bool01,
			BigDecimal number01, Character kcdIncl, Character momsIncl,
			String primproductchosen, Character showincontract,
			BigDecimal prisialt, BigDecimal minPris, String valgtnavn,
			BigDecimal reduction, BigDecimal kodacopydan,
			String primbusinesssphere, BigDecimal kampagnepris,
			BigDecimal fremtidigpris) {
		this.id = id;
		this.progofferselection = progofferselection;
		this.pricelabel = pricelabel;
		this.pricegroup = pricegroup;
		this.pricecalculation = pricecalculation;
		this.crd = crd;
		this.crt = crt;
		this.cru = cru;
		this.modd = modd;
		this.modt = modt;
		this.modu = modu;
		this.deld = deld;
		this.delt = delt;
		this.delu = delu;
		this.impd = impd;
		this.impt = impt;
		this.impu = impu;
		this.expd = expd;
		this.expt = expt;
		this.expu = expu;
		this.primarypristype = primarypristype;
		this.primarycdmmodelfield = primarycdmmodelfield;
		this.keyfieldvalue = keyfieldvalue;
		this.primarypris = primarypris;
		this.primaryprisklasse = primaryprisklasse;
		this.primaryprisskabelon = primaryprisskabelon;
		this.code = code;
		this.heading = heading;
		this.active = active;
		this.nr = nr;
		this.antal = antal;
		this.pris = pris;
		this.klasse = klasse;
		this.objekt = objekt;
		this.startdate = startdate;
		this.enddate = enddate;
		this.revDate = revDate;
		this.revUser = revUser;
		this.revision = revision;
		this.string01 = string01;
		this.string02 = string02;
		this.string03 = string03;
		this.bool01 = bool01;
		this.number01 = number01;
		this.kcdIncl = kcdIncl;
		this.momsIncl = momsIncl;
		this.primproductchosen = primproductchosen;
		this.showincontract = showincontract;
		this.prisialt = prisialt;
		this.minPris = minPris;
		this.valgtnavn = valgtnavn;
		this.reduction = reduction;
		this.kodacopydan = kodacopydan;
		this.primbusinesssphere = primbusinesssphere;
		this.kampagnepris = kampagnepris;
		this.fremtidigpris = fremtidigpris;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMPROGOFFERSELECTION")
	public Progofferselection getProgofferselection() {
		return this.progofferselection;
	}

	public void setProgofferselection(Progofferselection progofferselection) {
		this.progofferselection = progofferselection;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMPRICELABEL")
	public Pricelabel getPricelabel() {
		return this.pricelabel;
	}

	public void setPricelabel(Pricelabel pricelabel) {
		this.pricelabel = pricelabel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMARYPRISGRUPPE")
	public Pricegroup getPricegroup() {
		return this.pricegroup;
	}

	public void setPricegroup(Pricegroup pricegroup) {
		this.pricegroup = pricegroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMPRICECALCULATION")
	public Pricecalculation getPricecalculation() {
		return this.pricecalculation;
	}

	public void setPricecalculation(Pricecalculation pricecalculation) {
		this.pricecalculation = pricecalculation;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRT", length = 7)
	public Date getCrt() {
		return this.crt;
	}

	public void setCrt(Date crt) {
		this.crt = crt;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODT", length = 7)
	public Date getModt() {
		return this.modt;
	}

	public void setModt(Date modt) {
		this.modt = modt;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELT", length = 7)
	public Date getDelt() {
		return this.delt;
	}

	public void setDelt(Date delt) {
		this.delt = delt;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPT", length = 7)
	public Date getImpt() {
		return this.impt;
	}

	public void setImpt(Date impt) {
		this.impt = impt;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPT", length = 7)
	public Date getExpt() {
		return this.expt;
	}

	public void setExpt(Date expt) {
		this.expt = expt;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "PRIMARYPRISTYPE", length = 19)
	public String getPrimarypristype() {
		return this.primarypristype;
	}

	public void setPrimarypristype(String primarypristype) {
		this.primarypristype = primarypristype;
	}

	@Column(name = "PRIMARYCDMMODELFIELD", length = 19)
	public String getPrimarycdmmodelfield() {
		return this.primarycdmmodelfield;
	}

	public void setPrimarycdmmodelfield(String primarycdmmodelfield) {
		this.primarycdmmodelfield = primarycdmmodelfield;
	}

	@Column(name = "KEYFIELDVALUE")
	public String getKeyfieldvalue() {
		return this.keyfieldvalue;
	}

	public void setKeyfieldvalue(String keyfieldvalue) {
		this.keyfieldvalue = keyfieldvalue;
	}

	@Column(name = "PRIMARYPRIS", length = 19)
	public String getPrimarypris() {
		return this.primarypris;
	}

	public void setPrimarypris(String primarypris) {
		this.primarypris = primarypris;
	}

	@Column(name = "PRIMARYPRISKLASSE", length = 19)
	public String getPrimaryprisklasse() {
		return this.primaryprisklasse;
	}

	public void setPrimaryprisklasse(String primaryprisklasse) {
		this.primaryprisklasse = primaryprisklasse;
	}

	@Column(name = "PRIMARYPRISSKABELON", length = 19)
	public String getPrimaryprisskabelon() {
		return this.primaryprisskabelon;
	}

	public void setPrimaryprisskabelon(String primaryprisskabelon) {
		this.primaryprisskabelon = primaryprisskabelon;
	}

	@Column(name = "CODE", length = 55)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "HEADING")
	public String getHeading() {
		return this.heading;
	}

	public void setHeading(String heading) {
		this.heading = heading;
	}

	@Column(name = "ACTIVE", length = 1)
	public Character getActive() {
		return this.active;
	}

	public void setActive(Character active) {
		this.active = active;
	}

	@Column(name = "NR")
	public String getNr() {
		return this.nr;
	}

	public void setNr(String nr) {
		this.nr = nr;
	}

	@Column(name = "ANTAL", precision = 22, scale = 0)
	public BigDecimal getAntal() {
		return this.antal;
	}

	public void setAntal(BigDecimal antal) {
		this.antal = antal;
	}

	@Column(name = "PRIS", precision = 10)
	public BigDecimal getPris() {
		return this.pris;
	}

	public void setPris(BigDecimal pris) {
		this.pris = pris;
	}

	@Column(name = "KLASSE", length = 64)
	public String getKlasse() {
		return this.klasse;
	}

	public void setKlasse(String klasse) {
		this.klasse = klasse;
	}

	@Column(name = "OBJEKT", length = 64)
	public String getObjekt() {
		return this.objekt;
	}

	public void setObjekt(String objekt) {
		this.objekt = objekt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STARTDATE", length = 7)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDATE", length = 7)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REV_DATE", length = 7)
	public Date getRevDate() {
		return this.revDate;
	}

	public void setRevDate(Date revDate) {
		this.revDate = revDate;
	}

	@Column(name = "REV_USER", length = 19)
	public String getRevUser() {
		return this.revUser;
	}

	public void setRevUser(String revUser) {
		this.revUser = revUser;
	}

	@Column(name = "REVISION", length = 19)
	public String getRevision() {
		return this.revision;
	}

	public void setRevision(String revision) {
		this.revision = revision;
	}

	@Column(name = "STRING_01")
	public String getString01() {
		return this.string01;
	}

	public void setString01(String string01) {
		this.string01 = string01;
	}

	@Column(name = "STRING_02")
	public String getString02() {
		return this.string02;
	}

	public void setString02(String string02) {
		this.string02 = string02;
	}

	@Column(name = "STRING_03")
	public String getString03() {
		return this.string03;
	}

	public void setString03(String string03) {
		this.string03 = string03;
	}

	@Column(name = "BOOL_01", length = 1)
	public Character getBool01() {
		return this.bool01;
	}

	public void setBool01(Character bool01) {
		this.bool01 = bool01;
	}

	@Column(name = "NUMBER_01", precision = 10)
	public BigDecimal getNumber01() {
		return this.number01;
	}

	public void setNumber01(BigDecimal number01) {
		this.number01 = number01;
	}

	@Column(name = "KCD_INCL", length = 1)
	public Character getKcdIncl() {
		return this.kcdIncl;
	}

	public void setKcdIncl(Character kcdIncl) {
		this.kcdIncl = kcdIncl;
	}

	@Column(name = "MOMS_INCL", length = 1)
	public Character getMomsIncl() {
		return this.momsIncl;
	}

	public void setMomsIncl(Character momsIncl) {
		this.momsIncl = momsIncl;
	}

	@Column(name = "PRIMPRODUCTCHOSEN", length = 19)
	public String getPrimproductchosen() {
		return this.primproductchosen;
	}

	public void setPrimproductchosen(String primproductchosen) {
		this.primproductchosen = primproductchosen;
	}

	@Column(name = "SHOWINCONTRACT", length = 1)
	public Character getShowincontract() {
		return this.showincontract;
	}

	public void setShowincontract(Character showincontract) {
		this.showincontract = showincontract;
	}

	@Column(name = "PRISIALT", precision = 10)
	public BigDecimal getPrisialt() {
		return this.prisialt;
	}

	public void setPrisialt(BigDecimal prisialt) {
		this.prisialt = prisialt;
	}

	@Column(name = "MIN_PRIS", precision = 10)
	public BigDecimal getMinPris() {
		return this.minPris;
	}

	public void setMinPris(BigDecimal minPris) {
		this.minPris = minPris;
	}

	@Column(name = "VALGTNAVN")
	public String getValgtnavn() {
		return this.valgtnavn;
	}

	public void setValgtnavn(String valgtnavn) {
		this.valgtnavn = valgtnavn;
	}

	@Column(name = "REDUCTION", precision = 10)
	public BigDecimal getReduction() {
		return this.reduction;
	}

	public void setReduction(BigDecimal reduction) {
		this.reduction = reduction;
	}

	@Column(name = "KODACOPYDAN", precision = 10)
	public BigDecimal getKodacopydan() {
		return this.kodacopydan;
	}

	public void setKodacopydan(BigDecimal kodacopydan) {
		this.kodacopydan = kodacopydan;
	}

	@Column(name = "PRIMBUSINESSSPHERE", length = 50)
	public String getPrimbusinesssphere() {
		return this.primbusinesssphere;
	}

	public void setPrimbusinesssphere(String primbusinesssphere) {
		this.primbusinesssphere = primbusinesssphere;
	}

	@Column(name = "KAMPAGNEPRIS", precision = 10)
	public BigDecimal getKampagnepris() {
		return this.kampagnepris;
	}

	public void setKampagnepris(BigDecimal kampagnepris) {
		this.kampagnepris = kampagnepris;
	}

	@Column(name = "FREMTIDIGPRIS", precision = 10)
	public BigDecimal getFremtidigpris() {
		return this.fremtidigpris;
	}

	public void setFremtidigpris(BigDecimal fremtidigpris) {
		this.fremtidigpris = fremtidigpris;
	}

}
