package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Primaveraintegrationlog generated by hbm2java
 */
@Entity
@Table(name = "PRIMAVERAINTEGRATIONLOG", schema = "PCRM")
public class Primaveraintegrationlog implements java.io.Serializable {

	private String id;
	private Date crd;
	private Date impd;
	private Date expd;
	private String cru;
	private Date modd;
	private String impu;
	private String expu;
	private String modu;
	private String projectno;
	private String reasoncode;
	private String starcktrace;
	private String messagetext;

	public Primaveraintegrationlog() {
	}

	public Primaveraintegrationlog(String id) {
		this.id = id;
	}

	public Primaveraintegrationlog(String id, Date crd, Date impd, Date expd,
			String cru, Date modd, String impu, String expu, String modu,
			String projectno, String reasoncode, String starcktrace,
			String messagetext) {
		this.id = id;
		this.crd = crd;
		this.impd = impd;
		this.expd = expd;
		this.cru = cru;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.modu = modu;
		this.projectno = projectno;
		this.reasoncode = reasoncode;
		this.starcktrace = starcktrace;
		this.messagetext = messagetext;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "PROJECTNO", length = 20)
	public String getProjectno() {
		return this.projectno;
	}

	public void setProjectno(String projectno) {
		this.projectno = projectno;
	}

	@Column(name = "REASONCODE", length = 50)
	public String getReasoncode() {
		return this.reasoncode;
	}

	public void setReasoncode(String reasoncode) {
		this.reasoncode = reasoncode;
	}

	@Column(name = "STARCKTRACE", length = 4000)
	public String getStarcktrace() {
		return this.starcktrace;
	}

	public void setStarcktrace(String starcktrace) {
		this.starcktrace = starcktrace;
	}

	@Column(name = "MESSAGETEXT", length = 4000)
	public String getMessagetext() {
		return this.messagetext;
	}

	public void setMessagetext(String messagetext) {
		this.messagetext = messagetext;
	}

}
