package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductGroups generated by hbm2java
 */
@Entity
@Table(name = "PRODUCT_GROUPS", schema = "PCRM")
public class ProductGroups implements java.io.Serializable {

	private BigDecimal productGroup;
	private String groupName;
	private Set<Products> productses = new HashSet<Products>(0);

	public ProductGroups() {
	}

	public ProductGroups(BigDecimal productGroup) {
		this.productGroup = productGroup;
	}

	public ProductGroups(BigDecimal productGroup, String groupName,
			Set<Products> productses) {
		this.productGroup = productGroup;
		this.groupName = groupName;
		this.productses = productses;
	}

	@Id
	@Column(name = "PRODUCT_GROUP", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getProductGroup() {
		return this.productGroup;
	}

	public void setProductGroup(BigDecimal productGroup) {
		this.productGroup = productGroup;
	}

	@Column(name = "GROUP_NAME", length = 50)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productGroups")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
