package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProgsupplyKissOld generated by hbm2java
 */
@Entity
@Table(name = "PROGSUPPLY_KISS_OLD", schema = "PCRM")
public class ProgsupplyKissOld implements java.io.Serializable {

	private String id;
	private FrequencyrangeKissOld frequencyrangeKissOld;
	private Date crd;
	private String cru;
	private Date modd;
	private String modu;
	private Date impd;
	private String impu;
	private Date expd;
	private String expu;
	private String hfnr;
	private String anlaegsnr;
	private String leverandor;
	private String gruppering;
	private String leveringstype;
	private Character proveprogram;
	private String varenummer;
	private String varenavn;
	private String frekvens;
	private String kanal;
	private String area;
	private String band;
	private String pakkenr;
	private String startFrekvens;
	private String slutFrekvens;
	private String primheadend;
	private String primcableunit;
	private String primvarenr;
	private Set<Progsupplyvaluelink> progsupplyvaluelinks = new HashSet<Progsupplyvaluelink>(
			0);

	public ProgsupplyKissOld() {
	}

	public ProgsupplyKissOld(String id) {
		this.id = id;
	}

	public ProgsupplyKissOld(String id,
			FrequencyrangeKissOld frequencyrangeKissOld, Date crd, String cru,
			Date modd, String modu, Date impd, String impu, Date expd,
			String expu, String hfnr, String anlaegsnr, String leverandor,
			String gruppering, String leveringstype, Character proveprogram,
			String varenummer, String varenavn, String frekvens, String kanal,
			String area, String band, String pakkenr, String startFrekvens,
			String slutFrekvens, String primheadend, String primcableunit,
			String primvarenr, Set<Progsupplyvaluelink> progsupplyvaluelinks) {
		this.id = id;
		this.frequencyrangeKissOld = frequencyrangeKissOld;
		this.crd = crd;
		this.cru = cru;
		this.modd = modd;
		this.modu = modu;
		this.impd = impd;
		this.impu = impu;
		this.expd = expd;
		this.expu = expu;
		this.hfnr = hfnr;
		this.anlaegsnr = anlaegsnr;
		this.leverandor = leverandor;
		this.gruppering = gruppering;
		this.leveringstype = leveringstype;
		this.proveprogram = proveprogram;
		this.varenummer = varenummer;
		this.varenavn = varenavn;
		this.frekvens = frekvens;
		this.kanal = kanal;
		this.area = area;
		this.band = band;
		this.pakkenr = pakkenr;
		this.startFrekvens = startFrekvens;
		this.slutFrekvens = slutFrekvens;
		this.primheadend = primheadend;
		this.primcableunit = primcableunit;
		this.primvarenr = primvarenr;
		this.progsupplyvaluelinks = progsupplyvaluelinks;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMFREQUENCYRANGE")
	public FrequencyrangeKissOld getFrequencyrangeKissOld() {
		return this.frequencyrangeKissOld;
	}

	public void setFrequencyrangeKissOld(
			FrequencyrangeKissOld frequencyrangeKissOld) {
		this.frequencyrangeKissOld = frequencyrangeKissOld;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "HFNR", length = 11)
	public String getHfnr() {
		return this.hfnr;
	}

	public void setHfnr(String hfnr) {
		this.hfnr = hfnr;
	}

	@Column(name = "ANLAEGSNR", length = 10)
	public String getAnlaegsnr() {
		return this.anlaegsnr;
	}

	public void setAnlaegsnr(String anlaegsnr) {
		this.anlaegsnr = anlaegsnr;
	}

	@Column(name = "LEVERANDOR", length = 50)
	public String getLeverandor() {
		return this.leverandor;
	}

	public void setLeverandor(String leverandor) {
		this.leverandor = leverandor;
	}

	@Column(name = "GRUPPERING", length = 50)
	public String getGruppering() {
		return this.gruppering;
	}

	public void setGruppering(String gruppering) {
		this.gruppering = gruppering;
	}

	@Column(name = "LEVERINGSTYPE", length = 50)
	public String getLeveringstype() {
		return this.leveringstype;
	}

	public void setLeveringstype(String leveringstype) {
		this.leveringstype = leveringstype;
	}

	@Column(name = "PROVEPROGRAM", length = 1)
	public Character getProveprogram() {
		return this.proveprogram;
	}

	public void setProveprogram(Character proveprogram) {
		this.proveprogram = proveprogram;
	}

	@Column(name = "VARENUMMER", length = 15)
	public String getVarenummer() {
		return this.varenummer;
	}

	public void setVarenummer(String varenummer) {
		this.varenummer = varenummer;
	}

	@Column(name = "VARENAVN", length = 50)
	public String getVarenavn() {
		return this.varenavn;
	}

	public void setVarenavn(String varenavn) {
		this.varenavn = varenavn;
	}

	@Column(name = "FREKVENS", length = 15)
	public String getFrekvens() {
		return this.frekvens;
	}

	public void setFrekvens(String frekvens) {
		this.frekvens = frekvens;
	}

	@Column(name = "KANAL", length = 15)
	public String getKanal() {
		return this.kanal;
	}

	public void setKanal(String kanal) {
		this.kanal = kanal;
	}

	@Column(name = "AREA", length = 15)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "BAND", length = 15)
	public String getBand() {
		return this.band;
	}

	public void setBand(String band) {
		this.band = band;
	}

	@Column(name = "PAKKENR", length = 15)
	public String getPakkenr() {
		return this.pakkenr;
	}

	public void setPakkenr(String pakkenr) {
		this.pakkenr = pakkenr;
	}

	@Column(name = "START_FREKVENS", length = 40)
	public String getStartFrekvens() {
		return this.startFrekvens;
	}

	public void setStartFrekvens(String startFrekvens) {
		this.startFrekvens = startFrekvens;
	}

	@Column(name = "SLUT_FREKVENS", length = 40)
	public String getSlutFrekvens() {
		return this.slutFrekvens;
	}

	public void setSlutFrekvens(String slutFrekvens) {
		this.slutFrekvens = slutFrekvens;
	}

	@Column(name = "PRIMHEADEND", length = 11)
	public String getPrimheadend() {
		return this.primheadend;
	}

	public void setPrimheadend(String primheadend) {
		this.primheadend = primheadend;
	}

	@Column(name = "PRIMCABLEUNIT", length = 10)
	public String getPrimcableunit() {
		return this.primcableunit;
	}

	public void setPrimcableunit(String primcableunit) {
		this.primcableunit = primcableunit;
	}

	@Column(name = "PRIMVARENR", length = 50)
	public String getPrimvarenr() {
		return this.primvarenr;
	}

	public void setPrimvarenr(String primvarenr) {
		this.primvarenr = primvarenr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "progsupplyKissOld")
	public Set<Progsupplyvaluelink> getProgsupplyvaluelinks() {
		return this.progsupplyvaluelinks;
	}

	public void setProgsupplyvaluelinks(
			Set<Progsupplyvaluelink> progsupplyvaluelinks) {
		this.progsupplyvaluelinks = progsupplyvaluelinks;
	}

}
