package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Sf2066 generated by hbm2java
 */
@Entity
@Table(name = "SF_2066", schema = "PCRM")
public class Sf2066 implements java.io.Serializable {

	private Sf2066Id id;

	public Sf2066() {
	}

	public Sf2066(Sf2066Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "projectno", column = @Column(name = "PROJECTNO", length = 20)),
			@AttributeOverride(name = "cnt", column = @Column(name = "CNT", precision = 22, scale = 0)) })
	public Sf2066Id getId() {
		return this.id;
	}

	public void setId(Sf2066Id id) {
		this.id = id;
	}

}
