package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SfdcDocumentUploadingLog generated by hbm2java
 */
@Entity
@Table(name = "SFDC_DOCUMENT_UPLOADING_LOG", schema = "PCRM", uniqueConstraints = @UniqueConstraint(columnNames = "MESSAGE_ID"))
public class SfdcDocumentUploadingLog implements java.io.Serializable {

	private BigDecimal id;
	private String messageId;
	private String messageText;
	private String errorType;
	private BigDecimal numberOfAttempt;
	private String isAlive;
	private String errorCode;
	private String errorMessage;
	private String cableunitNumber;
	private String cpNumber;
	private String caseNumber;
	private String offerId;
	private Serializable createdDate;
	private String mid;

	public SfdcDocumentUploadingLog() {
	}

	public SfdcDocumentUploadingLog(BigDecimal id) {
		this.id = id;
	}

	public SfdcDocumentUploadingLog(BigDecimal id, String messageId,
			String messageText, String errorType, BigDecimal numberOfAttempt,
			String isAlive, String errorCode, String errorMessage,
			String cableunitNumber, String cpNumber, String caseNumber,
			String offerId, Serializable createdDate, String mid) {
		this.id = id;
		this.messageId = messageId;
		this.messageText = messageText;
		this.errorType = errorType;
		this.numberOfAttempt = numberOfAttempt;
		this.isAlive = isAlive;
		this.errorCode = errorCode;
		this.errorMessage = errorMessage;
		this.cableunitNumber = cableunitNumber;
		this.cpNumber = cpNumber;
		this.caseNumber = caseNumber;
		this.offerId = offerId;
		this.createdDate = createdDate;
		this.mid = mid;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	@Column(name = "MESSAGE_ID", unique = true, length = 50)
	public String getMessageId() {
		return this.messageId;
	}

	public void setMessageId(String messageId) {
		this.messageId = messageId;
	}

	@Column(name = "MESSAGE_TEXT", length = 2048)
	public String getMessageText() {
		return this.messageText;
	}

	public void setMessageText(String messageText) {
		this.messageText = messageText;
	}

	@Column(name = "ERROR_TYPE", length = 20)
	public String getErrorType() {
		return this.errorType;
	}

	public void setErrorType(String errorType) {
		this.errorType = errorType;
	}

	@Column(name = "NUMBER_OF_ATTEMPT", precision = 22, scale = 0)
	public BigDecimal getNumberOfAttempt() {
		return this.numberOfAttempt;
	}

	public void setNumberOfAttempt(BigDecimal numberOfAttempt) {
		this.numberOfAttempt = numberOfAttempt;
	}

	@Column(name = "IS_ALIVE", length = 1)
	public String getIsAlive() {
		return this.isAlive;
	}

	public void setIsAlive(String isAlive) {
		this.isAlive = isAlive;
	}

	@Column(name = "ERROR_CODE", length = 20)
	public String getErrorCode() {
		return this.errorCode;
	}

	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	@Column(name = "ERROR_MESSAGE", length = 512)
	public String getErrorMessage() {
		return this.errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}

	@Column(name = "CABLEUNIT_NUMBER", length = 10)
	public String getCableunitNumber() {
		return this.cableunitNumber;
	}

	public void setCableunitNumber(String cableunitNumber) {
		this.cableunitNumber = cableunitNumber;
	}

	@Column(name = "CP_NUMBER", length = 100)
	public String getCpNumber() {
		return this.cpNumber;
	}

	public void setCpNumber(String cpNumber) {
		this.cpNumber = cpNumber;
	}

	@Column(name = "CASE_NUMBER", length = 30)
	public String getCaseNumber() {
		return this.caseNumber;
	}

	public void setCaseNumber(String caseNumber) {
		this.caseNumber = caseNumber;
	}

	@Column(name = "OFFER_ID", length = 19)
	public String getOfferId() {
		return this.offerId;
	}

	public void setOfferId(String offerId) {
		this.offerId = offerId;
	}

	@Column(name = "CREATED_DATE")
	public Serializable getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Serializable createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "MID", length = 19)
	public String getMid() {
		return this.mid;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

}
