package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StaffpostalcodeRange generated by hbm2java
 */
@Entity
@Table(name = "STAFFPOSTALCODE_RANGE", schema = "PCRM")
public class StaffpostalcodeRange implements java.io.Serializable {

	private String id;
	private Staff staff;
	private Date crd;
	private Date impd;
	private Date expd;
	private String cru;
	private Date modd;
	private String impu;
	private String expu;
	private String modu;
	private BigDecimal fromPostalcode;
	private BigDecimal toPostalcode;
	private BigDecimal fromInstallation;
	private BigDecimal toInstallation;

	public StaffpostalcodeRange() {
	}

	public StaffpostalcodeRange(String id) {
		this.id = id;
	}

	public StaffpostalcodeRange(String id, Staff staff, Date crd, Date impd,
			Date expd, String cru, Date modd, String impu, String expu,
			String modu, BigDecimal fromPostalcode, BigDecimal toPostalcode,
			BigDecimal fromInstallation, BigDecimal toInstallation) {
		this.id = id;
		this.staff = staff;
		this.crd = crd;
		this.impd = impd;
		this.expd = expd;
		this.cru = cru;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.modu = modu;
		this.fromPostalcode = fromPostalcode;
		this.toPostalcode = toPostalcode;
		this.fromInstallation = fromInstallation;
		this.toInstallation = toInstallation;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRIMSTAFFID")
	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "FROM_POSTALCODE", precision = 22, scale = 0)
	public BigDecimal getFromPostalcode() {
		return this.fromPostalcode;
	}

	public void setFromPostalcode(BigDecimal fromPostalcode) {
		this.fromPostalcode = fromPostalcode;
	}

	@Column(name = "TO_POSTALCODE", precision = 22, scale = 0)
	public BigDecimal getToPostalcode() {
		return this.toPostalcode;
	}

	public void setToPostalcode(BigDecimal toPostalcode) {
		this.toPostalcode = toPostalcode;
	}

	@Column(name = "FROM_INSTALLATION", precision = 22, scale = 0)
	public BigDecimal getFromInstallation() {
		return this.fromInstallation;
	}

	public void setFromInstallation(BigDecimal fromInstallation) {
		this.fromInstallation = fromInstallation;
	}

	@Column(name = "TO_INSTALLATION", precision = 22, scale = 0)
	public BigDecimal getToInstallation() {
		return this.toInstallation;
	}

	public void setToInstallation(BigDecimal toInstallation) {
		this.toInstallation = toInstallation;
	}

}
