package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubcontractorCableunits generated by hbm2java
 */
@Entity
@Table(name = "SUBCONTRACTOR_CABLEUNITS", schema = "PCRM")
public class SubcontractorCableunits implements java.io.Serializable {

	private String id;
	private Date crd;
	private String cru;
	private Date modd;
	private String modu;
	private Date deld;
	private String delu;
	private String scode;
	private String sourceCableunit;
	private String targetCableunit;
	private String cableunitName;
	private Date startDate;
	private Date endDate;

	public SubcontractorCableunits() {
	}

	public SubcontractorCableunits(String id, String scode,
			String sourceCableunit, Date startDate, Date endDate) {
		this.id = id;
		this.scode = scode;
		this.sourceCableunit = sourceCableunit;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	public SubcontractorCableunits(String id, Date crd, String cru, Date modd,
			String modu, Date deld, String delu, String scode,
			String sourceCableunit, String targetCableunit,
			String cableunitName, Date startDate, Date endDate) {
		this.id = id;
		this.crd = crd;
		this.cru = cru;
		this.modd = modd;
		this.modu = modu;
		this.deld = deld;
		this.delu = delu;
		this.scode = scode;
		this.sourceCableunit = sourceCableunit;
		this.targetCableunit = targetCableunit;
		this.cableunitName = cableunitName;
		this.startDate = startDate;
		this.endDate = endDate;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DELD", length = 7)
	public Date getDeld() {
		return this.deld;
	}

	public void setDeld(Date deld) {
		this.deld = deld;
	}

	@Column(name = "DELU", length = 19)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Column(name = "SCODE", nullable = false, length = 19)
	public String getScode() {
		return this.scode;
	}

	public void setScode(String scode) {
		this.scode = scode;
	}

	@Column(name = "SOURCE_CABLEUNIT", nullable = false, length = 10)
	public String getSourceCableunit() {
		return this.sourceCableunit;
	}

	public void setSourceCableunit(String sourceCableunit) {
		this.sourceCableunit = sourceCableunit;
	}

	@Column(name = "TARGET_CABLEUNIT", length = 10)
	public String getTargetCableunit() {
		return this.targetCableunit;
	}

	public void setTargetCableunit(String targetCableunit) {
		this.targetCableunit = targetCableunit;
	}

	@Column(name = "CABLEUNIT_NAME", length = 40)
	public String getCableunitName() {
		return this.cableunitName;
	}

	public void setCableunitName(String cableunitName) {
		this.cableunitName = cableunitName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", nullable = false, length = 7)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", nullable = false, length = 7)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

}
