package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Systemconfigmap generated by hbm2java
 */
@Entity
@Table(name = "SYSTEMCONFIGMAP", schema = "PCRM")
public class Systemconfigmap implements java.io.Serializable {

	private String id;
	private Date crd;
	private String cru;
	private Date modd;
	private String modu;
	private Date impd;
	private String impu;
	private Date expd;
	private String expu;
	private Date startdate;
	private Date enddate;
	private String ownersystem;
	private String aliascode;
	private String aliasvalue;
	private String targetsystem;
	private String outputtype;
	private String usagetype;
	private String aliasusage;

	public Systemconfigmap() {
	}

	public Systemconfigmap(String id) {
		this.id = id;
	}

	public Systemconfigmap(String id, Date crd, String cru, Date modd,
			String modu, Date impd, String impu, Date expd, String expu,
			Date startdate, Date enddate, String ownersystem, String aliascode,
			String aliasvalue, String targetsystem, String outputtype,
			String usagetype, String aliasusage) {
		this.id = id;
		this.crd = crd;
		this.cru = cru;
		this.modd = modd;
		this.modu = modu;
		this.impd = impd;
		this.impu = impu;
		this.expd = expd;
		this.expu = expu;
		this.startdate = startdate;
		this.enddate = enddate;
		this.ownersystem = ownersystem;
		this.aliascode = aliascode;
		this.aliasvalue = aliasvalue;
		this.targetsystem = targetsystem;
		this.outputtype = outputtype;
		this.usagetype = usagetype;
		this.aliasusage = aliasusage;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 19)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CRD", length = 7)
	public Date getCrd() {
		return this.crd;
	}

	public void setCrd(Date crd) {
		this.crd = crd;
	}

	@Column(name = "CRU", length = 19)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODD", length = 7)
	public Date getModd() {
		return this.modd;
	}

	public void setModd(Date modd) {
		this.modd = modd;
	}

	@Column(name = "MODU", length = 19)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "IMPD", length = 7)
	public Date getImpd() {
		return this.impd;
	}

	public void setImpd(Date impd) {
		this.impd = impd;
	}

	@Column(name = "IMPU", length = 19)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EXPD", length = 7)
	public Date getExpd() {
		return this.expd;
	}

	public void setExpd(Date expd) {
		this.expd = expd;
	}

	@Column(name = "EXPU", length = 19)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "STARTDATE", length = 7)
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ENDDATE", length = 7)
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	@Column(name = "OWNERSYSTEM", length = 50)
	public String getOwnersystem() {
		return this.ownersystem;
	}

	public void setOwnersystem(String ownersystem) {
		this.ownersystem = ownersystem;
	}

	@Column(name = "ALIASCODE", length = 50)
	public String getAliascode() {
		return this.aliascode;
	}

	public void setAliascode(String aliascode) {
		this.aliascode = aliascode;
	}

	@Column(name = "ALIASVALUE")
	public String getAliasvalue() {
		return this.aliasvalue;
	}

	public void setAliasvalue(String aliasvalue) {
		this.aliasvalue = aliasvalue;
	}

	@Column(name = "TARGETSYSTEM", length = 50)
	public String getTargetsystem() {
		return this.targetsystem;
	}

	public void setTargetsystem(String targetsystem) {
		this.targetsystem = targetsystem;
	}

	@Column(name = "OUTPUTTYPE", length = 50)
	public String getOutputtype() {
		return this.outputtype;
	}

	public void setOutputtype(String outputtype) {
		this.outputtype = outputtype;
	}

	@Column(name = "USAGETYPE", length = 50)
	public String getUsagetype() {
		return this.usagetype;
	}

	public void setUsagetype(String usagetype) {
		this.usagetype = usagetype;
	}

	@Column(name = "ALIASUSAGE")
	public String getAliasusage() {
		return this.aliasusage;
	}

	public void setAliasusage(String aliasusage) {
		this.aliasusage = aliasusage;
	}

}
