package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VActivePrices generated by hbm2java
 */
@Entity
@Table(name = "V_ACTIVE_PRICES", schema = "PCRM")
public class VActivePrices implements java.io.Serializable {

	private VActivePricesId id;

	public VActivePrices() {
	}

	public VActivePrices(VActivePricesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productcode", column = @Column(name = "PRODUCTCODE", nullable = false, length = 20)),
			@AttributeOverride(name = "productname", column = @Column(name = "PRODUCTNAME", nullable = false, length = 40)),
			@AttributeOverride(name = "anlxg", column = @Column(name = "ANLXG", length = 10)),
			@AttributeOverride(name = "errorcode", column = @Column(name = "ERRORCODE", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "calculatedon", column = @Column(name = "CALCULATEDON", nullable = false, length = 7)),
			@AttributeOverride(name = "totalprice", column = @Column(name = "TOTALPRICE", nullable = false, precision = 32, scale = 16)),
			@AttributeOverride(name = "packageprice", column = @Column(name = "PACKAGEPRICE", nullable = false, precision = 32, scale = 16)),
			@AttributeOverride(name = "discount", column = @Column(name = "DISCOUNT", nullable = false, precision = 32, scale = 16)),
			@AttributeOverride(name = "tvroyality", column = @Column(name = "TVROYALITY", nullable = false, precision = 32, scale = 16)),
			@AttributeOverride(name = "radioroyality", column = @Column(name = "RADIOROYALITY", nullable = false, precision = 32, scale = 16)),
			@AttributeOverride(name = "copyrights", column = @Column(name = "COPYRIGHTS", nullable = false, precision = 32, scale = 16)),
			@AttributeOverride(name = "vat", column = @Column(name = "VAT", nullable = false, precision = 32, scale = 16)),
			@AttributeOverride(name = "groupindex", column = @Column(name = "GROUPINDEX", precision = 22, scale = 0)) })
	public VActivePricesId getId() {
		return this.id;
	}

	public void setId(VActivePricesId id) {
		this.id = id;
	}

}
