package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VActiveSubscription generated by hbm2java
 */
@Entity
@Table(name = "V_ACTIVE_SUBSCRIPTION", schema = "PCRM")
public class VActiveSubscription implements java.io.Serializable {

	private VActiveSubscriptionId id;

	public VActiveSubscription() {
	}

	public VActiveSubscription(VActiveSubscriptionId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "addressid", column = @Column(name = "ADDRESSID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "cableunitid", column = @Column(name = "CABLEUNITID", nullable = false, length = 10)),
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false, length = 19)),
			@AttributeOverride(name = "installationseq", column = @Column(name = "INSTALLATIONSEQ", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "location", column = @Column(name = "LOCATION", length = 256)),
			@AttributeOverride(name = "movingdate", column = @Column(name = "MOVINGDATE", length = 7)),
			@AttributeOverride(name = "startdate", column = @Column(name = "STARTDATE", length = 7)),
			@AttributeOverride(name = "adresseId", column = @Column(name = "ADRESSE_ID", nullable = false, length = 10)),
			@AttributeOverride(name = "instLbnr", column = @Column(name = "INST_LBNR", nullable = false, length = 10)),
			@AttributeOverride(name = "subscriptionStartdate", column = @Column(name = "SUBSCRIPTION_STARTDATE", nullable = false, length = 7)),
			@AttributeOverride(name = "subscriptionEnddate", column = @Column(name = "SUBSCRIPTION_ENDDATE", nullable = false, length = 7)) })
	public VActiveSubscriptionId getId() {
		return this.id;
	}

	public void setId(VActiveSubscriptionId id) {
		this.id = id;
	}

}
