package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VCrRegion2headend generated by hbm2java
 */
@Entity
@Table(name = "V_CR_REGION2HEADEND", schema = "PCRM")
public class VCrRegion2headend implements java.io.Serializable {

	private VCrRegion2headendId id;

	public VCrRegion2headend() {
	}

	public VCrRegion2headend(VCrRegion2headendId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "regionid", column = @Column(name = "REGIONID", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "mainheadend", column = @Column(name = "MAINHEADEND", nullable = false, precision = 9, scale = 0)) })
	public VCrRegion2headendId getId() {
		return this.id;
	}

	public void setId(VCrRegion2headendId id) {
		this.id = id;
	}

}
