package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VCrRegion2headendId generated by hbm2java
 */
@Embeddable
public class VCrRegion2headendId implements java.io.Serializable {

	private BigDecimal regionid;
	private int mainheadend;

	public VCrRegion2headendId() {
	}

	public VCrRegion2headendId(BigDecimal regionid, int mainheadend) {
		this.regionid = regionid;
		this.mainheadend = mainheadend;
	}

	@Column(name = "REGIONID", nullable = false, precision = 22, scale = 0)
	public BigDecimal getRegionid() {
		return this.regionid;
	}

	public void setRegionid(BigDecimal regionid) {
		this.regionid = regionid;
	}

	@Column(name = "MAINHEADEND", nullable = false, precision = 9, scale = 0)
	public int getMainheadend() {
		return this.mainheadend;
	}

	public void setMainheadend(int mainheadend) {
		this.mainheadend = mainheadend;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VCrRegion2headendId))
			return false;
		VCrRegion2headendId castOther = (VCrRegion2headendId) other;

		return ((this.getRegionid() == castOther.getRegionid()) || (this
				.getRegionid() != null && castOther.getRegionid() != null && this
				.getRegionid().equals(castOther.getRegionid())))
				&& (this.getMainheadend() == castOther.getMainheadend());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRegionid() == null ? 0 : this.getRegionid().hashCode());
		result = 37 * result + this.getMainheadend();
		return result;
	}

}
