package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VFdbNodeprogsupply generated by hbm2java
 */
@Entity
@Table(name = "V_FDB_NODEPROGSUPPLY", schema = "PCRM")
public class VFdbNodeprogsupply implements java.io.Serializable {

	private VFdbNodeprogsupplyId id;

	public VFdbNodeprogsupply() {
	}

	public VFdbNodeprogsupply(VFdbNodeprogsupplyId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nodeId", column = @Column(name = "NODE_ID", nullable = false, precision = 9, scale = 0)),
			@AttributeOverride(name = "productId", column = @Column(name = "PRODUCT_ID", length = 40)),
			@AttributeOverride(name = "shortName", column = @Column(name = "SHORT_NAME")),
			@AttributeOverride(name = "channel", column = @Column(name = "CHANNEL", nullable = false, length = 10)),
			@AttributeOverride(name = "freqHz", column = @Column(name = "FREQ_HZ", precision = 22, scale = 0)),
			@AttributeOverride(name = "packagerelation", column = @Column(name = "PACKAGERELATION", length = 40)),
			@AttributeOverride(name = "packagerelationname", column = @Column(name = "PACKAGERELATIONNAME")),
			@AttributeOverride(name = "overlap", column = @Column(name = "OVERLAP", length = 3)),
			@AttributeOverride(name = "lowerfrequency", column = @Column(name = "LOWERFREQUENCY", precision = 22, scale = 0)),
			@AttributeOverride(name = "upperfrequency", column = @Column(name = "UPPERFREQUENCY", precision = 22, scale = 0)),
			@AttributeOverride(name = "chKeySeq", column = @Column(name = "CH_KEY_SEQ", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "parentChKeySeq", column = @Column(name = "PARENT_CH_KEY_SEQ", precision = 22, scale = 0)),
			@AttributeOverride(name = "vendor", column = @Column(name = "VENDOR", length = 20)),
			@AttributeOverride(name = "deliveryType", column = @Column(name = "DELIVERY_TYPE", length = 8)),
			@AttributeOverride(name = "area", column = @Column(name = "AREA", length = 6)),
			@AttributeOverride(name = "band", column = @Column(name = "BAND", length = 6)),
			@AttributeOverride(name = "groupName", column = @Column(name = "GROUP_NAME", length = 50)),
			@AttributeOverride(name = "validFrom", column = @Column(name = "VALID_FROM", length = 7)),
			@AttributeOverride(name = "validTo", column = @Column(name = "VALID_TO", length = 7)) })
	public VFdbNodeprogsupplyId getId() {
		return this.id;
	}

	public void setId(VFdbNodeprogsupplyId id) {
		this.id = id;
	}

}
