package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VFdbProgrampackagerelation generated by hbm2java
 */
@Entity
@Table(name = "V_FDB_PROGRAMPACKAGERELATION", schema = "PCRM")
public class VFdbProgrampackagerelation implements java.io.Serializable {

	private VFdbProgrampackagerelationId id;

	public VFdbProgrampackagerelation() {
	}

	public VFdbProgrampackagerelation(VFdbProgrampackagerelationId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productId", column = @Column(name = "PRODUCT_ID", precision = 7, scale = 0)),
			@AttributeOverride(name = "shortName", column = @Column(name = "SHORT_NAME")),
			@AttributeOverride(name = "productGroup", column = @Column(name = "PRODUCT_GROUP", precision = 22, scale = 0)),
			@AttributeOverride(name = "packagerelation", column = @Column(name = "PACKAGERELATION", precision = 7, scale = 0)),
			@AttributeOverride(name = "packagerelationname", column = @Column(name = "PACKAGERELATIONNAME")),
			@AttributeOverride(name = "overlap", column = @Column(name = "OVERLAP", length = 3)) })
	public VFdbProgrampackagerelationId getId() {
		return this.id;
	}

	public void setId(VFdbProgrampackagerelationId id) {
		this.id = id;
	}

}
