package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VFdbproductgroups generated by hbm2java
 */
@Entity
@Table(name = "V_FDBPRODUCTGROUPS", schema = "PCRM")
public class VFdbproductgroups implements java.io.Serializable {

	private VFdbproductgroupsId id;

	public VFdbproductgroups() {
	}

	public VFdbproductgroups(VFdbproductgroupsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "productGroup", column = @Column(name = "PRODUCT_GROUP", precision = 22, scale = 0)),
			@AttributeOverride(name = "groupName", column = @Column(name = "GROUP_NAME", length = 50)),
			@AttributeOverride(name = "code", column = @Column(name = "CODE", length = 50)),
			@AttributeOverride(name = "type", column = @Column(name = "TYPE", length = 50)) })
	public VFdbproductgroupsId getId() {
		return this.id;
	}

	public void setId(VFdbproductgroupsId id) {
		this.id = id;
	}

}
