package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VFdbpackagegroups generated by hbm2java
 */
@Entity
@Table(name = "V_FDBPACKAGEGROUPS", schema = "PCRM")
public class VFdbpackagegroups implements java.io.Serializable {

	private VFdbpackagegroupsId id;

	public VFdbpackagegroups() {
	}

	public VFdbpackagegroups(VFdbpackagegroupsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "code", column = @Column(name = "CODE", length = 50)),
			@AttributeOverride(name = "productGroup", column = @Column(name = "PRODUCT_GROUP", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "description", column = @Column(name = "DESCRIPTION", length = 50)) })
	public VFdbpackagegroupsId getId() {
		return this.id;
	}

	public void setId(VFdbpackagegroupsId id) {
		this.id = id;
	}

}
