package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VInstallationTab generated by hbm2java
 */
@Entity
@Table(name = "V_INSTALLATION_TAB", schema = "PCRM")
public class VInstallationTab implements java.io.Serializable {

	private VInstallationTabId id;

	public VInstallationTab() {
	}

	public VInstallationTab(VInstallationTabId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "streetName", column = @Column(name = "STREET_NAME", nullable = false, length = 40)),
			@AttributeOverride(name = "houseno", column = @Column(name = "HOUSENO", length = 3)),
			@AttributeOverride(name = "staircase", column = @Column(name = "STAIRCASE", length = 2)),
			@AttributeOverride(name = "floor", column = @Column(name = "FLOOR", length = 2)),
			@AttributeOverride(name = "door", column = @Column(name = "DOOR", length = 6)),
			@AttributeOverride(name = "location", column = @Column(name = "LOCATION", length = 256)),
			@AttributeOverride(name = "locality", column = @Column(name = "LOCALITY", length = 34)),
			@AttributeOverride(name = "postalcode", column = @Column(name = "POSTALCODE", length = 4)),
			@AttributeOverride(name = "postalArea", column = @Column(name = "POSTAL_AREA", nullable = false, length = 40)),
			@AttributeOverride(name = "status", column = @Column(name = "STATUS", length = 43)),
			@AttributeOverride(name = "temporaryAddress", column = @Column(name = "TEMPORARY_ADDRESS", nullable = false, precision = 1, scale = 0)),
			@AttributeOverride(name = "fromCu", column = @Column(name = "FROM_CU", length = 10)),
			@AttributeOverride(name = "toCu", column = @Column(name = "TO_CU", length = 10)),
			@AttributeOverride(name = "movementDate", column = @Column(name = "MOVEMENT_DATE", length = 7)),
			@AttributeOverride(name = "srNo", column = @Column(name = "SR_NO", length = 10)),
			@AttributeOverride(name = "amsStartDt", column = @Column(name = "AMS_START_DT", nullable = false, length = 7)),
			@AttributeOverride(name = "amsEndDt", column = @Column(name = "AMS_END_DT", length = 7)),
			@AttributeOverride(name = "amsCreatedDt", column = @Column(name = "AMS_CREATED_DT", nullable = false, length = 7)),
			@AttributeOverride(name = "initials", column = @Column(name = "INITIALS", nullable = false, length = 10)),
			@AttributeOverride(name = "addressId", column = @Column(name = "ADDRESS_ID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "streetId", column = @Column(name = "STREET_ID", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "cableunit", column = @Column(name = "CABLEUNIT", nullable = false, length = 10)),
			@AttributeOverride(name = "seq", column = @Column(name = "SEQ", nullable = false, precision = 22, scale = 0)),
			@AttributeOverride(name = "casperaddressid", column = @Column(name = "CASPERADDRESSID", nullable = false, length = 10)),
			@AttributeOverride(name = "installStartDt", column = @Column(name = "INSTALL_START_DT", length = 7)),
			@AttributeOverride(name = "installEndDt", column = @Column(name = "INSTALL_END_DT", length = 7)),
			@AttributeOverride(name = "installationid", column = @Column(name = "INSTALLATIONID", nullable = false, length = 19)),
			@AttributeOverride(name = "flag", column = @Column(name = "FLAG", length = 1)) })
	public VInstallationTabId getId() {
		return this.id;
	}

	public void setId(VInstallationTabId id) {
		this.id = id;
	}

}
