package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VProjectsUnderDn generated by hbm2java
 */
@Entity
@Table(name = "V_PROJECTS_UNDER_DN", schema = "PCRM")
public class VProjectsUnderDn implements java.io.Serializable {

	private VProjectsUnderDnId id;

	public VProjectsUnderDn() {
	}

	public VProjectsUnderDn(VProjectsUnderDnId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "projectId", column = @Column(name = "PROJECT_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "nodeId", column = @Column(name = "NODE_ID", precision = 9, scale = 0)),
			@AttributeOverride(name = "name", column = @Column(name = "NAME", length = 40)),
			@AttributeOverride(name = "startDate", column = @Column(name = "START_DATE", length = 7)),
			@AttributeOverride(name = "salesConcept", column = @Column(name = "SALES_CONCEPT", length = 20)),
			@AttributeOverride(name = "loopMark", column = @Column(name = "LOOP_MARK", length = 1)),
			@AttributeOverride(name = "createdDateTime", column = @Column(name = "CREATED_DATE_TIME", length = 7)),
			@AttributeOverride(name = "createdByUser", column = @Column(name = "CREATED_BY_USER", length = 19)),
			@AttributeOverride(name = "changeByUser", column = @Column(name = "CHANGE_BY_USER", length = 19)),
			@AttributeOverride(name = "changeDateTime", column = @Column(name = "CHANGE_DATE_TIME", length = 7)) })
	public VProjectsUnderDnId getId() {
		return this.id;
	}

	public void setId(VProjectsUnderDnId id) {
		this.id = id;
	}

}
