package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WAnlxgInst generated by hbm2java
 */
@Entity
@Table(name = "W_ANLXG_INST", schema = "PCRM")
public class WAnlxgInst implements java.io.Serializable {

	private WAnlxgInstId id;

	public WAnlxgInst() {
	}

	public WAnlxgInst(WAnlxgInstId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "WPk", column = @Column(name = "W_PK", nullable = false, length = 19)),
			@AttributeOverride(name = "anlxgnr", column = @Column(name = "ANLXGNR", length = 10)),
			@AttributeOverride(name = "instadrId", column = @Column(name = "INSTADR_ID", length = 22)),
			@AttributeOverride(name = "instadrCommrate", column = @Column(name = "INSTADR_COMMRATE", precision = 22, scale = 0)),
			@AttributeOverride(name = "instadrVejnavn", column = @Column(name = "INSTADR_VEJNAVN", length = 40)),
			@AttributeOverride(name = "instadrHusnr", column = @Column(name = "INSTADR_HUSNR", length = 3)),
			@AttributeOverride(name = "instadrOpgang", column = @Column(name = "INSTADR_OPGANG", length = 1)),
			@AttributeOverride(name = "instadrEtage", column = @Column(name = "INSTADR_ETAGE", length = 2)),
			@AttributeOverride(name = "instadrSidedoer", column = @Column(name = "INSTADR_SIDEDOER", length = 10)),
			@AttributeOverride(name = "instadrPostnr", column = @Column(name = "INSTADR_POSTNR", length = 4)),
			@AttributeOverride(name = "instadrPostdist", column = @Column(name = "INSTADR_POSTDIST", length = 30)) })
	public WAnlxgInstId getId() {
		return this.id;
	}

	public void setId(WAnlxgInstId id) {
		this.id = id;
	}

}
