package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WAnlxgDoc generated by hbm2java
 */
@Entity
@Table(name = "W_ANLXG_DOC", schema = "PCRM")
public class WAnlxgDoc implements java.io.Serializable {

	private WAnlxgDocId id;

	public WAnlxgDoc() {
	}

	public WAnlxgDoc(WAnlxgDocId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "docTablepk", column = @Column(name = "DOC_TABLEPK", nullable = false, length = 19)),
			@AttributeOverride(name = "anlNr", column = @Column(name = "ANL_NR", length = 10)),
			@AttributeOverride(name = "anlNavn", column = @Column(name = "ANL_NAVN", length = 40)),
			@AttributeOverride(name = "docType", column = @Column(name = "DOC_TYPE")),
			@AttributeOverride(name = "docSpecifikation", column = @Column(name = "DOC_SPECIFIKATION", length = 70)),
			@AttributeOverride(name = "docOprindelse", column = @Column(name = "DOC_OPRINDELSE", length = 1)),
			@AttributeOverride(name = "docCrdate", column = @Column(name = "DOC_CRDATE", length = 8)),
			@AttributeOverride(name = "docSize", column = @Column(name = "DOC_SIZE", precision = 22, scale = 0)),
			@AttributeOverride(name = "docFiladresse", column = @Column(name = "DOC_FILADRESSE")),
			@AttributeOverride(name = "docFilextention", column = @Column(name = "DOC_FILEXTENTION")) })
	public WAnlxgDocId getId() {
		return this.id;
	}

	public void setId(WAnlxgDocId id) {
		this.id = id;
	}

}
