package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WHfudbudId generated by hbm2java
 */
@Embeddable
public class WHfudbudId implements java.io.Serializable {

	private String hfnr;
	private String hfName;
	private String amtsnr;
	private String postnr;
	private String varenummer;
	private String varenavn;
	private BigDecimal frekvens;
	private String kanal;
	private String area;
	private String band;
	private String leverandor;
	private String leveringstype;
	private String gruppering;
	private String primvarenr;
	private Date gyldigtTil;
	private String id;
	private String crd;
	private String code;
	private String impt;
	private String expt;
	private String impd;
	private String expd;
	private String modt;
	private String cru;
	private String delt;
	private String modd;
	private String impu;
	private String expu;
	private String deld;
	private String modu;
	private String head;
	private String delu;
	private String crt;

	public WHfudbudId() {
	}

	public WHfudbudId(String kanal) {
		this.kanal = kanal;
	}

	public WHfudbudId(String hfnr, String hfName, String amtsnr, String postnr,
			String varenummer, String varenavn, BigDecimal frekvens,
			String kanal, String area, String band, String leverandor,
			String leveringstype, String gruppering, String primvarenr,
			Date gyldigtTil, String id, String crd, String code, String impt,
			String expt, String impd, String expd, String modt, String cru,
			String delt, String modd, String impu, String expu, String deld,
			String modu, String head, String delu, String crt) {
		this.hfnr = hfnr;
		this.hfName = hfName;
		this.amtsnr = amtsnr;
		this.postnr = postnr;
		this.varenummer = varenummer;
		this.varenavn = varenavn;
		this.frekvens = frekvens;
		this.kanal = kanal;
		this.area = area;
		this.band = band;
		this.leverandor = leverandor;
		this.leveringstype = leveringstype;
		this.gruppering = gruppering;
		this.primvarenr = primvarenr;
		this.gyldigtTil = gyldigtTil;
		this.id = id;
		this.crd = crd;
		this.code = code;
		this.impt = impt;
		this.expt = expt;
		this.impd = impd;
		this.expd = expd;
		this.modt = modt;
		this.cru = cru;
		this.delt = delt;
		this.modd = modd;
		this.impu = impu;
		this.expu = expu;
		this.deld = deld;
		this.modu = modu;
		this.head = head;
		this.delu = delu;
		this.crt = crt;
	}

	@Column(name = "HFNR", length = 11)
	public String getHfnr() {
		return this.hfnr;
	}

	public void setHfnr(String hfnr) {
		this.hfnr = hfnr;
	}

	@Column(name = "HF_NAME", length = 40)
	public String getHfName() {
		return this.hfName;
	}

	public void setHfName(String hfName) {
		this.hfName = hfName;
	}

	@Column(name = "AMTSNR", length = 3)
	public String getAmtsnr() {
		return this.amtsnr;
	}

	public void setAmtsnr(String amtsnr) {
		this.amtsnr = amtsnr;
	}

	@Column(name = "POSTNR", length = 4)
	public String getPostnr() {
		return this.postnr;
	}

	public void setPostnr(String postnr) {
		this.postnr = postnr;
	}

	@Column(name = "VARENUMMER", length = 40)
	public String getVarenummer() {
		return this.varenummer;
	}

	public void setVarenummer(String varenummer) {
		this.varenummer = varenummer;
	}

	@Column(name = "VARENAVN", length = 32)
	public String getVarenavn() {
		return this.varenavn;
	}

	public void setVarenavn(String varenavn) {
		this.varenavn = varenavn;
	}

	@Column(name = "FREKVENS", precision = 22, scale = 0)
	public BigDecimal getFrekvens() {
		return this.frekvens;
	}

	public void setFrekvens(BigDecimal frekvens) {
		this.frekvens = frekvens;
	}

	@Column(name = "KANAL", nullable = false, length = 10)
	public String getKanal() {
		return this.kanal;
	}

	public void setKanal(String kanal) {
		this.kanal = kanal;
	}

	@Column(name = "AREA", length = 6)
	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	@Column(name = "BAND", length = 6)
	public String getBand() {
		return this.band;
	}

	public void setBand(String band) {
		this.band = band;
	}

	@Column(name = "LEVERANDOR", length = 20)
	public String getLeverandor() {
		return this.leverandor;
	}

	public void setLeverandor(String leverandor) {
		this.leverandor = leverandor;
	}

	@Column(name = "LEVERINGSTYPE", length = 8)
	public String getLeveringstype() {
		return this.leveringstype;
	}

	public void setLeveringstype(String leveringstype) {
		this.leveringstype = leveringstype;
	}

	@Column(name = "GRUPPERING", length = 50)
	public String getGruppering() {
		return this.gruppering;
	}

	public void setGruppering(String gruppering) {
		this.gruppering = gruppering;
	}

	@Column(name = "PRIMVARENR", length = 40)
	public String getPrimvarenr() {
		return this.primvarenr;
	}

	public void setPrimvarenr(String primvarenr) {
		this.primvarenr = primvarenr;
	}

	@Column(name = "GYLDIGT_TIL", length = 7)
	public Date getGyldigtTil() {
		return this.gyldigtTil;
	}

	public void setGyldigtTil(Date gyldigtTil) {
		this.gyldigtTil = gyldigtTil;
	}

	@Column(name = "ID", length = 5)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "CRD", length = 0)
	public String getCrd() {
		return this.crd;
	}

	public void setCrd(String crd) {
		this.crd = crd;
	}

	@Column(name = "CODE", length = 0)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "IMPT", length = 0)
	public String getImpt() {
		return this.impt;
	}

	public void setImpt(String impt) {
		this.impt = impt;
	}

	@Column(name = "EXPT", length = 0)
	public String getExpt() {
		return this.expt;
	}

	public void setExpt(String expt) {
		this.expt = expt;
	}

	@Column(name = "IMPD", length = 0)
	public String getImpd() {
		return this.impd;
	}

	public void setImpd(String impd) {
		this.impd = impd;
	}

	@Column(name = "EXPD", length = 0)
	public String getExpd() {
		return this.expd;
	}

	public void setExpd(String expd) {
		this.expd = expd;
	}

	@Column(name = "MODT", length = 0)
	public String getModt() {
		return this.modt;
	}

	public void setModt(String modt) {
		this.modt = modt;
	}

	@Column(name = "CRU", length = 0)
	public String getCru() {
		return this.cru;
	}

	public void setCru(String cru) {
		this.cru = cru;
	}

	@Column(name = "DELT", length = 0)
	public String getDelt() {
		return this.delt;
	}

	public void setDelt(String delt) {
		this.delt = delt;
	}

	@Column(name = "MODD", length = 0)
	public String getModd() {
		return this.modd;
	}

	public void setModd(String modd) {
		this.modd = modd;
	}

	@Column(name = "IMPU", length = 0)
	public String getImpu() {
		return this.impu;
	}

	public void setImpu(String impu) {
		this.impu = impu;
	}

	@Column(name = "EXPU", length = 0)
	public String getExpu() {
		return this.expu;
	}

	public void setExpu(String expu) {
		this.expu = expu;
	}

	@Column(name = "DELD", length = 0)
	public String getDeld() {
		return this.deld;
	}

	public void setDeld(String deld) {
		this.deld = deld;
	}

	@Column(name = "MODU", length = 0)
	public String getModu() {
		return this.modu;
	}

	public void setModu(String modu) {
		this.modu = modu;
	}

	@Column(name = "HEAD", length = 0)
	public String getHead() {
		return this.head;
	}

	public void setHead(String head) {
		this.head = head;
	}

	@Column(name = "DELU", length = 0)
	public String getDelu() {
		return this.delu;
	}

	public void setDelu(String delu) {
		this.delu = delu;
	}

	@Column(name = "CRT", length = 0)
	public String getCrt() {
		return this.crt;
	}

	public void setCrt(String crt) {
		this.crt = crt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WHfudbudId))
			return false;
		WHfudbudId castOther = (WHfudbudId) other;

		return ((this.getHfnr() == castOther.getHfnr()) || (this.getHfnr() != null
				&& castOther.getHfnr() != null && this.getHfnr().equals(
				castOther.getHfnr())))
				&& ((this.getHfName() == castOther.getHfName()) || (this
						.getHfName() != null && castOther.getHfName() != null && this
						.getHfName().equals(castOther.getHfName())))
				&& ((this.getAmtsnr() == castOther.getAmtsnr()) || (this
						.getAmtsnr() != null && castOther.getAmtsnr() != null && this
						.getAmtsnr().equals(castOther.getAmtsnr())))
				&& ((this.getPostnr() == castOther.getPostnr()) || (this
						.getPostnr() != null && castOther.getPostnr() != null && this
						.getPostnr().equals(castOther.getPostnr())))
				&& ((this.getVarenummer() == castOther.getVarenummer()) || (this
						.getVarenummer() != null
						&& castOther.getVarenummer() != null && this
						.getVarenummer().equals(castOther.getVarenummer())))
				&& ((this.getVarenavn() == castOther.getVarenavn()) || (this
						.getVarenavn() != null
						&& castOther.getVarenavn() != null && this
						.getVarenavn().equals(castOther.getVarenavn())))
				&& ((this.getFrekvens() == castOther.getFrekvens()) || (this
						.getFrekvens() != null
						&& castOther.getFrekvens() != null && this
						.getFrekvens().equals(castOther.getFrekvens())))
				&& ((this.getKanal() == castOther.getKanal()) || (this
						.getKanal() != null && castOther.getKanal() != null && this
						.getKanal().equals(castOther.getKanal())))
				&& ((this.getArea() == castOther.getArea()) || (this.getArea() != null
						&& castOther.getArea() != null && this.getArea()
						.equals(castOther.getArea())))
				&& ((this.getBand() == castOther.getBand()) || (this.getBand() != null
						&& castOther.getBand() != null && this.getBand()
						.equals(castOther.getBand())))
				&& ((this.getLeverandor() == castOther.getLeverandor()) || (this
						.getLeverandor() != null
						&& castOther.getLeverandor() != null && this
						.getLeverandor().equals(castOther.getLeverandor())))
				&& ((this.getLeveringstype() == castOther.getLeveringstype()) || (this
						.getLeveringstype() != null
						&& castOther.getLeveringstype() != null && this
						.getLeveringstype()
						.equals(castOther.getLeveringstype())))
				&& ((this.getGruppering() == castOther.getGruppering()) || (this
						.getGruppering() != null
						&& castOther.getGruppering() != null && this
						.getGruppering().equals(castOther.getGruppering())))
				&& ((this.getPrimvarenr() == castOther.getPrimvarenr()) || (this
						.getPrimvarenr() != null
						&& castOther.getPrimvarenr() != null && this
						.getPrimvarenr().equals(castOther.getPrimvarenr())))
				&& ((this.getGyldigtTil() == castOther.getGyldigtTil()) || (this
						.getGyldigtTil() != null
						&& castOther.getGyldigtTil() != null && this
						.getGyldigtTil().equals(castOther.getGyldigtTil())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null
						&& castOther.getId() != null && this.getId().equals(
						castOther.getId())))
				&& ((this.getCrd() == castOther.getCrd()) || (this.getCrd() != null
						&& castOther.getCrd() != null && this.getCrd().equals(
						castOther.getCrd())))
				&& ((this.getCode() == castOther.getCode()) || (this.getCode() != null
						&& castOther.getCode() != null && this.getCode()
						.equals(castOther.getCode())))
				&& ((this.getImpt() == castOther.getImpt()) || (this.getImpt() != null
						&& castOther.getImpt() != null && this.getImpt()
						.equals(castOther.getImpt())))
				&& ((this.getExpt() == castOther.getExpt()) || (this.getExpt() != null
						&& castOther.getExpt() != null && this.getExpt()
						.equals(castOther.getExpt())))
				&& ((this.getImpd() == castOther.getImpd()) || (this.getImpd() != null
						&& castOther.getImpd() != null && this.getImpd()
						.equals(castOther.getImpd())))
				&& ((this.getExpd() == castOther.getExpd()) || (this.getExpd() != null
						&& castOther.getExpd() != null && this.getExpd()
						.equals(castOther.getExpd())))
				&& ((this.getModt() == castOther.getModt()) || (this.getModt() != null
						&& castOther.getModt() != null && this.getModt()
						.equals(castOther.getModt())))
				&& ((this.getCru() == castOther.getCru()) || (this.getCru() != null
						&& castOther.getCru() != null && this.getCru().equals(
						castOther.getCru())))
				&& ((this.getDelt() == castOther.getDelt()) || (this.getDelt() != null
						&& castOther.getDelt() != null && this.getDelt()
						.equals(castOther.getDelt())))
				&& ((this.getModd() == castOther.getModd()) || (this.getModd() != null
						&& castOther.getModd() != null && this.getModd()
						.equals(castOther.getModd())))
				&& ((this.getImpu() == castOther.getImpu()) || (this.getImpu() != null
						&& castOther.getImpu() != null && this.getImpu()
						.equals(castOther.getImpu())))
				&& ((this.getExpu() == castOther.getExpu()) || (this.getExpu() != null
						&& castOther.getExpu() != null && this.getExpu()
						.equals(castOther.getExpu())))
				&& ((this.getDeld() == castOther.getDeld()) || (this.getDeld() != null
						&& castOther.getDeld() != null && this.getDeld()
						.equals(castOther.getDeld())))
				&& ((this.getModu() == castOther.getModu()) || (this.getModu() != null
						&& castOther.getModu() != null && this.getModu()
						.equals(castOther.getModu())))
				&& ((this.getHead() == castOther.getHead()) || (this.getHead() != null
						&& castOther.getHead() != null && this.getHead()
						.equals(castOther.getHead())))
				&& ((this.getDelu() == castOther.getDelu()) || (this.getDelu() != null
						&& castOther.getDelu() != null && this.getDelu()
						.equals(castOther.getDelu())))
				&& ((this.getCrt() == castOther.getCrt()) || (this.getCrt() != null
						&& castOther.getCrt() != null && this.getCrt().equals(
						castOther.getCrt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getHfnr() == null ? 0 : this.getHfnr().hashCode());
		result = 37 * result
				+ (getHfName() == null ? 0 : this.getHfName().hashCode());
		result = 37 * result
				+ (getAmtsnr() == null ? 0 : this.getAmtsnr().hashCode());
		result = 37 * result
				+ (getPostnr() == null ? 0 : this.getPostnr().hashCode());
		result = 37
				* result
				+ (getVarenummer() == null ? 0 : this.getVarenummer()
						.hashCode());
		result = 37 * result
				+ (getVarenavn() == null ? 0 : this.getVarenavn().hashCode());
		result = 37 * result
				+ (getFrekvens() == null ? 0 : this.getFrekvens().hashCode());
		result = 37 * result
				+ (getKanal() == null ? 0 : this.getKanal().hashCode());
		result = 37 * result
				+ (getArea() == null ? 0 : this.getArea().hashCode());
		result = 37 * result
				+ (getBand() == null ? 0 : this.getBand().hashCode());
		result = 37
				* result
				+ (getLeverandor() == null ? 0 : this.getLeverandor()
						.hashCode());
		result = 37
				* result
				+ (getLeveringstype() == null ? 0 : this.getLeveringstype()
						.hashCode());
		result = 37
				* result
				+ (getGruppering() == null ? 0 : this.getGruppering()
						.hashCode());
		result = 37
				* result
				+ (getPrimvarenr() == null ? 0 : this.getPrimvarenr()
						.hashCode());
		result = 37
				* result
				+ (getGyldigtTil() == null ? 0 : this.getGyldigtTil()
						.hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getCrd() == null ? 0 : this.getCrd().hashCode());
		result = 37 * result
				+ (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result
				+ (getImpt() == null ? 0 : this.getImpt().hashCode());
		result = 37 * result
				+ (getExpt() == null ? 0 : this.getExpt().hashCode());
		result = 37 * result
				+ (getImpd() == null ? 0 : this.getImpd().hashCode());
		result = 37 * result
				+ (getExpd() == null ? 0 : this.getExpd().hashCode());
		result = 37 * result
				+ (getModt() == null ? 0 : this.getModt().hashCode());
		result = 37 * result
				+ (getCru() == null ? 0 : this.getCru().hashCode());
		result = 37 * result
				+ (getDelt() == null ? 0 : this.getDelt().hashCode());
		result = 37 * result
				+ (getModd() == null ? 0 : this.getModd().hashCode());
		result = 37 * result
				+ (getImpu() == null ? 0 : this.getImpu().hashCode());
		result = 37 * result
				+ (getExpu() == null ? 0 : this.getExpu().hashCode());
		result = 37 * result
				+ (getDeld() == null ? 0 : this.getDeld().hashCode());
		result = 37 * result
				+ (getModu() == null ? 0 : this.getModu().hashCode());
		result = 37 * result
				+ (getHead() == null ? 0 : this.getHead().hashCode());
		result = 37 * result
				+ (getDelu() == null ? 0 : this.getDelu().hashCode());
		result = 37 * result
				+ (getCrt() == null ? 0 : this.getCrt().hashCode());
		return result;
	}

}
