package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WUpdateStamp generated by hbm2java
 */
@Entity
@Table(name = "W_UPDATE_STAMP", schema = "PCRM")
public class WUpdateStamp implements java.io.Serializable {

	private Date caUpdateStamp;

	public WUpdateStamp() {
	}

	public WUpdateStamp(Date caUpdateStamp) {
		this.caUpdateStamp = caUpdateStamp;
	}

	@Id
	@Temporal(TemporalType.DATE)
	@Column(name = "CA_UPDATE_STAMP", length = 7)
	public Date getCaUpdateStamp() {
		return this.caUpdateStamp;
	}

	public void setCaUpdateStamp(Date caUpdateStamp) {
		this.caUpdateStamp = caUpdateStamp;
	}

}
