package com.tdc.persistence.kiss.dao.entity;

// Generated 31-03-2015 11:56:29 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Youseehierarchycustomer generated by hbm2java
 */
@Entity
@Table(name = "YOUSEEHIERARCHYCUSTOMER", schema = "PCRM")
public class Youseehierarchycustomer implements java.io.Serializable {

	private YouseehierarchycustomerId id;

	public Youseehierarchycustomer() {
	}

	public Youseehierarchycustomer(YouseehierarchycustomerId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "company", column = @Column(name = "COMPANY", length = 256)),
			@AttributeOverride(name = "custno", column = @Column(name = "CUSTNO", length = 256)),
			@AttributeOverride(name = "custname", column = @Column(name = "CUSTNAME", length = 256)),
			@AttributeOverride(name = "custname2", column = @Column(name = "CUSTNAME2", length = 256)),
			@AttributeOverride(name = "createddate", column = @Column(name = "CREATEDDATE", length = 7)),
			@AttributeOverride(name = "changeddate", column = @Column(name = "CHANGEDDATE", length = 7)) })
	public YouseehierarchycustomerId getId() {
		return this.id;
	}

	public void setId(YouseehierarchycustomerId id) {
		this.id = id;
	}

}
